### ISSUE TITLE
[Issue] Keras model save/load error

### ISSUE THREAD

**Issue by hhbyyh** [intel-analytics/analytics-zoo#1004]
I found an issue with Keras model save/load. I’m using the master branch of Zoo. I need to save a transfer learning model for the customer use case.

If the model saving and loading happen in one python program, everything works fine. But when I try to load a model that was saved in another python program, I met error. 

Code to repro (run it first with the save part, then run another time with just loading)
```
from bigdl.nn.criterion import *
from bigdl.optim.optimizer import *
from bigdl.nn.layer import Model as BigDLModel
from zoo.common.nncontext import *
from zoo.feature.image.imagePreprocessing import *
from zoo.pipeline.api.keras.layers import Input, Flatten, Dense, GlobalAveragePooling2D
from zoo.pipeline.api.keras.models import Model as KModel
from zoo.pipeline.api.net import Net

sparkConf = create_spark_conf().setAppName("test_dell_x_ray")
sc = init_nncontext(sparkConf)

# full_model = Net.load_bigdl("/home/yuhao/workspace/model/analytics-zoo_resnet-50_imagenet_0.1.0.model")
# model = full_model.new_graph(["pool5"])
# print(('num of model layers: ', len(model.layers)))
# inputNode = Input(name="input", shape=(3, 224, 224))
# inception = model.to_keras()(inputNode)
# flatten = GlobalAveragePooling2D(dim_ordering='th')(inception)
# logits = Dense(14, activation="sigmoid")(flatten)
# finalModel = KModel(inputNode, logits)
# finalModel.saveModel("./kerasModel/m.bigdl", "./kerasModel/m.bin", True)

loaded = BigDLModel.loadModel("./kerasModel/m.bigdl", "./kerasModel/m.bin")
print("reload succeed")
```
Exception message:
```
Caused by: java.lang.IllegalArgumentException: requirement failed: _inputs value cannot be found
              at scala.Predef$.require(Predef.scala:224)
              at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$$anonfun$doLoadModule$1$$anonfun$apply$1.apply(ModuleSerializable.scala:137)
              at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$$anonfun$doLoadModule$1$$anonfun$apply$1.apply(ModuleSerializable.scala:125)
              at scala.collection.immutable.List.foreach(List.scala:381)
              at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$$anonfun$doLoadModule$1.apply(ModuleSerializable.scala:125)
              at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$$anonfun$doLoadModule$1.apply(ModuleSerializable.scala:124)
              at scala.collection.immutable.List.foreach(List.scala:381)
              at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.doLoadModule(ModuleSerializable.scala:124)
              at com.intel.analytics.bigdl.utils.serializer.ContainerSerializer$.com$intel$analytics$bigdl$utils$serializer$ContainerSerializable$$super$doLoadModule(ModuleSerializable.scala:421)
              at com.intel.analytics.bigdl.utils.serializer.ContainerSerializable$class.doLoadModule(ModuleSerializable.scala:394)
              at com.intel.analytics.bigdl.utils.serializer.ContainerSerializer$.doLoadModule(ModuleSerializable.scala:421)
              at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.loadModule(ModuleSerializable.scala:95)
              at com.intel.analytics.bigdl.utils.serializer.ContainerSerializer$.loadModule(ModuleSerializable.scala:421)
              at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.load(ModuleSerializer.scala:149)
              ... 14 more
```

**Comment by zhichao-li** [comment]
In theory protobuf format is neutral to process, so my wild guess is the `finalModel.saveModel("./kerasModel/m.bigdl", "./kerasModel/m.bin", True)` wasn't correctly serialized to binary. @hkvision

**Comment by hkvision** [comment]
call `Net.load()`?

**Comment by dding3** [comment]
I met the same exception with scala code. And the code is quite simple:
`
val x = Variable[Float](Shape(1, 10))
    val y = Variable[Float](Shape(1, 10))
    val z = x + y
    val model = Model[Float](input = Array(x, y), output = z)
    val absPath = "/tmp/para.model"
    model.saveModule(absPath, overWrite = true)
`
and load code is:
`    val absPath2 = "/tmp/para.model"
    val model2 = Module.loadModule[Float](absPath2)
`

**Comment by zhichao-li** [comment]
@hhbyyh @dding3  Please use  `Net.load(...)` and try again for your case as the model you constructed is based on the API from Analytics-ZOO.

**Comment by dding3** [comment]
Thanks for your suggestions. It works for me now :)

**Comment by zhichao-li** [comment]
Closing this for now as it has been solved. Please reopen it if still facing the problem.
