### ISSUE TITLE
Analytics Zoo cannot be used when Keras 2 is installed?

### ISSUE THREAD

**Issue by hhbyyh** [intel-analytics/analytics-zoo#1019]
User will meet an error if they have Keras 2.x installed in their system when they import net.

2018-12-25 17:55:08 WARN  Utils:66 - Your hostname, yuhao-devbox resolves to a loopback address: 127.0.1.1; using 143.183.81.148 instead (on interface enp0s31f6)
2018-12-25 17:55:08 WARN  Utils:66 - Set SPARK_LOCAL_IP if you need to bind to another address
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/yuhao/workspace/github/hhbyyh/BigDL-ImageProcessing-Examples/xray_nnclassifier/train.py", line 20, in <module>
    from zoo.pipeline.api.net import Net
  File "/home/yuhao/workspace/github/hhbyyh/analytics-zoo/dist/lib/analytics-zoo-bigdl_0.7.1-spark_2.1.0-0.4.0-SNAPSHOT-python-api.zip/zoo/pipeline/api/net.py", line 35, in <module>
  File "/home/yuhao/workspace/github/hhbyyh/analytics-zoo/dist/lib/analytics-zoo-bigdl_0.7.1-spark_2.1.0-0.4.0-SNAPSHOT-python-api.zip/bigdl/keras/optimization.py", line 22, in <module>
  File "/home/yuhao/workspace/github/hhbyyh/analytics-zoo/dist/lib/analytics-zoo-bigdl_0.7.1-spark_2.1.0-0.4.0-SNAPSHOT-python-api.zip/bigdl/keras/converter.py", line 22, in <module>
ImportError: cannot import name 'Layer'
2018-12-25 17:55:08 WARN  Utils:66 - Your hostname, yuhao-devbox resolves to a loopback address: 127.0.1.1; using 143.183.81.148 instead (on interface enp0s31f6)
2018-12-25 17:55:08 WARN  Utils:66 - Set SPARK_LOCAL_IP if you need to bind to another address
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/yuhao/workspace/github/hhbyyh/BigDL-ImageProcessing-Examples/xray_nnclassifier/train.py", line 20, in <module>
    from zoo.pipeline.api.net import Net
  File "/home/yuhao/workspace/github/hhbyyh/analytics-zoo/dist/lib/analytics-zoo-bigdl_0.7.1-spark_2.1.0-0.4.0-SNAPSHOT-python-api.zip/zoo/pipeline/api/net.py", line 35, in <module>
  File "/home/yuhao/workspace/github/hhbyyh/analytics-zoo/dist/lib/analytics-zoo-bigdl_0.7.1-spark_2.1.0-0.4.0-SNAPSHOT-python-api.zip/bigdl/keras/optimization.py", line 22, in <module>
  File "/home/yuhao/workspace/github/hhbyyh/analytics-zoo/dist/lib/analytics-zoo-bigdl_0.7.1-spark_2.1.0-0.4.0-SNAPSHOT-python-api.zip/bigdl/keras/converter.py", line 22, in <module>
ImportError: cannot import name 'Layer'
``

In bigdl/keras/converter.py 
`from keras.models import Sequential, Model, Layer` will cause error since Layer in not there anymore in Keras 2.x.

**Comment by hhbyyh** [comment]
cc @yangw1234

**Comment by hkvision** [comment]
Oops. Then we remove the dependency of `bigdl/keras/converter.py`? I think @yangw1234 has done this in the latest PR.
