### ISSUE TITLE
TFnet report error when using tf.keras.layers.Dropout

### ISSUE THREAD

**Issue by hhbyyh** [intel-analytics/analytics-zoo#1082]
code to repro:
```
import time
import os
import re
import sys
import tarfile

import tensorflow as tf
from bigdl.optim.optimizer import *
from zoo import init_nncontext
from zoo.pipeline.api.net import TFOptimizer, TFDataset

n_classes = 10

def get_deep_cnn(images):
    # From: https://github.com/keras-team/keras/blob/master/examples/cifar10_cnn.py
    x = tf.keras.layers.Conv2D(32, (3, 3), padding='same', activation='relu')(images)
    x = tf.keras.layers.Conv2D(32, (3, 3), activation='relu')(x)
    x = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(x)
    x = tf.keras.layers.Dropout(0.25)(x)

    x = tf.keras.layers.Conv2D(64, (3, 3), padding='same', activation='relu')(x)
    x = tf.keras.layers.Conv2D(64, (3, 3), activation='relu')(x)
    x = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(x)
    #x = tf.keras.layers.Dropout(0.25)(x)

    x = tf.keras.layers.Flatten()(x)
    x = tf.keras.layers.Dense(512, activation='relu')(x)
    x = tf.keras.layers.Dropout(0.5)(x)
    preds = tf.keras.layers.Dense(10, activation='softmax')(x)
    return preds

if __name__ == '__main__':

    sc = init_nncontext()
    from keras.datasets import cifar10 as kcifar10

    (x_train, y_train), (x_val, y_val) = kcifar10.load_data()

    x_train = x_train[0: 10000]
    y_train = y_train[0: 10000]

    x_val = x_val[0: 1000]
    y_val = y_val[0: 1000]

    x_train_rdd = sc.parallelize(x_train)
    y_train_rdd = sc.parallelize(y_train)
    training_rdd = x_train_rdd.zip(y_train_rdd) \
        .map(lambda rec_tuple: [rec_tuple[0], np.array(rec_tuple[1])])

    x_val_rdd = sc.parallelize(x_val)
    y_val_rdd = sc.parallelize(y_val)
    val_rdd = x_val_rdd.zip(y_val_rdd) \
        .map(lambda rec_tuple: [rec_tuple[0], np.array(rec_tuple[1])])

    dataset = TFDataset.from_rdd(training_rdd,
                                 names=["features", "labels"],
                                 shapes=[[32, 32, 3], [1]],
                                 types=[tf.float32, tf.int32],
                                 batch_size=256,
                                 val_rdd = val_rdd)

    # construct the model from TFDataset
    images, labels = dataset.tensors
    labels_sq = tf.squeeze(labels)
    logits = get_deep_cnn(images)

    # logits = get_tf_nn_convnet(images)
    loss = tf.reduce_mean(tf.losses.sparse_softmax_cross_entropy(logits=logits, labels=labels_sq))

    # create a optimizer
    optimizer = TFOptimizer(loss, Adam(1e-3),
                    val_outputs=[logits],
                    val_labels=[labels],
                    val_method=Top1Accuracy())
    optimizer.set_train_summary(TrainSummary("/tmp/az_lenet", "lenet"))
    optimizer.set_val_summary(ValidationSummary("/tmp/az_lenet", "lenet"))

    start = time.time()
    # kick off training
    optimizer.optimize(end_trigger=MaxEpoch(20))

```

error:
```
2019-01-17 14:42:38.289589: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
creating: createTop1Accuracy
Traceback (most recent call last):
  File "/home/yuhao/PycharmProjects/RLTest/tfnet_cifar10/zoo_cifar10_train.py", line 138, in <module>
    val_method=Top1Accuracy())
  File "/home/yuhao/workspace/github/hhbyyh/analytics-zoo/pyzoo/zoo/pipeline/api/net.py", line 385, in __init__
    val_outputs, val_labels, val_method)
  File "/home/yuhao/workspace/github/hhbyyh/analytics-zoo/pyzoo/zoo/pipeline/api/net.py", line 526, in _get_arguments_from_loss
    _check_the_same(all_required_inputs, inputs)
  File "/home/yuhao/workspace/github/hhbyyh/analytics-zoo/pyzoo/zoo/pipeline/api/net.py", line 733, in _check_the_same
    "found %s" % inputs_not_in_dataset)
ValueError: You should not use any placeholder that are not defined in dataset, found [<tf.Tensor 'dropout/keras_learning_phase:0' shape=() dtype=bool>]
```

**Comment by hhbyyh** [comment]
cc @yangw1234

**Comment by yangw1234** [comment]
hi @hhbyyh, you should use the TFOptimizer.from_keras() which is specifically designed for keras model.
The following code works fine.

```
import tensorflow as tf
from bigdl.optim.optimizer import *
from zoo import init_nncontext
from zoo.pipeline.api.net import TFOptimizer, TFDataset

n_classes = 10

def get_deep_cnn_model():
    # From: https://github.com/keras-team/keras/blob/master/examples/cifar10_cnn.py
    images = tf.keras.layers.Input(shape=(32, 32, 3))
    x = tf.keras.layers.Conv2D(32, (3, 3), padding='same', activation='relu')(images)
    x = tf.keras.layers.Conv2D(32, (3, 3), activation='relu')(x)
    x = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(x)
    x = tf.keras.layers.Dropout(0.25)(x)

    x = tf.keras.layers.Conv2D(64, (3, 3), padding='same', activation='relu')(x)
    x = tf.keras.layers.Conv2D(64, (3, 3), activation='relu')(x)
    x = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(x)
    #x = tf.keras.layers.Dropout(0.25)(x)

    x = tf.keras.layers.Flatten()(x)
    x = tf.keras.layers.Dense(512, activation='relu')(x)
    x = tf.keras.layers.Dropout(0.5)(x)
    preds = tf.keras.layers.Dense(10)(x)

    model = tf.keras.models.Model(inputs=images, outputs=preds)
    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

if __name__ == '__main__':

    sc = init_nncontext()
    from keras.datasets import cifar10 as kcifar10

    (x_train, y_train), (x_val, y_val) = kcifar10.load_data()

    x_train = x_train[0: 10000]
    y_train = y_train[0: 10000]

    x_val = x_val[0: 1000]
    y_val = y_val[0: 1000]

    x_train_rdd = sc.parallelize(x_train)
    y_train_rdd = sc.parallelize(y_train)
    training_rdd = x_train_rdd.zip(y_train_rdd) \
        .map(lambda rec_tuple: [rec_tuple[0], np.array(rec_tuple[1])])

    x_val_rdd = sc.parallelize(x_val)
    y_val_rdd = sc.parallelize(y_val)
    val_rdd = x_val_rdd.zip(y_val_rdd) \
        .map(lambda rec_tuple: [rec_tuple[0], np.array(rec_tuple[1])])

    dataset = TFDataset.from_rdd(training_rdd,
                                 names=["features", "labels"],
                                 shapes=[[32, 32, 3], []],
                                 types=[tf.float32, tf.int32],
                                 batch_size=256,
                                 val_rdd = val_rdd)


    model = get_deep_cnn_model()

    # create a optimizer
    optimizer = TFOptimizer.from_keras(model, dataset)
    optimizer.set_train_summary(TrainSummary("/tmp/az_lenet", "lenet"))
    optimizer.set_val_summary(ValidationSummary("/tmp/az_lenet", "lenet"))

    start = time.time()
    # kick off training
    optimizer.optimize(end_trigger=MaxEpoch(20))
```

**Comment by jason-dai** [comment]
You should check and report the error properly.

**Comment by hhbyyh** [comment]
@yangw1234 Thanks for the quick reply. 

@jason-dai Do you mean I should provide more details in the issue description? or our TFNet code should check the model and report proper error message... just to confirm..

**Comment by jason-dai** [comment]
Our implementation should check and report meaningful error

**Comment by hhbyyh** [comment]
Thanks.

Hi @yangw1234 I tried your version and it does work with tensorflow 1.10. 

Yet in TF 1.11 and TF 1.12, the code report error:
```
Traceback (most recent call last):
  File "/home/yuhao/PycharmProjects/RLTest/tfnet_cifar10/wangyang_version.py", line 68, in <module>
    optimizer = TFOptimizer.from_keras(model, dataset)
  File "/home/yuhao/workspace/github/hhbyyh/analytics-zoo/pyzoo/zoo/pipeline/api/net.py", line 577, in from_keras
    tensors_with_value=tensor_with_value, **kwargs)
  File "/home/yuhao/workspace/github/hhbyyh/analytics-zoo/pyzoo/zoo/pipeline/api/net.py", line 466, in __init__
    raise e
py4j.protocol.Py4JJavaError: An error occurred while calling o35.createTFTrainingHelper.
: java.lang.IllegalArgumentException: NodeDef mentions attr 'Truncate' not in Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: loss/dense_1_loss/Cast = Cast[DstT=DT_INT64, SrcT=DT_FLOAT, Truncate=false](loss/dense_1_loss/Reshape). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	at org.tensorflow.Graph.importGraphDef(Native Method)
	at org.tensorflow.Graph.importGraphDef(Graph.java:130)
	at org.tensorflow.Graph.importGraphDef(Graph.java:114)
	at com.intel.analytics.zoo.pipeline.api.net.TFNet$.apply(TFNet.scala:748)
	at com.intel.analytics.zoo.pipeline.api.net.TFTrainingHelper$.apply(TFTrainingHelper.scala:168)
	at com.intel.analytics.zoo.pipeline.api.net.python.PythonZooNet.createTFTrainingHelper(PythonZooNet.scala:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
```
is it expected?

**Comment by jason-dai** [comment]
I think we only support TF 1.10 for now: https://analytics-zoo.github.io/master/#ProgrammingGuide/tensorflow/

**Comment by yangw1234** [comment]
@jason-dai I'll submit a pr to improve the error message
