### ISSUE TITLE
SSD predict NPE 

### ISSUE THREAD

**Issue by kaiseu** [intel-analytics/analytics-zoo#114]
Follow the instructions [here](https://github.com/intel-analytics/analytics-zoo/tree/master/pipeline/objectDetection/ssd) to try SSD with BigDL, found many NPE in executor's log, the command used is as below: 
spark-submit   --master spark://bb-node1:7077   --executor-cores 5   --num-executors 10   --total-executor-cores 50   --driver-memory 30G   --executor-memory 200G   --driver-class-path /mnt/disk1/SSD_Predict/models/ssd/jars/object-detection-0.1-SNAPSHOT-jar-with-dependencies-and-spark.jar   --class com.intel.analytics.zoo.pipeline.ssd.example.Predict   /mnt/disk1/SSD_Predict/models/ssd/jars/object-detection-0.1-SNAPSHOT-jar-with-dependencies-and-spark.jar   -f hdfs://bb-node1:8020/dlbenchmark/data/PASCAL/seq/test/   --folderType seq   --caffeDefPath  /mnt/disk1/SSD_Predict/models/ssd/caffe/VGGNet/VOC0712/SSD_300x300/test.prototxt --caffeModelPath  /mnt/disk1/SSD_Predict/models/ssd/caffe/VGGNet/VOC0712/SSD_300x300/VGG_VOC0712_SSD_300x300_iter_120000.caffemodel   --classname /mnt/disk1/SSD_Predict/models/ssd/caffe/VGGNet/VOC0712/classname.txt   -b 200   -r 300   -p 50   -q false

executor log:
18/03/02 13:30:41 WARN FeatureTransformer$: failed /mnt/disk1/SSD_Predict/data/PASCAL/VOCdevkit/VOC2007/JPEGImages/009934.jpg in transformer class com.intel.analytics.bigdl.transform.vision.image.augmentation.Resize
java.lang.NullPointerException
	at org.opencv.imgproc.Imgproc.resize(Imgproc.java:2761)
	at com.intel.analytics.bigdl.transform.vision.image.augmentation.Resize$.transform(Resize.scala:69)
	at com.intel.analytics.bigdl.transform.vision.image.augmentation.Resize.transformMat(Resize.scala:53)
	at com.intel.analytics.bigdl.transform.vision.image.FeatureTransformer.transform(FeatureTransformer.scala:58)
	at com.intel.analytics.bigdl.transform.vision.image.ChainedFeatureTransformer.transform(FeatureTransformer.scala:111)
	at com.intel.analytics.bigdl.transform.vision.image.ChainedFeatureTransformer.transform(FeatureTransformer.scala:111)
	at com.intel.analytics.bigdl.transform.vision.image.ChainedFeatureTransformer.transform(FeatureTransformer.scala:111)
	at com.intel.analytics.bigdl.transform.vision.image.FeatureTransformer$$anonfun$apply$1.apply(FeatureTransformer.scala:80)
	at com.intel.analytics.bigdl.transform.vision.image.FeatureTransformer$$anonfun$apply$1.apply(FeatureTransformer.scala:80)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$GroupedIterator.takeDestructively(Iterator.scala:1076)
	at scala.collection.Iterator$GroupedIterator.go(Iterator.scala:1091)
	at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1128)
	at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1132)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.util.Utils$.getIteratorSize(Utils.scala:1760)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1158)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1158)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1951)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1951)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jason-dai** [comment]
@wzhongyuan please take a look

**Comment by wzhongyuan** [comment]
@kaiseu    It was because you passed in `seq` as the file type and it apply 'RecordToFeature' to transform image bytes to ImageFeature but this transformer does not initialize the `ImageFeature.mate` content thus caused the null pointer exception. I would suggest not to use `seq` file if you want to use `Predict` class.

Also , `Predit` does not provide any model specific transformers, in order to use pre-trained parameters, i would suggest you use `Test` class in example,  the  [doc](https://github.com/intel-analytics/analytics-zoo/tree/master/pipeline/objectDetection/ssd) also uses this as well.
