### ISSUE TITLE
tfpark KerasModel has error when specifying batch_input_shape with RNN

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#1228]
```
model = tf.keras.Sequential([
      tf.keras.layers.Embedding(vocab_size, embedding_dim,
                                batch_input_shape=[BATCH_SIZE, None]),
      tf.keras.layers.GRU(rnn_units,
                          return_sequences=True,
                          recurrent_initializer='glorot_uniform',
                          stateful=True),
      tf.keras.layers.Dense(vocab_size)
    ])
```
The above code will throw the following Scala error:
```
py4j.protocol.Py4JJavaError: An error occurred while calling o50.createTFTrainingHelper.
: java.lang.IllegalArgumentException: Node 'gradients/lstm/while/Exit_2_grad/b_exit' expects to be colocated with unknown node 'lstm/while/Exit_2'
```

Have spotted the problem is that we specify batch_size in input_shape, since a stateful RNN needs batch_size.
It can work if we change batch_input_shape to input_shape and use a stateless RNN.

**Comment by hkvision** [comment]
Also, in the above error, since it contains `expects to be colocated with unknown node` as well, I still get the python error message for embedding, which doesn't make sense. The logic of throwing error better to be modified.
```
Traceback (most recent call last):
  File "/home/kai/analytics-zoo/pyzoo/zoo/examples/tensorflow/tfpark/text_generation.py", line 111, in <module>
    distributed=True)
  File "/home/kai/analytics-zoo/pyzoo/zoo/tfpark/model.py", line 118, in fit
    self._fit_distributed(dataset, validation_split, epochs, **kwargs)
  File "/home/kai/analytics-zoo/pyzoo/zoo/tfpark/model.py", line 133, in _fit_distributed
    val_spilt=validation_split, **kwargs)
  File "/home/kai/analytics-zoo/pyzoo/zoo/pipeline/api/net.py", line 585, in from_keras
    tensors_with_value=tensor_with_value, **kwargs)
  File "/home/kai/analytics-zoo/pyzoo/zoo/pipeline/api/net.py", line 471, in __init__
    """)
Exception: 
If you are using the embedding layer in tf.keras, then this is a
known issue of TensorFlow, see https://github.com/tensorflow/tensorflow/issues/21889.
Please add zoo.util.tf.variable_creator_scope before model construction.
For example:
from zoo.util.tf import variable_creator_scope
with variable_creator_scope():
    model = tf.keras.models.Sequential([
    tf.keras.layers.Embedding(1, 1, input_length=1)])
```

**Comment by yangw1234** [comment]
@hkvision Seems these two kinds of error is indistinguishable simply from the error message.  Do you have a better idea?

**Comment by yangw1234** [comment]
@hkvision this is caused by a bug in tensorflow's `convert_variables_to_constants`. I do not think we can easily fix this.
@jason-dai maybe we should think of not using the frozen graph.

**Comment by hkvision** [comment]
For the current error msg, can just check `embedding` in the str to report the embedding error?
```
if "expects to be colocated with unknown node" in str(e) and "embedding" in str(e):
```

**Comment by hkvision** [comment]
```
To keep this prediction step simple, use a batch size of 1.

Because of the way the RNN state is passed from timestep to timestep, the model only accepts a fixed batch size once built.

To run the model with a different batch_size, we need to rebuild the model and restore the weights from the checkpoint.
```

@jason-dai During inference, it just rebuild the model with batch_size=1 and set the trained weights...
