### ISSUE TITLE
Error while running the openvino example

### ISSUE THREAD

**Issue by zhichao-li** [intel-analytics/analytics-zoo#1374]
Run by downloading the prebuilt package.
https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/examples/openvino

Traceback (most recent call last):
  File "/tmp/1558587157102-0/model-optimizer/mo_tf.py", line 28, in <module>
    from mo.main import main
  File "/tmp/1558587157102-0/model-optimizer/mo/main.py", line 28, in <module>
    from mo.utils.cli_parser import get_placeholder_shapes, get_tuple_values, get_model_name, \
  File "/tmp/1558587157102-0/model-optimizer/mo/utils/cli_parser.py", line 26, in <module>
    from mo.front.extractor import split_node_in_port
  File "/tmp/1558587157102-0/model-optimizer/mo/front/extractor.py", line 21, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'

**Comment by hkvision** [comment]
According to @glorysdj you need to install networkx by yourself.

**Comment by glorysdj** [comment]
ye, need to install networkx

**Comment by qiyuangong** [comment]
Will add dependencies into Inference Model doc.

**Comment by qiyuangong** [comment]
Add requirements into docs:

    tensorflow>=1.2.0
    networkx>=1.11
    numpy>=1.12.0
    protobuf==3.6.1
    onnx>=1.1.2

**Comment by zhichao-li** [comment]
@qiyuangong seems like the readme on this example hasn't been updated before closing?

**Comment by zhichao-li** [comment]
I run this on Gondolin server and faced the following issue. Maybe we should enrich the document if there's more platform requirement?
```
Traceback (most recent call last):
  File "/home/zhichao/god/rayonspark/pyzoo/zoo/examples/openvino/predict.py", line 44, in <module>
    model.load_tf(options.model_path, backend="openvino", model_type=options.model_type)
  File "/home/zhichao/god/analytics-zoo/dist/lib/analytics-zoo-bigdl_0.8.0-spark_2.1.0-0.5.0-SNAPSHOT-python-api.zip/zoo/pipeline/inference/inference_model.py", line 106, in load_tf
  File "/home/zhichao/god/analytics-zoo/dist/lib/analytics-zoo-bigdl_0.8.0-spark_2.1.0-0.5.0-SNAPSHOT-python-api.zip/bigdl/util/common.py", line 589, in callBigDlFunc
py4j.protocol.Py4JJavaError: An error occurred while calling o50.inferenceModelOpenVINOLoadTF.
: java.lang.UnsatisfiedLinkError: /tmp/dlNativeLoader3753295025550583139libinference_engine.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/dlNativeLoader3753295025550583139libinference_engine.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at com.intel.analytics.zoo.core.openvino.OpenvinoNativeLoader.loadLib(OpenvinoNativeLoader.java:61)
        at com.intel.analytics.zoo.core.openvino.OpenvinoNativeLoader.load(OpenvinoNativeLoader.java:44)
        at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$$anonfun$1.apply$mcZ$sp(OpenVinoInferenceSupportive.scala:60)
        at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$$anonfun$1.apply(OpenVinoInferenceSupportive.scala:60)
        at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$$anonfun$1.apply(OpenVinoInferenceSupportive.scala:60)
        at com.intel.analytics.zoo.pipeline.inference.InferenceSupportive$class.timing(InferenceSupportive.scala:42)
        at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$.timing(OpenVinoInferenceSupportive.scala:56)
        at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$.<init>(OpenVinoInferenceSupportive.scala:59)
        at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$.<clinit>(OpenVinoInferenceSupportive.scala)
        at com.intel.analytics.zoo.pipeline.inference.InferenceModelFactory$.loadOpenVINOModelForTF(InferenceModelFactory.scala:59)
        at com.intel.analytics.zoo.pipeline.inference.InferenceModel.doLoadTensorflowModelAsOpenVINO(InferenceModel.scala:303)
        at com.intel.analytics.zoo.pipeline.inference.InferenceModel.doLoadTF(InferenceModel.scala:133)
        at com.intel.analytics.zoo.pipeline.inference.PythonInferenceModel.inferenceModelOpenVINOLoadTF(PythonInferenceModel.scala:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:280)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by qiyuangong** [comment]
Currently, OpenVINO requires Ubuntu 16.04 or higher, whose gcc and glibc versions are higher than CentOS. I will add this requirement into doc.

**Comment by qiyuangong** [comment]
Added System/OS requirements and link in #1408 .

**Comment by zhichao-li** [comment]
Another exception which might be related to the size of images
```
 -----
Traceback (most recent call last):
  File "/opt/work/analytics-zoo/pyzoo/zoo/examples/openvino/predict.py", line 44, in <module>
    model.load_tf(options.model_path, backend="openvino", model_type=options.model_type)
  File "/opt/work/analytics-zoo/dist/lib/analytics-zoo-bigdl_0.8.0-spark_2.1.0-0.5.0-SNAPSHOT-python-api.zip/zoo/pipeline/inference/inference_model.py", line 106, in load_tf
  File "/opt/work/analytics-zoo/dist/lib/analytics-zoo-bigdl_0.8.0-spark_2.1.0-0.5.0-SNAPSHOT-python-api.zip/bigdl/util/common.py", line 589, in callBigDlFunc
  File "/opt/work/analytics-zoo/dist/lib/analytics-zoo-bigdl_0.8.0-spark_2.1.0-0.5.0-SNAPSHOT-python-api.zip/bigdl/util/common.py", line 585, in callBigDlFunc
  File "/opt/work/analytics-zoo/dist/lib/analytics-zoo-bigdl_0.8.0-spark_2.1.0-0.5.0-SNAPSHOT-python-api.zip/bigdl/util/common.py", line 634, in callJavaFunc
  File "/opt/work/spark-2.4.0-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/opt/work/spark-2.4.0-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o51.inferenceModelOpenVINOLoadTF.
: com.intel.analytics.zoo.pipeline.inference.InferenceRuntimeException: Openvino optimize tf object detection model error: 1, [ ERROR ]  Cannot infer shapes or values for node "Reshape_5".,[ ERROR ]  Number of elements in input [  1 300   4] and output [100, 4] of reshape node Reshape_5 mismatch,[ ERROR ]  ,[ ERROR ]  It can happen due to bug in custom shape infer function <function tf_reshape_ext.<locals>.<lambda> at 0x7f42089af620>.,[ ERROR ]  Or because the node inputs have incorrect values/shapes.,[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).,[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.,[ ERROR ]  Stopped shape/value propagation at "Reshape_5" node.
        at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$$anonfun$optimizeTFObjectDetectionModel$1.apply$mcV$sp(OpenVinoInferenceSupportive.scala:259)
        at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$$anonfun$optimizeTFObjectDetectionModel$1.apply(OpenVinoInferenceSupportive.scala:236)
        at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$$anonfun$optimizeTFObjectDetectionModel$1.apply(OpenVinoInferenceSupportive.scala:236)
        at com.intel.analytics.zoo.pipeline.inference.InferenceSupportive$class.timing(InferenceSupportive.scala:42)
        at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$.timing(OpenVinoInferenceSupportive.scala:56)
        at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$.optimizeTFObjectDetectionModel(OpenVinoInferenceSupportive.scala:236)
        at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$.loadTensorflowModel(OpenVinoInferenceSupportive.scala:315)
        at com.intel.analytics.zoo.pipeline.inference.InferenceModelFactory$.loadOpenVINOModelForTF(InferenceModelFactory.scala:59)
        at com.intel.analytics.zoo.pipeline.inference.InferenceModel.doLoadTensorflowModelAsOpenVINO(InferenceModel.scala:303)
        at com.intel.analytics.zoo.pipeline.inference.InferenceModel.doLoadTF(InferenceModel.scala:133)
        at com.intel.analytics.zoo.pipeline.inference.PythonInferenceModel.inferenceModelOpenVINOLoadTF(PythonInferenceModel.scala:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:745)


```

**Comment by hkvision** [comment]
Same error tested here. @glorysdj @qiyuangong

**Comment by hkvision** [comment]
When added `pipeline.config` (just as what ut does) the problem got resolved. But it is not reasonable. @glorysdj @qiyuangong

**Comment by hkvision** [comment]
Also, when I put 64 images, it will throw error:
```
Traceback (most recent call last):
  File "/home/kai/analytics-zoo/pyzoo/zoo/examples/openvino/predict.py", line 46, in <module>
    predictions = model.predict(input_data)
  File "/home/kai/analytics-zoo/pyzoo/zoo/pipeline/inference/inference_model.py", line 235, in predict
    input_is_table)
  File "/home/kai/anaconda2/envs/nlp-architect/lib/python3.5/site-packages/bigdl/util/common.py", line 588, in callBigDlFunc
    raise e
  File "/home/kai/anaconda2/envs/nlp-architect/lib/python3.5/site-packages/bigdl/util/common.py", line 584, in callBigDlFunc
    result = callJavaFunc(api, *args)
  File "/home/kai/anaconda2/envs/nlp-architect/lib/python3.5/site-packages/bigdl/util/common.py", line 632, in callJavaFunc
    args = [_py2java(gateway, a) for a in args]
  File "/home/kai/anaconda2/envs/nlp-architect/lib/python3.5/site-packages/bigdl/util/common.py", line 632, in <listcomp>
    args = [_py2java(gateway, a) for a in args]
  File "/home/kai/anaconda2/envs/nlp-architect/lib/python3.5/site-packages/bigdl/util/common.py", line 659, in _py2java
    obj = ListConverter().convert([_py2java(gateway, x) for x in obj],
  File "/home/kai/anaconda2/envs/nlp-architect/lib/python3.5/site-packages/bigdl/util/common.py", line 659, in <listcomp>
    obj = ListConverter().convert([_py2java(gateway, x) for x in obj],
  File "/home/kai/anaconda2/envs/nlp-architect/lib/python3.5/site-packages/bigdl/util/common.py", line 674, in _py2java
    obj = gateway.jvm.org.apache.spark.bigdl.api.python.BigDLSerDe.loads(data)
  File "/home/kai/anaconda2/envs/nlp-architect/lib/python3.5/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/kai/anaconda2/envs/nlp-architect/lib/python3.5/site-packages/py4j/protocol.py", line 332, in get_return_value
    format(target_id, ".", name, value))
py4j.protocol.Py4JError: An error occurred while calling z:org.apache.spark.bigdl.api.python.BigDLSerDe.loads. Trace:
java.lang.NegativeArraySizeException
	at py4j.Base64.decode(Base64.java:321)
	at py4j.Protocol.getBytes(Protocol.java:175)
	at py4j.Protocol.getObject(Protocol.java:296)
	at py4j.commands.AbstractCommand.getArguments(AbstractCommand.java:82)
	at py4j.commands.CallCommand.execute(CallCommand.java:77)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```
But if I give smaller images, there is no problem.

**Comment by glorysdj** [comment]
> When added `pipeline.config` (just as what ut does) the problem got resolved. But it is not reasonable. @glorysdj @qiyuangong

the root cause of this issue is pipeline.config is changed, we packed latest pipeline.config in the analytics-zoo, but the test model is not compatible with it.
To fix this, we need to upload new test data or pass pipeline.config manually.

**Comment by zhichao-li** [comment]
It's not recommended to passing "big" object through py4j. You are supposed to use py4j to executing command or testing data only and use RDD or DataFrame instead for serious Task.

**Comment by glorysdj** [comment]
> > When added `pipeline.config` (just as what ut does) the problem got resolved. But it is not reasonable. @glorysdj @qiyuangong
> 
> the root cause of this issue is pipeline.config is changed, we packed latest pipeline.config in the analytics-zoo, but the test model is not compatible with it.
> To fix this, we need to upload new test data or pass pipeline.config manually.

it seems no new test data compatible with latest pipeline.config can be found, we have to pass pipeline.config in the function.
BTW, with py4j, it calls callBigDlFunc, so each parameter is passed to callBigDlFunc, and each of them is only plain strins for file path. not big. imo.
