### ISSUE TITLE
Error while running estimator_inception.py

### ISSUE THREAD

**Issue by dding3** [intel-analytics/analytics-zoo#1384]
I am following https://github.com/intel-analytics/analytics-zoo/tree/branch-0.5/pyzoo/zoo/examples/tensorflow/tfpark to run estimator_inception.py and the training images are copy from https://github.com/intel-analytics/analytics-zoo/tree/master/zoo/src/test/resources/imagenet while the folder structure is:
/cats
./cats/cat.001.jpg
./dogs
./dogs/dog.001.jpg

And the exception is:
Traceback (most recent call last):
  File "/tmp/test/estimator_inception.py", line 86, in <module>
    main(options)
  File "/tmp/test/estimator_inception.py", line 78, in main
    estimator.train(input_fn, steps=100)
  File "/tmp/test/lib/analytics-zoo-bigdl_0.7.2-spark_2.2.0-0.5.0-SNAPSHOT-python-api.zip/zoo/tfpark/estimator.py", line 125, in train
  File "/home/ding/tensorflow_venv/venv/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1074, in _call_input_fn
    return input_fn(**kwargs)
  File "/tmp/test/estimator_inception.py", line 35, in input_fn
    sc=sc, with_label=True, one_based_label=False)
TypeError: read() got an unexpected keyword argument 'with_label'

**Comment by yangw1234** [comment]
are you sure you are using the right version of analytics-zoo

**Comment by yangw1234** [comment]
In your exception,
```
And the exception is:
Traceback (most recent call last):
File "/tmp/test/estimator_inception.py", line 86, in 
main(options)
File "/tmp/test/estimator_inception.py", line 78, in main
estimator.train(input_fn, steps=100)
File "/tmp/test/lib/analytics-zoo-bigdl_0.7.2-spark_2.2.0-0.5.0-SNAPSHOT-python-api.zip/zoo/tfpark/estimator.py", line 125, in train
File "/home/ding/tensorflow_venv/venv/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1074, in _call_input_fn
return input_fn(**kwargs)
File "/tmp/test/estimator_inception.py", line 35, in input_fn
sc=sc, with_label=True, one_based_label=False)
TypeError: read() got an unexpected keyword argument 'with_label'
```
It seems you are still using **bigdl_0.7.2**, which, I believe, have been upgraded to 0.8.0 a really long time ago.

**Comment by dding3** [comment]
Ok. I downloaded the prebuilt package from https://analytics-zoo.github.io/master/#release-download/, seems like it's not upgraded to bigdl 0.8. 

If we have requirement for bigdl version for this example, it might be better if we document this in the README.

**Comment by yangw1234** [comment]
@dding3 look at the date, they are not the newest version.

**Comment by dding3** [comment]
Ok. Tried the branch 0.5 and the example can run successfully, close this issue.
