### ISSUE TITLE
Joint use of TFEstimator and KerasModel for prediction will raise java.lang.IllegalStateException: run() cannot be called on the Session after close()

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#1450]
Code for repro:
```
    def test_predict(self):
        model_fn = self.create_model_fn()
        input_fn = self.create_input_fn()
        estimator = TFEstimator(model_fn, tf.train.AdamOptimizer())
        results = estimator.predict(input_fn)
        # results = self.sc.parallelize(results.collect())
        from tensorflow.keras.layers import Dense
        from tensorflow.keras.models import Sequential
        from zoo.tfpark.model import KerasModel
        kmodel = Sequential()
        kmodel.add(Dense(5, input_shape=(10, )))
        dataset = TFDataset.from_rdd(results,
                                          names=["features"],
                                          shapes=[[10]],
                                          types=[tf.float32],
                                          batch_per_thread=4)
        predictions = KerasModel(kmodel).predict(dataset)
        predictions.collect()
```
test_predict is in test_tfpark_estimator.py

Error:
```
E                   java.lang.IllegalStateException: run() cannot be called on the Session after close()
E                   	at org.tensorflow.Session$Runner$Reference.<init>(Session.java:350)
E                   	at org.tensorflow.Session$Runner.runHelper(Session.java:310)
E                   	at org.tensorflow.Session$Runner.run(Session.java:264)
E                   	at com.intel.analytics.zoo.pipeline.api.net.TFNet.updateOutput(TFNet.scala:275)
E                   	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:259)
E                   	at com.intel.analytics.zoo.pipeline.api.Predictor$$anonfun$predict$1$$anonfun$apply$2.apply(Predictor.scala:177)
E                   	at com.intel.analytics.zoo.pipeline.api.Predictor$$anonfun$predict$1$$anonfun$apply$2.apply(Predictor.scala:175)
E                   	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
E                   	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
E                   	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
E                   	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.hasNext(SerDeUtil.scala:153)
E                   	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
E                   	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.foreach(SerDeUtil.scala:148)
E                   	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:223)
E                   	at org.apache.spark.api.python.PythonRunner$$anon$2.writeIteratorToStream(PythonRunner.scala:439)
E                   	at org.apache.spark.api.python.BasePythonRunner$WriterThread$$anonfun$run$1.apply(PythonRunner.scala:247)
E                   	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1992)
E                   	at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:170)
E                   
E                   	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:265)
E                   	at com.intel.analytics.zoo.pipeline.api.Predictor$$anonfun$predict$1$$anonfun$apply$2.apply(Predictor.scala:177)
E                   	at com.intel.analytics.zoo.pipeline.api.Predictor$$anonfun$predict$1$$anonfun$apply$2.apply(Predictor.scala:175)
E                   	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
E                   	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
E                   	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
E                   	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.hasNext(SerDeUtil.scala:153)
E                   	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
E                   	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.foreach(SerDeUtil.scala:148)
E                   	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:223)
E                   	at org.apache.spark.api.python.PythonRunner$$anon$2.writeIteratorToStream(PythonRunner.scala:439)
E                   	at org.apache.spark.api.python.BasePythonRunner$WriterThread$$anonfun$run$1.apply(PythonRunner.scala:247)
E                   	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1992)
E                   	at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:170)
```

**Comment by yangw1234** [comment]
I can reproduce this when running a anlytics-zoo compiled using spark-2.1.0 but run on spark-2.3.2.
No such problem running on spark-2.1.0.

**Comment by hkvision** [comment]
I tried if I build with spark 2.1 and set SPARK_HOME to spark 2.1 and it works.
But if I build with spark 2.4.3 and use pyspark 2.4.3, the error still exists.
This is still an issue as for pip users they would fail.

**Comment by hkvision** [comment]
In IDE I can successfully run with spark-2.1.0 with zoo build on spark-2.1.0. While when running on a single machine in cluster it still doesn't work... Probably also related to other factors such as TF version? May need more investigation on this.
But since my data is not large, I can first collect and then parallelize to bypass this. Thus it is of low priority.
