### ISSUE TITLE
export_tf gives X is a Placeholder but not listed in inputs

### ISSUE THREAD

**Issue by eyaler** [intel-analytics/analytics-zoo#1519]
trying to export this popular tfhub model i am getting an error on tf=1.13.1

```
import tensorflow as tf
import tensorflow_hub as hub
from tf import export_tf

module_handle = "https://tfhub.dev/google/faster_rcnn/openimages_v4/inception_resnet_v2/1"

with tf.Graph().as_default():
    detector = hub.Module(module_handle)

    image_string_placeholder = tf.placeholder(tf.string)
    decoded_image = tf.image.decode_jpeg(image_string_placeholder)
    decoded_image_float = tf.image.convert_image_dtype(image=decoded_image, dtype=tf.float32)
    module_input = tf.expand_dims(decoded_image_float, 0)
    result = detector(module_input, as_dict=True)
    init_ops = [tf.global_variables_initializer(), tf.tables_initializer()]
    session = tf.Session()
    session.run(init_ops)
    export_tf(session, 'export', inputs=[image_string_placeholder], outputs=[decoded_image, *result.values()])
```

error:
```
Traceback (most recent call last):
  File "C:/Users/eyaler/Dropbox/python/arc/bug_export.py", line 18, in <module>
    export_tf(session, 'export', inputs=[image_string_placeholder], outputs=[decoded_image, *result.values()])
  File "C:\Users\eyaler\Dropbox\python\arc\tf.py", line 123, in export_tf
    % (node.name, inputs))
ValueError: Node module_apply_default/image_tensor is a Placeholder but not listed in inputs, inputs are [<tf.Tensor 'Placeholder:0' shape=<unknown> dtype=string>]
```

**Comment by helenlly** [comment]
@yangw1234  could you help t o have a look? or let me know if you are not right owner,thanks

**Comment by helenlly** [comment]
@yangw1234 could you help t o have a look? and give suggestions?

**Comment by yangw1234** [comment]
this method is deprecated.
