### ISSUE TITLE
How to load checkpoint snapshot?

### ISSUE THREAD

**Issue by hhbyyh** [intel-analytics/analytics-zoo#1550]
Getting NullPointerException when trying to reload model from checkpoint, right now I met error when using both BigDL model and AZ Keras model. I further tried with the unit test in BigDL https://github.com/intel-analytics/BigDL/blob/362ce786936fc30612d1e26c027b1efcbcb9398c/spark/dl/src/test/scala/com/intel/analytics/bigdl/optim/DistriOptimizerSpec.scala#L494, still getting the error when using 
```
    val loaded = Module.loadModule[Float](optimizer.getCheckpointPath().get +
      s"/model.$numIterations")
```

error:
```
java.lang.NullPointerException was thrown.
java.lang.NullPointerException
	at com.intel.analytics.bigdl.utils.serializer.ModuleLoader$.initTensorStorage(ModuleLoader.scala:122)
	at com.intel.analytics.bigdl.utils.serializer.ModuleLoader$.loadFromFile(ModuleLoader.scala:59)
	at com.intel.analytics.bigdl.nn.Module$.loadModule(Module.scala:61)
	at com.intel.analytics.bigdl.optim.DistriOptimizerSpec$$anonfun$17.apply$mcV$sp(DistriOptimizerSpec.scala:500)
	at com.intel.analytics.bigdl.optim.DistriOptimizerSpec$$anonfun$17.apply(DistriOptimizerSpec.scala:474)
	at com.intel.analytics.bigdl.optim.DistriOptimizerSpec$$anonfun$17.apply(DistriOptimizerSpec.scala:474)
```

**Comment by jason-dai** [comment]
try `Net.load`?

**Comment by hhbyyh** [comment]
Tried that, and report same error for keras model.
I checked, save/load works find. The error only happens when loading check point.

**Comment by jason-dai** [comment]
@yangw1234 please take a look

**Comment by yangw1234** [comment]
Snapshot uses Java based serialization and should use `Module.load` to load. `Module.loadModule` is not supposed to work.

**Comment by hhbyyh** [comment]
Oh, I thought we have removed that java serialization function. Thanks @yangw1234
