### ISSUE TITLE
TFNet saveModule reports unrecognized type error 

### ISSUE THREAD

**Issue by hhbyyh** [intel-analytics/analytics-zoo#1563]
Does BigDL supports saving `TFGraphHolder` by default? I met some error.
```
requirement failed: unrecognized type com.intel.analytics.zoo.pipeline.api.net.TFNet.TFGraphHolder
java.lang.IllegalArgumentException: requirement failed: unrecognized type com.intel.analytics.zoo.pipeline.api.net.TFNet.TFGraphHolder
	at scala.Predef$.require(Predef.scala:224)
	at com.intel.analytics.bigdl.utils.serializer.converters.DataConverter$CustomConverterDelegator$.setAttributeValue(DataConverter.scala:571)
	at com.intel.analytics.bigdl.utils.serializer.converters.DataConverter$.setAttributeValue(DataConverter.scala:199)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$$anonfun$doSerializeModule$1.apply(ModuleSerializable.scala:213)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$$anonfun$doSerializeModule$1.apply(ModuleSerializable.scala:199)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.doSerializeModule(ModuleSerializable.scala:199)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.doSerializeModule(ModuleSerializer.scala:35)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.serializeModule(ModuleSerializable.scala:170)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.serializeModule(ModuleSerializer.scala:35)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.serialize(ModuleSerializer.scala:97)
	at com.intel.analytics.bigdl.utils.serializer.ModulePersister$.serializeModule(ModuleLoader.scala:253)
	at com.intel.analytics.bigdl.utils.serializer.ModulePersister$.saveToFile(ModuleLoader.scala:240)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.saveModule(AbstractModule.scala:551)
	at com.intel.analytics.zoo.pipeline.api.net.TFNetSpec$$anonfun$2.apply$mcV$sp(TFNetSpec.scala:65)
	at com.intel.analytics.zoo.pipeline.api.net.TFNetSpec$$anonfun$2.apply(TFNetSpec.scala:61)
	at com.intel.analytics.zoo.pipeline.api.net.TFNetSpec$$anonfun$2.apply(TFNetSpec.scala:61)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
```

code to repro, I think all unit tests can repro the error when trying to save

    val resource = getClass().getClassLoader().getResource("tfnet")
    val net = TFNet(resource.getPath)
    val result = net.forward(Tensor[Float](2, 4).rand())
    net.saveModule("/home/yuhao/workspace/github/hhbyyh/PyTorch_Test/models/m",
    "/home/yuhao/workspace/github/hhbyyh/PyTorch_Test/models/w")

    result.toTensor[Float].size() should be(Array(2, 2))

**Comment by hhbyyh** [comment]
cc @yangw1234 @hkvision

**Comment by hkvision** [comment]
Seems `TFGraphHolder` doesn't have a converter for BigDL serialization.

**Comment by hhbyyh** [comment]
Thanks, what's the recommended way to save a trained TF model?

**Comment by hkvision** [comment]
Use tensorflow to save the model, then use tensorflow to load back and then put it into TFNet?

**Comment by hhbyyh** [comment]
I see.

**Comment by hhbyyh** [comment]
Thanks closing the issue.

**Comment by jason-dai** [comment]
> Use tensorflow to save the model, then use tensorflow to load back and then put it into TFNet?

Do we have an example for this?

**Comment by hkvision** [comment]
> > Use tensorflow to save the model, then use tensorflow to load back and then put it into TFNet?
> 
> Do we have an example for this?

Seems only examples in Python for TFOptimizer...

**Comment by jason-dai** [comment]
> > > Use tensorflow to save the model, then use tensorflow to load back and then put it into TFNet?
> > 
> > 
> > Do we have an example for this?
> 
> Seems only examples in Python for TFOptimizer...

Do you have the link to the example?

**Comment by hkvision** [comment]
> > > > Use tensorflow to save the model, then use tensorflow to load back and then put it into TFNet?
> > > 
> > > 
> > > Do we have an example for this?
> > 
> > 
> > Seems only examples in Python for TFOptimizer...
> 
> Do you have the link to the example?

Here: https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/examples/tensorflow/distributed_training/evaluate_lenet.py#L64
