### ISSUE TITLE
How to support large model ( > 200M parameters) 

### ISSUE THREAD

**Issue by hhbyyh** [intel-analytics/analytics-zoo#1585]
Getting error:

```
Exception in thread "main" java.lang.OutOfMemoryError
	at java.io.ByteArrayOutputStream.hugeCapacity(ByteArrayOutputStream.java:123)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:117)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
	at java.io.ObjectOutputStream$BlockDataOutputStream.flush(ObjectOutputStream.java:1822)
	at java.io.ObjectOutputStream.flush(ObjectOutputStream.java:719)
	at java.io.ObjectOutputStream.close(ObjectOutputStream.java:740)
	at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:160)
	at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:178)
	at org.apache.commons.lang3.SerializationUtils.clone(SerializationUtils.java:81)
	at com.intel.analytics.bigdl.models.utils.ModelBroadcastImp.broadcast(ModelBroadcast.scala:122)
	at com.intel.analytics.bigdl.models.utils.ModelBroadcastImp.broadcast(ModelBroadcast.scala:81)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$.com$intel$analytics$bigdl$optim$DistriOptimizer$$initThreadModels(DistriOptimizer.scala:556)
	at com.intel.analytics.bigdl.optim.DistriOptimizer.optimize(DistriOptimizer.scala:854)
	at com.intel.analytics.zoo.pipeline.nnframes.NNEstimator.internalFit(NNEstimator.scala:441)
	at com.intel.analytics.zoo.pipeline.nnframes.NNEstimator.internalFit(NNEstimator.scala:180)
	at org.apache.spark.ml.DLEstimatorBase.fit(DLEstimatorBase.scala:58)
	at torch.test.TrainingTest$.main(TrainingTest.scala:71)
	at torch.test.TrainingTest.main(TrainingTest.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```
when training a model with 1G param, and keep meeting other OOM errors when trying with model of 400M parameters.

It seems that multiple places in BigDL `ModelBroadcast` are not compatible with large model (exceeding int limit when serialized to byte array).
E.g.
line 122:
`putWeightBias(SerializationUtils.clone(weightsBias), model)`

line 150:
`val localModel = broadcastModel.value.model.cloneModule()`

**Comment by hhbyyh** [comment]
Marking as high priority since it's from customer.

**Comment by jason-dai** [comment]
What's the model size? Spark has 2GB broadcast limit due to Java byte
array.
