### ISSUE TITLE
Something wrong when i run InferenceModel.doLoadTF

### ISSUE THREAD

**Issue by JamesZhan107** [intel-analytics/analytics-zoo#1592]
Caused by: com.intel.analytics.zoo.pipeline.inference.InferenceRuntimeException: Openvino optimize tf image classification model error: 1, E0830 15:14:58.079914 140209311373056 main.py:337] ----------------- INTERNAL ERROR ----------------
	at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$$anonfun$optimizeTFImageClassificationModel$2.apply$mcV$sp(OpenVinoInferenceSupportive.scala:250)
       at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$$anonfun$optimizeTFImageClassificationModel$2.apply(OpenVinoInferenceSupportive.scala:215)
	at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$$anonfun$optimizeTFImageClassificationModel$2.apply(OpenVinoInferenceSupportive.scala:215)
	at com.intel.analytics.zoo.pipeline.inference.InferenceSupportive$class.timing(InferenceSupportive.scala:42)
	at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$.timing(OpenVinoInferenceSupportive.scala:58)
	at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$.optimizeTFImageClassificationModel(OpenVinoInferenceSupportive.scala:215)
	at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$.loadTensorflowModel(OpenVinoInferenceSupportive.scala:482)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModelFactory$.loadOpenVINOModelForTF(InferenceModelFactory.scala:101)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModel.doLoadTensorflowModelAsOpenVINO(InferenceModel.scala:442)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModel.doLoadTF(InferenceModel.scala:271)
	at com.tianchi.james.TextFlatMap.open(TextFlatMap.java:75)

the flink taskexeucutor log:

E0830 15:14:58.067785 140250066544384 main.py:337] ----------------- INTERNAL ERROR ----------------
E0830 15:14:58.067850 140250066544384 main.py:338] Unexpected exception happened.
E0830 15:14:58.067894 140250066544384 main.py:339] Please contact Model Optimizer developers and forward the following information:
E0830 15:14:58.067934 140250066544384 main.py:340] After re-inference of Add_ node, old and new shapes do not match. Old shapes: [array([  1, 224, 224,   3])], new shapes: [array([  1, 224, 224,  -1])].
E0830 15:14:58.068701 140250066544384 main.py:341] Traceback (most recent call last):
  File "/tmp/ZooVino643722341768851616/model-optimizer/mo/main.py", line 325, in main
    return driver(argv)
  File "/tmp/ZooVino643722341768851616/model-optimizer/mo/main.py", line 267, in driver
    mean_scale_values=mean_scale)
  File "/tmp/ZooVino643722341768851616/model-optimizer/mo/pipeline/tf.py", line 317, in tf2nx
    add_mean_scale_values(graph, mean_scale_values)
  File "/tmp/ZooVino643722341768851616/model-optimizer/mo/middle/passes/infer.py", line 385, in add_mean_scale_values
    apply_mean_value(graph, input_node, node_mean_scale_values)
  File "/tmp/ZooVino643722341768851616/model-optimizer/mo/middle/passes/infer.py", line 427, in apply_mean_value
    add_node.create_node_with_data(inputs=[add_input, add_data], data_nodes=out_node)
  File "/tmp/ZooVino643722341768851616/model-optimizer/mo/ops/op.py", line 204, in create_node_with_data
    [data_node.shape for data_node in data_nodes])
AssertionError: After re-inference of Add_ node, old and new shapes do not match. Old shapes: [array([  1, 224, 224,   3])], new shapes: [array([  1, 224, 224,  -1])].

E0830 15:14:58.068830 140250066544384 main.py:342] ---------------- END OF BUG REPORT --------------
E0830 15:14:58.068881 140250066544384 main.py:343] -------------------------------------------------

**Comment by qiyuangong** [comment]
Hi @JamesZhan107 

According to error message, I think your are using wrong input shape `[ 1, 224, 224, -1]`. For now, OpenVINO doesn't support `-1` shape. We need to pass positive input shape.

Can you share detailed parameters used in your program, and the model you are using ?  :)

**Comment by JamesZhan107** [comment]
Thanks for  anwser!   @qiyuangong 

Now,  i find the reason. It is true that the input shape is wrong. After i change the input data shape, problem is solved.

What puzzled me was that Why do errors occur when loading models, not when making predictions?

Close the issuse first.

**Comment by qiyuangong** [comment]
Hi @JamesZhan107 

Your last question is related to OpenVINO's design. 

When it comes to TensorFlow model, OpenVINO need to convert TensorFlow model into OpenVINO model, then load it into memory and device. In analytics-zoo, we merged these 2-steps with `doLoadTF`.

The error you encountered happen in step 1: covert TensorFlow model into OpenVINO model. OpenVINO failed to convert TensorFlow layers into OpenVINO layers based on parameters we given (like input shape). You can imagine it as a pre-check during convert.
