### ISSUE TITLE
after pip install, use pyspark to inital sc, it occurs "TypeError: 'JavaPackage' object is not callable"

### ISSUE THREAD

**Issue by linjiaqin** [intel-analytics/analytics-zoo#1607]
the error information are as below：
Using Python version 2.7.16 (default, Aug 22 2019 16:00:36)
SparkSession available as 'spark'.
>>> from zoo.common.nncontext import *
Prepending /home/linjiaqin/anaconda2/envs/zoo/lib/python2.7/site-packages/bigdl/share/conf/spark-bigdl.conf to sys.path
Adding /home/linjiaqin/anaconda2/envs/zoo/lib/python2.7/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.8.0-spark_2.4.3-0.5.1-jar-with-dependencies.jar to BIGDL_JARS
Prepending /home/linjiaqin/anaconda2/envs/zoo/lib/python2.7/site-packages/zoo/share/conf/spark-analytics-zoo.conf to sys.path
>>> sc = init_nncontext()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/linjiaqin/anaconda2/envs/zoo/lib/python2.7/site-packages/zoo/common/nncontext.py", line 39, in init_nncontext
    redire_spark_logs()
  File "/home/linjiaqin/anaconda2/envs/zoo/lib/python2.7/site-packages/bigdl/util/common.py", line 438, in redire_spark_logs
    callBigDlFunc(bigdl_type, "redirectSparkLogs", log_path)
  File "/home/linjiaqin/anaconda2/envs/zoo/lib/python2.7/site-packages/bigdl/util/common.py", line 580, in callBigDlFunc
    for jinvoker in JavaCreator.instance(bigdl_type, gateway).value:
  File "/home/linjiaqin/anaconda2/envs/zoo/lib/python2.7/site-packages/bigdl/util/common.py", line 56, in instance
    cls._instance = cls(bigdl_type, *args)
  File "/home/linjiaqin/anaconda2/envs/zoo/lib/python2.7/site-packages/bigdl/util/common.py", line 93, in __init__
    self.value.append(getattr(jclass, "ofFloat")())
TypeError: 'JavaPackage' object is not callable

**Comment by hkvision** [comment]
You can't use `pyspark` to start, use `python` instead.
