### ISSUE TITLE
anomaly_detection.py Error: size 8 should be divided by partitionNum 192

### ISSUE THREAD

**Issue by qiyuangong** [intel-analytics/analytics-zoo#1613]
Issue reported from user
```
python anomaly_detection.py --input_dir ./data/nyc_taxi.csv --batch_size 960
```

```
“2019-09-11 23:12:12 INFO  DistriOptimizer$:452 - [Epoch 20 9408/9296][Iteration 980][Wall Clock 60.62146763s] Epoch finished. Wall clock time is 60650.710505 ms
Traceback (most recent call last):
  File "anomaly_detection.py", line 58, in <module>
    y_predict = model.predict(test).map(lambda x: float(x[0]))
  File "/usr/lib/python2.7/site-packages/zoo/models/anomalydetection/anomaly_detector.py", line 100, in predict
    batch_per_thread)
  File "/usr/lib64/python2.7/site-packages/bigdl/util/common.py", line 589, in callBigDlFunc
    raise e
pyspark.sql.utils.IllegalArgumentException: u'requirement failed: Predictor.predict: total batch size 8 should be divided by partitionNum 192'”
```

**Comment by qiyuangong** [comment]
#1614 merged to master. Issue closed. :)
