### ISSUE TITLE
Got java.lang.UnstatisfiedLinkError when load TF model

### ISSUE THREAD

**Issue by DayChan** [intel-analytics/analytics-zoo#1616]
When I execute
``` java
AbstractInferenceModel model = new AbstractInferenceModel(){}
model.loadTF(modelPath, shape1, true , means, 1.0f, "input_1");
```
It throwed exception.
I stepped into found it stucked at
```java
com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive..MODULE$.loadTensorflowModel(savedModelDir, inputShape, ifReverseInputChannels, meanValues, scale, input);
```

Errors are as below:
```
2019-09-14 15:10:03 WARN  InferenceSupportive$:422 - concurrentNum is 20 > 1, openvino model does not support shared weights model copies
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/7m/s6t4m91x1hz_bv1r7ps3nc0h0000gn/T/dlNativeLoader15611260868248979491libiomp5.so: dlopen(/private/var/folders/7m/s6t4m91x1hz_bv1r7ps3nc0h0000gn/T/dlNativeLoader15611260868248979491libiomp5.so, 1): no suitable image found.  Did find:
	/private/var/folders/7m/s6t4m91x1hz_bv1r7ps3nc0h0000gn/T/dlNativeLoader15611260868248979491libiomp5.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/private/var/folders/7m/s6t4m91x1hz_bv1r7ps3nc0h0000gn/T/dlNativeLoader15611260868248979491libiomp5.so: stat() failed with errno=38
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
	at java.base/java.lang.Runtime.load0(Runtime.java:767)
	at java.base/java.lang.System.load(System.java:1831)
	at com.intel.analytics.zoo.core.openvino.OpenvinoNativeLoader.loadLib(OpenvinoNativeLoader.java:61)
	at com.intel.analytics.zoo.core.openvino.OpenvinoNativeLoader.load(OpenvinoNativeLoader.java:44)
	at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$$anonfun$1.apply$mcZ$sp(OpenVinoInferenceSupportive.scala:62)
	at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$$anonfun$1.apply(OpenVinoInferenceSupportive.scala:62)
	at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$$anonfun$1.apply(OpenVinoInferenceSupportive.scala:62)
	at com.intel.analytics.zoo.pipeline.inference.InferenceSupportive$class.timing(InferenceSupportive.scala:42)
	at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$.timing(OpenVinoInferenceSupportive.scala:58)
	at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$.<init>(OpenVinoInferenceSupportive.scala:61)
	at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$.<clinit>(OpenVinoInferenceSupportive.scala)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModelFactory$.loadOpenVINOModelForTF(InferenceModelFactory.scala:91)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModel.doLoadTensorflowModelAsOpenVINO(InferenceModel.scala:426)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModel.doLoadTF(InferenceModel.scala:249)
	at com.intel.analytics.zoo.pipeline.inference.AbstractInferenceModel.loadTF(AbstractInferenceModel.java:83)
	at com.alibaba.tianchi.flinktianchiday.ImageMain.main(ImageMain.java:23)
```

**Comment by qiyuangong** [comment]
Hi @DayChan 
It seems that load OpenVINO related native shared lib encountered some problems. Are you using `model.loadTF` on macOS?

**Comment by DayChan** [comment]
> Hi @DayChan
> It seems that load OpenVINO related native shared lib encountered some problems. Are you using `model.loadTF` on macOS?

Yes, indeed.

**Comment by qiyuangong** [comment]
Hi @DayChan 
In current Zoo release, we used a stable OpenVINO, i.e., 2018_R5, which didn't support macOS originally. We are still working on this problem. 

Best solution in current stage is switching to Ubuntu or running with Docker/VM.

**Comment by DayChan** [comment]
> Hi @DayChan
> In current Zoo release, we used a stable OpenVINO, i.e., 2018_R5, which didn't support macOS originally. We are still working on this problem.
> 
> Best solution in current stage is switching to Ubuntu or running with Docker/VM.

OK, thank you very much : )

**Comment by qiyuangong** [comment]
Issue closed. 

Feel free to re-open it, if you have any further problems. :)
