### ISSUE TITLE
Out of memory issue happened when the big model was broadcast 

### ISSUE THREAD

**Issue by jack1981** [intel-analytics/analytics-zoo#1623]
This issue happened when the parameter size of the model was big , in the progress of broadcasting and here is the exception track : 
base on the exception , we assumed it was because the 2G size limitation of org.apache.commons.lang3.SerializationUtils 

ERROR yarn.ApplicationMaster: User class threw exception: java.lang.OutOfMemoryError
j
java.lang.OutOfMemoryError

at java.io.ByteArrayOutputStream.hugeCapacity(ByteArrayOutputStream.java:123)

at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:117)

at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)

at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)

at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)

at java.io.ObjectOutputStream$BlockDataOutputStream.flush(ObjectOutputStream.java:1822)

at java.io.ObjectOutputStream.flush(ObjectOutputStream.java:719)

at java.io.ObjectOutputStream.close(ObjectOutputStream.java:740)

at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:160)

at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:178)

at org.apache.commons.lang3.SerializationUtils.clone(SerializationUtils.java:81)

at com.intel.analytics.bigdl.models.utils.ModelBroadcastImp.broadcast(ModelBroadcast.scala:122)

at com.intel.analytics.bigdl.models.utils.ModelBroadcastImp.broadcast(ModelBroadcast.scala:81)

at com.intel.analytics.bigdl.optim.DistriOptimizer$.com$intel$analytics$bigdl$optim$DistriOptimizer$$initThreadModels(DistriOptimizer.scala:552)

at com.intel.analytics.bigdl.optim.DistriOptimizer.optimize(DistriOptimizer.scala:843)

at com.intel.analytics.zoo.pipeline.nnframes.NNEstimator.internalFit(NNEstimator.scala:443)

at com.intel.analytics.zoo.pipeline.nnframes.NNEstimator.internalFit(NNEstimator.scala:183)

at org.apache.spark.ml.DLEstimatorBase.fit(DLEstimatorBase.scala:58)

**Comment by jenniew** [comment]
can you provide the example code?

**Comment by jack1981** [comment]
Hi Jenniew
   Could you please reach Yuhao yang , he already reproduced the issue , it is a general issue

Suqiang Song ( Jack)
Director
Software Development Engineering

Mastercard
123 Mission Street  | San Francisco
California
tel 001-650-654-7510  | mobile 001-408-663-0953
[cid:image001.png@01D57555.CE87E4A0]<www.mastercard.com>

**Comment by helenlly** [comment]
@jenniew  could you check the status?
