### ISSUE TITLE
Model predict error

### ISSUE THREAD

**Issue by qwaiz** [intel-analytics/analytics-zoo#1643]
when i use doPredict(...), i get error, i cant understand the error information. please help me,thanks~

The program finished with the following exception:

org.apache.flink.client.program.ProgramInvocationException: Job failed. (JobID: d27b09b6ae906b6122adbe0d229418d2)
	at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:268)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:483)
	at org.apache.flink.streaming.api.environment.StreamContextEnvironment.execute(StreamContextEnvironment.java:66)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:1509)
	at com.hytera.RunMain.main(RunMain.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:529)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:421)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:423)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:813)
	at org.apache.flink.client.cli.CliFrontend.runProgram(CliFrontend.java:287)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:213)
	at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:1050)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$11(CliFrontend.java:1126)
	at org.apache.flink.runtime.security.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:30)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1126)
Caused by: org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
	at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:146)
	at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:265)
	... 18 more
Caused by: java.lang.NullPointerException
	at com.intel.analytics.zoo.pipeline.inference.InferenceModel.retrieveModel(InferenceModel.scala:579)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModel.com$intel$analytics$zoo$pipeline$inference$InferenceModel$$predict(InferenceModel.scala:548)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModel$$anonfun$doPredict$2.apply(InferenceModel.scala:507)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModel$$anonfun$doPredict$2.apply(InferenceModel.scala:504)
	at com.intel.analytics.zoo.pipeline.inference.InferenceSupportive$class.timing(InferenceSupportive.scala:42)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModel.timing(InferenceModel.scala:29)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModel.doPredict(InferenceModel.scala:504)
	at com.intel.analytics.zoo.pipeline.inference.AbstractInferenceModel.predict(AbstractInferenceModel.java:133)
	at com.hytera.PredictFlatMap.flatMap(PredictFlatMap.java:343)
	at com.hytera.PredictFlatMap.flatMap(PredictFlatMap.java:24)
	at org.apache.flink.streaming.api.operators.StreamFlatMap.processElement(StreamFlatMap.java:50)
	at org.apache.flink.streaming.runtime.io.StreamInputProcessor.processInput(StreamInputProcessor.java:202)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask.run(OneInputStreamTask.java:105)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:300)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:748)

**Comment by qiyuangong** [comment]
I think your problem is the same with this error https://github.com/intel-analytics/analytics-zoo/issues/1626#issuecomment-536249938.
```
Caused by: java.lang.NullPointerException
```

**Comment by qiyuangong** [comment]
Issue closed. :)
Feel free to re-open it if you have any further question. :)
