### ISSUE TITLE
[Streaming] Errors when running pyzoo/zoo/examples/streaming/objectdetection

### ISSUE THREAD

**Issue by hhbyyh** [intel-analytics/analytics-zoo#1652]
Run with 
```
MASTER=local[1]
img_path=/home/yuhao/workspace/data/dogs-vs-cats/demo/cats
streaming_path=/home/yuhao/tmp/streaming/buffer
${ANALYTICS_ZOO_HOME}/bin/spark-submit-python-with-zoo.sh \
    --master ${MASTER} \
    --driver-memory 5g \
    image_path_writer.py \
    --streaming_path ${streaming_path} --img_path ${img_path}
```

getting error:

```
2019-10-08 15:36:03 WARN  Utils:66 - Your hostname, yuhao-devbox resolves to a loopback address: 127.0.1.1; using 172.25.115.20 instead (on interface enp8s0)
2019-10-08 15:36:03 WARN  Utils:66 - Set SPARK_LOCAL_IP if you need to bind to another address
Tmp dir at /tmp/5363
Traceback (most recent call last):
  File "/home/yuhao/workspace/github/hhbyyh/analytics-zoo/pyzoo/zoo/examples/streaming/objectdetection/image_path_writer.py", line 67, in <module>
    package_path_to_text(args.streaming_path, args.img_path)
  File "/home/yuhao/workspace/github/hhbyyh/analytics-zoo/pyzoo/zoo/examples/streaming/objectdetection/image_path_writer.py", line 53, in package_path_to_text
    batch_file_name)
OSError: [Errno 18] Invalid cross-device link: '/tmp/5363/0.txt' -> '/home/yuhao/workspace/github/hhbyyh/analytics-zoo/pyzoo/zoo/examples/streaming/objectdetection/buffer/0'
```

**Comment by qiyuangong** [comment]
Got it. Will check it ASAP. :)

**Comment by hhbyyh** [comment]
Reading image from 2019-10-08 15:26:22 INFO  Engine$:112 - Auto detect executor number and executor cores number
2019-10-09 18:28:55 ERROR Executor:91 - Exception in task 0.0 in stage 0.0 (TID 0)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/home/yuhao/workspace/lib/spark-2.1.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 174, in main
    process()
  File "/home/yuhao/workspace/lib/spark-2.1.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 169, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/home/yuhao/workspace/lib/spark-2.1.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/home/yuhao/tmp/streaming/streaming_object_detection.py", line 34, in read_image_file
    img = Image.open(path)
  File "/home/yuhao/anaconda3/lib/python3.5/site-packages/PIL/Image.py", line 2477, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '2019-10-08 15:26:22 INFO  Engine$:112 - Auto detect executor number and executor cores number'

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:89

when running streaming app.

**Comment by qiyuangong** [comment]
#1656 has already merged to master. :)
