### ISSUE TITLE
[attention example]An error occurred while calling o44.connectInputs.

### ISSUE THREAD

**Issue by aqtjin** [intel-analytics/analytics-zoo#1659]
```
Run attention example would occur a problem as below
Traceback (most recent call last):
  File "/home/aqtjin/analytics-zoo/pyzoo/zoo/examples/attention/transformer.py", line 71, in <module>
    O_seq = GlobalAveragePooling1D()(O_seq)
  File "/home/aqtjin/ENTER/envs/tf_env/lib/python3.7/site-packages/zoo/pipeline/api/keras/base.py", line 43, in __call__
    to_list(x)))
  File "/home/aqtjin/ENTER/envs/tf_env/lib/python3.7/site-packages/bigdl/util/common.py", line 589, in callBigDlFunc
    raise e
  File "/home/aqtjin/ENTER/envs/tf_env/lib/python3.7/site-packages/bigdl/util/common.py", line 585, in callBigDlFunc
    result = callJavaFunc(api, *args)
  File "/home/aqtjin/ENTER/envs/tf_env/lib/python3.7/site-packages/bigdl/util/common.py", line 634, in callJavaFunc
    result = func(*args)
  File "/home/aqtjin/ENTER/envs/tf_env/lib/python3.7/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/aqtjin/ENTER/envs/tf_env/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o44.connectInputs.
: java.lang.RuntimeException: Invalid operation
	at com.intel.analytics.bigdl.utils.Shape$class.toSingle(Shape.scala:25)
	at com.intel.analytics.bigdl.utils.MultiShape.toSingle(Shape.scala:81)
	at com.intel.analytics.zoo.pipeline.api.keras.layers.GlobalAveragePooling1D.doBuild(GlobalAveragePooling1D.scala:45)
	at com.intel.analytics.bigdl.nn.keras.KerasLayer.build(KerasLayer.scala:225)
	at com.intel.analytics.bigdl.nn.keras.KerasLayer.inputs(KerasLayer.scala:244)
	at com.intel.analytics.zoo.pipeline.api.keras.python.PythonZooKeras.connectInputs(PythonZooKeras.scala:1164)
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by yangw1234** [comment]
investigated a little bit, seems to be broke by https://github.com/intel-analytics/analytics-zoo/pull/1329/files#diff-a60d1a62bd469b02d4ec0354a58bbaa9R289
