### ISSUE TITLE
[Resnet50ImageClassification Flink example]Openvino optimize tf image classification model error

### ISSUE THREAD

**Issue by respecteverything** [intel-analytics/analytics-zoo#1668]
Run example in Ubuntu16.04.
com.intel.analytics.zoo.pipeline.inference.InferenceRuntimeException: Openvino optimize tf image classification model error: 1, [ ERROR ]  
	at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$$anonfun$optimizeTFImageClassificationModel$1.apply$mcV$sp(OpenVinoInferenceSupportive.scala:200)
	at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$$anonfun$optimizeTFImageClassificationModel$1.apply(OpenVinoInferenceSupportive.scala:166)
	at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$$anonfun$optimizeTFImageClassificationModel$1.apply(OpenVinoInferenceSupportive.scala:166)
	at com.intel.analytics.zoo.pipeline.inference.InferenceSupportive$class.timing(InferenceSupportive.scala:42)
	at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$.timing(OpenVinoInferenceSupportive.scala:58)
	at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$.optimizeTFImageClassificationModel(OpenVinoInferenceSupportive.scala:166)
	at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$.loadTensorflowModel(OpenVinoInferenceSupportive.scala:393)
	at com.intel.analytics.zoo.pipeline.inference.OpenVinoInferenceSupportive$.loadTensorflowModel(OpenVinoInferenceSupportive.scala:433)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModelFactory$.loadOpenVINOModelForTF(InferenceModelFactory.scala:81)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModel.doLoadTensorflowModelAsOpenVINO(InferenceModel.scala:409)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModel.doLoadTF(InferenceModel.scala:226)
	at com.intel.analytics.zoo.apps.model.inference.flink.Resnet50ImageClassification.Resnet50InferenceModel.<init>(Resnet50InferenceModel.scala:6)
	at com.intel.analytics.zoo.apps.model.inference.flink.Resnet50ImageClassification.ModelPredictionMapFunction.open(ImageClassificationStreaming.scala:91)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:424)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:290)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:704)
	at java.lang.Thread.run(Thread.java:748)

**Comment by glorysdj** [comment]
please prepare openvino required optimize env
    apt install python3-pip
    pip3 install numpy
    pip3 install networkx
    pip3 install tensorflow

**Comment by respecteverything** [comment]
Already Fix.
When run`${FLINK_HOME}/bin/flink run \
    -m localhost:8081 -p ${task_slot_num} \
    -c com.intel.analytics.zoo.apps.model.inference.flink.Resnet50ImageClassification.ImageClassificationStreaming  \
    ${ANALYTICS_ZOO_HOME}/apps/model-inference-examples/model-inference-flink/target/model-inference-flink-0.1.0-SNAPSHOT-jar-with-dependencies.jar  \
    --modelType resnet_v1_50 --checkpointPath ${MODEL_PATH}  \
    --inputShape "1,224,224,3" --ifReverseInputChannels true --meanValues "123.68,116.78,103.94" --scale 1`, the `task_slot_num` should be same with or smaller  than `taskmanager.numberofslots` in flink-conf.yaml
