### ISSUE TITLE
Exception while using the pip package generated by release.sh

### ISSUE THREAD

**Issue by zhichao-li** [intel-analytics/analytics-zoo#169]
```
>>> import zoo
2018-05-14 14:00:00 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
2018-05-14 14:00:00 WARN  Utils:66 - Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
2018-05-14 14:00:00 WARN  Utils:66 - Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/zoo/__init__.py", line 25, in <module>
    check_version()
  File "/usr/local/lib/python2.7/dist-packages/zoo/common/nncontext.py", line 46, in check_version
    _check_spark_version(sc, report_warn)
  File "/usr/local/lib/python2.7/dist-packages/zoo/common/nncontext.py", line 58, in _check_spark_version
    version_info = _get_bigdl_verion_conf()
  File "/usr/local/lib/python2.7/dist-packages/zoo/common/nncontext.py", line 105, in _get_bigdl_verion_conf
    " is located in zoo/target/extra-resources")
RuntimeError: Error while locating file zoo-version-info.properties, please make sure the mvn generate-resources phase is executed and a zoo-version-info.properties file is located in zoo/target/extra-resources

```

**Comment by zhichao-li** [comment]
I guess we need to copy `zoo-version-info.properties` into the package as well

**Comment by zhichao-li** [comment]
let's enable the pip install test in nightly built when there's free slot.
