### ISSUE TITLE
build default zoo image failed.

### ISSUE THREAD

**Issue by qiuxin2012** [intel-analytics/analytics-zoo#1707]
Run

https://github.com/intel-analytics/analytics-zoo/tree/master/docker/zoo#by-default-you-can-build-a-analytics-zoodefault-image-with-latest-nightly-build-analytics-zoo-distributions

Will throw error below:
```
Setting up build-essential (12.4ubuntu1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
Collecting setuptools
  Downloading https://mirrors.aliyun.com/pypi/packages/6a/9a/50fadfd53ec909e4399b67c74cc7f4e883488035cfcdb90b685758fa8b34/setuptools-41.4.0-py2.py3-none-any.whl (580kB)
Installing collected packages: setuptools
  Found existing installation: setuptools 39.0.1
    Not uninstalling setuptools at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed setuptools-41.4.0
Collecting numpy
  Downloading https://mirrors.aliyun.com/pypi/packages/ac/36/325b27ef698684c38b1fe2e546e2e7ef9cecd7037bcdb35c87efec4356af/numpy-1.17.2.zip (6.5MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-JZil6o/numpy/setup.py", line 31, in <module>
        raise RuntimeError("Python version >= 3.5 required.")
    RuntimeError: Python version >= 3.5 required.
    
    ----------------------------------------

```

**Comment by glorysdj** [comment]
will change py2 to py3
