### ISSUE TITLE
 TestNNClassifer.test_nnEstimator_fit_with_Cache_Disk failed on Jenkins build

### ISSUE THREAD

**Issue by qiyuangong** [intel-analytics/analytics-zoo#1722]
http://10.239.47.211:18888/job/ZOO-PR-Validation/2694/

```
=================================== FAILURES ===================================
_____________ TestNNClassifer.test_nnEstimator_fit_with_Cache_Disk _____________

self = <test.zoo.pipeline.nnframes.test_nn_classifier.TestNNClassifer object at 0x7f89a45fc828>

    def test_nnEstimator_fit_with_Cache_Disk(self):
        model = Sequential().add(Linear(2, 2))
        criterion = MSECriterion()
        estimator = NNEstimator(model, criterion, SeqToTensor([2]), ArrayToTensor([2])) \
            .setBatchSize(1).setLearningRate(0.2).setMaxEpoch(2) \
            .setDataCacheLevel("DISK_AND_DRAM", 2)
    
        data = self.sc.parallelize([
            ((2.0, 1.0), (1.0, 2.0)),
            ((1.0, 2.0), (2.0, 1.0)),
            ((2.0, 1.0), (1.0, 2.0)),
            ((1.0, 2.0), (2.0, 1.0)),
            ((2.0, 1.0), (1.0, 2.0)),
            ((1.0, 2.0), (2.0, 1.0)),
            ((2.0, 1.0), (1.0, 2.0)),
            ((1.0, 2.0), (2.0, 1.0))])
    
        schema = StructType([
            StructField("features", ArrayType(DoubleType(), False), False),
            StructField("label", ArrayType(DoubleType(), False), False)])
        df = self.sqlContext.createDataFrame(data, schema)
>       estimator.fit(df)

../test/zoo/pipeline/nnframes/test_nn_classifier.py:209: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/work/spark-2.2.2/python/lib/pyspark.zip/pyspark/ml/base.py:64: in fit
    return self._fit(dataset)
/opt/work/spark-2.2.2/python/lib/pyspark.zip/pyspark/ml/wrapper.py:265: in _fit
    java_model = self._fit_java(dataset)
/opt/work/spark-2.2.2/python/lib/pyspark.zip/pyspark/ml/wrapper.py:262: in _fit_java
    return self._java_obj.fit(dataset._jdf)
/opt/work/spark-2.2.2/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py:1257: in __call__
    answer, self.gateway_client, self.target_id, self.name)
/opt/work/spark-2.2.2/python/lib/pyspark.zip/pyspark/sql/utils.py:63: in deco
    return f(*a, **kw)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

answer = 'xro24902'
gateway_client = <py4j.java_gateway.GatewayClient object at 0x7f89ae1259e8>
target_id = 'o24867', name = 'fit'

    def get_return_value(answer, gateway_client, target_id=None, name=None):
        """Converts an answer received from the Java gateway into a Python object.
    
        For example, string representation of integers are converted to Python
        integer, string representation of objects are converted to JavaObject
        instances, etc.
    
        :param answer: the string returned by the Java gateway
        :param gateway_client: the gateway client used to communicate with the Java
            Gateway. Only necessary if the answer is a reference (e.g., object,
            list, map)
        :param target_id: the name of the object from which the answer comes from
            (e.g., *object1* in `object1.hello()`). Optional.
        :param name: the name of the member from which the answer comes from
            (e.g., *hello* in `object1.hello()`). Optional.
        """
        if is_error(answer)[0]:
            if len(answer) > 1:
                type = answer[1]
                value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
                if answer[1] == REFERENCE_TYPE:
                    raise Py4JJavaError(
                        "An error occurred while calling {0}{1}{2}.\n".
>                       format(target_id, ".", name), value)
E                   py4j.protocol.Py4JJavaError: An error occurred while calling o24867.fit.
E                   : java.lang.UnsupportedOperationException: empty collection
E                   	at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$apply$36.apply(RDD.scala:1028)
E                   	at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$apply$36.apply(RDD.scala:1028)
E                   	at scala.Option.getOrElse(Option.scala:121)
E                   	at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1028)
E                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
E                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
E                   	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
E                   	at org.apache.spark.rdd.RDD.reduce(RDD.scala:1008)
E                   	at com.intel.analytics.bigdl.optim.DistriOptimizer$.optimize(DistriOptimizer.scala:150)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
E                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E                   	at java.lang.reflect.Method.invoke(Method.java:498)
E                   	at com.intel.analytics.zoo.pipeline.api.keras.layers.utils.KerasUtils$.invokeMethod(KerasUtils.scala:302)
E                   	at com.intel.analytics.zoo.pipeline.api.keras.layers.utils.KerasUtils$.invokeMethodWithEv(KerasUtils.scala:329)
E                   	at com.intel.analytics.zoo.pipeline.api.keras.models.InternalOptimizerUtil$.optimizeModels(Topology.scala:1014)
E                   	at com.intel.analytics.zoo.pipeline.api.keras.models.InternalDistriOptimizer.train(Topology.scala:1151)
E                   	at com.intel.analytics.zoo.pipeline.api.keras.models.InternalDistriOptimizer.train(Topology.scala:1345)
E                   	at com.intel.analytics.zoo.pipeline.nnframes.NNEstimator.internalFit(NNEstimator.scala:470)
E                   	at com.intel.analytics.zoo.pipeline.nnframes.NNEstimator.internalFit(NNEstimator.scala:198)
E                   	at org.apache.spark.ml.DLEstimatorBase.fit(DLEstimatorBase.scala:58)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
E                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E                   	at java.lang.reflect.Method.invoke(Method.java:498)
E                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
E                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
E                   	at py4j.Gateway.invoke(Gateway.java:282)
E                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
E                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
E                   	at py4j.GatewayConnection.run(GatewayConnection.java:238)
E                   	at java.lang.Thread.run(Thread.java:748)

/opt/work/spark-2.2.2/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py:328: Py4JJavaError
```

**Comment by qiyuangong** [comment]
Already solved. Issue closed. :)
