### ISSUE TITLE
[OpenVINO] Model optimization error after adding BN between FC

### ISSUE THREAD

**Issue by qiyuangong** [intel-analytics/analytics-zoo#1738]
```
[ ERROR ]  Traceback (most recent call last):
  File "/home/intel/Develop/dldt/model-optimizer/mo/main.py", line 325, in main
    return driver(argv)
  File "/home/intel/Develop/dldt/model-optimizer/mo/main.py", line 267, in driver
    mean_scale_values=mean_scale)
  File "/home/intel/Develop/dldt/model-optimizer/mo/pipeline/tf.py", line 356, in tf2nx
    for_graph_and_each_sub_graph_recursively(graph, fuse_linear_ops)
  File "/home/intel/Develop/dldt/model-optimizer/mo/middle/pattern_match.py", line 58, in for_graph_and_each_sub_graph_recursively
    func(graph)
  File "/home/intel/Develop/dldt/model-optimizer/mo/middle/passes/fusing/fuse_linear_ops.py", line 276, in fuse_linear_ops
    is_fused = _fuse_add(graph, node, fuse_nodes, False)
  File "/home/intel/Develop/dldt/model-optimizer/mo/middle/passes/fusing/fuse_linear_ops.py", line 210, in _fuse_add
    fuse_node.in_node(2).value += np.dot(fuse_node.in_node(1).value, value)
  File "<__array_function__ internals>", line 6, in dot
ValueError: shapes (1024,512) and (0,) not aligned: 512 (dim 1) != 0 (dim 0)
```

Quite similar to this error on stackoverflow
https://stackoverflow.com/questions/54644391/how-to-optimize-keras-model-with-batchnorm-layers-with-intel-inference-engine-o

**Comment by qiyuangong** [comment]
It's a known issue about OpenVINO 2018_R5. Will be fixed after upgrading to OpenVINO 2019.
