### ISSUE TITLE
Cluster Serving loading TF and OpenVINO issue

### ISSUE THREAD

**Issue by Litchilitchy** [intel-analytics/analytics-zoo#1773]
in my local pc, tf and openvino work well but on aep-009 they raise error
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/tensorflow_native_libraries-1574080376074-0/libtensorflow_framework.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/tensorflow_native_libraries-1574080376074-0/libtensorflow_framework.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.intel.analytics.zoo.core.TFNetNative.<clinit>(TFNetNative.java:79)
	at com.intel.analytics.zoo.pipeline.api.net.TFNet$.<init>(TFNet.scala:579)
	at com.intel.analytics.zoo.pipeline.api.net.TFNet$.<clinit>(TFNet.scala)
	at com.intel.analytics.zoo.pipeline.inference.ModelLoader$$anonfun$loadFloatModelForTF$1.apply(ModelLoader.scala:62)
	at com.intel.analytics.zoo.pipeline.inference.ModelLoader$$anonfun$loadFloatModelForTF$1.apply(ModelLoader.scala:60)
	at com.intel.analytics.zoo.pipeline.inference.InferenceSupportive$class.timing(InferenceSupportive.scala:42)
	at com.intel.analytics.zoo.pipeline.inference.ModelLoader$.timing(ModelLoader.scala:29)
	at com.intel.analytics.zoo.pipeline.inference.ModelLoader$.loadFloatModelForTF(ModelLoader.scala:60)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModelFactory$.loadFloatModelForTF(InferenceModelFactory.scala:49)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModel.doLoadTensorflowModel(InferenceModel.scala:400)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModel.doLoadTF(InferenceModel.scala:120)
```
However, when running @qiyuangong built version, it could work. Thus, this may be a issue related to compile environment & dependencies. 

Any quick fix to allow every one to build a functioning version? @yangw1234 @qiyuangong

**Comment by Litchilitchy** [comment]
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.tensorflow.Operation.dtype(JJI)I
	at org.tensorflow.Operation.dtype(Native Method)
	at org.tensorflow.Operation.dtype(Operation.java:197)
	at org.tensorflow.Output.dataType(Output.java:54)
	at com.intel.analytics.zoo.pipeline.api.net.TFNet.com$intel$analytics$zoo$pipeline$api$net$TFNet$$name2type(TFNet.scala:480)
	at com.intel.analytics.zoo.pipeline.api.net.TFNet$$anonfun$3.apply(TFNet.scala:119)
	at com.intel.analytics.zoo.pipeline.api.net.TFNet$$anonfun$3.apply(TFNet.scala:119)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at com.intel.analytics.zoo.pipeline.api.net.TFNet.<init>(TFNet.scala:119)
	at com.intel.analytics.zoo.pipeline.api.net.TFNet$.apply(TFNet.scala:754)
	at com.intel.analytics.zoo.pipeline.api.net.TFNet$.apply(TFNet.scala:801)
	at com.intel.analytics.zoo.pipeline.api.net.TFNet$.apply(TFNet.scala:795)
	at com.intel.analytics.zoo.pipeline.inference.ModelLoader$$anonfun$loadFloatModelForTF$1.apply(ModelLoader.scala:62)
	at com.intel.analytics.zoo.pipeline.inference.ModelLoader$$anonfun$loadFloatModelForTF$1.apply(ModelLoader.scala:60)
	at com.intel.analytics.zoo.pipeline.inference.InferenceSupportive$class.timing(InferenceSupportive.scala:42)
	at com.intel.analytics.zoo.pipeline.inference.ModelLoader$.timing(ModelLoader.scala:29)
	at com.intel.analytics.zoo.pipeline.inference.ModelLoader$.loadFloatModelForTF(ModelLoader.scala:60)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModelFactory$.loadFloatModelForTF(InferenceModelFactory.scala:49)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModel.doLoadTensorflowModel(InferenceModel.scala:400)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModel.doLoadTF(InferenceModel.scala:120)
	at com.intel.analytics.zoo.serving.utils.ClusterServingHelper.loadInferenceModel(ClusterServingHelper.scala:171)
	at com.intel.analytics.zoo.serving.ClusterServing$.main(ClusterServing.scala:177)
	at com.intel.analytics.zoo.serving.ClusterServing.main(ClusterServing.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by Litchilitchy** [comment]
also @qiyuangong

**Comment by qiyuangong** [comment]
```
ldd libtensorflow_jni.so 
ldd: warning: you do not have execution permission for `./libtensorflow_jni.so'
./libtensorflow_jni.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./libtensorflow_jni.so)
./libtensorflow_jni.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./libtensorflow_jni.so)
./libtensorflow_jni.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./libtensorflow_jni.so)
	linux-vdso.so.1 =>  (0x00007ffd9ef15000)
	libtensorflow_framework.so.1 => not found
	libiomp5.so => /root/Qiyuan/zoo-jar/linux-x86_64/./libiomp5.so (0x00007fd7524f3000)
	libmklml_intel.so => /root/Qiyuan/zoo-jar/linux-x86_64/./libmklml_intel.so (0x00007fd74aa61000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fd74a85d000)
	libm.so.6 => /lib/libm.so.6 (0x00007fd74a554000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd74a338000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fd74a130000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fd749e29000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fd749c13000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fd749846000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd75c77d000)
```
I guess **libtensorflow_framework.so.1 => not found** may be the root cause.

@yangw1234

**Comment by yangw1234** [comment]
I'll build a version that use lower version of libstdc++

**Comment by qiyuangong** [comment]
```
[ERROR] /home/intel/test_repo/analytics-zoo/zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNetForInference.scala:208: value cast is not a member of org.tensorflow.op.Ops                           [ERROR]         val floatVariable = ops.cast(readVariable, classOf[java.lang.Float])
[ERROR]                                 ^    
[ERROR] /home/intel/test_repo/analytics-zoo/zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNetForInference.scala:213: value graph is not a member of org.tensorflow.op.Scope
[ERROR]         val builder = ops.scope().graph().opBuilder("AssignVariableOp",                                                                                                                                    [ERROR]                                   ^
[ERROR] /home/intel/test_repo/analytics-zoo/zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNetForInference.scala:223: value cast is not a member of org.tensorflow.op.Ops
[ERROR]         val floatVariable = ops.cast(readVariable, classOf[java.lang.Float])
[ERROR]                                 ^
[ERROR] /home/intel/test_repo/analytics-zoo/zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNetForInference.scala:228: value graph is not a member of org.tensorflow.op.Scope
[ERROR]         val builder = ops.scope().graph().opBuilder("Assign",          
[ERROR]                                   ^          
[ERROR] /home/intel/test_repo/analytics-zoo/zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNetForInference.scala:239: value _1 is not a member of Nothing
[ERROR]     val readVariableNames = newOps.map(_._1)                           
[ERROR]                                          ^                             
[ERROR] /home/intel/test_repo/analytics-zoo/zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNetForInference.scala:240: value _2 is not a member of Nothing
[ERROR]     val placeholderNames = newOps.map(_._2)
[ERROR]                                         ^                              
[ERROR] /home/intel/test_repo/analytics-zoo/zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNetForInference.scala:241: value _3 is not a member of Nothing
[ERROR]     val assign = newOps.map(_._3)    
[ERROR]                               ^                                        
[ERROR] /home/intel/test_repo/analytics-zoo/zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNetForInference.scala:242: value _4 is not a member of Nothing                                           [ERROR]     val dataTypes = newOps.map(_._4)                         
[ERROR]                                  ^
[ERROR] /home/intel/test_repo/analytics-zoo/zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNetForInference.scala:243: value _5 is not a member of Nothing
[ERROR]     val dataShapes = newOps.map(x => (x._5, x._6))            
[ERROR]                                         ^
[ERROR] /home/intel/test_repo/analytics-zoo/zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNetForInference.scala:243: value _6 is not a member of Nothing
[ERROR]     val dataShapes = newOps.map(x => (x._5, x._6))                                
[ERROR]                                               ^
[ERROR] /home/intel/test_repo/analytics-zoo/zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNetForInference.scala:245: value graph is not a member of org.tensorflow.op.Scope
[ERROR]     val graphdef = GraphDef.parseFrom(ops.scope().graph().toGraphDef)
[ERROR]                                                   ^
[ERROR] /home/intel/test_repo/analytics-zoo/zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/net/TFNetForInference.scala:248: value graph is not a member of org.tensorflow.op.Scope
[ERROR]       ops.scope().graph().toGraphDef,

```

@Litchilitchy Pls re-base with master.

**Comment by yangw1234** [comment]
TFNet/TFPark now works on aep-009, please verify
