### ISSUE TITLE
Cannot use a model several times to build another

### ISSUE THREAD

**Issue by LoannGio** [intel-analytics/analytics-zoo#1792]
(First Github issue ever so please apologize if I'm doing something wrong)

I'm trying to write with Analytics Zoo a working model written in Keras 2.3 so I can train it on my spark cluster.
In its topology, my model does something like :

```
input1 = Input(shape=(50,10), name="model1_input")
dense = Dense(16, activation="softmax", name="model1_dense")(input1)
model1 = Model(input1, dense, name="model1")

input2 = Input(shape=(50,50), name="model2_input")
models = []
for i in range(5):
    new_layer = Lambda(function=lambda t: t.slice(2, 10,10))(input2)
    new_model = model1(new_layer)
    models.append(new_model)

model2 = Model(input2, models, name="model2")
```

This piece of code works fine in my original keras 2.3 model but implementing this with Analytics Zoo's Keras API (Keras 1.2.2 according to doc) gives a "IllegalArgumentException: requirement failed: Some module is duplicate in the current model: model1" 

Full output with error Message :
creating: createZooKerasModel
creating: createZooKerasInput
creating: createZooKerasVariable
creating: createZooKerasLambdaLayer
creating: createZooKerasVariable
creating: createZooKerasLambdaLayer
creating: createZooKerasVariable
creating: createZooKerasLambdaLayer
creating: createZooKerasVariable
creating: createZooKerasLambdaLayer
creating: createZooKerasVariable
creating: createZooKerasLambdaLayer
creating: createZooKerasModel
Traceback (most recent call last):
  File "/home/toto/Documents/giot/colinware1/test.py", line 21, in <module>
    model2 = Model(input2, models, name="model2")
  File "/home/toto/analytic_zoo/lib/analytics-zoo-bigdl_0.9.1-spark_2.4.3-0.6.0-python-api.zip/zoo/pipeline/api/keras/models.py", line 87, in __init__
  File "/home/toto/analytic_zoo/lib/analytics-zoo-bigdl_0.9.1-spark_2.4.3-0.6.0-python-api.zip/zoo/pipeline/api/keras/base.py", line 91, in __init__
  File "/home/toto/.local/lib/python3.6/site-packages/bigdl/share/lib/bigdl-0.9.0-python-api.zip/bigdl/nn/layer.py", line 131, in __init__
  File "/home/toto/.local/lib/python3.6/site-packages/bigdl/share/lib/bigdl-0.9.0-python-api.zip/bigdl/util/common.py", line 589, in callBigDlFunc
  File "/home/toto/.local/lib/python3.6/site-packages/bigdl/share/lib/bigdl-0.9.0-python-api.zip/bigdl/util/common.py", line 585, in callBigDlFunc
  File "/home/toto/.local/lib/python3.6/site-packages/bigdl/share/lib/bigdl-0.9.0-python-api.zip/bigdl/util/common.py", line 634, in callJavaFunc
  File "/home/toto/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/home/toto/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o37.createZooKerasModel.
: java.lang.IllegalArgumentException: requirement failed: Some module is duplicate in the current model: model1
	at scala.Predef$.require(Predef.scala:224)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.checkDuplicate(AbstractModule.scala:1127)
	at com.intel.analytics.bigdl.nn.Container.checkDuplicate(Container.scala:227)
	at com.intel.analytics.bigdl.nn.Container$$anonfun$checkDuplicate$1.apply(Container.scala:228)
	at com.intel.analytics.bigdl.nn.Container$$anonfun$checkDuplicate$1.apply(Container.scala:228)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.intel.analytics.bigdl.nn.Container.checkDuplicate(Container.scala:228)
	at com.intel.analytics.bigdl.nn.StaticGraph.populateModules(StaticGraph.scala:124)
	at com.intel.analytics.bigdl.nn.Graph.<init>(Graph.scala:150)
	at com.intel.analytics.bigdl.nn.StaticGraph.<init>(StaticGraph.scala:43)
	at com.intel.analytics.zoo.pipeline.api.keras.models.Model.doBuild(Topology.scala:623)
	at com.intel.analytics.zoo.pipeline.api.keras.models.Model.<init>(Topology.scala:604)
	at com.intel.analytics.zoo.pipeline.api.keras.models.Model$.apply(Topology.scala:719)
	at com.intel.analytics.zoo.pipeline.api.keras.python.PythonZooKeras.createZooKerasModel(PythonZooKeras.scala:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

**Comment by hkvision** [comment]
Hi @LoannGio You got this error because currently we don't support share weights / reuse modules. Sorry about that. As an alternative, I think you can possibly flatten your input into shape (250, 10), and pass through a single Dense(16) layer, and then slice back to five outputs?

**Comment by LoannGio** [comment]
Hi, thanks for your answer.
I'll try that and some other things I've thought of. I'll have to change my topology anyway.

**Comment by hkvision** [comment]
Sure. Feel free to tell us if you encounter further problems. We will give you feedback as soon as possible.
