### ISSUE TITLE
libjdnn.dylib not found in macOS

### ISSUE THREAD

**Issue by qiyuangong** [intel-analytics/analytics-zoo#2075]
Seems like this bigdl lib is missing in our jar.

```
Exception in thread "main" java.lang.Error: Can't find the library libjdnn.dylib in the resource folder.
	at com.intel.analytics.bigdl.mkl.Loader.resource(Loader.java:89)
	at com.intel.analytics.bigdl.mkl.Loader.copyAll(Loader.java:80)
	at com.intel.analytics.bigdl.mkl.Loader.init(Loader.java:52)
	at com.intel.analytics.bigdl.mkl.MklDnn.<clinit>(MklDnn.java:27)
	at com.intel.analytics.bigdl.mkl.hardware.Affinity.<clinit>(Affinity.java:16)
	at com.intel.analytics.bigdl.utils.Engine$.setMklDnnEnvironments(Engine.scala:571)
	at com.intel.analytics.bigdl.utils.Engine$.<init>(Engine.scala:47)
	at com.intel.analytics.bigdl.utils.Engine$.<clinit>(Engine.scala)
	at com.intel.analytics.zoo.examples.vnni.openvino.Perf$$anonfun$main$1.apply(Perf.scala:72)
	at com.intel.analytics.zoo.examples.vnni.openvino.Perf$$anonfun$main$1.apply(Perf.scala:62)
	at scala.Option.foreach(Option.scala:257)
	at com.intel.analytics.zoo.examples.vnni.openvino.Perf$.main(Perf.scala:62)
	at com.intel.analytics.zoo.examples.vnni.openvino.Perf.main(Perf.scala)
```

**Comment by qiyuangong** [comment]
After detailed check in 0.7 release, this lib is also missing. It will lead to exception on macOS if we use initEngine.

**Comment by i8run** [comment]
Hi @qiyuangong , We haven't supported `mkldnn` backend on OSX. Thanks.

**Comment by qiyuangong** [comment]
Got it. :)

I also found that is cause by my code problem. I should not set `mkdnn` when using openvino backend.

**Comment by qiyuangong** [comment]
Issue closed. :)
