### ISSUE TITLE
Caused by: java.lang.RuntimeException: Didn't find weight block test_0weightBytes1 in the block manager. Did you initialize this AllReduceParameter on every executor

### ISSUE THREAD

**Issue by qiuxin2012** [intel-analytics/analytics-zoo#2112]
A error message and related solution from customer support:

When run zoo apps on yarn, and get below error, it may be caused by OutOfMemory error in executors.
If you meet this error, please check your executors' log to see if it's a OutOfMemory error. To sovle this, you can increase the executor memory, or decrease training batchsize.
```
Caused by: java.lang.RuntimeException: Didn't find weight block test_0weightBytes1 in the block manager. Did you initialize this AllReduceParameter on every executor?
	at com.intel.analytics.bigdl.parameters.AllReduceParameter$$anonfun$1$$anon$3$$anonfun$2.apply(AllReduceParameter.scala:209)

	at com.intel.analytics.bigdl.parameters.AllReduceParameter$$anonfun$1$$anon$3$$anonfun$2.apply(AllReduceParameter.scala:209)

	at scala.Option.getOrElse(Option.scala:121)

	at com.intel.analytics.bigdl.parameters.AllReduceParameter$$anonfun$1$$anon$3.call(AllReduceParameter.scala:208)

	at com.intel.analytics.bigdl.parameters.AllReduceParameter$$anonfun$1$$anon$3.call(AllReduceParameter.scala:204)

	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

	... 3 more
```

**Comment by dding3** [comment]
@qiuxin2012  What do you think if we update the error message as 
"Didn't find weight block test_0weightBytes1 in the block manager. This is usually caused by executor crashed. Please check your executors' log to see the error(usually a OutOfMemory error)"

**Comment by jason-dai** [comment]
Yes, we should add more detailed error messages.
