### ISSUE TITLE
module 'scipy.misc' has no attribute 'imread' for new scipy version in app variational-autoencoder/utils.py

### ISSUE THREAD

**Issue by glorysdj** [intel-analytics/analytics-zoo#2187]
AttributeError: module 'scipy.misc' has no attribute 'imread'

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:452)
	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:588)
	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:571)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:406)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more

**Comment by glorysdj** [comment]
scipy.misc.imresize is also deprecated

**Comment by glorysdj** [comment]
code 
https://github.com/intel-analytics/analytics-zoo/blob/master/apps/variational-autoencoder/utils.py

**Comment by glorysdj** [comment]
the recent env:
imageio                   2.8.0                      py_0    conda-forge
pillow                    7.1.1            py36h8328e55_0    conda-forge
scipy                     1.4.1            py36h2d22cac_2    conda-forge

**Comment by glorysdj** [comment]
scipy.misc.imresize
scipy.misc.imresize(*args, **kwds)
imresize is deprecated! imresize is deprecated in SciPy 1.0.0, and will be removed in 1.3.0. Use Pillow instead: numpy.array(Image.fromarray(arr).resize()).

scipy.misc.imread(*args, **kwds)
imread is deprecated! imread is deprecated in SciPy 1.0.0, and will be removed in 1.2.0. Use imageio.imread instead.
