### ISSUE TITLE
java.lang.NoSuchMethodError for json4s exception

### ISSUE THREAD

**Issue by glorysdj** [intel-analytics/analytics-zoo#2188]
http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Python-AppTests-part3/18/console

java.lang.NoSuchMethodError: org.json4s.jackson.JsonMethods$.parse(Lorg/json4s/JsonInput;Z)Lorg/json4s/JsonAST$JValue;
	at com.intel.analytics.zoo.pipeline.api.net.NetUtils$.processTFFolder(NetUtils.scala:196)
	at com.intel.analytics.zoo.pipeline.api.net.TFNet$.apply(TFNet.scala:649)
	at com.intel.analytics.zoo.pipeline.api.net.TFNet$.apply(TFNet.scala:645)
	at com.intel.analytics.zoo.pipeline.api.net.python.PythonZooNet.createTFNet(PythonZooNet.scala:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

**Comment by glorysdj** [comment]
fixed
