### ISSUE TITLE
error when run apps/pytorch/face_generation.py

### ISSUE THREAD

**Issue by glorysdj** [intel-analytics/analytics-zoo#2189]
Traceback (most recent call last):
  File "/opt/work/jenkins/workspace/ZOO-PR-Python-AppTests-part3/dist/apps/pytorch/face_generation.py", line 39, in <module>
    pretrained=True, useGPU=False)
  File "/opt/work/conda/envs/py36/lib/python3.6/site-packages/torch/hub.py", line 340, in load
    model = entry(*args, **kwargs)
  File "/root/.cache/torch/hub/facebookresearch_pytorch_GAN_zoo_hub/hubconf.py", line 95, in PGAN
    state_dict = model_zoo.load_url(checkpoint[kwargs["model_name"]], map_location='cpu')
  File "/opt/work/conda/envs/py36/lib/python3.6/site-packages/torch/hub.py", line 433, in load_state_dict_from_url
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/opt/work/conda/envs/py36/lib/python3.6/site-packages/torch/hub.py", line 377, in _download_url_to_file
    .format(hash_prefix, digest))
RuntimeError: invalid hash value (expected "9c72988c", got "a0dcaa0a29addee3247c54b11dc75ac6b410c2768bab9fd01402d4abe321dec7")

http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Python-AppTests-part3/19/console

**Comment by glorysdj** [comment]
fixed
