### ISSUE TITLE
org/tensorflow/util/SaverDefOrBuilder when pip test python examples

### ISSUE THREAD

**Issue by glorysdj** [intel-analytics/analytics-zoo#2204]
http://10.239.47.210:18888/view/ZOO-PR/job/ZOO-PR-Pip-Example-Integration/93/consoleFull

py4j.protocol.Py4JJavaError: An error occurred while calling o47.createTFNetFromSavedModel.
: java.lang.NoClassDefFoundError: org/tensorflow/util/SaverDefOrBuilder
	at com.intel.analytics.zoo.pipeline.api.net.TFNetForInference$.fromSavedModel(TFNetForInference.scala:232)
	at com.intel.analytics.zoo.pipeline.api.net.python.PythonZooNet.createTFNetFromSavedModel(PythonZooNet.scala:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.tensorflow.util.SaverDefOrBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more

Clearing up environment. Uninstalling analytics-zoo
Found existing installation: analytics-zoo 0.8.0.dev0
Uninstalling analytics-zoo-0.8.0.dev0:
  Successfully uninstalled analytics-zoo-0.8.0.dev0
Found existing installation: BigDL 0.10.0
Uninstalling BigDL-0.10.0:
  Successfully uninstalled BigDL-0.10.0
Found existing installation: pyspark 2.4.3
Uninstalling pyspark-2.4.3:
  Successfully uninstalled pyspark-2.4.3
tensorflow distributed_training evaluate_lenet failed

**Comment by yangw1234** [comment]
this is because the class file is deleted in building pip whl in #1892

**Comment by yangw1234** [comment]
@Litchilitchy how about just deleting the conflict class instead of the whole package?

**Comment by yangw1234** [comment]
fixed http://172.168.2.101:8080/view/ZOO-PR/job/ZOO-PR-Pip-Example-Integration/99/console
