### ISSUE TITLE
NullPointerException when using Estimator

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/analytics-zoo#2270]
> When we run yarn client mode , it can finish but had previous exception
But when we run yarn cluster mode, we got another exception, here are the details :

+------+----+------+-----+-------------------+
| uid| mid|labels|count| features|
+------+----+------+-----+-------------------+
| 344.0|21.0| 0.0| 2| [344.0, 21.0, 2.0]|
| 238.0|98.0| 0.0| 0| [238.0, 98.0, 0.0]|
| 785.0| 2.0| 0.0| 0| [785.0, 2.0, 0.0]|
|3318.0|23.0| 0.0| 0|[3318.0, 23.0, 0.0]|
|2196.0|12.0| 0.0| 1|[2196.0, 12.0, 1.0]|
+------+----+------+-----+-------------------+
only showing top 5 rows

pos: 6271 neg: 3914
label df count: 10185
+------+----+------+-----+-------------------+
| uid| mid|labels|count| features|
+------+----+------+-----+-------------------+
|1574.0| 4.0| 0.0| 2| [1574.0, 4.0, 2.0]|
| 4.0| 9.0| 0.0| 27| [4.0, 9.0, 27.0]|
|1966.0|11.0| 0.0| 0|[1966.0, 11.0, 0.0]|
| 457.0| 3.0| 0.0| 7| [457.0, 3.0, 7.0]|
| 527.0| 6.0| 0.0| 3| [527.0, 6.0, 3.0]|
+------+----+------+-----+-------------------+
only showing top 5 rows

pos: 6272 neg: 3918
label df count: 10190
+------+----+------+-----+-------------------+
| uid| mid|labels|count| features|
+------+----+------+-----+-------------------+
| 4.0| 9.0| 0.0| 35| [4.0, 9.0, 35.0]|
|2041.0| 2.0| 0.0| 1| [2041.0, 2.0, 1.0]|
|3678.0|11.0| 0.0| 0|[3678.0, 11.0, 0.0]|
| 853.0| 6.0| 0.0| 1| [853.0, 6.0, 1.0]|
|3176.0|89.0| 0.0| 1|[3176.0, 89.0, 1.0]|
+------+----+------+-----+-------------------+
only showing top 5 rows

WARNING:tensorflow:From /dfs/1/yarn/nm/usercache/dw/appcache/application_1586627890098_48586/container_e21_1586627890098_48586_02_000001/venv.zip/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/initializers.py:119: calling RandomUniform.init (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:OMP_NUM_THREADS is no longer used by the default Keras config. To configure the number of threads, use tf.config.threading APIs.
2020-04-26 21:47:12.901176: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-04-26 21:47:12.901217: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2020-04-26 21:47:12.901245: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (hdp2stl020005.mastercard.int): /proc/driver/nvidia/version does not exist
2020-04-26 21:47:12.901617: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-04-26 21:47:12.917515: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2100000000 Hz
2020-04-26 21:47:12.920890: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55baf2a8dac0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-26 21:47:12.920915: I tensorflow/compiler/xla/service/service.cc:176] StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From /dfs/1/yarn/nm/usercache/dw/appcache/application_1586627890098_48586/container_e21_1586627890098_48586_02_000001/venv.zip/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.init (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Model: "model"

Layer (type) Output Shape Param # Connected to
input_1 (InputLayer) [(None, 3)] 0

tf_op_layer_strided_slice (Tens [(None,)] 0 input_1[0][0]

tf_op_layer_strided_slice_1 (Te [(None,)] 0 input_1[0][0]

embedding (Embedding) (None, 100) 2000100 tf_op_layer_strided_slice[0][0]

embedding_1 (Embedding) (None, 50) 10050 tf_op_layer_strided_slice_1[0][0]

flatten (Flatten) (None, 100) 0 embedding[0][0]

flatten_1 (Flatten) (None, 50) 0 embedding_1[0][0]

concatenate (Concatenate) (None, 150) 0 flatten[0][0]
flatten_1[0][0]

dense (Dense) (None, 75) 11325 concatenate[0][0]

dense_1 (Dense) (None, 2) 152 dense[0][0]
Total params: 2,021,627
Trainable params: 2,021,627
Non-trainable params: 0

WARNING:tensorflow:From /dfs/1/yarn/nm/usercache/dw/appcache/application_1586627890098_48586/container_e21_1586627890098_48586_02_000001/venv.zip/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/math_grad.py:1424: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /dfs/1/yarn/nm/usercache/dw/appcache/application_1586627890098_48586/container_e21_1586627890098_48586_02_000001/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/tfpark/tf_optimizer.py:616: The name tf.keras.backend.get_session is deprecated. Please use tf.compat.v1.keras.backend.get_session instead.

creating: createRMSprop
creating: createSampleToMiniBatch
creating: createSampleToMiniBatch
creating: createZooKerasSparseCategoricalCrossEntropy
creating: createLoss
creating: createZooKerasSparseCategoricalAccuracy
WARNING:tensorflow:From /dfs/1/yarn/nm/usercache/dw/appcache/application_1586627890098_48586/container_e21_1586627890098_48586_02_000001/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/tfpark/tf_optimizer.py:157: The name tf.is_numeric_tensor is deprecated. Please use tf.debugging.is_numeric_tensor instead.

creating: createTFValidationMethod
creating: createTFValidationMethod
WARNING:tensorflow:From /dfs/1/yarn/nm/usercache/dw/appcache/application_1586627890098_48586/container_e21_1586627890098_48586_02_000001/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/tfpark/tf_optimizer.py:175: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /dfs/1/yarn/nm/usercache/dw/appcache/application_1586627890098_48586/container_e21_1586627890098_48586_02_000001/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/util/tf.py:37: The name tf.unsorted_segment_sum is deprecated. Please use tf.math.unsorted_segment_sum instead.

WARNING:tensorflow:From /dfs/1/yarn/nm/usercache/dw/appcache/application_1586627890098_48586/container_e21_1586627890098_48586_02_000001/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/tfpark/tf_optimizer.py:185: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From /dfs/1/yarn/nm/usercache/dw/appcache/application_1586627890098_48586/container_e21_1586627890098_48586_02_000001/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/tfpark/tf_optimizer.py:199: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /dfs/1/yarn/nm/usercache/dw/appcache/application_1586627890098_48586/container_e21_1586627890098_48586_02_000001/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/tfpark/tf_optimizer.py:200: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.

WARNING:tensorflow:From /dfs/1/yarn/nm/usercache/dw/appcache/application_1586627890098_48586/container_e21_1586627890098_48586_02_000001/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/tfpark/tf_optimizer.py:239: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

WARNING:tensorflow:From /dfs/1/yarn/nm/usercache/dw/appcache/application_1586627890098_48586/container_e21_1586627890098_48586_02_000001/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/tfpark/tf_optimizer.py:272: The name tf.tables_initializer is deprecated. Please use tf.compat.v1.tables_initializer instead.

WARNING:tensorflow:From /dfs/1/yarn/nm/usercache/dw/appcache/application_1586627890098_48586/container_e21_1586627890098_48586_02_000001/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/tfpark/tf_optimizer.py:281: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

creating: createTFTrainingHelper
linux-x86_64/libiomp5.so
linux-x86_64/libmklml_intel.so
linux-x86_64/libtensorflow_framework-zoo.so
linux-x86_64/libtensorflow_jni.so
creating: createIdentityCriterion
creating: createSampleToMiniBatch
creating: createSampleToMiniBatch
creating: createEstimator
creating: createMaxEpoch
creating: createEveryEpoch
Traceback (most recent call last):
File "ncf_dl_keras.py", line 175, in
model.fit(dataset,epochs=max_epoch,distributed=True)
File "/dfs/1/yarn/nm/usercache/dw/appcache/application_1586627890098_48586/container_e21_1586627890098_48586_02_000001/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/tfpark/model.py", line 141, in fit
File "/dfs/1/yarn/nm/usercache/dw/appcache/application_1586627890098_48586/container_e21_1586627890098_48586_02_000001/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/tfpark/model.py", line 164, in _fit_distributed
File "/dfs/1/yarn/nm/usercache/dw/appcache/application_1586627890098_48586/container_e21_1586627890098_48586_02_000001/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/tfpark/tf_optimizer.py", line 703, in optimize
File "/dfs/1/yarn/nm/usercache/dw/appcache/application_1586627890098_48586/container_e21_1586627890098_48586_02_000001/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/pipeline/estimator/estimator.py", line 103, in train_minibatch
File "/dfs/1/yarn/nm/usercache/dw/appcache/application_1586627890098_48586/container_e21_1586627890098_48586_02_000001/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/common/utils.py", line 129, in callZooFunc
File "/dfs/1/yarn/nm/usercache/dw/appcache/application_1586627890098_48586/container_e21_1586627890098_48586_02_000001/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/common/utils.py", line 123, in callZooFunc
File "/opt/cloudera/parcels/SPARK2-2.4.0.cloudera2-1.cdh5.13.3.p0.1041012/lib/spark2/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in call
File "/opt/cloudera/parcels/SPARK2-2.4.0.cloudera2-1.cdh5.13.3.p0.1041012/lib/spark2/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
File "/opt/cloudera/parcels/SPARK2-2.4.0.cloudera2-1.cdh5.13.3.p0.1041012/lib/spark2/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o66.estimatorTrainMiniBatch.
: java.lang.NullPointerException
at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:192)
at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:192)
at scala.collection.SeqLike$class.size(SeqLike.scala:106)
at scala.collection.mutable.ArrayOps$ofRef.size(ArrayOps.scala:186)
at scala.collection.mutable.Builder$class.sizeHint(Builder.scala:69)
at scala.collection.mutable.ArrayBuilder.sizeHint(ArrayBuilder.scala:22)
at scala.collection.TraversableLike$class.builder$1(TraversableLike.scala:230)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:233)
at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
at com.intel.analytics.zoo.pipeline.api.keras.models.InternalDistriOptimizer$.getLatestFile(Topology.scala:1531)
at com.intel.analytics.zoo.pipeline.api.keras.models.InternalDistriOptimizer.train(Topology.scala:1229)
at com.intel.analytics.zoo.pipeline.api.keras.models.InternalDistriOptimizer.train(Topology.scala:1382)
at com.intel.analytics.zoo.pipeline.api.keras.models.InternalDistriOptimizer.train(Topology.scala:1070)
at com.intel.analytics.zoo.pipeline.estimator.Estimator.train(Estimator.scala:152)
at com.intel.analytics.zoo.pipeline.estimator.python.PythonEstimator.estimatorTrainMiniBatch(PythonEstimator.scala:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
at py4j.Gateway.invoke(Gateway.java:282)
at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
at py4j.commands.CallCommand.execute(CallCommand.java:79)
at py4j.GatewayConnection.run(GatewayConnection.java:238)
at java.lang.Thread.run(Thread.java:748)

**Comment by jack1981** [comment]
Update : 
We added those spark-configurations ,the exceptions gone and job was finished in Yarn Cluster mode , no idea which one impacted ...
Guess something associated with our cluster , if it did not show from other places , then I think we can close it.

--conf spark.sql.catalogImplementation=hive \
    --conf spark.dynamicAllocation.enabled=false \
    --conf spark.ui.showConsoleProgress=false \
    --conf spark.driver.extraJavaOptions="-XX:ParallelGCThreads=8 -XX:+UseParallelGC -XX:+UseParallelOldGC " \
    --conf spark.locality.wait=1s \
    --conf spark.driver.maxResultSize=10g \
    --conf spark.sql.parquet.binaryAsString=true \
    --conf spark.rpc.io.serverThreads=64 \
    --conf spark.executor.extraJavaOptions="-XX:ParallelGCThreads=8 -XX:+UseParallelGC -XX:+UseParallelOldGC" \
    --conf spark.shuffle.consolidateFiles=true \
    --conf spark.rdd.compress=true \
    --conf spark.stage.maxConsecutiveAttempts=10 \
    --conf spark.network.timeout=10000000 \
    --conf spark.executor.heartbeatInterval=10000000 \

**Comment by yangw1234** [comment]
Hi @jack1981 , thank you for the update. I'll first close it then. Please kindly reopen if it shows up again.
