### ISSUE TITLE
Cluster Serving SparseTensor Support

### ISSUE THREAD

**Issue by respecteverything** [intel-analytics/analytics-zoo#2334]
It seems our cluster serving does not support SparseTensor as input.

```
java.lang.IllegalArgumentException: requirement failed: SparseLinear's input must be a SparseTensor,but got com.intel.analytics.bigdl.tensor.DenseType$@7d335e02
        at scala.Predef$.require(Predef.scala:224)
        at com.intel.analytics.bigdl.nn.SparseLinear.updateOutput(SparseLinear.scala:61)
        at com.intel.analytics.bigdl.nn.SparseLinear.updateOutput(SparseLinear.scala:44)
        at com.intel.analytics.bigdl.nn.keras.KerasLayer.updateOutput(KerasLayer.scala:187)
        at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:259)
        at com.intel.analytics.bigdl.nn.StaticGraph.updateOutput(StaticGraph.scala:62)
        at com.intel.analytics.bigdl.nn.keras.KerasLayer.updateOutput(KerasLayer.scala:187)
        at com.intel.analytics.zoo.models.common.ZooModel.updateOutput(ZooModel.scala:120)
        at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:259)
        at com.intel.analytics.zoo.pipeline.inference.FloatModel.predict(FloatModel.scala:55)
        at com.intel.analytics.zoo.pipeline.inference.InferenceModel.predict(InferenceModel.scala:751)
        at com.intel.analytics.zoo.pipeline.inference.InferenceModel.doPredict(InferenceModel.scala:732)
        at com.intel.analytics.zoo.serving.ClusterServing$$anonfun$2$$anonfun$3$$anonfun$apply$1$$anonfun$apply$2.apply(ClusterServing.scala:188)
        at com.intel.analytics.zoo.serving.ClusterServing$$anonfun$2$$anonfun$3$$anonfun$apply$1$$anonfun$apply$2.apply(ClusterServing.scala:178)
        at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:657)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
        at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:648)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

        at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:265)
        at com.intel.analytics.bigdl.nn.StaticGraph.updateOutput(StaticGraph.scala:62)
        at com.intel.analytics.bigdl.nn.keras.KerasLayer.updateOutput(KerasLayer.scala:187)
        at com.intel.analytics.zoo.models.common.ZooModel.updateOutput(ZooModel.scala:120)
        at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:259)
        at com.intel.analytics.zoo.pipeline.inference.FloatModel.predict(FloatModel.scala:55)
        at com.intel.analytics.zoo.pipeline.inference.InferenceModel.predict(InferenceModel.scala:751)
        at com.intel.analytics.zoo.pipeline.inference.InferenceModel.doPredict(InferenceModel.scala:732)
        at com.intel.analytics.zoo.serving.ClusterServing$$anonfun$2$$anonfun$3$$anonfun$apply$1$$anonfun$apply$2.apply(ClusterServing.scala:188)
        at com.intel.analytics.zoo.serving.ClusterServing$$anonfun$2$$anonfun$3$$anonfun$apply$1$$anonfun$apply$2.apply(ClusterServing.scala:178)
        at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:657)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
        at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:648)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by respecteverything** [comment]
Btw, if we add some functions to get input shape and type in inferenceModel, it would be much more convenience.

**Comment by jason-dai** [comment]
@Litchilitchy please take a look
