### ISSUE TITLE
Error while deploying spark-submit-python-with-zoo.sh

### ISSUE THREAD

**Issue by apprenticearnab** [intel-analytics/analytics-zoo#2393]
Hi , I am Arnab , while running this command in the terminal ,

`${ANALYTICS_ZOO_HOME}/bin/spark-submit-python-with-zoo.sh --master spark://arnab:7077 `/home/arnab/Desktop/spark/examples/src/main/python/pi.py``,

I am getting this type of error ,

Traceback (most recent call last):
  File "/home/arnab/Desktop/spark/examples/src/main/python/pi.py", line 33, in <module>
    .appName("PythonPi")\
  File "/home/arnab/Desktop/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 183, in getOrCreate
  File "/home/arnab/Desktop/spark/python/lib/pyspark.zip/pyspark/context.py", line 370, in getOrCreate
  File "/home/arnab/Desktop/spark/python/lib/pyspark.zip/pyspark/context.py", line 130, in __init__
  File "/home/arnab/Desktop/spark/python/lib/pyspark.zip/pyspark/context.py", line 192, in _do_init
  File "/home/arnab/Desktop/spark/python/lib/pyspark.zip/pyspark/context.py", line 309, in _initialize_context
  File "/home/arnab/Desktop/spark/python/lib/py4j-0.10.8.1-src.zip/py4j/java_gateway.py", line 1554, in __call__
  File "/home/arnab/Desktop/spark/python/lib/py4j-0.10.8.1-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: java.lang.ExceptionInInitializerError
	at org.apache.spark.storage.BlockManagerMasterEndpoint.<init>(BlockManagerMasterEndpoint.scala:93)
	at org.apache.spark.SparkEnv$.$anonfun$create$9(SparkEnv.scala:369)
	at org.apache.spark.SparkEnv$.registerOrLookupEndpoint$1(SparkEnv.scala:310)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:358)
	at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:188)
	at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:277)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:462)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at org.apache.commons.lang3.SystemUtils.isJavaVersionAtLeast(SystemUtils.java:1626)
	at org.apache.spark.storage.StorageUtils$.<init>(StorageUtils.scala:207)
	at org.apache.spark.storage.StorageUtils$.<clinit>(StorageUtils.scala)

Can anyone please help me in coping up with this issue as I am unable to figure it out?
Other things are working well.

**Comment by hkvision** [comment]
Hi @apprenticearnab There's error when creating a SparkContext, which is not related to Analytics Zoo actually. Probably you can check your spark/pyspark settings?

**Comment by apprenticearnab** [comment]
Thank you sir . I have resolved this issue and I am closing this .
