### ISSUE TITLE
XShards __del__ gets exception if xshards was not cached before

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/analytics-zoo#2433]
When xshards.__del__ is called by gc, if xshards was not cached before, it gets such exception:
Exception ignored in: <bound method SparkXShards.__del__ of <zoo.orca.data.shard.SparkXShards object at 0x7fa5ce0c1470>>
Traceback (most recent call last):
  File "/home/jwang/git/analytics-zoo-jennie4/dist/lib/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/orca/data/shard.py", line 282, in __del__
  File "/home/jwang/git/analytics-zoo-jennie4/dist/lib/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/orca/data/shard.py", line 148, in uncache
  File "/tools/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/rdd.py", line 255, in unpersist
  File "/tools/spark-2.4.3-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/tools/spark-2.4.3-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 332, in get_return_value
py4j.protocol.Py4JError: An error occurred while calling o81.unpersist. Trace:
py4j.Py4JException: Target Object ID does not exist for this gateway :o81
	at py4j.Gateway.invoke(Gateway.java:279)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jason-dai** [comment]
we should catch the error in __del__ @cyita

**Comment by jason-dai** [comment]
and we may also need to check if the rdd is cached before calling `unpersist`?

**Comment by cyita** [comment]
> and we may also need to check if the rdd is cached before calling `unpersist`?

Fixed in #2434
