### ISSUE TITLE
spark read from HDFS would get error when the number of files is large

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#2471]
```
train_data = zoo.orca.data.pandas.read_json("hdfs://rbi_data_full/train", sc,
                                                                        orient='columns', lines=True)
```
If there are 40 files under the folder, it works. If there are 360 files, the following error happens:
```
  File "/dir1/yarn/nm_0/usercache/root/appcache/application_1588741658055_0249/container_1588741658055_0249_01_000009/python_env/lib/python3.6/site-packages/pandas/io/json/_json.py", line 586, in read_json
    compression=compression,
  File "/dir1/yarn/nm_0/usercache/root/appcache/application_1588741658055_0249/container_1588741658055_0249_01_000009/python_env/lib/python3.6/site-packages/pandas/io/json/_json.py", line 651, in __init__
    self.data = self._preprocess_data(data)
  File "/dir1/yarn/nm_0/usercache/root/appcache/application_1588741658055_0249/container_1588741658055_0249_01_000009/python_env/lib/python3.6/site-packages/pandas/io/json/_json.py", line 662, in _preprocess_data
    data = data.read()
  File "pyarrow/io.pxi", line 328, in pyarrow.lib.NativeFile.read
  File "pyarrow/error.pxi", line 123, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
OSError: HDFS read failed, errno: 255 (Unknown error 255) Please check that you are connecting to the correct HDFS RPC port
```

**Comment by hkvision** [comment]
https://issues.apache.org/jira/browse/ARROW-3957

**Comment by jason-dai** [comment]
I think we may switch to `spark.read.csv` which can read large csv files into multiple partitions, and then  convert each partition into Pandas dataframe (similar to, e.g., https://github.com/apache/spark/blob/master/python/pyspark/sql/pandas/conversion.py#L42).

**Comment by hkvision** [comment]
Okay.

**Comment by hkvision** [comment]
Finally figured out the root cause:
```
20/06/17 14:04:30 WARN hdfs.DFSClient: DFS Read
org.apache.hadoop.hdfs.BlockMissingException: Could not obtain block: BP-1062893380-172.16.0.103-1555661453399:blk_1077181725_3440903 file=/rbi_data_full/train/part-00008-00026850-8a67-46b1-849c-6c371dd75d45-c000.json
        at org.apache.hadoop.hdfs.DFSInputStream.chooseDataNode(DFSInputStream.java:983)
        at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:642)
        at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:882)
        at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:934)
        at java.io.DataInputStream.read(DataInputStream.java:100)
```
One file 008 is broken on HDFS......
Loading this file locally can get the actual error. But when operating in RDD, the root cause is hidden and can only see the error above.

**Comment by jenniew** [comment]
We cannot see this error in executor log?

**Comment by hkvision** [comment]
Close this issue first. Created a PR #2473 to follow up if we want to use spark.read.csv. @jason-dai

**Comment by jason-dai** [comment]
1. `spark.read.csv` is useful is we want to split large files into multiple partitions
2. Looking at the code below, shall we catch the exception and skip the bad files?
```
import pyarrow as pa
fs = pa.hdfs.connect()
for path in paths:
       with fs.open(path, 'rb') as f:
              if file_type == "json":
                    df = pd.read_json(f, **kwargs)
              elif file_type == "csv":
                    df = pd.read_csv(f, **kwargs)
              else:
                    raise Exception("Unsupported file type")
              df_list.append(df)
```

**Comment by jenniew** [comment]
Found pd.read_csv and pyspark.sql.DataFrameReader.csv have so many different parameters(more than 30 parameters). If support all pandas paramters in Spark DataFrame may take lots of efforts.
```
pd.read_csv(filepath_or_buffer: FilePathOrBuffer,  sep=default_sep, delimiter=None,
      header="infer",  names=None,  _index_col_=None,  usecols=None,
        squeeze=False,  prefix=None,  mangle_dupe_cols=True,
        dtype=None,  engine=None,  converters=None,  true_values=None,
        false_values=None,  skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None,
        na_values=None,  keep_default_na=True, na_filter=True,  verbose=False,
        skip_blank_lines=True,
        parse_dates=False,  infer_datetime_format=False,  keep_date_col=False,
        date_parser=None,  dayfirst=False,  cache_dates=True,
        iterator=False, chunksize=None,
       compression="infer",  thousands=None,  decimal=b".",  lineterminator=None,
        quotechar='"',  quoting=csv.QUOTE_MINIMAL,  doublequote=True,
        escapechar=None,  comment=None,  encoding=None,  dialect=None,
        error_bad_lines=True,  warn_bad_lines=True,
        delim_whitespace=False, low_memory=_c_parser_defaults["low_memory"],
        memory_map=False, float_precision=None,)

pyspark.sql.DataFrameReader.csv(self, path, schema=None, sep=None, encoding=None, quote=None, escape=None,
            comment=None, header=None, inferSchema=None, ignoreLeadingWhiteSpace=None,
            ignoreTrailingWhiteSpace=None, nullValue=None, nanValue=None, positiveInf=None,
            negativeInf=None, dateFormat=None, timestampFormat=None, maxColumns=None,
            maxCharsPerColumn=None, maxMalformedLogPerPartition=None, mode=None,
            columnNameOfCorruptRecord=None, multiLine=None, charToEscapeQuoteEscaping=None,
            samplingRatio=None, enforceSchema=None, emptyValue=None, locale=None, lineSep=None, pathGlobFilter=None, recursiveFileLookup=None)
```

**Comment by jason-dai** [comment]
> Found pd.read_csv and pyspark.sql.DataFrameReader.csv have so many different parameters(more than 30 parameters). If support all pandas paramters in Spark DataFrame may take lots of efforts.
> 
> ```
> pd.read_csv(filepath_or_buffer: FilePathOrBuffer,  sep=default_sep, delimiter=None,
>       header="infer",  names=None,  _index_col_=None,  usecols=None,
>         squeeze=False,  prefix=None,  mangle_dupe_cols=True,
>         dtype=None,  engine=None,  converters=None,  true_values=None,
>         false_values=None,  skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None,
>         na_values=None,  keep_default_na=True, na_filter=True,  verbose=False,
>         skip_blank_lines=True,
>         parse_dates=False,  infer_datetime_format=False,  keep_date_col=False,
>         date_parser=None,  dayfirst=False,  cache_dates=True,
>         iterator=False, chunksize=None,
>        compression="infer",  thousands=None,  decimal=b".",  lineterminator=None,
>         quotechar='"',  quoting=csv.QUOTE_MINIMAL,  doublequote=True,
>         escapechar=None,  comment=None,  encoding=None,  dialect=None,
>         error_bad_lines=True,  warn_bad_lines=True,
>         delim_whitespace=False, low_memory=_c_parser_defaults["low_memory"],
>         memory_map=False, float_precision=None,)
> 
> pyspark.sql.DataFrameReader.csv(self, path, schema=None, sep=None, encoding=None, quote=None, escape=None,
>             comment=None, header=None, inferSchema=None, ignoreLeadingWhiteSpace=None,
>             ignoreTrailingWhiteSpace=None, nullValue=None, nanValue=None, positiveInf=None,
>             negativeInf=None, dateFormat=None, timestampFormat=None, maxColumns=None,
>             maxCharsPerColumn=None, maxMalformedLogPerPartition=None, mode=None,
>             columnNameOfCorruptRecord=None, multiLine=None, charToEscapeQuoteEscaping=None,
>             samplingRatio=None, enforceSchema=None, emptyValue=None, locale=None, lineSep=None, pathGlobFilter=None, recursiveFileLookup=None)
> ```

See https://github.com/databricks/koalas/blob/master/databricks/koalas/namespace.py#L175

**Comment by jenniew** [comment]
So we use Koalas in XShards?
