### ISSUE TITLE
run example get the error : Py4JJavaError: An error occurred while calling o67.estimatorTrainMiniBatch. 

### ISSUE THREAD

**Issue by abner2015** [intel-analytics/analytics-zoo#2502]
example url :https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/examples/tensorflow/tfpark/keras/keras_dataset.py

**### ERROR**
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-30-3897df1d5c1d> in <module>
----> 1 main(3,sc)

<ipython-input-29-3e030477b1c3> in main(max_epoch, sc)
     28     keras_model.fit(dataset,
     29                     epochs=max_epoch,
---> 30                     distributed=True)
     31 
     32     eval_dataset = TFDataset.from_rdd(

/usr/local/miniconda3/envs/zoo-tf1.15-0.8/lib/python3.6/site-packages/zoo/tfpark/model.py in fit(self, x, y, batch_size, epochs, validation_split, validation_data, distributed, **kwargs)
    156             if isinstance(x, TFNdarrayDataset):
    157                 x = _standarize_feature_label_dataset(x, self.model)
--> 158             self._fit_distributed(x, validation_split, epochs, **kwargs)
    159 
    160         elif distributed:

/usr/local/miniconda3/envs/zoo-tf1.15-0.8/lib/python3.6/site-packages/zoo/tfpark/model.py in _fit_distributed(self, dataset, validation_split, epochs, **kwargs)
    183             self.tf_optimizer.set_val_summary(self.val_summary)
    184 
--> 185         self.tf_optimizer.optimize(MaxEpoch(epochs))
    186 
    187     def evaluate(self,

/usr/local/miniconda3/envs/zoo-tf1.15-0.8/lib/python3.6/site-packages/zoo/tfpark/tf_optimizer.py in optimize(self, end_trigger, checkpoint_trigger)
    701                                            checkpoint_trigger=checkpoint_trigger,
    702                                            validation_set=self.val_rdd,
--> 703                                            validation_method=self.tf_model.val_methods)
    704         else:
    705             self.estimator.train_minibatch(train_set=self.training_rdd,

/usr/local/miniconda3/envs/zoo-tf1.15-0.8/lib/python3.6/site-packages/zoo/pipeline/estimator/estimator.py in train_minibatch(self, train_set, criterion, end_trigger, checkpoint_trigger, validation_set, validation_method)
    101         callZooFunc(self.bigdl_type, "estimatorTrainMiniBatch", self.value, train_set,
    102                     criterion, end_trigger, checkpoint_trigger, validation_set,
--> 103                     validation_method)
    104         return self
    105 

/usr/local/miniconda3/envs/zoo-tf1.15-0.8/lib/python3.6/site-packages/zoo/common/utils.py in callZooFunc(bigdl_type, name, *args)
    127             if not ("does not exist" in str(e)
    128                     and "Method {}".format(name) in str(e)):
--> 129                 raise e
    130         else:
    131             return result

/usr/local/miniconda3/envs/zoo-tf1.15-0.8/lib/python3.6/site-packages/zoo/common/utils.py in callZooFunc(bigdl_type, name, *args)
    121         try:
    122             api = getattr(jinvoker, name)
--> 123             java_result = api(*args)
    124             result = _java2py(gateway, java_result)
    125         except Exception as e:

/usr/local/miniconda3/envs/zoo-tf1.15-0.8/lib/python3.6/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/usr/local/miniconda3/envs/zoo-tf1.15-0.8/lib/python3.6/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o67.estimatorTrainMiniBatch.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 18.0 failed 4 times, most recent failure: Lost task 1.3 in stage 18.0 (TID 288, h3, executor 2): java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.List$SerializationProxy to field org.apache.spark.rdd.RDD.org$apache$spark$rdd$RDD$$dependencies_ of type scala.collection.Seq in instance of org.apache.spark.rdd.MapPartitionsRDD
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2301)
	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1431)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2349)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2267)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2125)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2343)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2267)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2125)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:490)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2234)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2125)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2343)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2267)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2125)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2343)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2267)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2125)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:88)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1889)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1877)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1876)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1876)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:926)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2110)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2059)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2048)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:737)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
	at org.apache.spark.rdd.RDD.count(RDD.scala:1168)
	at com.intel.analytics.zoo.feature.DistributedFeatureSet$$anon$1.cache(FeatureSet.scala:139)
	at com.intel.analytics.zoo.feature.DistributedDataSetWrapper.cache(FeatureSet.scala:216)
	at com.intel.analytics.bigdl.optim.AbstractOptimizer.prepareInput(AbstractOptimizer.scala:281)
	at com.intel.analytics.bigdl.optim.DistriOptimizer.prepareInput(DistriOptimizer.scala:799)
	at com.intel.analytics.zoo.pipeline.api.keras.models.InternalDistriOptimizer.train(Topology.scala:1124)
	at com.intel.analytics.zoo.pipeline.api.keras.models.InternalDistriOptimizer.train(Topology.scala:1382)
	at com.intel.analytics.zoo.pipeline.api.keras.models.InternalDistriOptimizer.train(Topology.scala:1070)
	at com.intel.analytics.zoo.pipeline.estimator.Estimator.train(Estimator.scala:152)
	at com.intel.analytics.zoo.pipeline.estimator.python.PythonEstimator.estimatorTrainMiniBatch(PythonEstimator.scala:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.List$SerializationProxy to field org.apache.spark.rdd.RDD.org$apache$spark$rdd$RDD$$dependencies_ of type scala.collection.Seq in instance of org.apache.spark.rdd.MapPartitionsRDD
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2301)
	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1431)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2349)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2267)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2125)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2343)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2267)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2125)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:490)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2234)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2125)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2343)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2267)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2125)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2343)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2267)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2125)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:88)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more

### My code
def get_data_rdd(dataset, sc):
    from bigdl.dataset import mnist
    (images_data, labels_data) = mnist.read_data_sets("/dataset", dataset)
    image_rdd = sc.parallelize(images_data)
    labels_rdd = sc.parallelize(labels_data)
    rdd = image_rdd.zip(labels_rdd) \
        .map(lambda rec_tuple: ((rec_tuple[0] - mnist.TRAIN_MEAN) / mnist.TRAIN_STD,
                                np.array(rec_tuple[1])))
    return rdd

from zoo import *
def main(max_epoch):
    
    sc = init_spark_on_yarn(
        hadoop_conf="/hadoop/conf",
        conda_name="zoo-tf1.15-0.8", 
        num_executor=1,
        executor_cores=1,
        executor_memory="8g",
        driver_memory="10g",
        driver_cores=2
        
    )
    training_rdd = get_data_rdd("train", sc)
    testing_rdd = get_data_rdd("test", sc)

    dataset = TFDataset.from_rdd(training_rdd,
                                 features=(tf.float32, [28, 28, 1]),
                                 labels=(tf.int32, []),
                                 batch_size=320,
                                 val_rdd=testing_rdd)

    model = tf.keras.Sequential(
        [tf.keras.layers.Flatten(input_shape=(28, 28, 1)),
         tf.keras.layers.Dense(64, activation='relu'),
         tf.keras.layers.Dense(64, activation='relu'),
         tf.keras.layers.Dense(10, activation='softmax'),
         ]
    )
    
    model.compile(optimizer=tf.keras.optimizers.RMSprop(),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    keras_model = KerasModel(model)

    keras_model.fit(dataset,
                    epochs=max_epoch,
                    distributed=True)

    eval_dataset = TFDataset.from_rdd(
        testing_rdd,
        features=(tf.float32, [28, 28, 1]),
        labels=(tf.int32, []), batch_per_thread=80)
    result = keras_model.evaluate(eval_dataset)

    print(model.metrics_names)
    print(result)
    # >> ['loss', 'acc']
    # >> [0.08865142822265625, 0.9722]

    model.save_weights("/tmp/mnist_keras.h5")

**Comment by jason-dai** [comment]
@jenniew please take a look

**Comment by jenniew** [comment]
@abner2015 what's your data looks like? Can you share what content under '/dataset'?

**Comment by jenniew** [comment]
@abner2015 do you have different spark versions? when you pip install analytics-zoo in conda env, it install analytics zoo supporting spark 2.4.3 by default, and it also install pyspark 2.4.3 as well. If you have other versions of Spark in your environment, there may have problem. https://issues.apache.org/jira/browse/SPARK-9219

**Comment by abner2015** [comment]
thank for your reply ! spark  2.4.3 and hadoop3

**Comment by jenniew** [comment]
If you use spark-2.4.3-bin-hadoop2.7 build, then you need to use hadoop 2.7 to be compatible.

**Comment by abner2015** [comment]
@jenniew  Think u for your reply. the error is sloved. i meet other question that how can i trans tf model to zoo model  (***.model ), end of model
i have tf  model file :
model.ckpt***
frozen_inference_graph.pb
...
...

**Comment by jenniew** [comment]
What do you want? Do you want predict or evaluate? You can use TFNet which is an analytics zoo layer to load tf model and predict or evaluate. You can reference doc: https://analytics-zoo.github.io/master/#APIGuide/PipelineAPI/net/#tfnet

**Comment by abner2015** [comment]
@jenniew  i want to predict use zoo.   I had used TFNet load tf model and successs.  But  zoo object detection  API is simple, i want to use the api predict , noly predict . i found the model is ***.model file , how can i trans my tf model to ***.model  and use the zoo object detection API?  thank u!

**Comment by jenniew** [comment]
@abner2015 zoo object detection API can only load our pre-trained object detection model to predict. Your TF model is different from our models.  Even if load your tf model to bigdl,  you cannot use Zoo object detector to predict. You can TFNet to load your tf model and predict.

**Comment by Wercurial** [comment]
Hello @abner2015 , I have the same problem as you("Py4JJavaError: An error occurred while calling o67.estimatorTrainMiniBatch"), please ask you to solve the problem.

**Comment by jenniew** [comment]
@Wercurial Do you still have issue?

**Comment by Wercurial** [comment]
@jenniew no,thx
