### ISSUE TITLE
spark.read.json on Almaren node would throw java.lang.IllegalArgumentException: Illegal pattern component: XXX

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#2522]
I'm testing spark backend for reading json files. It works properly on my desktop. But when I run on Almaren node, I get the following error:
```
py4j.protocol.Py4JJavaError: An error occurred while calling o60.json.
: java.lang.IllegalArgumentException: Illegal pattern component: XXX
	at org.apache.commons.lang3.time.FastDatePrinter.parsePattern(FastDatePrinter.java:282)
	at org.apache.commons.lang3.time.FastDatePrinter.init(FastDatePrinter.java:149)
	at org.apache.commons.lang3.time.FastDatePrinter.<init>(FastDatePrinter.java:142)
	at org.apache.commons.lang3.time.FastDateFormat.<init>(FastDateFormat.java:384)
	at org.apache.commons.lang3.time.FastDateFormat.<init>(FastDateFormat.java:369)
	at org.apache.commons.lang3.time.FastDateFormat$1.createInstance(FastDateFormat.java:91)
	at org.apache.commons.lang3.time.FastDateFormat$1.createInstance(FastDateFormat.java:88)
	at org.apache.commons.lang3.time.FormatCache.getInstance(FormatCache.java:82)
	at org.apache.commons.lang3.time.FastDateFormat.getInstance(FastDateFormat.java:165)
	at org.apache.spark.sql.catalyst.json.JSONOptions.<init>(JSONOptions.scala:87)
	at org.apache.spark.sql.catalyst.json.JSONOptionsInRead.<init>(JSONOptions.scala:133)
	at org.apache.spark.sql.catalyst.json.JSONOptionsInRead.<init>(JSONOptions.scala:139)
	at org.apache.spark.sql.execution.datasources.json.JsonFileFormat.inferSchema(JsonFileFormat.scala:55)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$6.apply(DataSource.scala:180)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$6.apply(DataSource.scala:180)
	at scala.Option.orElse(Option.scala:289)
	at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:179)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:373)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:391)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)
```
After some search, https://www.jianshu.com/p/2feceb348df0 this post gives an solution:
```
spark.read.option("timestampFormat", "yyyy/MM/dd HH:mm:ss ZZ").json()
```
After adding .option, the error disappears. Why is this happening? I'm loading RBI's json files that don't contain timestamp fields. Some posts say this is related to the version of comman-langs package, but I'm not sure how this matters.
Need some help. cc @jason-dai @jenniew

**Comment by jason-dai** [comment]
A simple fix is to just add the option? Maybe it think some fields are timestamp by mistake.

**Comment by jenniew** [comment]
I met this issue before. It is the incompatible commons-lang3 problem. In spark, it uses commons-lang3-3.5.jar, but hadoop 2.7 use commons-lang3-3.3.2.jar. Default timestampFormat in spark read_csv/read_json is not working in hadoop. In our spark submit scripts, we set our jars to spark.driver.extraClassPath and spark.executor.extraClassPath, so the cluster would always use our libraries first to avoid this issue. And I fixed this issue in init_spark_on_yarn() too. How do you run the application, do you run python program directly on cluster, and the code use init_nncontext()?

**Comment by hkvision** [comment]
I saw your fix in this PR: https://github.com/intel-analytics/analytics-zoo/pull/2004 you specify --driver-class-path in submit command
I'm using init_spark_on_local, how to do this?

**Comment by jenniew** [comment]
Yes, I think we can do the same way.  Set spark.driver.extraClassPath in sparkconf is not working in client mode.  So for init_spark_on_local, we may need to move this to submit option too.

**Comment by jenniew** [comment]
created PR: https://github.com/intel-analytics/analytics-zoo/pull/2530 to fix.

**Comment by hkvision** [comment]
Why on my laptop it works but on server node it doesn't work?

**Comment by hkvision** [comment]
Tested this on almaren and the issues gets resolved.
