### ISSUE TITLE
Apptest: Incompatible argument to function

### ISSUE THREAD

**Issue by pinggao18** [intel-analytics/analytics-zoo#2549]
java.lang.VerifyError: (class: org/tensorflow/util/Event$Builder, method: getTaggedRunMetadataFieldBuilder signature: ()Lcom/intel/analytics/bigdl/shaded/protobuf/SingleFieldBuilderV3;) Incompatible argument to function

 http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-Pip-AppTests-part1/146/console

**Comment by muzixiang** [comment]
I have the same problem when starting cluster-serving.

The model I store in the Model directory is a LSTM, save by torch.jit.save().  

However, I face the errors as follows:

Exception in thread "main" java.lang.VerifyError: (class: org/tensorflow/util/Event$Builder, method: getTaggedRunMetadataFieldBuilder signature: ()Lcom/intel/analytics/bigdl/shaded/protobuf/SingleFieldBuilderV3;) Incompatible argument to function
	at org.tensorflow.util.Event.toBuilder(Event.java:694)
	at org.tensorflow.util.Event.newBuilder(Event.java:688)
	at com.intel.analytics.zoo.tensorboard.EventWriter.<init>(EventWriter.scala:41)
	at com.intel.analytics.zoo.tensorboard.FileWriter.<init>(FileWriter.scala:40)
	at com.intel.analytics.zoo.pipeline.inference.InferenceSummary.<init>(InferenceSummary.scala:27)
	at com.intel.analytics.zoo.pipeline.inference.InferenceSummary$.apply(InferenceSummary.scala:44)
	at com.intel.analytics.zoo.serving.SparkStreamingClusterServing$.main(SparkStreamingClusterServing.scala:81)
	at com.intel.analytics.zoo.serving.SparkStreamingClusterServing.main(SparkStreamingClusterServing.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by Wercurial** [comment]
hi @muzixiang,I have the same problem with u.Now have you solved the problem?
