### ISSUE TITLE
What shall I do?

### ISSUE THREAD

**Issue by 2017wxyzwxyz** [intel-analytics/analytics-zoo#2609]
I learn and try run analytics-zoo,according to it's document operate and the result as  following, What shall I do?

(ZooAutoml) wxy@SC-202007131929:~$ from zoo.common.nncontext import *
from: can't read /var/mail/zoo.common.nncontext
(ZooAutoml) wxy@SC-202007131929:~$ sudo from zoo.common.nncontext import *
[sudo] password for wxy:
from: can't read /var/mail/zoo.common.nncontext

**Comment by hkvision** [comment]
You should first type `python` to start a REPL and then import packages..........

**Comment by 2017wxyzwxyz** [comment]
It does ok!
But next, when I type ' sc = init_nncontext() ', there is an error as following:
...........................................................................................................................................................................
(ZooAutoml) wxy@SC-202007131929:~$ python
Python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from zoo.common.nncontext import *
Prepending /home/wxy/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/bigdl/share/conf/spark-bigdl.conf to sys.path
Adding /home/wxy/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.8.1-jar-with-dependencies.jar to BIGDL_JARS
Prepending /home/wxy/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/zoo/share/conf/spark-analytics-zoo.conf to sys.path
>>> sc = init_nncontext()
JAVA_HOME is not set
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wxy/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/zoo/common/nncontext.py", line 118, in init_nncontext
    sc = getOrCreateSparkContext(conf=conf)
  File "/home/wxy/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/zoo/common/nncontext.py", line 138, in getOrCreateSparkContext
    return SparkContext.getOrCreate(spark_conf)
  File "/home/wxy/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/pyspark/context.py", line 367, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/wxy/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/pyspark/context.py", line 133, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/wxy/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/pyspark/context.py", line 316, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/wxy/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/pyspark/java_gateway.py", line 46, in launch_gateway
    return _launch_gateway(conf)
  File "/home/wxy/anaconda3/envs/ZooAutoml/lib/python3.6/site-packages/pyspark/java_gateway.py", line 108, in _launch_gateway
    raise Exception("Java gateway process exited before sending its port number")
Exception: Java gateway process exited before sending its port number
>>> sc = init_nncontext()
...........................................................................................................................................................................

What shall I do to set 'JAVA_HOME'?

**Comment by hkvision** [comment]
This is the same issue as in https://github.com/intel-analytics/analytics-zoo/issues/2601, have you resolved that one?
Make sure you have installed JDK8 on your machine beforehand and the installation of JAVA would help you set JAVA_HOME.

**Comment by 2017wxyzwxyz** [comment]
Thank you for your reply. I will  try !
