### ISSUE TITLE
SparseEmbedding gives gradInput of null, graph Model throws NullPointerException

### ISSUE THREAD

**Issue by songhappy** [intel-analytics/analytics-zoo#2620]
Exception in thread "main" java.lang.NullPointerException
	at com.intel.analytics.bigdl.nn.Graph$$anonfun$findGradOutput$2.apply(Graph.scala:330)
	at com.intel.analytics.bigdl.nn.Graph$$anonfun$findGradOutput$2.apply(Graph.scala:329)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.intel.analytics.bigdl.nn.Graph.findGradOutput(Graph.scala:329)
	at com.intel.analytics.bigdl.nn.StaticGraph.backwardExecution(StaticGraph.scala:135)
	at com.intel.analytics.bigdl.nn.StaticGraph.updateGradInput(StaticGraph.scala:78)
	at com.intel.analytics.bigdl.nn.keras.KerasLayer.updateGradInput(KerasLayer.scala:192)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.backward(AbstractModule.scala:284)

code to reproduce it
```
def graphmodels() = {
    val input = Tensor(5, 4)
    input.setValue(1, 1, 1f)
    input.setValue(2, 3, 3f)
    val sparseInput = Tensor.sparse(input)
    val inputNode = Input(inputShape = Shape(4))
    val linear1 = SparseDense(4).inputs(inputNode)
    val embed = SparseEmbedding(4, 4).inputs(inputNode)
    val linear2 = CAdd(Array(4)).inputs(embed)
    val model2 = Model(inputNode, linear2)
    model1.summary()
    val out1 = model1.forward(sparseInput)
    model2.summary()
    val out2 = model2.forward(sparseInput)
    val gradinput1 = model1.backward(input, out1)
    println("sparselinear")
    print(out1)
    println(gradinput1)
    println("sparseEmbedding plus cadd")
    print(out2)
    val gradinput2 = model2.backward(input, out2)
    println(gradinput2)
  }
```

**Comment by hkvision** [comment]
You should look into BigDL SparseLinear.

**Comment by songhappy** [comment]
SparseLinear from BigDL and SparseDense from Zoo do not have any problems with both Sequential and Graph apis.
LookupTableSparse from BigDL and SparseEmbedding from Zoo do not have any problems with Sequential api, throw null pointer exception with its graph api respectively.

**Comment by hkvision** [comment]
> SparseLinear from BigDL and SparseDense from Zoo do not have any problems with both Sequential and Graph apis.
> LookupTableSparse from BigDL and SparseEmbedding from Zoo do not have any problems with Sequential api, throw null pointer exception with its graph api respectively. We can fix it at either SparseEmbedding/LooupTableSparse or Mode/Graph

So you mean there is a bug in Keras Graph construction?
