### ISSUE TITLE
Error messages not clear :  firstIndex(110) out of range [0, 110)

### ISSUE THREAD

**Issue by helenlly** [intel-analytics/analytics-zoo#2661]
error messagre not clear, Here is error trace:
Caused by: java.lang.IllegalArgumentException: requirement failed: firstIndex(110) out of range [0, 110)
  at scala.Predef$.require(Predef.scala:224)
  at com.intel.analytics.bigdl.tensor.DenseTensor$.narrow(DenseTensor.scala:2616)
  at com.intel.analytics.bigdl.tensor.DenseTensor.narrow(DenseTensor.scala:444)
  at com.intel.analytics.bigdl.parameters.AllReduceParameter.init(AllReduceParameter.scala:161)
  at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$11.apply(DistriOptimizer.scala:621)
  at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$11.apply(DistriOptimizer.scala:579)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
  at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:337)
  at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:335)
  at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1094)
  at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1085)

need modify error messages and let the user know more details or cause about the error . 
more details refer to [java.lang.IllegalArgumentException: requirement failed: firstIndex(110) out of range [0, 110)](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!searchin/bigdl-user-group/hibayesian@gmail.com%7Csort:date/bigdl-user-group/tLMAitWUJg0/9JUauNGTCQAJ)

**Comment by zcw111** [comment]
Hi Helenlly,

I had the same problem. Changing the num_executor to 8 or 4 does fix the problem. But I need to run it on more executors. Did you figure out how to fix this problem generally?
