### ISSUE TITLE
py4j.protocol.Py4JJavaError: An error occurred while calling o61.csv. : java.lang.IllegalArgumentException: Illegal pattern component: XXX

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/analytics-zoo#2664]
https://github.com/intel-analytics/analytics-zoo/pull/2628
This PR breaks spark.read.csv/json, with the following error:
```
py4j.protocol.Py4JJavaError: An error occurred while calling o61.csv.
: java.lang.IllegalArgumentException: Illegal pattern component: XXX
	at org.apache.commons.lang3.time.FastDatePrinter.parsePattern(FastDatePrinter.java:282)
	at org.apache.commons.lang3.time.FastDatePrinter.init(FastDatePrinter.java:149)
	at org.apache.commons.lang3.time.FastDatePrinter.<init>(FastDatePrinter.java:142)
	at org.apache.commons.lang3.time.FastDateFormat.<init>(FastDateFormat.java:384)
	at org.apache.commons.lang3.time.FastDateFormat.<init>(FastDateFormat.java:369)
	at org.apache.commons.lang3.time.FastDateFormat$1.createInstance(FastDateFormat.java:91)
	at org.apache.commons.lang3.time.FastDateFormat$1.createInstance(FastDateFormat.java:88)
	at org.apache.commons.lang3.time.FormatCache.getInstance(FormatCache.java:82)
	at org.apache.commons.lang3.time.FastDateFormat.getInstance(FastDateFormat.java:165)
	at org.apache.spark.sql.execution.datasources.csv.CSVOptions.<init>(CSVOptions.scala:139)
	at org.apache.spark.sql.execution.datasources.csv.CSVOptions.<init>(CSVOptions.scala:41)
	at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat.inferSchema(CSVFileFormat.scala:58)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$6.apply(DataSource.scala:180)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$6.apply(DataSource.scala:180)
	at scala.Option.orElse(Option.scala:289)
	at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:179)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:373)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:615)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```
Either revert this PR if the conflict can be resolved or refer to here: https://stackoverflow.com/questions/46429616/spark-2-2-illegal-pattern-component-xxx-java-lang-illegalargumentexception-ill

Error log: http://10.239.47.210:18888/job/ZOO-NB-Pip-ExampleTests-py36/84/console
Related issue: https://github.com/intel-analytics/analytics-zoo/issues/2522
cc @jenniew

**Comment by hkvision** [comment]
Also, for Spark backend, if we are running on a hadoop cluster, we still need to add `file://` for local file prefixes? @jenniew

**Comment by jenniew** [comment]
No need to add file:// in yarn.

**Comment by hkvision** [comment]
But it raises error:
```
>>> data_shard = zoo.orca.data.pandas.read_csv("/opt/work/client/kai/nyc_taxi.csv")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/work/client/anaconda3/envs/tianchi/lib/python3.7/site-packages/zoo/orca/data/pandas/preprocessing.py", line 33, in read_csv
    return read_file_spark(file_path, "csv", **kwargs)
  File "/opt/work/client/anaconda3/envs/tianchi/lib/python3.7/site-packages/zoo/orca/data/pandas/preprocessing.py", line 146, in read_file_spark
    df = spark.read.csv(file_path, **kwargs)
  File "/opt/work/client/anaconda3/envs/tianchi/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 472, in csv
    return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
  File "/opt/work/client/anaconda3/envs/tianchi/lib/python3.7/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/opt/work/client/anaconda3/envs/tianchi/lib/python3.7/site-packages/pyspark/sql/utils.py", line 69, in deco
    raise AnalysisException(s.split(': ', 1)[1], stackTrace)
pyspark.sql.utils.AnalysisException: 'Path does not exist: hdfs://Almaren-Node-003:9000/opt/work/client/kai/nyc_taxi.csv;'
```

**Comment by hkvision** [comment]
spark.read.csv/json defaults to use hadoop fs.

**Comment by hkvision** [comment]
This error also happens on YARN cluster. Need to fix it asap.

**Comment by yangw1234** [comment]
This is because bigdl and analytics-zoo pip using different spark versions to build?

**Comment by jenniew** [comment]
what error? "Path does not exist: hdfs://Almaren-Node-003:9000/opt/work/client/kai/nyc_taxi.csv" is because we use spark to read csv and spark uses hadoop fs to read file. I think we don't need to fix it. 
For  java.lang.IllegalArgumentException: Illegal pattern component: XXX, the error is inconsistent commons-lang3 version between spark and hadoop.  We could either put our bigdl/analytics-zoo jars before hadoop jars, or add option("timestampFormat", "yyyy/MM/dd HH:mm:ss ZZ") to fix it. My previous fix is put our jars at the front of driver and executor classpath, but https://github.com/intel-analytics/analytics-zoo/pull/2628 change that order of classpath. I think now we can may need to add this option("timestampFormat", "yyyy/MM/dd HH:mm:ss ZZ") to fix it.
