### ISSUE TITLE
IllegalArgumentException capacity when run cluster serving with TF

### ISSUE THREAD

**Issue by glorysdj** [intel-analytics/analytics-zoo#2769]
```
org.apache.flink.runtime.taskmanager.Task                     - Source: Custom Source -> Map -> Sink: Unnamed (1/1) (4bf7071d79b09d1603f35ba116bbb1a5) switched from RUNNING to FAILED.
java.lang.IllegalArgumentException: capacity < 0: (-520103681 < 0)
        at java.base/java.nio.Buffer.createCapacityException(Buffer.java:256)
        at java.base/java.nio.ByteBuffer.allocate(ByteBuffer.java:347)
        at com.intel.analytics.zoo.shaded.arrow.vector.ipc.message.MessageSerializer.readMessage(MessageSerializer.java:664)
        at com.intel.analytics.zoo.shaded.arrow.vector.ipc.message.MessageChannelReader.readNext(MessageChannelReader.java:58)
        at com.intel.analytics.zoo.shaded.arrow.vector.ipc.ArrowStreamReader.readSchema(ArrowStreamReader.java:163)
        at com.intel.analytics.zoo.shaded.arrow.vector.ipc.ArrowReader.initialize(ArrowReader.java:170)
        at com.intel.analytics.zoo.shaded.arrow.vector.ipc.ArrowReader.ensureInitialized(ArrowReader.java:161)
        at com.intel.analytics.zoo.shaded.arrow.vector.ipc.ArrowReader.getVectorSchemaRoot(ArrowReader.java:63)
        at com.intel.analytics.zoo.serving.http.Instances$.fromArrow(domains.scala:441)
        at com.intel.analytics.zoo.serving.PreProcessing.decodeArrowBase64(PreProcessing.scala:45)
        at com.intel.analytics.zoo.serving.engine.FlinkInference$$anonfun$1$$anonfun$apply$1.apply(FlinkInference.scala:57)
        at com.intel.analytics.zoo.serving.engine.FlinkInference$$anonfun$1$$anonfun$apply$1.apply(FlinkInference.scala:55)
        at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:657)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
        at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:648)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:159)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:443)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:149)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by Litchilitchy** [comment]
Seems an configuration error, arrow would allocate direct memory but on some machine the default config does not support

**Comment by Litchilitchy** [comment]
could try to increase `taskmanager.memory.task.off-heap.size`, the default is 0

**Comment by glorysdj** [comment]
tried     -D taskmanager.memory.task.off-heap.size=1000000000b
still get the same error when i run rps as 100

```
java.lang.IllegalArgumentException: capacity < 0: (-520103681 < 0)
	at java.base/java.nio.Buffer.createCapacityException(Buffer.java:256)
	at java.base/java.nio.ByteBuffer.allocate(ByteBuffer.java:347)
	at com.intel.analytics.zoo.shaded.arrow.vector.ipc.message.MessageSerializer.readMessage(MessageSerializer.java:664)
	at com.intel.analytics.zoo.shaded.arrow.vector.ipc.message.MessageChannelReader.readNext(MessageChannelReader.java:58)
	at com.intel.analytics.zoo.shaded.arrow.vector.ipc.ArrowStreamReader.readSchema(ArrowStreamReader.java:163)
	at com.intel.analytics.zoo.shaded.arrow.vector.ipc.ArrowReader.initialize(ArrowReader.java:170)
	at com.intel.analytics.zoo.shaded.arrow.vector.ipc.ArrowReader.ensureInitialized(ArrowReader.java:161)
	at com.intel.analytics.zoo.shaded.arrow.vector.ipc.ArrowReader.getVectorSchemaRoot(ArrowReader.java:63)
	at com.intel.analytics.zoo.serving.http.Instances$.fromArrow(domains.scala:441)
	at com.intel.analytics.zoo.serving.PreProcessing.decodeArrowBase64(PreProcessing.scala:45)
	at com.intel.analytics.zoo.serving.engine.FlinkInference$$anonfun$1$$anonfun$apply$1.apply(FlinkInference.scala:57)
	at com.intel.analytics.zoo.serving.engine.FlinkInference$$anonfun$1$$anonfun$apply$1.apply(FlinkInference.scala:55)
	at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:657)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
	at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:648)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:159)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:443)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by glorysdj** [comment]
I think it may caused by a large number of images as input has exceed the capacity of arrowStreamReader which is initialized as Integer.MAX_VALUE.

**Comment by glorysdj** [comment]
Failure allocating buffer.
org.apache.arrow.memory.OutOfMemoryException: Failure allocating buffer.
	at io.netty.buffer.PooledByteBufAllocatorL.allocate(PooledByteBufAllocatorL.java:67)
	at org.apache.arrow.memory.NettyAllocationManager.<init>(NettyAllocationManager.java:42)
	at org.apache.arrow.memory.NettyAllocationManager$Factory.create(NettyAllocationManager.java:82)
	at org.apache.arrow.memory.BaseAllocator.newAllocationManager(BaseAllocator.java:355)
	at org.apache.arrow.memory.BaseAllocator.newAllocationManager(BaseAllocator.java:350)
	at org.apache.arrow.memory.BaseAllocator.bufferWithoutReservation(BaseAllocator.java:338)
	at org.apache.arrow.memory.BaseAllocator.buffer(BaseAllocator.java:316)
	at org.apache.arrow.memory.BaseAllocator.buffer(BaseAllocator.java:280)
	at org.apache.arrow.vector.ipc.message.MessageSerializer.readMessageBody(MessageSerializer.java:691)
	at org.apache.arrow.vector.ipc.message.MessageChannelReader.readNext(MessageChannelReader.java:68)
	at org.apache.arrow.vector.ipc.ArrowStreamReader.loadNextBatch(ArrowStreamReader.java:106)
	at com.intel.analytics.zoo.serving.http.Instances$.fromArrow(domains.scala:445)
	at com.intel.analytics.zoo.serving.FrontendDomainsSpec$$anonfun$11$$anonfun$apply$mcV$sp$6$$anonfun$38.apply(FrontendDomainsSpec.scala:315)
	at com.intel.analytics.zoo.serving.FrontendDomainsSpec$$anonfun$11$$anonfun$apply$mcV$sp$6$$anonfun$38.apply(FrontendDomainsSpec.scala:315)
	at com.intel.analytics.zoo.serving.http.Supportive$class.timing(Supportive.scala:28)
	at com.intel.analytics.zoo.serving.FrontendDomainsSpec.timing(FrontendDomainsSpec.scala:28)
	at com.intel.analytics.zoo.serving.FrontendDomainsSpec$$anonfun$11$$anonfun$apply$mcV$sp$6.apply$mcVI$sp(FrontendDomainsSpec.scala:314)
	at com.intel.analytics.zoo.serving.FrontendDomainsSpec$$anonfun$11$$anonfun$apply$mcV$sp$6.apply(FrontendDomainsSpec.scala:303)
	at com.intel.analytics.zoo.serving.FrontendDomainsSpec$$anonfun$11$$anonfun$apply$mcV$sp$6.apply(FrontendDomainsSpec.scala:303)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.intel.analytics.zoo.serving.FrontendDomainsSpec$$anonfun$11.apply$mcV$sp(FrontendDomainsSpec.scala:303)
	at com.intel.analytics.zoo.serving.FrontendDomainsSpec$$anonfun$11.apply(FrontendDomainsSpec.scala:300)
	at com.intel.analytics.zoo.serving.FrontendDomainsSpec$$anonfun$11.apply(FrontendDomainsSpec.scala:300)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1647)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1683)
	at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1644)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1656)
	at com.intel.analytics.zoo.serving.FrontendDomainsSpec.org$scalatest$BeforeAndAfter$$super$runTest(FrontendDomainsSpec.scala:28)
	at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
	at com.intel.analytics.zoo.serving.FrontendDomainsSpec.runTest(FrontendDomainsSpec.scala:28)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1714)
	at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1683)
	at org.scalatest.Suite$class.run(Suite.scala:1424)
	at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1683)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1760)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1760)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1760)
	at com.intel.analytics.zoo.serving.FrontendDomainsSpec.org$scalatest$BeforeAndAfter$$super$run(FrontendDomainsSpec.scala:28)
	at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
	at com.intel.analytics.zoo.serving.FrontendDomainsSpec.run(FrontendDomainsSpec.scala:28)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 536870912, max: 536870912)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:226)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
	at io.netty.buffer.PooledByteBufAllocatorL$InnerAllocator.newDirectBufferL(PooledByteBufAllocatorL.java:181)
	at io.netty.buffer.PooledByteBufAllocatorL$InnerAllocator.directBuffer(PooledByteBufAllocatorL.java:214)
	at io.netty.buffer.PooledByteBufAllocatorL.allocate(PooledByteBufAllocatorL.java:58)
	... 75 more

**Comment by glorysdj** [comment]
fixed by https://github.com/intel-analytics/analytics-zoo/pull/2788
