### ISSUE TITLE
Failed to load com.intel.analytics.zoo.serving.SparkStreamingClusterServing.

### ISSUE THREAD

**Issue by WangHeguan** [intel-analytics/analytics-zoo#2805]
I use spark for backend in cluster-serving，an error occurred while executing the command: cluster-serving-start -e spark.  The error is:
20/08/31 20:55:06 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/08/31 20:55:06 WARN DependencyUtils: Local jar /usr/local/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-20200821.201231-75-cluster-serving-all/cluster-serving/zoo.jar does not exist, skipping.
20/08/31 20:55:06 WARN SparkSubmit$$anon$2: Failed to load com.intel.analytics.zoo.serving.SparkStreamingClusterServing.
java.lang.ClassNotFoundException: com.intel.analytics.zoo.serving.SparkStreamingClusterServing
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:806)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
20/08/31 20:55:06 INFO ShutdownHookManager: Shutdown hook called
20/08/31 20:55:06 INFO ShutdownHookManager: Deleting directory /private/var/folders/nq/s8rrp4ds4vd1t288hdwtnrd40000gn/T/spark-d11c77eb-2381-49c9-83fa-4880e9ae39c6

**Comment by Litchilitchy** [comment]
Glad that you are trying out this feature.

Seems your working directory `/usr/local/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-20200821.201231-75-cluster-serving-all/cluster-serving`. What is the contents of this directory now, is `zoo.jar` there?

**Comment by WangHeguan** [comment]
@Litchilitchy yes,zoo.jar is in the working directory  /usr/local/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-20200821.201231-75-cluster-serving-all/cluster-serving

**Comment by Litchilitchy** [comment]
Could you post your command and log like this:
```
#/path/to/dir$ cluster-serving-start
#/path/to/dir$ ls
```

**Comment by Litchilitchy** [comment]
Also you could use `jar tvf zoo.jar | grep serving | grep Spark` to check if this class exists. Sometimes jar deployment encounters some error and jar may be wrong.

**Comment by WangHeguan** [comment]
@Litchilitchy 

#/path/to/dir % sh cluster-serving-start
model_path="resources/model"
master of spark cluster not set, using default value local[*]
spark driver memory not set, using default value 4g
spark executor memory not set, using default value 1g
spark num-executors not set, using default value 1
spark executor-cores not set, using default value 4
spark executor-cores not set, using default value 4
Redis maxmemory is not set, using default value 8G
redis server started, please check log in redis.log
OK
OK
OK
redis config maxmemory set to 8G
OK
OK
Starting Cluster Serving with Flink backend
FLINK_HOME variable is not set, you need to set it to start Cluster Serving with Flink backend.
#/path/to/dir  % ls
TensorboardEventLogs						cluster-serving-start
analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-SNAPSHOT-http.jar	cluster-serving-stop
cluster-serving-demo.sh						cluster-with-numactl.sh
cluster-serving-init						config.yaml
cluster-serving-py-setup.py					download-serving-jar.sh
cluster-serving-restart						redis.log
cluster-serving-setup.sh					serving-python.zip
cluster-serving-shutdown					zoo.jar

**Comment by Litchilitchy** [comment]
@WangHeguan In your case you just use `cluster-serving-start -e spark`. The previous post is just an example.

**Comment by WangHeguan** [comment]
@Litchilitchy 
Now when I execute the cluster-serving-start -e spark command, the error that occurs is different, it becomes:

`model_path="resources/model"
master of spark cluster not set, using default value local[*]
spark driver memory not set, using default value 4g
spark executor memory not set, using default value 1g
spark num-executors not set, using default value 1
spark executor-cores not set, using default value 4
spark executor-cores not set, using default value 4
Redis maxmemory is not set, using default value 8G
redis server started, please check log in redis.log
OK
OK
OK
redis config maxmemory set to 8G
OK
OK
You are using non-default backend
/Library/Python/3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Library/Python/3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Library/Python/3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Library/Python/3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Library/Python/3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Library/Python/3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
20/09/01 10:42:15 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
(Loading config at ,config.yaml)
{path=resources/model, mode=null, inputs=null, outputs=null}path getted: resources/model
Your model path provided is empty, please check your model path.
Exception in thread "main" java.lang.NullPointerException
	at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:192)
	at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:192)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at com.intel.analytics.zoo.serving.utils.ClusterServingHelper.parseModelType(ClusterServingHelper.scala:386)
	at com.intel.analytics.zoo.serving.utils.ClusterServingHelper.initArgs(ClusterServingHelper.scala:116)
	at com.intel.analytics.zoo.serving.SparkStreamingClusterServing$.main(SparkStreamingClusterServing.scala:45)
	at com.intel.analytics.zoo.serving.SparkStreamingClusterServing.main(SparkStreamingClusterServing.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
`

**Comment by WangHeguan** [comment]
@Litchilitchy Now when I execute the cluster-serving-start -e spark command, the error that occurs is different, it becomes:

model_path="resources/model"
master of spark cluster not set, using default value local[*]
spark driver memory not set, using default value 4g
spark executor memory not set, using default value 1g
spark num-executors not set, using default value 1
spark executor-cores not set, using default value 4
spark executor-cores not set, using default value 4
Redis maxmemory is not set, using default value 8G
redis server started, please check log in redis.log
OK
OK
OK
redis config maxmemory set to 8G
OK
OK
You are using non-default backend
/Library/Python/3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Library/Python/3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Library/Python/3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Library/Python/3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Library/Python/3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Library/Python/3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
20/09/01 10:42:15 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
(Loading config at ,config.yaml)
{path=resources/model, mode=null, inputs=null, outputs=null}path getted: resources/model
Your model path provided is empty, please check your model path.
Exception in thread "main" java.lang.NullPointerException
	at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:192)
	at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:192)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at com.intel.analytics.zoo.serving.utils.ClusterServingHelper.parseModelType(ClusterServingHelper.scala:386)
	at com.intel.analytics.zoo.serving.utils.ClusterServingHelper.initArgs(ClusterServingHelper.scala:116)
	at com.intel.analytics.zoo.serving.SparkStreamingClusterServing$.main(SparkStreamingClusterServing.scala:45)
	at com.intel.analytics.zoo.serving.SparkStreamingClusterServing.main(SparkStreamingClusterServing.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by Litchilitchy** [comment]
Yes, seems you already get the env ready. Next step you should set your model, see this log
```
Your model path provided is empty, please check your model path.
```
You set your model path as `resources/model` does your model file in this directory?

**Comment by WangHeguan** [comment]
@Litchilitchy Although new problems appeared constantly, I slowly solved them. Now there is a new problem, I can't start, I still need your help:

model_path="resources/model"
master of spark cluster not set, using default value local[*]
spark driver memory not set, using default value 4g
spark executor memory not set, using default value 1g
spark num-executors not set, using default value 1
spark executor-cores not set, using default value 4
spark executor-cores not set, using default value 4
Redis maxmemory is not set, using default value 8G
redis server started, please check log in redis.log
OK
OK
OK
redis config maxmemory set to 8G
OK
OK
You are using non-default backend
/Library/Python/3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Library/Python/3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Library/Python/3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Library/Python/3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Library/Python/3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Library/Python/3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
TensorBoard 1.14.0 at http://0.0.0.0:6006/ (Press CTRL+C to quit)
20/09/01 11:18:19 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
(Loading config at ,config.yaml)
{path=resources/model, mode=null, inputs=null, outputs=null}path getted: resources/model
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/09/01 11:18:20 INFO Engine$: Auto detect executor number and executor cores number
20/09/01 11:18:20 INFO Engine$: Executor number is 1 and executor cores number is 6
20/09/01 11:18:22 INFO ThreadPool$: Set mkl threads to 1 on thread 1
20/09/01 11:18:22 INFO Engine$: Find existing spark context. Checking the spark conf...
20/09/01 11:18:22 INFO ClusterServingHelper: connected to redis localhost:6379
loading params, time is 08/11/2020 15:11:34
Exception in thread "main" java.lang.NullPointerException
	at com.intel.analytics.zoo.serving.SparkStreamingClusterServing$.main(SparkStreamingClusterServing.scala:103)
	at com.intel.analytics.zoo.serving.SparkStreamingClusterServing.main(SparkStreamingClusterServing.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by Litchilitchy** [comment]
@WangHeguan Thanks for your try, this is a bug. Spark version has not been kept up with the latest modification. Will fix in tomorrow snapshot.

Currently Cluster Serving is mainly focused on Flink backend version. But will also fix Spark version if any bug discovered.

**Comment by WangHeguan** [comment]
@Litchilitchy So using spark streaming as the backend is not stable yet, is Flink recommended?

**Comment by Litchilitchy** [comment]
@WangHeguan Yes, flink is recommended. If you are not familiar with both, use flink. If you only have Spark experience, could choose Spark. The working version could be available tomorrow.

**Comment by WangHeguan** [comment]
@Litchilitchy thanks so much!

**Comment by helenlly** [comment]
@WangHeguan  thanks for your question. if no other question, may we go ahead to close this issue?
