### ISSUE TITLE
how can i save checkpoint in the end of every epoch 

### ISSUE THREAD

**Issue by Tshzzz** [intel-analytics/analytics-zoo#2837]
I want to save the model at the end of each training epoch.  How can I set it?
```
estimator = Estimator.from_torch(model=dis_model,
                                     loss=NullLoss(),
                                     optimizer=Adam(lr=1e-4),
                                     backend="bigdl")

estimator.fit(data=train_dataloader,
                      epochs=10,
                      validation_data=None,
                      validation_methods=None,
                      checkpoint_trigger=EveryEpoch(),
            )
```

**Comment by Litchilitchy** [comment]
@qiuxin2012 @cyita 

@Tshzzz Is it orca API using pytorch model?

**Comment by qiuxin2012** [comment]
TorchModel couldn't save the model at the end of each training epoch currently.
You can use a loop to call fit every epoch. `dis_model.to_pytorch()` can convert TorchModel to pytorch model, then use `torch.save` to save your model. @Tshzzz

**Comment by jason-dai** [comment]
@qiuxin2012 @cyita I think we need to add the checkpoint support in PyTorch estimator??

**Comment by Tshzzz** [comment]
> TorchModel couldn't save the model at the end of each training epoch currently.
> You can use a loop to call fit every epoch. `dis_model.to_pytorch()` can convert TorchModel to pytorch model, then use `torch.save` to save your model. @Tshzzz

Should I construct estimator in the loop? I try this code, but it will cause java.lang.OutOfMemoryError
`
for i in range(epochs):
   estimator = Estimator.from_torch(model=model,
                                     loss=NullLoss(),
                                     optimizer=Adam(lr=1e-4,
                                     backend="bigdl")
    estimator.fit(data=train_dataloader,
                      epochs=1,
                      validation_data=None,
                      validation_methods=None,
    )

    dis_model = estimator.get_model()
    torch.save(dis_model.state_dict(), 'epoch_{}.pkl'.format(i))

`

**Comment by qiuxin2012** [comment]
> > TorchModel couldn't save the model at the end of each training epoch currently.
> > You can use a loop to call fit every epoch. `dis_model.to_pytorch()` can convert TorchModel to pytorch model, then use `torch.save` to save your model. @Tshzzz
> 
> Should I construct estimator in the loop? I try this code, but it will cause java.lang.OutOfMemoryError
> 
> ```
> for i in range(epochs):
>         estimator = Estimator.from_torch(model=model,
>                                          loss=NullLoss(),
>                                          optimizer=Adam(lr=1e-4,
>                                                         backend="bigdl")
>         estimator.fit(data=train_dataloader,
>                       epochs=1,
>                       validation_data=None,
>                       validation_methods=None,
>                       )
>         dis_model = estimator.get_model()
>         torch.save(dis_model.state_dict(), 'epoch_{}.pkl'.format(i))
> ```

please put `estimator.from_torch` out of the loop:
```
estimator = Estimator.from_torch(model=model,
                                                       loss=NullLoss(),
                                                       optimizer=Adam(lr=1e-4),
                                                        backend="bigdl")
for i in range(epochs):
        estimator.fit(data=train_dataloader,
                      epochs=1,
                      validation_data=None,
                      validation_methods=None,
                      )
        dis_model = estimator.get_model()
        torch.save(dis_model.state_dict(), 'epoch_{}.pkl'.format(i))
```

**Comment by Tshzzz** [comment]
> > > TorchModel couldn't save the model at the end of each training epoch currently.
> > > You can use a loop to call fit every epoch. `dis_model.to_pytorch()` can convert TorchModel to pytorch model, then use `torch.save` to save your model. @Tshzzz
> > 
> > 
> > Should I construct estimator in the loop? I try this code, but it will cause java.lang.OutOfMemoryError
> > ```
> > for i in range(epochs):
> >         estimator = Estimator.from_torch(model=model,
> >                                          loss=NullLoss(),
> >                                          optimizer=Adam(lr=1e-4,
> >                                                         backend="bigdl")
> >         estimator.fit(data=train_dataloader,
> >                       epochs=1,
> >                       validation_data=None,
> >                       validation_methods=None,
> >                       )
> >         dis_model = estimator.get_model()
> >         torch.save(dis_model.state_dict(), 'epoch_{}.pkl'.format(i))
> > ```
> 
> please put `estimator.from_torch` out of the loop:
> 
> ```
> estimator = Estimator.from_torch(model=model,
>                                                        loss=NullLoss(),
>                                                        optimizer=Adam(lr=1e-4),
>                                                         backend="bigdl")
> for i in range(epochs):
>         estimator.fit(data=train_dataloader,
>                       epochs=1,
>                       validation_data=None,
>                       validation_methods=None,
>                       )
>         dis_model = estimator.get_model()
>         torch.save(dis_model.state_dict(), 'epoch_{}.pkl'.format(i))
> ```

I've already experimented. it's out of memory too.

**Comment by qiuxin2012** [comment]
> > > > TorchModel couldn't save the model at the end of each training epoch currently.
> > > > You can use a loop to call fit every epoch. `dis_model.to_pytorch()` can convert TorchModel to pytorch model, then use `torch.save` to save your model. @Tshzzz
> > > 
> > > 
> > > Should I construct estimator in the loop? I try this code, but it will cause java.lang.OutOfMemoryError
> > > ```
> > > for i in range(epochs):
> > >         estimator = Estimator.from_torch(model=model,
> > >                                          loss=NullLoss(),
> > >                                          optimizer=Adam(lr=1e-4,
> > >                                                         backend="bigdl")
> > >         estimator.fit(data=train_dataloader,
> > >                       epochs=1,
> > >                       validation_data=None,
> > >                       validation_methods=None,
> > >                       )
> > >         dis_model = estimator.get_model()
> > >         torch.save(dis_model.state_dict(), 'epoch_{}.pkl'.format(i))
> > > ```
> > 
> > 
> > please put `estimator.from_torch` out of the loop:
> > ```
> > estimator = Estimator.from_torch(model=model,
> >                                                        loss=NullLoss(),
> >                                                        optimizer=Adam(lr=1e-4),
> >                                                         backend="bigdl")
> > for i in range(epochs):
> >         estimator.fit(data=train_dataloader,
> >                       epochs=1,
> >                       validation_data=None,
> >                       validation_methods=None,
> >                       )
> >         dis_model = estimator.get_model()
> >         torch.save(dis_model.state_dict(), 'epoch_{}.pkl'.format(i))
> > ```
> 
> I've already experimented. it's out of memory too.

Could you attach the full log?

**Comment by Tshzzz** [comment]
> > > > > TorchModel couldn't save the model at the end of each training epoch currently.
> > > > > You can use a loop to call fit every epoch. `dis_model.to_pytorch()` can convert TorchModel to pytorch model, then use `torch.save` to save your model. @Tshzzz
> > > > 
> > > > 
> > > > Should I construct estimator in the loop? I try this code, but it will cause java.lang.OutOfMemoryError
> > > > ```
> > > > for i in range(epochs):
> > > >         estimator = Estimator.from_torch(model=model,
> > > >                                          loss=NullLoss(),
> > > >                                          optimizer=Adam(lr=1e-4,
> > > >                                                         backend="bigdl")
> > > >         estimator.fit(data=train_dataloader,
> > > >                       epochs=1,
> > > >                       validation_data=None,
> > > >                       validation_methods=None,
> > > >                       )
> > > >         dis_model = estimator.get_model()
> > > >         torch.save(dis_model.state_dict(), 'epoch_{}.pkl'.format(i))
> > > > ```
> > > 
> > > 
> > > please put `estimator.from_torch` out of the loop:
> > > ```
> > > estimator = Estimator.from_torch(model=model,
> > >                                                        loss=NullLoss(),
> > >                                                        optimizer=Adam(lr=1e-4),
> > >                                                         backend="bigdl")
> > > for i in range(epochs):
> > >         estimator.fit(data=train_dataloader,
> > >                       epochs=1,
> > >                       validation_data=None,
> > >                       validation_methods=None,
> > >                       )
> > >         dis_model = estimator.get_model()
> > >         torch.save(dis_model.state_dict(), 'epoch_{}.pkl'.format(i))
> > > ```
> > 
> > 
> > I've already experimented. it's out of memory too.
> 
> Could you attach the full log?

creating: createEveryEpoch
creating: createMaxEpoch
Exception in thread "Thread-4" java.lang.OutOfMemoryError
	at java.lang.AbstractStringBuilder.hugeCapacity(AbstractStringBuilder.java:161)
	at java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:155)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:596)
	at java.lang.StringBuffer.append(StringBuffer.java:367)
	at java.io.BufferedReader.readLine(BufferedReader.java:370)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at py4j.commands.AbstractCommand.getStringArguments(AbstractCommand.java:102)
	at py4j.commands.AbstractCommand.getArguments(AbstractCommand.java:79)
	at py4j.commands.CallCommand.execute(CallCommand.java:77)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

**Comment by helenlly** [comment]
@cyita any update for next step?

**Comment by cyita** [comment]
You can define `model_dir` as the path to save the checkpoint in `Estimator.from_pytorch`, the estimator will automatically save the checkpoint while training. And you can use `estimator.load(checkpoint="model_dir", loss=None)` to load the saved checkpoint.
