### ISSUE TITLE
UT: python apptests failed on mac

### ISSUE THREAD

**Issue by pinggao18** [intel-analytics/analytics-zoo#2881]
Caused by: java.net.SocketException: Broken pipe (Write failed)

Traceback (most recent call last):
  File "/var/jenkins_home/workspace/ZOO-NB-Python-AppTests-MAC/dist/apps/anomaly-detection/tmp_test.py", line 293, in <module>
    nb_epoch=20)
  File "/var/jenkins_home/workspace/ZOO-NB-Python-AppTests-MAC/dist/lib/analytics-zoo-bigdl_0.11.1-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/pipeline/api/keras/engine/topology.py", line 239, in fit
  File "/var/jenkins_home/workspace/ZOO-NB-Python-AppTests-MAC/dist/lib/analytics-zoo-bigdl_0.11.1-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/common/utils.py", line 133, in callZooFunc
  File "/var/jenkins_home/workspace/ZOO-NB-Python-AppTests-MAC/dist/lib/analytics-zoo-bigdl_0.11.1-spark_2.4.3-0.9.0-SNAPSHOT-python-api.zip/zoo/common/utils.py", line 127, in callZooFunc
  File "/opt/work/spark-2.4.3-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/opt/work/spark-2.4.3-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o49.zooFit.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 0.0 failed 1 times, most recent failure: Lost task 2.0 in stage 0.0 (TID 2, localhost, executor driver): java.net.SocketException: Broken pipe (Write failed)

jenkins link:

http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-Python-AppTests-MAC/116/console

**Comment by qiyuangong** [comment]
This error is a bit strange. Because this test is running on single node.

**Comment by qiyuangong** [comment]
Doesn't appear in latest NB. Issue closed. 
Will re-open if encounter again. :)
