### ISSUE TITLE
UT: pip-apptests-part4 failed

### ISSUE THREAD

**Issue by pinggao18** [intel-analytics/analytics-zoo#2882]
jenkins link:
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-Pip-AppTests-part4/156/console

2020-09-17 14:51:35,682	INFO services.py:551 -- Failed to connect to the redis server, retrying.
2020-09-17 14:51:36,684	INFO services.py:551 -- Failed to connect to the redis server, retrying.
2020-09-17 14:51:37,685	INFO services.py:551 -- Failed to connect to the redis server, retrying.
2020-09-17 14:51:38,688	INFO services.py:551 -- Failed to connect to the redis server, retrying.
2020-09-17 14:51:39,690	INFO services.py:551 -- Failed to connect to the redis server, retrying.
Prepending /opt/work/conda/envs/py37/lib/python3.7/site-packages/bigdl/share/conf/spark-bigdl.conf to sys.path
Adding /opt/work/conda/envs/py37/lib/python3.7/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.11.1-spark_2.4.3-0.9.0-SNAPSHOT-jar-with-dependencies.jar to BIGDL_JARS
Prepending /opt/work/conda/envs/py37/lib/python3.7/site-packages/zoo/share/conf/spark-analytics-zoo.conf to sys.path
Current pyspark location is : /opt/work/conda/envs/py37/lib/python3.7/site-packages/pyspark/__init__.py
Start to getOrCreate SparkContext
pyspark_submit_args is:  --driver-class-path /opt/work/conda/envs/py37/lib/python3.7/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.11.1-spark_2.4.3-0.9.0-SNAPSHOT-jar-with-dependencies.jar:/opt/work/conda/envs/py37/lib/python3.7/site-packages/bigdl/share/lib/bigdl-0.11.1-jar-with-dependencies.jar pyspark-shell 
Successfully got a SparkContext
Traceback (most recent call last):
  File "/opt/work/jenkins/workspace/ZOO-NB-Pip-AppTests-part4/dist/apps/ray/parameter_server/sharded_parameter_server.py", line 68, in <module>
    ray_ctx.init()
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/zoo/ray/raycontext.py", line 461, in init
    resources=self.extra_params)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/ray/worker.py", line 750, in init
    ray_params=ray_params)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/ray/node.py", line 164, in __init__
    self.start_head_processes()
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/ray/node.py", line 627, in start_head_processes
    self.start_redis()
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/ray/node.py", line 451, in start_redis
    fate_share=self.kernel_fate_share)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/ray/services.py", line 757, in start_redis
    fate_share=fate_share)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/ray/services.py", line 948, in _start_redis_instance
    wait_for_redis_to_start("127.0.0.1", port, password=password)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/ray/services.py", line 556, in wait_for_redis_to_start
    raise RuntimeError("Unable to connect to Redis. If the Redis instance "
RuntimeError: Unable to connect to Redis. If the Redis instance is on a different machine, check that your firewall is configured properly.

**Comment by dding3** [comment]
I think it's an env issue. @glorysdj could you please take a look at it?

**Comment by glorysdj** [comment]
Unable to connect to Redis. Is the redis started successfully?

**Comment by glorysdj** [comment]
It's one time failure, since the builds after this  are all succeeded.  close it.
