### ISSUE TITLE
Error: py4j.protocol.Py4JJavaError: An error occurred while calling o42.initEngine

### ISSUE THREAD

**Issue by Sang565** [intel-analytics/analytics-zoo#2887]
I install Analytics-Zoo 0.8.1 on a Raspberry Pi 4B board (Architecture:  armv7l, 4-core CPU, 4GB RAM, OS: Raspbian Buster 32-bit) by using without pip option through a zip file downloaded from the Release Page (analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.8.1-dist-all.zip). The board is also equipped with Spark-2.4.3 and Python-3.7.3.

I choose the Run with pyspark option to test the installation of Analytics Zoo by several commands below:
> ${ANALYTICS_ZOO_HOME}/bin/pyspark-shell-with-zoo.sh --master local[*]
> import zoo
> from zoo.common.nncontext import *
> zoo.__version__
> sc = init_nncontext()

However, there is an error after running the sc = init_nncontext() command, seen the report below: 
>>> sc = init_nncontext()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/spark-db0647cd-73f1-4322-811c-8271a297b16b/userFiles-68efa8ca-93a4-40d7-b100-b9518ce006ff/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.8.1-python-api.zip/zoo/common/nncontext.py", line 123, in init_nncontext
  File "/tmp/spark-db0647cd-73f1-4322-811c-8271a297b16b/userFiles-68efa8ca-93a4-40d7-b100-b9518ce006ff/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.8.1-python-api.zip/bigdl/util/common.py", line 421, in init_engine
  File "/tmp/spark-db0647cd-73f1-4322-811c-8271a297b16b/userFiles-68efa8ca-93a4-40d7-b100-b9518ce006ff/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.8.1-python-api.zip/bigdl/util/common.py", line 594, in callBigDlFunc
  File "/tmp/spark-db0647cd-73f1-4322-811c-8271a297b16b/userFiles-68efa8ca-93a4-40d7-b100-b9518ce006ff/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.8.1-python-api.zip/bigdl/util/common.py", line 590, in callBigDlFunc
  File "/tmp/spark-db0647cd-73f1-4322-811c-8271a297b16b/userFiles-68efa8ca-93a4-40d7-b100-b9518ce006ff/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.8.1-python-api.zip/bigdl/util/common.py", line 639, in callJavaFunc
  File "/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/usr/local/spark/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value

py4j.protocol.Py4JJavaError: An **error** occurred while calling o42.initEngine.
: java.lang.NoClassDefFoundError: Could not initialize class com.intel.analytics.bigdl.mkl.MKL
        at com.intel.analytics.bigdl.utils.Engine$.initThreadPool(Engine.scala:367)
        at com.intel.analytics.bigdl.utils.Engine$.setCoreNumber(Engine.scala:293)
        at com.intel.analytics.bigdl.utils.Engine$.setNodeAndCore(Engine.scala:437)
        at com.intel.analytics.bigdl.utils.Engine$.init(Engine.scala:116)
        at com.intel.analytics.bigdl.python.api.PythonBigDL.initEngine(PythonBigDL.scala:2508)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:745)

**Comment by yangw1234** [comment]
Hi @Sang565 , thank you for trying out analytics zoo, but Raspberry Pi is not supported right now.

**Comment by Sang565** [comment]
> Hi @Sang565 , thank you for trying out analytics zoo, but Raspberry Pi is not supported right now.
Thanks for your answer, Yang.

Btw, the same error is also occured when I run Analytics Zoo on a VM with **Intel i686** architecture equipped with Ubuntu 32-bit OS.
After that, I've tried to run on another VM with **Intel x86_64** and Ubuntu 64-bit OS, and the error is gone. 

So, it leads me think Analytics Zoo might only support running on 64-bit architecture or OS, but haven't seen any document mention this. Any suggestion?

**Comment by yangw1234** [comment]
Hi @Sang565 , Analytics Zoo is only tested on 64-bit system because 32-bit system has very limited memory. We will update the document.

**Comment by helenlly** [comment]
@yangw1234  any update?

**Comment by yangw1234** [comment]
This is not an issue
