### ISSUE TITLE
ValueError - TimeSequencePredictor: Unknown argument found in the Trainable function.

### ISSUE THREAD

**Issue by MusaBilal4** [intel-analytics/analytics-zoo#2935]
I'm trying to run the `TimeSequencePredictor` with a simple example with the code below,

```from datetime import datetime
import pandas as pd
import ray
from zoo.automl.regression.time_sequence_predictor import TimeSequencePredictor
import timesynth as ts


if __name__ == '__main__':
    ray.init()
    
    time_sampler = ts.TimeSampler(stop_time=20)
    irregular_time_samples = time_sampler.sample_irregular_time(num_points=500, keep_percentage=50)
    datelist = pd.date_range(datetime.today(), periods=len(irregular_time_samples)).tolist()

    ddata = pd.DataFrame({"datetime": datelist,
                          "value": irregular_time_samples})

    tsp = TimeSequencePredictor()

    pipeline = tsp.fit(ddata,
                       metric="mse")
```

I get the following error with the above,

```
/anaconda3/envs/sw2_uc_time_baseline_xgb/lib/python3.6/site-packages/featuretools/synthesis/dfs.py:317: UnusedPrimitiveWarning: Some specified primitives were not used during DFS:
  agg_primitives: ['count']
This may be caused by a using a value of max_depth that is too small, not setting interesting values, or it may indicate no compatible variable types for the primitive were found in the data.
  warnings.warn(warning_msg, UnusedPrimitiveWarning)
Traceback (most recent call last):
  File "model.py", line 22, in <module>
    metric="mse")
  File "envs/baseline/lib/python3.6/site-packages/zoo/automl/regression/time_sequence_predictor.py", line 128, in fit
    remote_dir=remote_dir)
  File "envs/baseline/lib/python3.6/site-packages/zoo/automl/regression/time_sequence_predictor.py", line 261, in _hp_search
    searcher.run()
  File "envs/baseline/lib/python3.6/site-packages/zoo/automl/search/RayTuneSearchEngine.py", line 141, in run
    reuse_actors=True
  File "envs/baseline/lib/python3.6/site-packages/ray/tune/tune.py", line 326, in run
    restore=restore)
  File "envs/baseline/lib/python3.6/site-packages/ray/tune/experiment.py", line 138, in __init__
    self._run_identifier = Experiment.register_if_needed(run)
  File "envs/baseline/lib/python3.6/site-packages/ray/tune/experiment.py", line 258, in register_if_needed
    register_trainable(name, run_object)
  File "envs/baseline/lib/python3.6/site-packages/ray/tune/registry.py", line 62, in register_trainable
    trainable = wrap_function(trainable, warn=warn)
  File "envs/baseline/lib/python3.6/site-packages/ray/tune/function_runner.py", line 481, in wrap_function
    "Found: {}".format(func_args))
ValueError: Unknown argument found in the Trainable function. The function args must include a 'config' positional parameter. Any other args must be 'checkpoint_dir'. Found: ['config', 'tune_reporter']

Process finished with exit code 1
```

**Comment by yushan111** [comment]
Hi, this is the same issue with #2931 . If you use analytics-zoo 0.8, the corresponding ray version is 0.7.2. And our nightly build version (follow the instructions [here](https://analytics-zoo.github.io/master/#PythonUserGuide/install/#install-the-latest-nightly-build-wheels-for-pip) to download nightly build version) now supports ray 0.8.4.

**Comment by yushan111** [comment]
Does that work for you? If so, I will close the issue.

**Comment by helenlly** [comment]
@MusaBilal4 Does that work for you? If no update in a week, I will close the issue. and You can re-open when you need.
