### ISSUE TITLE
SparkXShards.to_ray does not work since ray 0.8.7

### ISSUE THREAD

**Issue by yangw1234** [intel-analytics/analytics-zoo#2948]
connecting plasma store reports error:
```
>>> client = plasma.connect(object_store_address)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/_plasma.pyx", line 848, in pyarrow._plasma.connect
  File "pyarrow/_plasma.pyx", line 289, in pyarrow._plasma.plasma_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
OSError: Connection reset by peer

```

**Comment by yangw1234** [comment]
One idea to solve this is to start a ray driver on each spark task and connecting to the same ray cluster, and use ray put.
e.g.
1. start an actor on each node with name its ip
2. run spark to write rdd data to ray cluster
```
def map_fn(data_iter):
    data = list(data_iter)
    ray.init(ray_cluster_address)
    object_id = ray.put(data)
    actor = ray.get_actor(curent_node_ip)
    actor.append_data.remote(object_id)
    return []
rdd.mapPartition(map_fn).collect()
```
3. getting the data from any actor (local or remote)
```
    actor = ray.get_actor(some_node_ip)
    data = actor.get_data()
````
