### ISSUE TITLE
build whl failed with default parameter.

### ISSUE THREAD

**Issue by qiuxin2012** [intel-analytics/analytics-zoo#2952]
run `bash pyzoo/dev/build.sh linux 0.9.0.dev0`

```
[INFO] ------------------------------------------------------------------------
[INFO] Building analytics-zoo-bigdl_0.11.1-spark_2.4.3 0.9.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.4:get (default-cli) @ analytics-zoo-bigdl_0.11.1-spark_2.4.3 ---
[INFO] Copying /home/xin/.m2/repository/com/intel/analytics/bigdl/dist-spark-2.2.0-scala-2.11.8-all/0.11.1/dist-spark-2.2.0-scala-2.11.8-all-0.11.1-python-api.zip to /home/xin/IntelAnalytics/analytics-zoo5/zoo/python_packages/bigdl-python-api-0.11.1.zip
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.668 s
[INFO] Finished at: 2020-10-13T09:19:33+08:00
[INFO] Final Memory: 31M/1926M
[INFO] ------------------------------------------------------------------------
Fetching nlp-architect 0.3.1
Running: wget -nc https://github.com/NervanaSystems/nlp-architect/archive/v0.3.1.zip -P /home/xin/IntelAnalytics/analytics-zoo5/zoo/python_packages
File ‘/home/xin/IntelAnalytics/analytics-zoo5/zoo/python_packages/v0.3.1.zip’ already there; not retrieving.

Fetching bert with d66a146741588fb208450bde15aa7db143baaa69
Running: wget -nc /bert/archive/d66a146741588fb208450bde15aa7db143baaa69.zip -P /home/xin/IntelAnalytics/analytics-zoo5/zoo/python_packages
/bert/archive/d66a146741588fb208450bde15aa7db143baaa69.zip: Scheme missing.
Failed to get bert package from GitHub.
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] zoo-parent ......................................... SUCCESS [  0.688 s]
[INFO] analytics-zoo-bigdl_0.11.1-spark_2.4.3 ............. FAILURE [01:01 min]
[INFO] ------------------------------------------------------------------------

```

**Comment by qiuxin2012** [comment]
fixed in #2944
