### ISSUE TITLE
Cluster Serving Tensor Copy Exception in logs

### ISSUE THREAD

**Issue by qiyuangong** [intel-analytics/analytics-zoo#3067]
Pre-check fail during Tensor copy. This exception has been caught by cluster serving, so it will not crash service.

2 kinds of errors:

1. dest is 0
```bash
java.lang.IllegalArgumentException: requirement failed: self element number(0) is not equal to source element number(150528)
        at scala.Predef$.require(Predef.scala:224)
        at com.intel.analytics.bigdl.tensor.DenseTensor$.copy(DenseTensor.scala:2661)
        at com.intel.analytics.bigdl.tensor.DenseTensor.copy(DenseTensor.scala:435)
        at com.intel.analytics.zoo.serving.engine.ClusterServingInference$$anonfun$batchInput$2$$anonfun$apply$mcVI$sp$2.apply(ClusterServingInference.scala:184)
        at com.intel.analytics.zoo.serving.engine.ClusterServingInference$$anonfun$batchInput$2$$anonfun$apply$mcVI$sp$2.apply(ClusterServingInference.scala:182)
        at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:134)
        at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:134)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
        at scala.collection.mutable.HashMap$$anon$1.foreach(HashMap.scala:134)
        at com.intel.analytics.zoo.serving.engine.ClusterServingInference$$anonfun$batchInput$2.apply$mcVI$sp(ClusterServingInference.scala:182)
        at com.intel.analytics.zoo.serving.engine.ClusterServingInference$$anonfun$batchInput$2.apply(ClusterServingInference.scala:180)
        at com.intel.analytics.zoo.serving.engine.ClusterServingInference$$anonfun$batchInput$2.apply(ClusterServingInference.scala:180)
        at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:143)
        at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:136)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:169)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:443)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:149)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

2. src is 0 (need to handle this issue)
```
java.lang.IllegalArgumentException: requirement failed: self element number(150528) is not equal to source element number(0)
```

**Comment by qiyuangong** [comment]
Issue fixed by #3062
