### ISSUE TITLE
Cluster Serving NP issue after merge #3062

### ISSUE THREAD

**Issue by qiyuangong** [intel-analytics/analytics-zoo#3068]
#3062 fixed #3067 by caused a new Exception. This NP exception is not handled by Cluster Serving, and will crash cluster serving service. It should be fixed ASAP.
```
Caused by: java.lang.NullPointerException
        at redis.clients.jedis.Connection.isConnected(Connection.java:190)
        at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:108)
        at redis.clients.jedis.Connection.sendCommand(Connection.java:114)
        at redis.clients.jedis.BinaryClient.hmset(BinaryClient.java:305)
        at redis.clients.jedis.Client.hmset(Client.java:221)
        at redis.clients.jedis.PipelineBase.hmset(PipelineBase.java:329)
        at com.intel.analytics.zoo.serving.pipeline.RedisIO$.writeHashMap(RedisIO.scala:54)
        at com.intel.analytics.zoo.serving.PreProcessing.writeNaNtoRedis(PreProcessing.scala:48)
        at com.intel.analytics.zoo.serving.PreProcessing.decodeArrowBase64(PreProcessing.scala:81)
        at com.intel.analytics.zoo.serving.engine.ClusterServingInference$$anonfun$2$$anonfun$apply$2.apply(ClusterServingInference.scala:57)
        at com.intel.analytics.zoo.serving.engine.ClusterServingInference$$anonfun$2$$anonfun$apply$2.apply(ClusterServingInference.scala:55)
        at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:657)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
        at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:648)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by qiyuangong** [comment]
Fixed #3072. Issue closed
