### ISSUE TITLE
UT: scala test failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3173]
Failed
com.intel.analytics.zoo.serving.models.TensorflowModelSpec.TensorflowModel tf auto should work

Error Message
/opt/work/jenkins/workspace/ZOO-NB-UnitTests-3.0-SCALA/zoo/target/test-classes/serving/ndarray-128-base64 (No such file or directory)
Stacktrace
      java.io.FileNotFoundException: /opt/work/jenkins/workspace/ZOO-NB-UnitTests-3.0-SCALA/zoo/target/test-classes/serving/ndarray-128-base64 (No such file or directory)
      at java.io.FileInputStream.open0(Native Method)
      at java.io.FileInputStream.open(FileInputStream.java:195)
      at java.io.FileInputStream.<init>(FileInputStream.java:138)
      at scala.io.Source$.fromFile(Source.scala:94)
      at scala.io.Source$.fromFile(Source.scala:79)
      at scala.io.Source$.fromFile(Source.scala:57)

Failed
com.intel.analytics.zoo.serving.models.TensorflowModelSpec.TensorflowModel tf_2out should work

Error Message
/opt/work/jenkins/workspace/ZOO-NB-UnitTests-3.0-SCALA/zoo/target/test-classes/serving/ndarray-2-base64 (No such file or directory)
Stacktrace
      java.io.FileNotFoundException: /opt/work/jenkins/workspace/ZOO-NB-UnitTests-3.0-SCALA/zoo/target/test-classes/serving/ndarray-2-base64 (No such file or directory)
      at java.io.FileInputStream.open0(Native Method)
      at java.io.FileInputStream.open(FileInputStream.java:195)
      at java.io.FileInputStream.<init>(FileInputStream.java:138)
      at scala.io.Source$.fromFile(Source.scala:94)
      at scala.io.Source$.fromFile(Source.scala:79)
      at scala.io.Source$.fromFile(Source.scala:57)

jenkins link:
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-3.0-SCALA/8/

**Comment by glorysdj** [comment]
https://github.com/intel-analytics/analytics-zoo/pull/3142

please put resource files in src/test/resources
https://github.com/intel-analytics/analytics-zoo/tree/master/zoo/src/test/resources
