### ISSUE TITLE
Read TFRecord data from hdfs to train model(orca on yarn), get UnboundLocalError: local variable 'logs' referenced before assignment

### ISSUE THREAD

**Issue by GitEasonXu** [intel-analytics/analytics-zoo#3245]
## Problem Description:
When I using `init_orca_context` to train keras model, I get `UnboundLocalError: local variable 'logs' referenced before assignment`. But it work well, if I only use keras `model.fit` to train model.
I refer to this solution[#38064](https://github.com/tensorflow/tensorflow/issues/38064#issue-590802997), but it doesn't work
**Error detail:**
```
---------------------------------------------------------------------------
RayTaskError(UnboundLocalError)           Traceback (most recent call last)
<ipython-input-13-d2df687a7340> in <module>
      6                       init_ray_on_spark=True, memory="6g", driver_memory="6g",hadoop_user_name='hdfs', hadoop_conf="/etc/hadoop/3.0.1.0-187/0/")
      7 
----> 8 history = main(5)

<ipython-input-12-f49272480269> in main(max_epoch)
     11                     steps_per_epoch=50000 // batch_size,
     12                     validation_data_creator=val_data_creator,
---> 13                     validation_steps=10000 // batch_size
     14                      )
     15     print(history)

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/zoo/orca/learn/tf2/tf_ray_estimator.py in fit(self, data_creator, epochs, verbose, callbacks, validation_data_creator, class_weight, steps_per_epoch, validation_steps, validation_freq, data_config, feature_cols, label_cols)
    257 
    258             worker_stats = ray.get([self.remote_workers[i].step.remote(**params_list[i])
--> 259                                     for i in range(self.num_workers)])
    260             worker_stats = list(itertools.chain.from_iterable(worker_stats))
    261         stats = worker_stats[0].copy()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/worker.py in get(object_ids, timeout)
   1511                     worker.core_worker.dump_object_store_memory_usage()
   1512                 if isinstance(value, RayTaskError):
-> 1513                     raise value.as_instanceof_cause()
   1514                 else:
   1515                     raise value

RayTaskError(UnboundLocalError): ray::TFRunner.step() (pid=26123, ip=10.180.210.172)
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task.function_executor
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1607477474145_0055/container_1607477474145_0055_01_000003/python_env/lib/python3.6/site-packages/zoo/orca/learn/tf2/tf_runner.py", line 365, in step
    validation_freq=validation_freq)
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1607477474145_0055/container_1607477474145_0055_01_000003/python_env/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 117, in _method_wrapper
    mode=dc.CoordinatorMode.INDEPENDENT_WORKER)
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1607477474145_0055/container_1607477474145_0055_01_000003/python_env/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_coordinator.py", line 860, in run_distribute_coordinator
    task_id, session_config, rpc_layer)
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1607477474145_0055/container_1607477474145_0055_01_000003/python_env/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_coordinator.py", line 360, in _run_single_worker
    return worker_fn(strategy)
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1607477474145_0055/container_1607477474145_0055_01_000003/python_env/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 115, in <lambda>
    lambda _: method(self, *args, **kwargs),
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1607477474145_0055/container_1607477474145_0055_01_000003/python_env/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1104, in fit
    epoch_logs = copy.copy(logs)
UnboundLocalError: local variable 'logs' referenced before assignment
```
The test code can be geted [here](https://github.com/GitEasonXu/analytics-zoo-test-project/blob/main/tf2-zoo-orca-cifar10-hdfs.ipynb)

**Comment by yangw1234** [comment]
Could you try the following code.
```python
train_path = ["hdfs://manager:8020/zoo-datasets/cifar10_train.tfrecord", "hdfs://manager:8020/zoo-datasets/cifar10_train.tfrecord"]
```
Tensorflow will try to automaticly shard on the files. You have two workers, but you only have one file, so the second worker has nothing to process. 

Normally tensorflow will report an error but it somehow got swallowed in this case.
