### ISSUE TITLE
NNEstimator throws TypeError: can't pickle _thread._local objects .

### ISSUE THREAD

**Issue by kanishk1225** [intel-analytics/analytics-zoo#3258]
def create_estimator_keras(self,model):

        criterion = MSECriterion()
        self.estimator_to_fit = NNEstimator(model,criterion ,SeqToTensor([4,4,1]),SeqToTensor([1]))\
        .setBatchSize(self.batch_size).setLearningRate(0.2).setMaxEpoch(self.epoch)
        return self.estimator_to_fit 

### Logs
creating: createMSECriterion
creating: createSeqToTensor
creating: createSeqToTensor
creating: createFeatureLabelPreprocessing
creating: createNNEstimator
Traceback (most recent call last):
  File "zoo_train_model_v2.py", line 154, in <module>
    est_ker = keras_mod.create_estimator_keras(my_model)
  File "/dfs/7/yarn/nm/usercache/e088530/appcache/application_1606884929466_34534/container_e31_1606884929466_34534_01_000014/__pyfiles__/zoo_train_v2.py", line 115, in create_estimator_keras
    self.estimator_to_fit = NNEstimator(model,criterion ,SeqToTensor([4,4,1]),SeqToTensor([1]))\
  File "/dfs/7/yarn/nm/usercache/e088530/appcache/application_1606884929466_34534/container_e31_1606884929466_34534_01_000014/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-python-api.zip/zoo/pipeline/nnframes/nn_classifier.py", line 206, in __init__
  File "/dfs/7/yarn/nm/usercache/e088530/appcache/application_1606884929466_34534/container_e31_1606884929466_34534_01_000014/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-python-api.zip/zoo/common/utils.py", line 120, in callZooFunc
  File "/dfs/7/yarn/nm/usercache/e088530/appcache/application_1606884929466_34534/container_e31_1606884929466_34534_01_000014/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-python-api.zip/zoo/common/utils.py", line 120, in <listcomp>
  File "/dfs/7/yarn/nm/usercache/e088530/appcache/application_1606884929466_34534/container_e31_1606884929466_34534_01_000014/analytics-zoo-bigdl_0.10.0-spark_2.4.3-0.9.0-python-api.zip/bigdl/util/common.py", line 679, in _py2java
  File "/opt/cloudera/parcels/CDH-6.3.3-1.cdh6.3.3.p4342.6805295/lib/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 573, in dumps
TypeError: can't pickle _thread._local objects

**Comment by dding3** [comment]
Have tried below code on my env, but failed repro the error, the estimator can successfully be created.
`linear_model = Sequential().add(Linear(2, 2))
criterion = MSECriterion()
estimator_to_fit = NNEstimator(linear_model, criterion, SeqToTensor([4, 4, 1]), SeqToTensor([1])) \
    .setBatchSize(1024).setLearningRate(0.2).setMaxEpoch(10)`

Could you please share how the model is created. Also could you please tried the latest zoo code, from the error log, the exception is thrown from "nn_classifier.py" L206, however from above code, it should not touch that line(L206).

**Comment by adarshpatankar28** [comment]
Model is created as : 
def create_model():    
    model = models.Sequential()
    model.add(layers.Conv2D(32, (1, 1), activation='relu', input_shape=(4, 4, 1)))
    model.add(layers.MaxPooling2D((2, 2)))
    model.add(layers.Conv2D(32, (1, 1), activation='relu'))
    model.add(layers.Flatten())
    model.add(layers.Dense(32, activation='relu'))
    model.add(layers.Dense(1))
    return model


Sample dataframe is created as :
    data = np.around(5*np.random.rand(20000,16))
    df = pd.DataFrame(data, columns = list('abcdefghijklmnop'))
    df = spark.createDataFrame(df) 
    df = df.withColumn('label', F.round(20000*rand()))
    assembler = VectorAssembler(inputCols=list(' abcdefghijklmnop'),outputCol="features")
    df = assembler.transform(df).select("features","label")

And NNEstimator is called: 
    def create_estimator_keras(self,model):
        criterion = MSECriterion()
        self.estimator_to_fit = NNEstimator(model,criterion ,SeqToTensor([4,4,1]),SeqToTensor([1]))\
        .setBatchSize(self.batch_size).setLearningRate(0.2).setMaxEpoch(self.epoch)
        return self.estimator_to_fit

**Comment by jenniew** [comment]
Related user group issue: https://groups.google.com/g/bigdl-user-group/c/0aEgt2K9VdE

**Comment by jenniew** [comment]
The error occurs when pickle tf keras model. I think this issue may be similar as that: https://github.com/tensorflow/tensorflow/issues/33283. So it may be tensorflow issue. For NNEstimator, we need to pickle model, but for tfpark API, we save model in python side and load in Java side which avoid pickle model issue. I think we may change NNEstimator to use similar way or TFPark APIs in the backend. @yangw1234 Did you meet similar issue before? Can NNEstimator support tf model or tf keras model now?

**Comment by jenniew** [comment]
@adarshpatankar28 Is your model tensorflow keras model? If so, you can use our Orca TF estimator to train. You can refer: https://analytics-zoo.github.io/master/#Orca/orca-keras-quickstart/ and https://analytics-zoo.github.io/master/#Orca/orca-tf-estimator/. NNEstimator cannot support tf model training.
