### ISSUE TITLE
The problem of training the YOLOv1 algorithm based on the zoo platform

### ISSUE THREAD

**Issue by GitEasonXu** [intel-analytics/analytics-zoo#3271]
When I try to train YOLOv1 based on the zoo platform，I get the following question.
```
2020-12-22 09:33:22,413	INFO scripts.py:438 -- 
Started Ray on this node. If you wish to terminate the processes that have been started, run

    ray stop


{'node_ip_address': '192.168.1.2', 'redis_address': '192.168.1.1:48863', 'object_store_address': '/tmp/ray/session_2020-12-22_04-33-14_439676_188650/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2020-12-22_04-33-14_439676_188650/sockets/raylet', 'webui_url': 'localhost:8302', 'session_dir': '/tmp/ray/session_2020-12-22_04-33-14_439676_188650'}
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py in serialize(self, value)
    376             except Exception as e:
    377                 self.get_and_clear_contained_object_ids()
--> 378                 raise e
    379             finally:
    380                 self.set_out_of_band_serialization()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py in serialize(self, value)
    373                 self.set_in_band_serialization()
    374                 inband = pickle.dumps(
--> 375                     value, protocol=5, buffer_callback=writer.buffer_callback)
    376             except Exception as e:
    377                 self.get_and_clear_contained_object_ids()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py in dumps(obj, protocol, buffer_callback)
     70         cp = CloudPickler(file, protocol=protocol,
     71                           buffer_callback=buffer_callback)
---> 72         cp.dump(obj)
     73         return file.getvalue()
     74 

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py in dump(self, obj)
    615     def dump(self, obj):
    616         try:
--> 617             return Pickler.dump(self, obj)
    618         except RuntimeError as e:
    619             if "recursion" in e.args[0]:

TypeError: can't pickle _thread.RLock objects

Exception ignored in: 'ray._raylet.prepare_args'
Traceback (most recent call last):
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py", line 378, in serialize
    raise e
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py", line 375, in serialize
    value, protocol=5, buffer_callback=writer.buffer_callback)
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 72, in dumps
    cp.dump(obj)
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 617, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle _thread.RLock objects
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py in serialize(self, value)
    376             except Exception as e:
    377                 self.get_and_clear_contained_object_ids()
--> 378                 raise e
    379             finally:
    380                 self.set_out_of_band_serialization()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py in serialize(self, value)
    373                 self.set_in_band_serialization()
    374                 inband = pickle.dumps(
--> 375                     value, protocol=5, buffer_callback=writer.buffer_callback)
    376             except Exception as e:
    377                 self.get_and_clear_contained_object_ids()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py in dumps(obj, protocol, buffer_callback)
     70         cp = CloudPickler(file, protocol=protocol,
     71                           buffer_callback=buffer_callback)
---> 72         cp.dump(obj)
     73         return file.getvalue()
     74 

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py in dump(self, obj)
    615     def dump(self, obj):
    616         try:
--> 617             return Pickler.dump(self, obj)
    618         except RuntimeError as e:
    619             if "recursion" in e.args[0]:

TypeError: can't pickle _thread.RLock objects

Exception ignored in: 'ray._raylet.prepare_args'
Traceback (most recent call last):
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py", line 378, in serialize
    raise e
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py", line 375, in serialize
    value, protocol=5, buffer_callback=writer.buffer_callback)
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 72, in dumps
    cp.dump(obj)
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 617, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle _thread.RLock objects
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py in serialize(self, value)
    376             except Exception as e:
    377                 self.get_and_clear_contained_object_ids()
--> 378                 raise e
    379             finally:
    380                 self.set_out_of_band_serialization()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py in serialize(self, value)
    373                 self.set_in_band_serialization()
    374                 inband = pickle.dumps(
--> 375                     value, protocol=5, buffer_callback=writer.buffer_callback)
    376             except Exception as e:
    377                 self.get_and_clear_contained_object_ids()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py in dumps(obj, protocol, buffer_callback)
     70         cp = CloudPickler(file, protocol=protocol,
     71                           buffer_callback=buffer_callback)
---> 72         cp.dump(obj)
     73         return file.getvalue()
     74 

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py in dump(self, obj)
    615     def dump(self, obj):
    616         try:
--> 617             return Pickler.dump(self, obj)
    618         except RuntimeError as e:
    619             if "recursion" in e.args[0]:

TypeError: can't pickle _thread.RLock objects

Exception ignored in: 'ray._raylet.prepare_args'
Traceback (most recent call last):
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py", line 378, in serialize
    raise e
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py", line 375, in serialize
    value, protocol=5, buffer_callback=writer.buffer_callback)
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 72, in dumps
    cp.dump(obj)
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 617, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle _thread.RLock objects
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py in serialize(self, value)
    376             except Exception as e:
    377                 self.get_and_clear_contained_object_ids()
--> 378                 raise e
    379             finally:
    380                 self.set_out_of_band_serialization()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py in serialize(self, value)
    373                 self.set_in_band_serialization()
    374                 inband = pickle.dumps(
--> 375                     value, protocol=5, buffer_callback=writer.buffer_callback)
    376             except Exception as e:
    377                 self.get_and_clear_contained_object_ids()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py in dumps(obj, protocol, buffer_callback)
     70         cp = CloudPickler(file, protocol=protocol,
     71                           buffer_callback=buffer_callback)
---> 72         cp.dump(obj)
     73         return file.getvalue()
     74 

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py in dump(self, obj)
    615     def dump(self, obj):
    616         try:
--> 617             return Pickler.dump(self, obj)
    618         except RuntimeError as e:
    619             if "recursion" in e.args[0]:

TypeError: can't pickle _thread.RLock objects

Exception ignored in: 'ray._raylet.prepare_args'
Traceback (most recent call last):
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py", line 378, in serialize
    raise e
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py", line 375, in serialize
    value, protocol=5, buffer_callback=writer.buffer_callback)
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 72, in dumps
    cp.dump(obj)
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 617, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle _thread.RLock objects
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py in serialize(self, value)
    376             except Exception as e:
    377                 self.get_and_clear_contained_object_ids()
--> 378                 raise e
    379             finally:
    380                 self.set_out_of_band_serialization()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py in serialize(self, value)
    373                 self.set_in_band_serialization()
    374                 inband = pickle.dumps(
--> 375                     value, protocol=5, buffer_callback=writer.buffer_callback)
    376             except Exception as e:
    377                 self.get_and_clear_contained_object_ids()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py in dumps(obj, protocol, buffer_callback)
     70         cp = CloudPickler(file, protocol=protocol,
     71                           buffer_callback=buffer_callback)
---> 72         cp.dump(obj)
     73         return file.getvalue()
     74 

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py in dump(self, obj)
    615     def dump(self, obj):
    616         try:
--> 617             return Pickler.dump(self, obj)
    618         except RuntimeError as e:
    619             if "recursion" in e.args[0]:

TypeError: can't pickle _thread.RLock objects

Exception ignored in: 'ray._raylet.prepare_args'
Traceback (most recent call last):
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py", line 378, in serialize
    raise e
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py", line 375, in serialize
    value, protocol=5, buffer_callback=writer.buffer_callback)
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 72, in dumps
    cp.dump(obj)
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 617, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle _thread.RLock objects
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py in serialize(self, value)
    376             except Exception as e:
    377                 self.get_and_clear_contained_object_ids()
--> 378                 raise e
    379             finally:
    380                 self.set_out_of_band_serialization()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py in serialize(self, value)
    373                 self.set_in_band_serialization()
    374                 inband = pickle.dumps(
--> 375                     value, protocol=5, buffer_callback=writer.buffer_callback)
    376             except Exception as e:
    377                 self.get_and_clear_contained_object_ids()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py in dumps(obj, protocol, buffer_callback)
     70         cp = CloudPickler(file, protocol=protocol,
     71                           buffer_callback=buffer_callback)
---> 72         cp.dump(obj)
     73         return file.getvalue()
     74 

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py in dump(self, obj)
    615     def dump(self, obj):
    616         try:
--> 617             return Pickler.dump(self, obj)
    618         except RuntimeError as e:
    619             if "recursion" in e.args[0]:

TypeError: can't pickle _thread.RLock objects

Exception ignored in: 'ray._raylet.prepare_args'
Traceback (most recent call last):
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py", line 378, in serialize
    raise e
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py", line 375, in serialize
    value, protocol=5, buffer_callback=writer.buffer_callback)
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 72, in dumps
    cp.dump(obj)
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 617, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle _thread.RLock objects
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py in serialize(self, value)
    376             except Exception as e:
    377                 self.get_and_clear_contained_object_ids()
--> 378                 raise e
    379             finally:
    380                 self.set_out_of_band_serialization()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py in serialize(self, value)
    373                 self.set_in_band_serialization()
    374                 inband = pickle.dumps(
--> 375                     value, protocol=5, buffer_callback=writer.buffer_callback)
    376             except Exception as e:
    377                 self.get_and_clear_contained_object_ids()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py in dumps(obj, protocol, buffer_callback)
     70         cp = CloudPickler(file, protocol=protocol,
     71                           buffer_callback=buffer_callback)
---> 72         cp.dump(obj)
     73         return file.getvalue()
     74 

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py in dump(self, obj)
    615     def dump(self, obj):
    616         try:
--> 617             return Pickler.dump(self, obj)
    618         except RuntimeError as e:
    619             if "recursion" in e.args[0]:

TypeError: can't pickle _thread.RLock objects

Exception ignored in: 'ray._raylet.prepare_args'
Traceback (most recent call last):
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py", line 378, in serialize
    raise e
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py", line 375, in serialize
    value, protocol=5, buffer_callback=writer.buffer_callback)
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 72, in dumps
    cp.dump(obj)
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 617, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle _thread.RLock objects
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py in serialize(self, value)
    376             except Exception as e:
    377                 self.get_and_clear_contained_object_ids()
--> 378                 raise e
    379             finally:
    380                 self.set_out_of_band_serialization()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py in serialize(self, value)
    373                 self.set_in_band_serialization()
    374                 inband = pickle.dumps(
--> 375                     value, protocol=5, buffer_callback=writer.buffer_callback)
    376             except Exception as e:
    377                 self.get_and_clear_contained_object_ids()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py in dumps(obj, protocol, buffer_callback)
     70         cp = CloudPickler(file, protocol=protocol,
     71                           buffer_callback=buffer_callback)
---> 72         cp.dump(obj)
     73         return file.getvalue()
     74 

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py in dump(self, obj)
    615     def dump(self, obj):
    616         try:
--> 617             return Pickler.dump(self, obj)
    618         except RuntimeError as e:
    619             if "recursion" in e.args[0]:

TypeError: can't pickle _thread.RLock objects

Exception ignored in: 'ray._raylet.prepare_args'
Traceback (most recent call last):
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py", line 378, in serialize
    raise e
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/serialization.py", line 375, in serialize
    value, protocol=5, buffer_callback=writer.buffer_callback)
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 72, in dumps
    cp.dump(obj)
  File "/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 617, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle _thread.RLock objects
(pid=188804, ip=192.168.1.1) Prepending /hadoop/yarn/local/usercache/hdfs/appcache/application_1608014057528_0031/container_e15_1608014057528_0031_01_000005/python_env/lib/python3.6/site-packages/bigdl/share/conf/spark-bigdl.conf to sys.path
(pid=188804, ip=192.168.1.1) Prepending /hadoop/yarn/local/usercache/hdfs/appcache/application_1608014057528_0031/container_e15_1608014057528_0031_01_000005/python_env/lib/python3.6/site-packages/zoo/share/conf/spark-analytics-zoo.conf to sys.path
(pid=188679, ip=192.168.1.1) Prepending /hadoop/yarn/local/usercache/hdfs/appcache/application_1608014057528_0031/container_e15_1608014057528_0031_01_000004/python_env/lib/python3.6/site-packages/bigdl/share/conf/spark-bigdl.conf to sys.path
(pid=188679, ip=192.168.1.1) Prepending /hadoop/yarn/local/usercache/hdfs/appcache/application_1608014057528_0031/container_e15_1608014057528_0031_01_000004/python_env/lib/python3.6/site-packages/zoo/share/conf/spark-analytics-zoo.conf to sys.path
(pid=188731, ip=192.168.1.1) Prepending /hadoop/yarn/local/usercache/hdfs/appcache/application_1608014057528_0031/container_e15_1608014057528_0031_01_000002/python_env/lib/python3.6/site-packages/bigdl/share/conf/spark-bigdl.conf to sys.path
(pid=188731, ip=192.168.1.1) Prepending /hadoop/yarn/local/usercache/hdfs/appcache/application_1608014057528_0031/container_e15_1608014057528_0031_01_000002/python_env/lib/python3.6/site-packages/zoo/share/conf/spark-analytics-zoo.conf to sys.path
(pid=188805, ip=192.168.1.1) Prepending /hadoop/yarn/local/usercache/hdfs/appcache/application_1608014057528_0031/container_e15_1608014057528_0031_01_000005/python_env/lib/python3.6/site-packages/bigdl/share/conf/spark-bigdl.conf to sys.path
(pid=188805, ip=192.168.1.1) Prepending /hadoop/yarn/local/usercache/hdfs/appcache/application_1608014057528_0031/container_e15_1608014057528_0031_01_000005/python_env/lib/python3.6/site-packages/zoo/share/conf/spark-analytics-zoo.conf to sys.path
(pid=188851, ip=192.168.1.1) Prepending /hadoop/yarn/local/usercache/hdfs/appcache/application_1608014057528_0031/container_e15_1608014057528_0031_01_000003/python_env/lib/python3.6/site-packages/bigdl/share/conf/spark-bigdl.conf to sys.path
(pid=188851, ip=192.168.1.1) Prepending /hadoop/yarn/local/usercache/hdfs/appcache/application_1608014057528_0031/container_e15_1608014057528_0031_01_000003/python_env/lib/python3.6/site-packages/zoo/share/conf/spark-analytics-zoo.conf to sys.path
(pid=188680, ip=192.168.1.1) Prepending /hadoop/yarn/local/usercache/hdfs/appcache/application_1608014057528_0031/container_e15_1608014057528_0031_01_000004/python_env/lib/python3.6/site-packages/bigdl/share/conf/spark-bigdl.conf to sys.path
(pid=188680, ip=192.168.1.1) Prepending /hadoop/yarn/local/usercache/hdfs/appcache/application_1608014057528_0031/container_e15_1608014057528_0031_01_000004/python_env/lib/python3.6/site-packages/zoo/share/conf/spark-analytics-zoo.conf to sys.path
(pid=188730, ip=192.168.1.1) Prepending /hadoop/yarn/local/usercache/hdfs/appcache/application_1608014057528_0031/container_e15_1608014057528_0031_01_000002/python_env/lib/python3.6/site-packages/bigdl/share/conf/spark-bigdl.conf to sys.path
(pid=188730, ip=192.168.1.1) Prepending /hadoop/yarn/local/usercache/hdfs/appcache/application_1608014057528_0031/container_e15_1608014057528_0031_01_000002/python_env/lib/python3.6/site-packages/zoo/share/conf/spark-analytics-zoo.conf to sys.path
(pid=188852, ip=192.168.1.1) Prepending /hadoop/yarn/local/usercache/hdfs/appcache/application_1608014057528_0031/container_e15_1608014057528_0031_01_000003/python_env/lib/python3.6/site-packages/bigdl/share/conf/spark-bigdl.conf to sys.path
(pid=188852, ip=192.168.1.1) Prepending /hadoop/yarn/local/usercache/hdfs/appcache/application_1608014057528_0031/container_e15_1608014057528_0031_01_000003/python_env/lib/python3.6/site-packages/zoo/share/conf/spark-analytics-zoo.conf to sys.path
(pid=188679, ip=192.168.1.1) 2020-12-22 04:33:23.163373: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/jdk64/java/jre/lib/amd64/server:/usr/hdp/3.0.1.0-187/usr/lib/
(pid=188679, ip=192.168.1.1) 2020-12-22 04:33:23.163429: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
(pid=188805, ip=192.168.1.1) 2020-12-22 04:33:23.156236: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/jdk64/java/jre/lib/amd64/server:/usr/hdp/3.0.1.0-187/usr/lib/
(pid=188805, ip=192.168.1.1) 2020-12-22 04:33:23.156305: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
(pid=188804, ip=192.168.1.1) 2020-12-22 04:33:23.163178: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/jdk64/java/jre/lib/amd64/server:/usr/hdp/3.0.1.0-187/usr/lib/
(pid=188804, ip=192.168.1.1) 2020-12-22 04:33:23.163239: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
(pid=188851, ip=192.168.1.1) 2020-12-22 04:33:23.181150: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/jdk64/java/jre/lib/amd64/server:/usr/hdp/3.0.1.0-187/usr/lib/
(pid=188851, ip=192.168.1.1) 2020-12-22 04:33:23.181191: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
(pid=188680, ip=192.168.1.1) 2020-12-22 04:33:23.192742: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/jdk64/java/jre/lib/amd64/server:/usr/hdp/3.0.1.0-187/usr/lib/
(pid=188680, ip=192.168.1.1) 2020-12-22 04:33:23.192802: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
(pid=188731, ip=192.168.1.1) 2020-12-22 04:33:23.192729: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/jdk64/java/jre/lib/amd64/server:/usr/hdp/3.0.1.0-187/usr/lib/
(pid=188731, ip=192.168.1.1) 2020-12-22 04:33:23.192795: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
(pid=188852, ip=192.168.1.1) 2020-12-22 04:33:23.192744: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/jdk64/java/jre/lib/amd64/server:/usr/hdp/3.0.1.0-187/usr/lib/
(pid=188852, ip=192.168.1.1) 2020-12-22 04:33:23.192803: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
(pid=188730, ip=192.168.1.1) 2020-12-22 04:33:23.233367: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/jdk64/java/jre/lib/amd64/server:/usr/hdp/3.0.1.0-187/usr/lib/
(pid=188730, ip=192.168.1.1) 2020-12-22 04:33:23.233437: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
---------------------------------------------------------------------------
RayTaskError(AssertionError)              Traceback (most recent call last)
<timed exec> in <module>

<ipython-input-8-a6ffe331ab73> in main(max_epoch)
      5     }
      6 
----> 7     est = Estimator.from_keras(model_creator, config=config, workers_per_node=2)
      8 
      9     # callback

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/zoo/orca/learn/tf2/tf_ray_estimator.py in from_keras(cls, model_creator, config, verbose, workers_per_node, compile_args_creator, backend)
    189         return cls(model_creator, config=config,
    190                    verbose=verbose, workers_per_node=workers_per_node,
--> 191                    backend=backend, compile_args_creator=compile_args_creator)
    192 
    193     def fit(self, data_creator, epochs=1, verbose=1,

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/zoo/orca/learn/tf2/tf_ray_estimator.py in __init__(self, model_creator, compile_args_creator, config, verbose, backend, workers_per_node)
    151                                    for i in range(0, num_nodes)]
    152             ips = ray.get(
--> 153                 [worker.get_node_ip.remote() for worker in self.remote_workers])
    154             ports = ray.get(
    155                 [worker.find_free_port.remote() for worker in self.remote_workers])

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/worker.py in get(object_ids, timeout)
   1511                     worker.core_worker.dump_object_store_memory_usage()
   1512                 if isinstance(value, RayTaskError):
-> 1513                     raise value.as_instanceof_cause()
   1514                 else:
   1515                     raise value

RayTaskError(AssertionError): ray::IDLE (pid=188804, ip=192.168.1.1)
  File "python/ray/_raylet.pyx", line 414, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 417, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 440, in ray._raylet.execute_task
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1608014057528_0031/container_e15_1608014057528_0031_01_000005/python_env/lib/python3.6/site-packages/ray/signature.py", line 139, in recover_args
    "Flattened arguments need to be even-numbered. See `flatten_args`.")
AssertionError: Flattened arguments need to be even-numbered. See `flatten_args`.
```

The test code can be geted [here](https://github.com/GitEasonXu/analytics-zoo-test-project/blob/main/train_yolov1.ipynb)

**Comment by yangw1234** [comment]
You should create all tensorflow related objects inside model_creator, data_creator, etc. Creating them in the driver and serializing them does not work.

**Comment by GitEasonXu** [comment]
I try to modify model_creator and data_creator, but there is `ModuleNotFoundError`.

**Comment by GitEasonXu** [comment]
> I try to modify model_creator and data_creator, but there is `ModuleNotFoundError`.

https://github.com/intel-analytics/analytics-zoo/issues/3279#issue-773616018

**Comment by yangw1234** [comment]
This issue has been resolved. I am closing it.
