### ISSUE TITLE
pytorch mnist example on Colab  timed out after [100 seconds]

### ISSUE THREAD

**Issue by Le-Zheng** [intel-analytics/analytics-zoo#3283]
```
Py4JJavaError: An error occurred while calling o48.createFeatureSetFromPyTorch.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 1, localhost, executor driver): jep.JepException: java.util.concurrent.TimeoutException: Futures timed out after [100 seconds]
	at com.intel.analytics.zoo.common.PythonInterpreter$.threadExecute(PythonInterpreter.scala:100)
	at com.intel.analytics.zoo.common.PythonInterpreter$.createInterpreter(PythonInterpreter.scala:84)
	at com.intel.analytics.zoo.common.PythonInterpreter$.init(PythonInterpreter.scala:65)
	at com.intel.analytics.zoo.common.PythonInterpreter$.check(PythonInterpreter.scala:58)
	at com.intel.analytics.zoo.common.PythonInterpreter$.exec(PythonInterpreter.scala:106)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:357)
	at com.intel.analytics.zoo.feature.PythonFeatureSet$$anonfun$loadPythonSet$1.apply(FeatureSet.scala:353)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [100 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:190)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$5.apply(PythonInterpreter.scala:93)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$5.apply(PythonInterpreter.scala:92)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
```

colab notebook link : https://colab.research.google.com/drive/1YUGUWBtsHk4XUX3ylUa7sf2EUrRV-slz?usp=sharing

**Comment by qiuxin2012** [comment]
It seems the colab is using system build-in python, but not conda environment, I need to find a way to support system's python.

**Comment by qiuxin2012** [comment]
It's hard to use colab's build-in python, we can try to install a conda envriment to colab.

**Comment by qiuxin2012** [comment]
@Le-Zheng You try can add below command to colab:
```
!pip install -q condacolab
import condacolab
condacolab.install_anaconda()

import condacolab # this check is optional
condacolab.check()


# Install jdk8
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
# Set jdk environment path which enables you to run Pyspark in your Colab environment.
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
!update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
!java -version

!conda install pip
!conda install numpy
!pip install jep==3.9.0 cloudpickle==1.6.0 analytics-zoo
!pip install torch torchvision
```
