### ISSUE TITLE
Fail to find file data.pkl when evaluating PyTorch Model after loaded.

### ISSUE THREAD

**Issue by KimiLiuQh** [intel-analytics/analytics-zoo#3294]
I failed to load a pytorch model at the model.evaluate() step and it shows that file data.pkl not found.
I run the code on Linux Ubuntu 18.04.5 , with IDEA 2017.2; python version is 3.7 with pytorch==1.7.1

Code:
```
// model path is "path/to/pytorch_model/new_inception_v1.pt"
val model = TorchModel(modelBytes, new Array[Float](0))  // no error
model.evaluate()   // report an error after running this line
```

Error Message:
```
jep.JepException: <class 'RuntimeError'>: [enforce fail at inline_container.cc:222] . file not found: new_inception_v1/data.pkl
jep.JepException: jep.JepException: <class 'RuntimeError'>: [enforce fail at inline_container.cc:222] . file not found: new_inception_v1/data.pkl
	at com.intel.analytics.zoo.common.PythonInterpreter$.threadExecute(PythonInterpreter.scala:100)
	at com.intel.analytics.zoo.common.PythonInterpreter$.exec(PythonInterpreter.scala:110)
	at com.intel.analytics.zoo.pipeline.api.net.TorchModel.load$lzycompute(TorchModel.scala:67)
	at com.intel.analytics.zoo.pipeline.api.net.TorchModel.load(TorchModel.scala:47)
	at com.intel.analytics.zoo.pipeline.api.net.TorchModel.evaluate(TorchModel.scala:190)
	at com.intel.analytics.zoo.pipeline.api.net.TorchModel.evaluate(TorchModel.scala:33)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModelFactory$.loadFloatModelForPyTorch(InferenceModelFactory.scala:127)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModel.doLoadPyTorchModel(InferenceModel.scala:464)
	at com.intel.analytics.zoo.pipeline.inference.InferenceModel.doLoadPyTorch(InferenceModel.scala:252)
	at com.intel.analytics.zoo.serving.utils.ClusterServingHelper.loadInferenceModel(ClusterServingHelper.scala:346)
	at com.intel.analytics.zoo.serving.models.PyTorchModelSpec$$anonfun$1.apply$mcV$sp(PyTorchModelSpec.scala:41)
	at com.intel.analytics.zoo.serving.models.PyTorchModelSpec$$anonfun$1.apply(PyTorchModelSpec.scala:33)
	at com.intel.analytics.zoo.serving.models.PyTorchModelSpec$$anonfun$1.apply(PyTorchModelSpec.scala:33)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1679)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
	at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1692)
	at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:393)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:381)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:370)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:407)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:381)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:376)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
	at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1750)
	at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1685)
	at org.scalatest.Suite$class.run(Suite.scala:1124)
	at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
	at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpec.run(FlatSpec.scala:1685)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1349)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1343)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1343)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1012)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1509)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1011)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
Caused by: jep.JepException: <class 'RuntimeError'>: [enforce fail at inline_container.cc:222] . file not found: new_inception_v1/data.pkl
	at /home/arda/anaconda3/envs/zoo37/lib/python3.7/site-packages/torch/serialization._load(serialization.py:850)
	at /home/arda/anaconda3/envs/zoo37/lib/python3.7/site-packages/torch/serialization.load(serialization.py:594)
	at <string>.<module>(<string>:12)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:108)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:107)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:107)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by qiuxin2012** [comment]
`file not found: new_inception_v1/data.pkl`, please make sure your path is correct.
