### ISSUE TITLE
AZ 0.10.0 version. The yolov1 training process is always interrupted suddenly

### ISSUE THREAD

**Issue by GitEasonXu** [intel-analytics/analytics-zoo#3342]
I'm training Yolo model based on AZ(0.10.0), but the training process is always interruputed by such error:
```shell
E0107 22:25:42.346453 162416 task_manager.cc:254] Task failed: IOError: 14: Socket closed: Type=ACTOR_TASK, Language=PYTHON, function_descriptor={type=PythonFunctionDescriptor, module_name=zoo.orca.learn.tf2.tf_runner, class_name=TFRunner, function_name=step, function_hash=}, task_id=aa25f630203d0effcd8f56890100, job_id=0100, num_args=20, num_returns=2, actor_task_spec={actor_id=cd8f56890100, actor_caller_id=ffffffffffffffffffffffff0100, actor_counter=3}
Traceback (most recent call last):
  File "train_yolov1.py", line 137, in <module>
    history = main(20)
  File "train_yolov1.py", line 114, in main
    callbacks = lr_scheduler_callback
  File "/root/anaconda3/envs/zoo0.10.0-tf2.3/lib/python3.6/site-packages/zoo/orca/learn/tf2/tf_ray_estimator.py", line 259, in fit
    for i in range(self.num_workers)])
  File "/root/anaconda3/envs/zoo0.10.0-tf2.3/lib/python3.6/site-packages/ray/worker.py", line 1515, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
Stopping pgids: [162393]
2021-01-07 22:25:42,353	WARNING worker.py:1072 -- A worker died or was killed while executing task ffffffffffffffffcd8f56890100.
Stopping by pgid 162393
Stopping orca context
```
The problem seems to be related to `keras's callbacks`, but using AZ(0.9.0) no such problem.

**Comment by yangw1234** [comment]
hi @GitEasonXu , do you have more logs?

**Comment by leonardozcm** [comment]
hi @GitEasonXu ,anymore details like running at local or yarn?

**Comment by GitEasonXu** [comment]
I train Yolo in yarn mode.
`bigdl.log` just has such info:
```
2021-01-08 13:07:32 WARN  ScriptBasedMapping:254 - Exception running /etc/hadoop/conf/topology_script.py 10.180.210.67 
java.io.IOException: Cannot run program "/etc/hadoop/conf/topology_script.py" (in directory "/root/app"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:938)
	at org.apache.hadoop.util.Shell.run(Shell.java:901)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:1213)
	at org.apache.hadoop.net.ScriptBasedMapping$RawScriptBasedMapping.runResolveCommand(ScriptBasedMapping.java:251)
	at org.apache.hadoop.net.ScriptBasedMapping$RawScriptBasedMapping.resolve(ScriptBasedMapping.java:188)
	at org.apache.hadoop.net.CachedDNSToSwitchMapping.resolve(CachedDNSToSwitchMapping.java:119)
	at org.apache.hadoop.yarn.util.RackResolver.coreResolve(RackResolver.java:101)
	at org.apache.hadoop.yarn.util.RackResolver.resolve(RackResolver.java:81)
	at org.apache.spark.scheduler.cluster.YarnScheduler.getRackForHost(YarnScheduler.scala:37)
	at org.apache.spark.scheduler.TaskSetManager.dequeueTask(TaskSetManager.scala:414)
	at org.apache.spark.scheduler.TaskSetManager.resourceOffer(TaskSetManager.scala:467)
	at org.apache.spark.scheduler.TaskSchedulerImpl$$anonfun$org$apache$spark$scheduler$TaskSchedulerImpl$$resourceOfferSingleTaskSet$1.apply$mcVI$sp(TaskSchedulerImpl.scala:315)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at org.apache.spark.scheduler.TaskSchedulerImpl.org$apache$spark$scheduler$TaskSchedulerImpl$$resourceOfferSingleTaskSet(TaskSchedulerImpl.scala:310)
	at org.apache.spark.scheduler.TaskSchedulerImpl$$anonfun$resourceOffers$4$$anonfun$apply$11.apply(TaskSchedulerImpl.scala:412)
	at org.apache.spark.scheduler.TaskSchedulerImpl$$anonfun$resourceOffers$4$$anonfun$apply$11.apply(TaskSchedulerImpl.scala:409)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.apache.spark.scheduler.TaskSchedulerImpl$$anonfun$resourceOffers$4.apply(TaskSchedulerImpl.scala:409)
	at org.apache.spark.scheduler.TaskSchedulerImpl$$anonfun$resourceOffers$4.apply(TaskSchedulerImpl.scala:396)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.TaskSchedulerImpl.resourceOffers(TaskSchedulerImpl.scala:396)
	at org.apache.spark.scheduler.cluster.CoarseGrainedSchedulerBackend$DriverEndpoint.org$apache$spark$scheduler$cluster$CoarseGrainedSchedulerBackend$DriverEndpoint$$makeOffers(CoarseGrainedSchedulerBackend.scala:273)
	at org.apache.spark.scheduler.cluster.CoarseGrainedSchedulerBackend$DriverEndpoint$$anonfun$receive$1.applyOrElse(CoarseGrainedSchedulerBackend.scala:127)
	at org.apache.spark.rpc.netty.Inbox$$anonfun$process$1.apply$mcV$sp(Inbox.scala:117)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:205)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
	at org.apache.spark.rpc.netty.Dispatcher$MessageLoop.run(Dispatcher.scala:221)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 32 more
```

**Comment by leonardozcm** [comment]
hi @GitEasonXu ,I've tested it with latest AZ, but failed to recurring this issue.
- Maybe you could try again with `pip  uninstall analytics-zoo; pip install --pre analytics-zoo` to get you in the latest release envs.
- And if failure still occurs, consider to reduce the batch_size.

Also, here is my configs as a reference:
```
init_orca_context(cluster_mode="yarn-client", num_nodes=2, cores=30,
                  init_ray_on_spark=True, memory="50g", driver_memory="8g",
                  hadoop_conf="/opt/work/hadoop-2.9.0/etc/hadoop",
                  conf={
                    "spark.executor.extraLibraryPath":"${JAVA_HOME}/jre/lib/amd64/server",
                  },
                  env=env)
```
and 

```
def main(max_epoch):
    batch_size = 256
```

**Comment by leonardozcm** [comment]
> I train Yolo in yarn mode.
> `bigdl.log` just has such info:
> 
> ```
> 2021-01-08 13:07:32 WARN  ScriptBasedMapping:254 - Exception running /etc/hadoop/conf/topology_script.py 10.180.210.67 
> java.io.IOException: Cannot run program "/etc/hadoop/conf/topology_script.py" (in directory "/root/app"): error=2, No such file or directory
> 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
> 	at org.apache.hadoop.util.Shell.runCommand(Shell.java:938)
> 	at org.apache.hadoop.util.Shell.run(Shell.java:901)
> 	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:1213)
> 	at org.apache.hadoop.net.ScriptBasedMapping$RawScriptBasedMapping.runResolveCommand(ScriptBasedMapping.java:251)
> 	at org.apache.hadoop.net.ScriptBasedMapping$RawScriptBasedMapping.resolve(ScriptBasedMapping.java:188)
> 	at org.apache.hadoop.net.CachedDNSToSwitchMapping.resolve(CachedDNSToSwitchMapping.java:119)
> 	at org.apache.hadoop.yarn.util.RackResolver.coreResolve(RackResolver.java:101)
> 	at org.apache.hadoop.yarn.util.RackResolver.resolve(RackResolver.java:81)
> 	at org.apache.spark.scheduler.cluster.YarnScheduler.getRackForHost(YarnScheduler.scala:37)
> 	at org.apache.spark.scheduler.TaskSetManager.dequeueTask(TaskSetManager.scala:414)
> 	at org.apache.spark.scheduler.TaskSetManager.resourceOffer(TaskSetManager.scala:467)
> 	at org.apache.spark.scheduler.TaskSchedulerImpl$$anonfun$org$apache$spark$scheduler$TaskSchedulerImpl$$resourceOfferSingleTaskSet$1.apply$mcVI$sp(TaskSchedulerImpl.scala:315)
> 	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
> 	at org.apache.spark.scheduler.TaskSchedulerImpl.org$apache$spark$scheduler$TaskSchedulerImpl$$resourceOfferSingleTaskSet(TaskSchedulerImpl.scala:310)
> 	at org.apache.spark.scheduler.TaskSchedulerImpl$$anonfun$resourceOffers$4$$anonfun$apply$11.apply(TaskSchedulerImpl.scala:412)
> 	at org.apache.spark.scheduler.TaskSchedulerImpl$$anonfun$resourceOffers$4$$anonfun$apply$11.apply(TaskSchedulerImpl.scala:409)
> 	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
> 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
> 	at org.apache.spark.scheduler.TaskSchedulerImpl$$anonfun$resourceOffers$4.apply(TaskSchedulerImpl.scala:409)
> 	at org.apache.spark.scheduler.TaskSchedulerImpl$$anonfun$resourceOffers$4.apply(TaskSchedulerImpl.scala:396)
> 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
> 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
> 	at org.apache.spark.scheduler.TaskSchedulerImpl.resourceOffers(TaskSchedulerImpl.scala:396)
> 	at org.apache.spark.scheduler.cluster.CoarseGrainedSchedulerBackend$DriverEndpoint.org$apache$spark$scheduler$cluster$CoarseGrainedSchedulerBackend$DriverEndpoint$$makeOffers(CoarseGrainedSchedulerBackend.scala:273)
> 	at org.apache.spark.scheduler.cluster.CoarseGrainedSchedulerBackend$DriverEndpoint$$anonfun$receive$1.applyOrElse(CoarseGrainedSchedulerBackend.scala:127)
> 	at org.apache.spark.rpc.netty.Inbox$$anonfun$process$1.apply$mcV$sp(Inbox.scala:117)
> 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:205)
> 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
> 	at org.apache.spark.rpc.netty.Dispatcher$MessageLoop.run(Dispatcher.scala:221)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.io.IOException: error=2, No such file or directory
> 	at java.lang.UNIXProcess.forkAndExec(Native Method)
> 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
> 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
> 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
> 	... 32 more
> ```

BTW, it seems that your hadoop configs files missed. 
You could check if your envs variables are set right refer to [here](https://github.com/intel-analytics/analytics-zoo/blob/a8e84fef7df296c646e80c9b5ec652abab41476c/pyzoo/zoo/examples/orca/learn/tf/lenet/README.md).

**Comment by GitEasonXu** [comment]
Hi @leonardozcm 
Maybe the errors in the `bigdl.log` are not the essential problem. These two errors also exist when training yolo based on `AZ-0.9.0`, but using `AZ-0.9.0` can train yolo model.

**Comment by yangw1234** [comment]
synced offline, @GitEasonXu will try a smaller batch size and larger memory

**Comment by GitEasonXu** [comment]
@yangw1234 @leonardozcm 
Maybe it is related to OOM. The code runs normally after using a smaller batch size and larger memory.

**Comment by yangw1234** [comment]
great, then I'll close this issue.

**Comment by jason-dai** [comment]
How does the user get the correct error message?

**Comment by yangw1234** [comment]
> How does the user get the correct error message?

I don't think there is a way for the driver to know why some worker has been killed. Maybe there are some cues in workers' log, but it probably needs to be checked manually.
