### ISSUE TITLE
py4j.Py4JException: Method getNumOfSlice([]) does not exist when running tfpark gan example

### ISSUE THREAD

**Issue by cyita** [intel-analytics/analytics-zoo#3363]
When running tfpark gan example, the following error raised:

```
creating: createIdentityCriterion
creating: createEstimator
creating: createEveryEpoch
Traceback (most recent call last):
  File "/home/yina/Documents/analytics-zoo/pyzoo/zoo/examples/tensorflow/tfpark/gan/gan_train_and_evaluate.py", line 85, in <module>
    opt.train(input_fn, MaxIteration(1000))
  File "/home/yina/Documents/analytics-zoo/pyzoo/zoo/tfpark/gan/gan_estimator.py", line 175, in train
    opt.optimize(end_trigger)
  File "/home/yina/Documents/analytics-zoo/pyzoo/zoo/tfpark/tf_optimizer.py", line 763, in optimize
    if self.train_data.value.getNumOfSlice() != 1:
  File "/opt/spark-2.4.3-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/opt/spark-2.4.3-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 332, in get_return_value
py4j.protocol.Py4JError: An error occurred while calling o65.getNumOfSlice. Trace:
py4j.Py4JException: Method getNumOfSlice([]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:274)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

related PR #3344

**Comment by yangw1234** [comment]
Is it possible that you did not compiled the jar using the latest code? We have auto-tested this example.
