### ISSUE TITLE
Zoo jar expose Hadoop DEBUG mode today

### ISSUE THREAD

**Issue by Le-Zheng** [intel-analytics/analytics-zoo#3382]
http://10.239.47.210:18888/job/ZOO-NB-Python-ExampleTests-py36/321/consoleFull 
Python example runs on local on Jenkins, but throw `java.io.IOException: HADOOP_HOME or hadoop.home.dir are not set.`
Bellow error also occurs when running any examples on yarn and K8s.
```
#1 start example test for textclassification
analytics-zoo-data/data/glove.6B.zip already exists
analytics-zoo-data/data/20news-18828.tar.gz already exists
Picked up _JAVA_OPTIONS: -Xmx100G -XX:MaxPermSize=3G
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=3G; support was removed in 8.0
Picked up _JAVA_OPTIONS: -Xmx100G -XX:MaxPermSize=3G
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=3G; support was removed in 8.0
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/work/jenkins/workspace/ZOO-NB-Python-ExampleTests-py36/dist/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/work/spark-2.4.3-bin-hadoop2.7/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
12:54:33.366 [main] DEBUG o.a.spark.util.ShutdownHookManager - Adding shutdown hook
12:54:33.380 [main] DEBUG org.apache.hadoop.util.Shell - Failed to detect a valid hadoop home directory
java.io.IOException: HADOOP_HOME or hadoop.home.dir are not set.
	at org.apache.hadoop.util.Shell.checkHadoopHome(Shell.java:326) [hadoop-common-2.7.3.jar:na]
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:351) [hadoop-common-2.7.3.jar:na]
	at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:80) [hadoop-common-2.7.3.jar:na]
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2823) [hadoop-common-2.7.3.jar:na]
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2818) [hadoop-common-2.7.3.jar:na]
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2684) [hadoop-common-2.7.3.jar:na]
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373) [hadoop-common-2.7.3.jar:na]
	at org.apache.spark.deploy.DependencyUtils$.org$apache$spark$deploy$DependencyUtils$$resolveGlobPath(DependencyUtils.scala:191) [spark-core_2.11-2.4.3.jar:2.4.3]
	at org.apache.spark.deploy.DependencyUtils$$anonfun$resolveGlobPaths$2.apply(DependencyUtils.scala:147) [spark-core_2.11-2.4.3.jar:2.4.3]
	at org.apache.spark.deploy.DependencyUtils$$anonfun$resolveGlobPaths$2.apply(DependencyUtils.scala:145) [spark-core_2.11-2.4.3.jar:2.4.3]
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241) [scala-library-2.11.12.jar:na]
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241) [scala-library-2.11.12.jar:na]
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [scala-library-2.11.12.jar:na]
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35) [scala-library-2.11.12.jar:na]
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241) [scala-library-2.11.12.jar:na]
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104) [scala-library-2.11.12.jar:na]
	at org.apache.spark.deploy.DependencyUtils$.resolveGlobPaths(DependencyUtils.scala:145) [spark-core_2.11-2.4.3.jar:2.4.3]
	at org.apache.spark.deploy.SparkSubmit$$anonfun$prepareSubmitEnvironment$3.apply(SparkSubmit.scala:354) [spark-core_2.11-2.4.3.jar:2.4.3]
	at org.apache.spark.deploy.SparkSubmit$$anonfun$prepareSubmitEnvironment$3.apply(SparkSubmit.scala:354) [spark-core_2.11-2.4.3.jar:2.4.3]
	at scala.Option.map(Option.scala:146) [scala-library-2.11.12.jar:na]
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:354) [spark-core_2.11-2.4.3.jar:2.4.3]
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:143) [spark-core_2.11-2.4.3.jar:2.4.3]
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86) [spark-core_2.11-2.4.3.jar:2.4.3]
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924) [spark-core_2.11-2.4.3.jar:2.4.3]
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933) [spark-core_2.11-2.4.3.jar:2.4.3]
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala) [spark-core_2.11-2.4.3.jar:2.4.3]
12:54:33.431 [main] DEBUG org.apache.hadoop.util.Shell - setsid exited with exit code 0
12:54:33.464 [main] DEBUG o.a.h.m.lib.MutableMetricsFactory - field org.apache.hadoop.metrics2.lib.MutableRate org.apache.hadoop.security.UserGroupInformation$UgiMetrics.loginSuccess with annotation @org.apache.hadoop.metrics2.annotation.Metric(about=, sampleName=Ops, always=false, type=DEFAULT, valueName=Time, value=[Rate of successful kerberos logins and latency (milliseconds)])
12:54:33.470 [main] DEBUG o.a.h.m.lib.MutableMetricsFactory - field org.apache.hadoop.metrics2.lib.MutableRate org.apache.hadoop.security.UserGroupInformation$UgiMetrics.loginFailure with annotation @org.apache.hadoop.metrics2.annotation.Metric(about=, sampleName=Ops, always=false, type=DEFAULT, valueName=Time, value=[Rate of failed kerberos logins and latency (milliseconds)])
12:54:33.470 [main] DEBUG o.a.h.m.lib.MutableMetricsFactory - field org.apache.hadoop.metrics2.lib.MutableRate org.apache.hadoop.security.UserGroupInformation$UgiMetrics.getGroups with annotation @org.apache.hadoop.metrics2.annotation.Metric(about=, sampleName=Ops, always=false, type=DEFAULT, valueName=Time, value=[GetGroups])
12:54:33.471 [main] DEBUG o.a.h.m.impl.MetricsSystemImpl - UgiMetrics, User and group related metrics
12:54:33.505 [main] DEBUG o.a.h.s.a.util.KerberosName - Kerberos krb5 configuration not found, setting default realm to empty
12:54:33.507 [main] DEBUG org.apache.hadoop.security.Groups -  Creating new Groups object
12:54:33.508 [main] DEBUG o.a.hadoop.util.NativeCodeLoader - Trying to load the custom-built native-hadoop library...
12:54:33.509 [main] DEBUG o.a.hadoop.util.NativeCodeLoader - Failed to load native-hadoop with error: java.lang.UnsatisfiedLinkError: no hadoop in java.library.path
12:54:33.509 [main] DEBUG o.a.hadoop.util.NativeCodeLoader - java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
12:54:33.509 [main] WARN  o.a.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
12:54:33.509 [main] DEBUG o.a.hadoop.util.PerformanceAdvisory - Falling back to shell based
12:54:33.509 [main] DEBUG o.a.h.s.JniBasedUnixGroupsMappingWithFallback - Group mapping impl=org.apache.hadoop.security.ShellBasedUnixGroupsMapping
12:54:33.566 [main] DEBUG org.apache.hadoop.security.Groups - Group mapping impl=org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback; cacheTimeout=300000; warningDeltaMs=5000
12:54:33.569 [main] DEBUG o.a.h.security.UserGroupInformation - hadoop login
12:54:33.569 [main] DEBUG o.a.h.security.UserGroupInformation - hadoop login commit
12:54:33.572 [main] DEBUG o.a.h.security.UserGroupInformation - using local user:UnixPrincipal: root
12:54:33.572 [main] DEBUG o.a.h.security.UserGroupInformation - Using user: "UnixPrincipal: root" with name root
12:54:33.572 [main] DEBUG o.a.h.security.UserGroupInformation - User entry: "root"
12:54:33.573 [main] DEBUG o.a.h.security.UserGroupInformation - UGI loginUser:root (auth:SIMPLE)
12:54:33.721 [main] INFO  org.apache.spark.SecurityManager - Changing view acls to: root
12:54:33.722 [main] INFO  org.apache.spark.SecurityManager - Changing modify acls to: root
12:54:33.722 [main] INFO  org.apache.spark.SecurityManager - Changing view acls groups to: 
12:54:33.723 [main] INFO  org.apache.spark.SecurityManager - Changing modify acls groups to: 
12:54:33.723 [main] INFO  org.apache.spark.SecurityManager - SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
pyspark_submit_args is:  --driver-class-path /opt/work/jenkins/workspace/ZOO-NB-Python-ExampleTests-py36/dist/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-SNAPSHOT-jar-with-dependencies.jar pyspark-shell 
```

**Comment by glorysdj** [comment]
maybe the log level is changed to DEBUG. need to check the latest commits.

**Comment by glorysdj** [comment]
caused by https://github.com/intel-analytics/analytics-zoo/pull/3369
@Litchilitchy
logback override the log4j
