### ISSUE TITLE
Orca PyTorch Estimator test for dataframe failed.

### ISSUE THREAD

**Issue by cyita** [intel-analytics/analytics-zoo#3396]
When running orca pytorch estimator test for dataframe, an error raised:

```
Warn: jep.JepException: <class 'IndexError'>: Dimension out of range (expected to be in range of [-1, 0], but got 1)
	at /opt/work/conda/envs/py37/lib/python3.7/site-packages/torch/nn/functional.log_softmax(functional.py:1591)
	at /opt/work/conda/envs/py37/lib/python3.7/site-packages/torch/nn/functional.cross_entropy(functional.py:2422)
	at /opt/work/conda/envs/py37/lib/python3.7/site-packages/torch/nn/modules/loss.forward(loss.py:948)
	at /opt/work/jenkins/workspace/ZOO-PR-Pip-JEP-UT-Spark2.4/pyzoo/test/zoo/orca/learn/jep/test_pytorch_estimator_for_dataframe.loss_func(test_pytorch_estimator_for_dataframe.py:54)
	at <string>.<module>(<string>:1)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply$mcV$sp(PythonInterpreter.scala:108)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:107)
	at com.intel.analytics.zoo.common.PythonInterpreter$$anonfun$1.apply(PythonInterpreter.scala:107)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2021-01-18 07:57:47 ERROR Executor:91 - Exception in task 0.0 in stage 14.0 (TID 15)
jep.JepException: jep.JepException: <class 'IndexError'>: Dimension out of range (expected to be in range of [-1, 0], but got 1)
	at com.intel.analytics.zoo.common.PythonInterpreter$.threadExecute(PythonInterpreter.scala:100)
	at com.intel.analytics.zoo.common.PythonInterpreter$.exec(PythonInterpreter.scala:110)
	at com.intel.analytics.zoo.pipeline.api.net.TorchLoss.updateOutput(TorchLoss.scala:71)
	at com.intel.analytics.zoo.pipeline.api.net.TorchLoss.updateOutput(TorchLoss.scala:27)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractCriterion.forward(AbstractCriterion.scala:73)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$5$$anonfun$apply$2.apply$mcI$sp(DistriOptimizer.scala:270)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$5$$anonfun$apply$2.apply(DistriOptimizer.scala:260)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$4$$anonfun$5$$anonfun$apply$2.apply(DistriOptimizer.scala:260)
	at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$1$$anon$5.call(ThreadPool.scala:160)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cyita** [comment]
Please refer #3393

**Comment by yangw1234** [comment]
fixed
