### ISSUE TITLE
win10 can't init initNNContext

### ISSUE THREAD

**Issue by JWenBin** [intel-analytics/analytics-zoo#3415]
**here is my code:**   
 System.setProperty("hadoop.home.dir", "D:\\hadoop-common-2.2.0-bin-master")
    val conf = new SparkConf()
    conf.setAppName("NCFExample")
      .set("spark.sql.crossJoin.enabled", "true")
      .setMaster("local[6]") 
    val sc = NNContext.initNNContext(conf)

**and the error info is:**
Exception in thread "main" java.lang.Error: Can't extract dynamic lib file to /tmp dir.
java.lang.Error: Can't find dynamic lib file in jar, path = libiomp5md.dll
	at com.intel.analytics.bigdl.mkl.MKL.extract(MKL.java:343)
	at com.intel.analytics.bigdl.mkl.MKL.<clinit>(MKL.java:54)
	at com.intel.analytics.bigdl.utils.Engine$.initThreadPool(Engine.scala:400)
	at com.intel.analytics.bigdl.utils.Engine$.setCoreNumber(Engine.scala:313)
	at com.intel.analytics.bigdl.utils.Engine$.setNodeAndCore(Engine.scala:470)
	at com.intel.analytics.bigdl.utils.Engine$.init(Engine.scala:124)
	at com.intel.analytics.zoo.common.NNContext$.initNNContext(NNContext.scala:148)
	at com.intel.analytics.zoo.common.NNContext$.initNNContext(NNContext.scala:164)
	at NeuralCFexample$.run(NeuralCFexample.scala:71)
	at NeuralCFexample$$anonfun$main$2.apply(NeuralCFexample.scala:57)
	at NeuralCFexample$$anonfun$main$2.apply(NeuralCFexample.scala:56)
	at scala.Option.map(Option.scala:146)
	at NeuralCFexample$.main(NeuralCFexample.scala:55)
	at NeuralCFexample.main(NeuralCFexample.scala)

**any one here facing the same error with me? it seems I should download libiomp5md.dll by myself. I tried, but I can't find a correct libiomp5md.dll**

**Comment by glorysdj** [comment]
Analytics Zoo only supports linux and mac now. Please try it on linux or mac.

**Comment by JWenBin** [comment]
> 
> 
> Analytics Zoo only supports linux and mac now. Please try it on linux or mac.

thanks!
