### ISSUE TITLE
Cluster serving don't load pb model

### ISSUE THREAD

**Issue by gtfaiwxm** [intel-analytics/analytics-zoo#3422]
When I used the Cluster serving to inference my segmentation model whose node was pb, the error was occured:
```
org.apache.flink.runtime.jobmaster.slotpool.SingleLogicalSlot@48c2e335.
java.lang.Error: Model loading failed
at com.intel.analytics.zoo.serving.engine.FlinkInference.open(FlinkInference.scala:63) ~[zoo.jar:?]
at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36) ~[zoo.jar:?]
at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102) ~[zoo.jar:?]
at org.apache.flink.streaming.runtime.tasks.OperatorChain.initializeStateAndOpenOperators(OperatorChain.java:291) ~[zoo.jar:?]
at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$beforeInvoke$0(StreamTask.java:479) ~[zoo.jar:?]
at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:92) ~[zoo.jar:?]
at org.apache.flink.streaming.runtime.tasks.StreamTask.beforeInvoke(StreamTask.java:475) ~[zoo.jar:?]
at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:528) ~[zoo.jar:?]
at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:721) ~[zoo.jar:?]
at org.apache.flink.runtime.taskmanager.Task.run(Task.java:546) ~[zoo.jar:?]
at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_121]
2021-01-22 16:14:08,249 INFO  org.apache.flink.runtime.executiongraph.failover.flip1.RestartPipelinedRegionFailoverStrategy [] - Calculating tasks to restart to recover the failed task cbc357ccb763df2852fee8c4fc7d55f2_0.
2021-01-22 16:14:08,250 INFO  org.apache.flink.runtime.executiongraph.failover.flip1.RestartPipelinedRegionFailoverStrategy [] - 1 tasks should be restarted to recover the failed task cbc357ccb763df2852fee8c4fc7d55f2_0. 
2021-01-22 16:14:08,252 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Job Cluster Serving - serving_stream (ae853e98b1ffdabc870cecfca6f97d4d) switched from state RUNNING to FAILING.
```

**Comment by Litchilitchy** [comment]
@gtfaiwxm hi, 1. where does this log come from, and 2. could you list the contents in your model directory?

**Comment by gtfaiwxm** [comment]
hi, the log files and the contents in my model directory:
[log_pb.zip](https://github.com/intel-analytics/analytics-zoo/files/5864014/log_pb.zip)

**Comment by Litchilitchy** [comment]
The error is shown in `xxx.err`, Cluster Serving only support frozen graph format of 
```
frozen_inference_graph.pb
graph_meta.json
```
Could you change the format into this, or try savedModel format?

**Comment by Litchilitchy** [comment]
> The error is shown in `xxx.err`, Cluster Serving only support frozen graph format of
> 
> ```
> frozen_inference_graph.pb
> graph_meta.json
> ```
> 
> Could you change the format into this, or try savedModel format?

Any new TF frozen API supported now? @jason-dai @yangw1234

**Comment by gtfaiwxm** [comment]
I have modified the name of my model files.
[new_log_pb.zip](https://github.com/intel-analytics/analytics-zoo/files/5864525/new_log_pb.zip)

**Comment by Litchilitchy** [comment]
It is recommended to use SavedModel to load tensorflow model.

The frozen model of Cluster Serving is a fixed-format API and the `.pb` name should be regulated and `graph_meta.json` should be exported by Analytics Zoo [export tf method](https://github.com/intel-analytics/analytics-zoo/blob/9c29bc7d678b526cd8ff256d731ed9ac2c18cc81/pyzoo/zoo/util/tf.py#L50)

**Comment by gtfaiwxm** [comment]
@Litchilitchy Can you give me the code which can obtain json file from pb file?

**Comment by Litchilitchy** [comment]
@gtfaiwxm update after check with our TF expert @yangw1234 :

The `.pb` model file does not contain the information of inputs and outputs, if you use TF, you should still provide these two arguments when loading `.pb`. 

Thus there is no way to export inputs and outputs meta from `.pb`.

**Comment by Litchilitchy** [comment]
@gtfaiwxm I would post the link of `.meta` regulation here.

**Comment by jason-dai** [comment]
> @gtfaiwxm update after check with our TF expert @yangw1234 :
> 
> The `.pb` model file does not contain the information of inputs and outputs, if you use TF, you should still provide these two arguments when loading `.pb`.
> 
> Thus there is no way to export inputs and outputs meta from `.pb`.

Does it make more sense to use SavedModel instead of `.pb` file here?

**Comment by Litchilitchy** [comment]
@jason-dai I think both make sense, the `.pb` here is frozen graph, in Analytics Zoo API we could use a `.meta` file to substitute the variables in tf python api, like mentioned here https://github.com/intel-analytics/analytics-zoo/blob/master/docs/docs/ClusterServingGuide/ProgrammingGuide.md#preparing-model

**Comment by Litchilitchy** [comment]
We discussed in our team, as `graph_meta.json` is provided, the regulation makes sense, and this part would not change currently.
