### ISSUE TITLE
Exception happened when running the example notebook in latest hyper-zoo image

### ISSUE THREAD

**Issue by dding3** [intel-analytics/analytics-zoo#3428]
The exception is 
[I 11:31:01.307 NotebookApp] Kernel started: e3e23ef3-7652-4b85-8b06-b37ffbd3822a, name: python3
[E 11:31:01.845 NotebookApp] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f61c752d710>, count=0)
    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
        ret = callback()
      File "/root/miniconda3/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
        return fn(*args, **kwargs)
      File "/root/miniconda3/lib/python3.7/site-packages/notebook/services/kernels/handlers.py", line 207, in nudge
        if self.ws_connection is None or self.ws_connection.is_closing():
    AttributeError: 'WebSocketProtocol13' object has no attribute 'is_closing'
[E 11:32:01.849 NotebookApp] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f61c752dc20>, <Future finished exception=TimeoutError('Timeout')>)
    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
        ret = callback()
      File "/root/miniconda3/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
        return fn(*args, **kwargs)
      File "/root/miniconda3/lib/python3.7/site-packages/tornado/websocket.py", line 553, in <lambda>
        self.stream.io_loop.add_future(result, lambda f: f.result())
    tornado.util.TimeoutError: Timeout
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=TimeoutError('Timeout')>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/miniconda3/lib/python3.7/site-packages/tornado/websocket.py", line 757, in _accept_connection
    yield open_result
  File "/root/miniconda3/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/root/miniconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/root/miniconda3/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/tornado/websocket.py", line 553, in <lambda>
    self.stream.io_loop.add_future(result, lambda f: f.result())
tornado.util.TimeoutError: Timeout
 
Need to reinstall jupyterlab `sudo -H pip install jupyterlab -U` to fix it.

**Comment by glorysdj** [comment]
need to update dockerfile of hyperzoo to install jupyterlab as dingding mentioned sudo -H pip install jupyterlab -U
