### ISSUE TITLE
java.lang.NullPointerException raised when Orca bigdl estimator doing evaluation

### ISSUE THREAD

**Issue by leonardozcm** [intel-analytics/analytics-zoo#3437]
when codes run at ：
```
print('Evaluating...')
result = est.evaluate(val_dataset)
print(result)
```
raise error：
```
Traceback (most recent call last):
  File "/home/arda/PycharmProjects/inception/main.py", line 81, in <module>
    result = est.evaluate(val_dataset)
  File "/home/arda/Project/analytics-zoo/pyzoo/zoo/orca/learn/bigdl/estimator.py", line 192, in evaluate
    result = self.estimator.evaluate(val_feature_set, validation_metrics, batch_size)
  File "/home/arda/Project/analytics-zoo/pyzoo/zoo/pipeline/estimator/estimator.py", line 202, in evaluate
    validation_set, validation_method, batch_size)
  File "/home/arda/Project/analytics-zoo/pyzoo/zoo/common/utils.py", line 133, in callZooFunc
    raise e
  File "/home/arda/Project/analytics-zoo/pyzoo/zoo/common/utils.py", line 127, in callZooFunc
    java_result = api(*args)
  File "/home/arda/Public/spark-2.4.3-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/home/arda/Public/spark-2.4.3-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o51.estimatorEvaluate.
: java.lang.NullPointerException
	at scala.collection.convert.Wrappers$JListWrapper.length(Wrappers.scala:86)
	at scala.collection.SeqLike$class.size(SeqLike.scala:106)
	at scala.collection.AbstractSeq.size(Seq.scala:41)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:285)
	at scala.collection.AbstractTraversable.toArray(Traversable.scala:104)
	at com.intel.analytics.zoo.pipeline.estimator.python.PythonEstimator.estimatorEvaluate(PythonEstimator.scala:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cyita** [comment]
You should pass the validation metrics like
```
eval_result = estimator.evaluate(data=data_shard,
                                             validation_metrics=[Accuracy()],
                                             batch_size=8)
```

**Comment by cyita** [comment]
I'll add an error msg for this.

**Comment by leonardozcm** [comment]
> You should pass the validation metrics like
> 
> ```
> eval_result = estimator.evaluate(data=data_shard,
>                                              validation_metrics=[Accuracy()],
>                                              batch_size=8)
> ```

Yes, it works. Thanks a lot!
