### ISSUE TITLE
Error when running object detection problem example (Retraining model) analytics-zoo / apps / object-detection / messi.ipynb

### ISSUE THREAD

**Issue by beta21s** [intel-analytics/analytics-zoo#3473]
Hi everybody,
I tried to retrain the model, but using them for recognition didn't work.
Please everyone have done the relative detection problem help me
I have a question with the messi example model then the model name ```bigdl_messi_quantize.model``` which has the training model available is ```analytics-zoo-*. model```. Which means why one side is ```bigdl- *``` and the other side is ```analytics-zoo *``` ?
[https://github.com/intel-analytics/analytics-zoo/blob/master/apps/object-detection/messi.ipynb](https://github.com/intel-analytics/analytics-zoo/blob/master/apps/object-detection/messi.ipynb)
```
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"

from zoo.common.nncontext import *
from zoo.feature.image import *
from zoo.feature.common import ChainedPreprocessing
from zoo.models.image.common.image_config import ImageConfigure
from zoo.models.image.objectdetection import *

import os
from IPython.display import Image, display
from moviepy.editor import *

sc = init_nncontext()
model=ObjectDetector.load_model("final.model")

print ('load model done')

preprocess = ChainedPreprocessing([ImageResize(300, 300), ImageChannelNormalize(123.0, 117.0, 104.0), ImageMatToTensor(), ImageSetToSample()])
postprocess = ScaleDetection()

label_map = {0: '__background__', 1: 'African_hunting_dog'}
config = ImageConfigure(preprocess, postprocess, 2, label_map)

output = model.predict_image_set('/home/at/Desktop/img-3.png', config)
```
And here is the error when running the code above
```
/usr/local/lib/python3.6/dist-packages/bigdl/util/engine.py:41: UserWarning: Find both SPARK_HOME and pyspark. You may need to check whether they match with each other. SPARK_HOME environment variable is set to: /opt/spark-2.4.3, and pyspark is found in: /usr/local/lib/python3.6/dist-packages/pyspark/__init__.py. If they are unmatched, please use one source only to avoid conflict. For example, you can unset SPARK_HOME and use pyspark only.
  warnings.warn(warning_msg)
Prepending /usr/local/lib/python3.6/dist-packages/bigdl/share/conf/spark-bigdl.conf to sys.path
/usr/local/lib/python3.6/dist-packages/zoo/util/engine.py:42: UserWarning: Find both SPARK_HOME and pyspark. You may need to check whether they match with each other. SPARK_HOME environment variable is set to: /opt/spark-2.4.3, and pyspark is found in: /usr/local/lib/python3.6/dist-packages/pyspark/__init__.py. If they are unmatched, you are recommended to use one source only to avoid conflict. For example, you can unset SPARK_HOME and use pyspark only.
  warnings.warn(warning_msg)
Adding /usr/local/lib/python3.6/dist-packages/zoo/share/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.9.0-jar-with-dependencies.jar to BIGDL_JARS
Prepending /usr/local/lib/python3.6/dist-packages/zoo/share/conf/spark-analytics-zoo.conf to sys.path
pyspark_submit_args is:  --driver-class-path /usr/local/lib/python3.6/dist-packages/zoo/share/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.9.0-jar-with-dependencies.jar:/usr/local/lib/python3.6/dist-packages/bigdl/share/lib/bigdl-0.12.1-jar-with-dependencies.jar pyspark-shell 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/lib/python3.6/dist-packages/zoo/share/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.9.0-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/spark-2.4.3/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2021-02-07 13:12:41 WARN  Utils:66 - Your hostname, at resolves to a loopback address: 127.0.1.1; using 10.10.100.120 instead (on interface enp0s3)
2021-02-07 13:12:41 WARN  Utils:66 - Set SPARK_LOCAL_IP if you need to bind to another address
2021-02-07 13:12:41 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

User settings:

   KMP_AFFINITY=granularity=fine,compact,1,0
   KMP_BLOCKTIME=0
   KMP_SETTINGS=1
   OMP_NUM_THREADS=1

Effective settings:

   KMP_ABORT_DELAY=0
   KMP_ADAPTIVE_LOCK_PROPS='1,1024'
   KMP_ALIGN_ALLOC=64
   KMP_ALL_THREADPRIVATE=128
   KMP_ATOMIC_MODE=2
   KMP_BLOCKTIME=0
   KMP_CPUINFO_FILE: value is not defined
   KMP_DETERMINISTIC_REDUCTION=false
   KMP_DEVICE_THREAD_LIMIT=2147483647
   KMP_DISP_HAND_THREAD=false
   KMP_DISP_NUM_BUFFERS=7
   KMP_DUPLICATE_LIB_OK=false
   KMP_FORCE_REDUCTION: value is not defined
   KMP_FOREIGN_THREADS_THREADPRIVATE=true
   KMP_FORKJOIN_BARRIER='2,2'
   KMP_FORKJOIN_BARRIER_PATTERN='hyper,hyper'
   KMP_FORKJOIN_FRAMES=true
   KMP_FORKJOIN_FRAMES_MODE=3
   KMP_GTID_MODE=3
   KMP_HANDLE_SIGNALS=false
   KMP_HOT_TEAMS_MAX_LEVEL=1
   KMP_HOT_TEAMS_MODE=0
   KMP_INIT_AT_FORK=true
   KMP_ITT_PREPARE_DELAY=0
   KMP_LIBRARY=throughput
   KMP_LOCK_KIND=queuing
   KMP_MALLOC_POOL_INCR=1M
   KMP_MWAIT_HINTS=0
   KMP_NUM_LOCKS_IN_BLOCK=1
   KMP_PLAIN_BARRIER='2,2'
   KMP_PLAIN_BARRIER_PATTERN='hyper,hyper'
   KMP_REDUCTION_BARRIER='1,1'
   KMP_REDUCTION_BARRIER_PATTERN='hyper,hyper'
   KMP_SCHEDULE='static,balanced;guided,iterative'
   KMP_SETTINGS=true
   KMP_SPIN_BACKOFF_PARAMS='4096,100'
   KMP_STACKOFFSET=64
   KMP_STACKPAD=0
   KMP_STACKSIZE=8M
   KMP_STORAGE_MAP=false
   KMP_TASKING=2
   KMP_TASKLOOP_MIN_TASKS=0
   KMP_TASK_STEALING_CONSTRAINT=1
   KMP_TEAMS_THREAD_LIMIT=4
   KMP_TOPOLOGY_METHOD=all
   KMP_USER_LEVEL_MWAIT=false
   KMP_USE_YIELD=1
   KMP_VERSION=false
   KMP_WARNINGS=true
   OMP_AFFINITY_FORMAT='OMP: pid %P tid %i thread %n bound to OS proc set {%A}'
   OMP_ALLOCATOR=omp_default_mem_alloc
   OMP_CANCELLATION=false
   OMP_DEBUG=disabled
   OMP_DEFAULT_DEVICE=0
   OMP_DISPLAY_AFFINITY=false
   OMP_DISPLAY_ENV=false
   OMP_DYNAMIC=false
   OMP_MAX_ACTIVE_LEVELS=2147483647
   OMP_MAX_TASK_PRIORITY=0
   OMP_NESTED=false
   OMP_NUM_THREADS='1'
   OMP_PLACES: value is not defined
   OMP_PROC_BIND='intel'
   OMP_SCHEDULE='static'
   OMP_STACKSIZE=8M
   OMP_TARGET_OFFLOAD=DEFAULT
   OMP_THREAD_LIMIT=2147483647
   OMP_TOOL=enabled
   OMP_TOOL_LIBRARIES: value is not defined
   OMP_WAIT_POLICY=PASSIVE
   KMP_AFFINITY='noverbose,warnings,respect,granularity=fine,compact,1,0'

cls.getname: com.intel.analytics.bigdl.python.api.Sample
BigDLBasePickler registering: bigdl.util.common  Sample
cls.getname: com.intel.analytics.bigdl.python.api.EvaluatedResult
BigDLBasePickler registering: bigdl.util.common  EvaluatedResult
cls.getname: com.intel.analytics.bigdl.python.api.JTensor
BigDLBasePickler registering: bigdl.util.common  JTensor
cls.getname: com.intel.analytics.bigdl.python.api.JActivity
BigDLBasePickler registering: bigdl.util.common  JActivity
Traceback (most recent call last):
  File "a.py", line 15, in <module>
    model=ObjectDetector.load_model("final.model")
  File "/usr/local/lib/python3.6/dist-packages/zoo/models/image/objectdetection/object_detector.py", line 65, in load_model
    jmodel = callZooFunc(bigdl_type, "loadObjectDetector", path, weight_path)
  File "/usr/local/lib/python3.6/dist-packages/zoo/common/utils.py", line 133, in callZooFunc
    raise e
  File "/usr/local/lib/python3.6/dist-packages/zoo/common/utils.py", line 127, in callZooFunc
    java_result = api(*args)
  File "/usr/local/lib/python3.6/dist-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/local/lib/python3.6/dist-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o43.loadObjectDetector.
: java.lang.RuntimeException: Loading module com.intel.analytics.zoo.models.image.objectdetection.ssd.SSDVGG exception :
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.load(ModuleSerializer.scala:154)
	at com.intel.analytics.bigdl.utils.serializer.ModuleLoader$.loadFromFile(ModuleLoader.scala:64)
	at com.intel.analytics.bigdl.nn.Module$.loadModule(Module.scala:61)
	at com.intel.analytics.zoo.models.image.common.ImageModel$.loadModel(ImageModel.scala:132)
	at com.intel.analytics.zoo.models.image.objectdetection.ObjectDetector$.loadModel(ObjectDetector.scala:51)
	at com.intel.analytics.zoo.models.python.PythonZooModel.loadObjectDetector(PythonZooModel.scala:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Loading module com.intel.analytics.bigdl.nn.Sequential exception :
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.load(ModuleSerializer.scala:154)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializable$$anonfun$loadSubModules$1.apply(ModuleSerializable.scala:486)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializable$$anonfun$loadSubModules$1.apply(ModuleSerializable.scala:485)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializable$class.loadSubModules(ModuleSerializable.scala:485)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializer$.loadSubModules(ModuleSerializable.scala:521)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializable$class.doLoadModule(ModuleSerializable.scala:495)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializer$.doLoadModule(ModuleSerializable.scala:521)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.loadModule(ModuleSerializable.scala:101)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializer$.loadModule(ModuleSerializable.scala:521)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.load(ModuleSerializer.scala:151)
	... 16 more
Caused by: java.lang.RuntimeException: Loading module com.intel.analytics.bigdl.nn.StaticGraph exception :
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.load(ModuleSerializer.scala:154)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializable$$anonfun$loadSubModules$1.apply(ModuleSerializable.scala:486)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializable$$anonfun$loadSubModules$1.apply(ModuleSerializable.scala:485)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializable$class.loadSubModules(ModuleSerializable.scala:485)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializer$.loadSubModules(ModuleSerializable.scala:521)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializable$class.doLoadModule(ModuleSerializable.scala:495)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializer$.doLoadModule(ModuleSerializable.scala:521)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.loadModule(ModuleSerializable.scala:101)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializer$.loadModule(ModuleSerializable.scala:521)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.load(ModuleSerializer.scala:151)
	... 29 more
Caused by: java.lang.RuntimeException: Loading module com.intel.analytics.bigdl.nn.SpatialConvolution exception :
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.load(ModuleSerializer.scala:154)
	at com.intel.analytics.bigdl.nn.GraphSerializable$$anonfun$prepareLoadModule$3.apply(Graph.scala:586)
	at com.intel.analytics.bigdl.nn.GraphSerializable$$anonfun$prepareLoadModule$3.apply(Graph.scala:585)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at com.intel.analytics.bigdl.nn.GraphSerializable$class.prepareLoadModule(Graph.scala:585)
	at com.intel.analytics.bigdl.nn.Graph$.prepareLoadModule(Graph.scala:476)
	at com.intel.analytics.bigdl.nn.GraphSerializable$class.doLoadModule(Graph.scala:633)
	at com.intel.analytics.bigdl.nn.Graph$.doLoadModule(Graph.scala:476)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.loadModule(ModuleSerializable.scala:101)
	at com.intel.analytics.bigdl.nn.Graph$.loadModule(Graph.scala:476)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.load(ModuleSerializer.scala:151)
	... 42 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaMethodMirror.jinvokeraw(JavaMirrors.scala:336)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaMethodMirror.jinvoke(JavaMirrors.scala:339)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaVanillaMethodMirror.apply(JavaMirrors.scala:355)
	at com.intel.analytics.bigdl.utils.ReflectionUtils$.reflection(ReflectionUtils.scala:69)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.doLoadModule(ModuleSerializable.scala:128)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.doLoadModule(ModuleSerializer.scala:36)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.loadModule(ModuleSerializable.scala:101)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.loadModule(ModuleSerializer.scala:36)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.load(ModuleSerializer.scala:151)
	... 55 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at scala.reflect.ManifestFactory$$anon$11.newArray(Manifest.scala:133)
	at scala.reflect.ManifestFactory$$anon$11.newArray(Manifest.scala:131)
	at com.intel.analytics.bigdl.tensor.Tensor$.apply(Tensor.scala:963)
	at com.intel.analytics.bigdl.nn.SpatialConvolution.<init>(SpatialConvolution.scala:117)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaMethodMirror.jinvokeraw(JavaMirrors.scala:336)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaMethodMirror.jinvoke(JavaMirrors.scala:339)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaVanillaMethodMirror.apply(JavaMirrors.scala:355)
	at com.intel.analytics.bigdl.utils.ReflectionUtils$.reflection(ReflectionUtils.scala:69)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.doLoadModule(ModuleSerializable.scala:128)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.doLoadModule(ModuleSerializer.scala:36)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.loadModule(ModuleSerializable.scala:101)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.loadModule(ModuleSerializer.scala:36)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.load(ModuleSerializer.scala:151)
	at com.intel.analytics.bigdl.nn.GraphSerializable$$anonfun$prepareLoadModule$3.apply(Graph.scala:586)
	at com.intel.analytics.bigdl.nn.GraphSerializable$$anonfun$prepareLoadModule$3.apply(Graph.scala:585)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at com.intel.analytics.bigdl.nn.GraphSerializable$class.prepareLoadModule(Graph.scala:585)
	at com.intel.analytics.bigdl.nn.Graph$.prepareLoadModule(Graph.scala:476)
	at com.intel.analytics.bigdl.nn.GraphSerializable$class.doLoadModule(Graph.scala:633)
	at com.intel.analytics.bigdl.nn.Graph$.doLoadModule(Graph.scala:476)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializable$class.loadModule(ModuleSerializable.scala:101)
	at com.intel.analytics.bigdl.nn.Graph$.loadModule(Graph.scala:476)
	at com.intel.analytics.bigdl.utils.serializer.ModuleSerializer$.load(ModuleSerializer.scala:151)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializable$$anonfun$loadSubModules$1.apply(ModuleSerializable.scala:486)
	at com.intel.analytics.bigdl.utils.serializer.ContainerSerializable$$anonfun$loadSubModules$1.apply(ModuleSerializable.scala:485)
```

**Comment by qiuxin2012** [comment]
From your error stack, I find it's a OOM Error `Caused by: java.lang.OutOfMemoryError: Java heap space`.
You need to increase your driver memory to fix this issue. See https://github.com/intel-analytics/analytics-zoo/tree/master/apps/object-detection#run-jupyter-after-pip-install or https://github.com/intel-analytics/analytics-zoo/tree/master/apps/object-detection#run-jupyter-with-prebuilt-package for help.


`I have a question with the messi example model then the model name bigdl_messi_quantize.model which has the training model available is analytics-zoo-*. model. Which means why one side is bigdl- * and the other side is analytics-zoo * ?`
analytics-zoo integrates BigDL, analytics-zoo use BigDL as a deep learning engine, and you can use all bigdl models in analytics-zoo.

**Comment by beta21s** [comment]
Thank you for supporting me!
I have an error and cannot resolve it.

I train as shown below. And run the training code and generate the error below
I really don't understand where the error came from even though it was supported. I would like to thank you very much?
[https://github.com/intel-analytics/analytics-zoo/issues/3299](https://github.com/intel-analytics/analytics-zoo/issues/3299)
```
spark-submit \
    --master local[4] \
    --driver-memory 40g \
    --executor-memory 40g \
    --conf "spark.serializer=org.apache.spark.serializer.JavaSerializer" \
    --class com.intel.analytics.zoo.examples.objectdetection.finetune.ssd.Train \
    analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-SNAPSHOT-jar-with-dependencies.jar \
    --resolution 300 \
    --model analytics-zoo_ssd-vgg16-300x300_PASCAL_0.1.0.model \
    --class /home/at/Desktop/dogs/classname.txt \
    -f /home/at/Desktop/dogs/seq/train \
    -v /home/at/Desktop/dogs/seq/test \
    -e 1 -b 4 \
    --modelDir /home/at/Desktop/dogs/model \
    -l 0.0001 --learningRateDecay 0.0005
```

```
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_DRIVER_MEMORY"] = "8g"

from zoo.common.nncontext import *
from zoo.models.image.objectdetection import *

from zoo.models.image.common.image_config import ImageConfigure
from zoo.feature.image.imagePreprocessing import ImageResize
from zoo.feature.common import ChainedPreprocessing


ImageConfigure(pre_processor=ImageResize(224, 224))
ImageConfigure(pre_processor=ChainedPreprocessing([ImageResize(224, 224), ImageResize(224, 224)]))

sc = init_nncontext()
model = ObjectDetector.load_model("/home/at/Desktop/final.model")
print('done')
```

```/usr/local/lib/python3.6/dist-packages/bigdl/util/engine.py:41: UserWarning: Find both SPARK_HOME and pyspark. You may need to check whether they match with each other. SPARK_HOME environment variable is set to: /opt/spark-2.4.3, and pyspark is found in: /usr/local/lib/python3.6/dist-packages/pyspark/__init__.py. If they are unmatched, please use one source only to avoid conflict. For example, you can unset SPARK_HOME and use pyspark only.
  warnings.warn(warning_msg)
Prepending /usr/local/lib/python3.6/dist-packages/bigdl/share/conf/spark-bigdl.conf to sys.path
/usr/local/lib/python3.6/dist-packages/zoo/util/engine.py:42: UserWarning: Find both SPARK_HOME and pyspark. You may need to check whether they match with each other. SPARK_HOME environment variable is set to: /opt/spark-2.4.3, and pyspark is found in: /usr/local/lib/python3.6/dist-packages/pyspark/__init__.py. If they are unmatched, you are recommended to use one source only to avoid conflict. For example, you can unset SPARK_HOME and use pyspark only.
  warnings.warn(warning_msg)
Adding /usr/local/lib/python3.6/dist-packages/zoo/share/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.9.0-jar-with-dependencies.jar to BIGDL_JARS
Prepending /usr/local/lib/python3.6/dist-packages/zoo/share/conf/spark-analytics-zoo.conf to sys.path
creating: createImageResize
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/lib/python3.6/dist-packages/zoo/share/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.9.0-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/spark-2.4.3/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2021-02-08 22:59:23 WARN  Utils:66 - Your hostname, at resolves to a loopback address: 127.0.1.1; using 10.10.100.120 instead (on interface enp0s3)
2021-02-08 22:59:23 WARN  Utils:66 - Set SPARK_LOCAL_IP if you need to bind to another address
2021-02-08 22:59:23 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
creating: createImageConfigure
cls.getname: com.intel.analytics.bigdl.python.api.Sample
BigDLBasePickler registering: bigdl.util.common  Sample
cls.getname: com.intel.analytics.bigdl.python.api.EvaluatedResult
BigDLBasePickler registering: bigdl.util.common  EvaluatedResult
cls.getname: com.intel.analytics.bigdl.python.api.JTensor
BigDLBasePickler registering: bigdl.util.common  JTensor
cls.getname: com.intel.analytics.bigdl.python.api.JActivity
BigDLBasePickler registering: bigdl.util.common  JActivity
creating: createImageResize
creating: createImageResize
creating: createChainedPreprocessing
creating: createImageConfigure
2021-02-08 22:59:30 WARN  ImageConfigure$:66 - Only support to create default image configuration for models published by analytics zoo. Third-party models need to pass its own image configuration during prediction
Traceback (most recent call last):
  File "predict.py", line 17, in <module>
    model = ObjectDetector.load_model("/home/at/Desktop/final.model")
  File "/usr/local/lib/python3.6/dist-packages/zoo/models/image/objectdetection/object_detector.py", line 65, in load_model
    jmodel = callZooFunc(bigdl_type, "loadObjectDetector", path, weight_path)
  File "/usr/local/lib/python3.6/dist-packages/zoo/common/utils.py", line 133, in callZooFunc
    raise e
  File "/usr/local/lib/python3.6/dist-packages/zoo/common/utils.py", line 127, in callZooFunc
    java_result = api(*args)
  File "/usr/local/lib/python3.6/dist-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/local/lib/python3.6/dist-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o33.loadObjectDetector.
: java.lang.ClassCastException: com.intel.analytics.zoo.models.image.objectdetection.ssd.SSDVGG cannot be cast to com.intel.analytics.zoo.models.image.objectdetection.ObjectDetector
	at com.intel.analytics.zoo.models.image.objectdetection.ObjectDetector$.loadModel(ObjectDetector.scala:51)
	at com.intel.analytics.zoo.models.python.PythonZooModel.loadObjectDetector(PythonZooModel.scala:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)


```

**Comment by qiuxin2012** [comment]
You have two versions of analytics-zoo:
1. one is scala, in your first command I find this latest 0.10.0-snapshot.
2. Another is python, From the error logs, I find is 0.9.0.
So the python version doesn't include Jennie's bug fix, you should update to latest 0.10.0-snapshot. See https://analytics-zoo.github.io/master/#PythonUserGuide/install/#install-the-latest-nightly-build-wheels-for-pip to help.

**Comment by beta21s** [comment]
@qiuxin2012  It run. Thank you so much for the help from you.

Thanks very much.

**Comment by qiuxin2012** [comment]
> @qiuxin2012 It run. Thank you so much for the help from you.
> 
> Thanks very much.

It's my pleasure. 
You can open a new issue, if you meet other question in the feature.
