### ISSUE TITLE
jenkins : k8s example tests failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3506]
Traceback (most recent call last):
  File "/opt/work/jenkins/workspace/ZOO-NB-K8s-ExampleTests/pyzoo/zoo/examples/orca/learn/horovod/pytorch_estimator.py", line 149, in <module>
    train_example(workers_per_node=args.workers_per_node)
  File "/opt/work/jenkins/workspace/ZOO-NB-K8s-ExampleTests/pyzoo/zoo/examples/orca/learn/horovod/pytorch_estimator.py", line 93, in train_example
    stats = estimator.fit(train_data_creator, batch_size=4, epochs=5)
  File "/opt/analytics-zoo-0.10.0-SNAPSHOT/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-SNAPSHOT-python-api.zip/zoo/orca/learn/pytorch/estimator.py", line 130, in fit
  File "/opt/analytics-zoo-0.10.0-SNAPSHOT/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-SNAPSHOT-python-api.zip/zoo/orca/learn/pytorch/pytorch_ray_estimator.py", line 226, in train
  File "/opt/analytics-zoo-0.10.0-SNAPSHOT/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-SNAPSHOT-python-api.zip/zoo/orca/learn/pytorch/pytorch_ray_estimator.py", line 258, in _train_epochs
  File "/opt/analytics-zoo-0.10.0-SNAPSHOT/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-SNAPSHOT-python-api.zip/zoo/orca/learn/pytorch/pytorch_ray_estimator.py", line 48, in check_for_failure
  File "/root/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1513, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): [36mray::Worker.train_epochs()[39m (pid=111, ip=172.30.72.5)
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task.function_executor
  File "/opt/analytics-zoo-0.10.0-SNAPSHOT/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-SNAPSHOT-python-api.zip/zoo/orca/learn/pytorch/torch_runner.py", line 259, in train_epochs
    loader = data_creator(config)
TypeError: train_data_creator() missing 1 required positional argument: 'batch_size'
Stopping pgids: [63694]

jenkins link:
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-K8s-ExampleTests/20/console

**Comment by pinggao187** [comment]
@xiejinglei [#3481](https://github.com/intel-analytics/analytics-zoo/pull/3481)

**Comment by hkvision** [comment]
Is the image the latest? https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/orca/learn/pytorch/torch_runner.py#L257

**Comment by pinggao187** [comment]
update image and re-run.
pass!
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-K8s-ExampleTests/25/
