### ISSUE TITLE
orca.estimator threw "null uri host" exception at Spark 3.0.2 compatible with S3 API at save_keras_model and fit functions 

### ISSUE THREAD

**Issue by jack1981** [intel-analytics/analytics-zoo#3596]
We are testing Zoo Spark 3 version at our new Spark cluster which is running Spark 3.0.2 + Minio ( S3 compatible API) 
   When we test the NCF use case , read and write to S3 folder, we found the orca.estimator fit, save_keras_model encountered the issue  : java.lang.NullPointerException: null uri host.
But the code can read source data and write target data from S3 folder ( I guess it uses native Spark API) 
  We are wondering there is issue for orca.estimator compatible with S3 API 
 
We are using this night build version  
Index of /repositories/snapshots/com/intel/analytics/zoo/analytics-zoo-bigdl_0.12.1-spark_3.0.0/0.10.0-SNAPSHOT (sonatype.org)

Traceback (most recent call last):
  File "ncf_main.py", line 95, in <module>
    est.save_keras_model(save_model_dir)
  File "/apps_01/udap/app_logs/hadoop-yarn/cache/dc-user/nm-local-dir/usercache/dc-user/appcache/application_1615828176656_0011/container_e06_1615828176656_0011_01_000001/analytics-zoo-bigdl_0.12.1-spark_3.0.0-0.10.0-SNAPSHOT-python-api.zip/zoo/orca/learn/tf/estimator.py", line 902, in save_keras_model
  File "/apps_01/udap/app_logs/hadoop-yarn/cache/dc-user/nm-local-dir/usercache/dc-user/appcache/application_1615828176656_0011/container_e06_1615828176656_0011_01_000001/analytics-zoo-bigdl_0.12.1-spark_3.0.0-0.10.0-SNAPSHOT-python-api.zip/zoo/tfpark/model.py", line 82, in save_model
  File "/apps_01/udap/app_logs/hadoop-yarn/cache/dc-user/nm-local-dir/usercache/dc-user/appcache/application_1615828176656_0011/container_e06_1615828176656_0011_01_000001/analytics-zoo-bigdl_0.12.1-spark_3.0.0-0.10.0-SNAPSHOT-python-api.zip/zoo/common/utils.py", line 86, in save_file
  File "/apps_01/udap/app_logs/hadoop-yarn/cache/dc-user/nm-local-dir/usercache/dc-user/appcache/application_1615828176656_0011/container_e06_1615828176656_0011_01_000001/analytics-zoo-bigdl_0.12.1-spark_3.0.0-0.10.0-SNAPSHOT-python-api.zip/zoo/common/utils.py", line 110, in put_local_file_to_remote
  File "/apps_01/udap/app_logs/hadoop-yarn/cache/dc-user/nm-local-dir/usercache/dc-user/appcache/application_1615828176656_0011/container_e06_1615828176656_0011_01_000001/analytics-zoo-bigdl_0.12.1-spark_3.0.0-0.10.0-SNAPSHOT-python-api.zip/zoo/common/utils.py", line 133, in callZooFunc
  File "/apps_01/udap/app_logs/hadoop-yarn/cache/dc-user/nm-local-dir/usercache/dc-user/appcache/application_1615828176656_0011/container_e06_1615828176656_0011_01_000001/analytics-zoo-bigdl_0.12.1-spark_3.0.0-0.10.0-SNAPSHOT-python-api.zip/zoo/common/utils.py", line 127, in callZooFunc
  File "/apps_01/udap/dlp/lib/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
  File "/apps_01/udap/dlp/lib/spark/python/pyspark/sql/utils.py", line 128, in deco
    return f(*a, **kw)
  File "/apps_01/udap/dlp/lib/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o83.putLocalFileToRemote.
: java.lang.NullPointerException: null uri host.
        at java.util.Objects.requireNonNull(Objects.java:228)
        at org.apache.hadoop.fs.s3native.S3xLoginHelper.buildFSURI(S3xLoginHelper.java:73)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.setUri(S3AFileSystem.java:470)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:235)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3303)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352)
        at org.apache.hadoop.fs.FileSystem$Cache.getUnique(FileSystem.java:3326)

**Comment by jenniew** [comment]
We're looking at this issue and let you know later.

**Comment by jenniew** [comment]
@jack1981 We tested with Spark3.0.2 and Analytics Zoo nightly build, and didn't reproduce this issue. Is it possible the issue is related with your environment, like Minio, etc.?

**Comment by jack1981** [comment]
we found the issue from our side , after we turn off SSL configuration , it is working now , we will validate the SSL issue at PROD environment , thanks !
