### ISSUE TITLE
Class not found exception testing BERT Example

### ISSUE THREAD

**Issue by EmiCareOfCell44** [intel-analytics/analytics-zoo#3648]
I am trying to test the BERT example from the  but I have a ClassNotFound Exception:

java.lang.NoClassDefFoundError: com/intel/analytics/zoo/mkl/MKL
	at com.intel.analytics.zoo.common.MKLBlas$.erf(MKLBlas.scala:36)
	at com.intel.analytics.zoo.pipeline.api.keras.layers.internal.InternalERF.updateOutput(InternalERF.scala:31)
	at com.intel.analytics.zoo.pipeline.api.keras.layers.internal.InternalERF.updateOutput(InternalERF.scala:26)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:282)
	at com.intel.analytics.zoo.pipeline.api.keras.layers.LayerWrapperByForward$.computeOutputShape(KerasLayerWrapper.scala:93)
	at com.intel.analytics.zoo.pipeline.api.keras.layers.LayerWrapperByForward.computeOutputShape(KerasLayerWrapper.scala:46)
	at com.intel.analytics.bigdl.nn.abstractnn.InferShape$class.build(InferShape.scala:71)
	at com.intel.analytics.bigdl.nn.keras.KerasLayer.build(KerasLayer.scala:312)
	at com.intel.analytics.bigdl.nn.keras.KerasLayer.inputs(KerasLayer.scala:329)
	at com.intel.analytics.zoo.pipeline.api.autograd.AutoGrad$.erf(math.scala:361)
	at com.intel.analytics.zoo.pipeline.api.keras.layers.BERT.gelu(BERT.scala:90)
	at com.intel.analytics.zoo.pipeline.api.keras.layers.TransformerLayer.mlp(TransformerLayer.scala:132)
	at com.intel.analytics.zoo.pipeline.api.keras.layers.TransformerLayer.block(TransformerLayer.scala:124)
	at com.intel.analytics.zoo.pipeline.api.keras.layers.TransformerLayer.doBuild(TransformerLayer.scala:85)
	at com.intel.analytics.bigdl.nn.keras.KerasLayer.build(KerasLayer.scala:310)

OS: MacOs
Sbt dependencies:

"com.intel.analytics.zoo" % "analytics-zoo-bigdl_0.12.1-spark_2.4.3" % "0.9.0" excludeAll("ml.dmlc", "xgboost4j-spark")
"org.apache.spark" %% "spark-mllib" % "2.4.3"

I had to exclude manually the xgboost4j because the resolver was unable to find that dependency:

	module not found: ml.dmlc#xgboost4j_2.11;1.2.0-SNAPSHOT

is it because the MacOS distribution does not include that dependency?, haw can I solve that to test the BERT/Transformer implementation?

**Comment by jason-dai** [comment]
@dding3 please take a look

**Comment by dding3** [comment]
Thank you for reporting this issue. We have reproed java.lang.NoClassDefFoundError: com/intel/analytics/zoo/mkl/MKL and we are  working on the fix. 

xgboost4j_2.11;1.2.0-SNAPSHOT is one of the dependencies of analytics-zoo 0.9.0 version and somehow it is no longer hosted in s3, so there is "module not found for xgboost4j_2.11;1.2.0-SNAPSHOT" error. Please try latest nightly build of analytics-zoo https://analytics-zoo.readthedocs.io/en/latest/doc/UserGuide/scala.html?highlight=sbt#nightly-build, the module not found error has been fixed.

**Comment by EmiCareOfCell44** [comment]
I have been working with the Docker image and it works as expected. I´ll try with the last nightly build. Thanks

**Comment by dding3** [comment]
The ClassNotFound exception on mac has been fixed now. 

Below is the sbt dependencies:
libraryDependencies ++= Seq(
  "com.intel.analytics.zoo" % "analytics-zoo-bigdl_0.12.1-spark_2.4.3" % "0.10.0-SNAPSHOT",
  "com.intel.analytics.zoo" % "zoo-core-mkl-mac" % "0.10.0-SNAPSHOT"
)

and test code:
```
 val layer = BERT[Float](vocab = 100,
    hiddenSize = 10,
    nBlock = 3,
    nHead = 2,
    intermediateSize = 64,
    hiddenPDrop = 0.1,
    attnPDrop = 0.1,
    maxPositionLen = 10,
    outputAllBlock = false,
    inputSeqLen = 10)

    val shape = Shape(List(Shape(1, 10), Shape(1, 10), Shape(1, 10), Shape(1, 1, 1, 10)))
    layer.build(shape)
    val w = layer.parameters()._1
    val inputIds = Tensor[Float](Array[Float](7, 20, 39, 27, 10,
      39, 30, 21, 17, 15), Array(1, 10))
    val segmentIds = Tensor[Float](Array[Float](0, 0, 0, 0, 0, 1, 1, 1, 1, 1), Array(1, 10))
    val positionIds = Tensor[Float](Array[Float](0, 1, 2, 3, 4, 5, 6, 7, 8, 9), Array(1, 10))
    val masks = Tensor[Float](1, 1, 1, 10).fill(1.0f)
    val output = layer.forward(T(inputIds, segmentIds, positionIds, masks))
    val gradOutput = T(Tensor[Float](1, 10, 10).rand(), Tensor[Float](1, 10).rand())

    val gradInput = layer.backward(T(inputIds, segmentIds, positionIds, masks), gradOutput)
```

**Comment by EmiCareOfCell44** [comment]
It works. Thank you very much
