### ISSUE TITLE
Problems with Spark DataFrame Produced by `convert_predict_rdd_to_dataframe` for Multi-dimensional Output

### ISSUE THREAD

**Issue by GZHoffie** [intel-analytics/analytics-zoo#3654]
I tried to use `zoo.orca.learn.utils.convert_predict_rdd_to_dataframe` to put the predicted result into the `result_df` Spark DataFrame. When calling the schema of the data frame, the result is as expected:
```python
StructType(List(StructField(feature,ArrayType(ArrayType(ArrayType(ArrayType(ArrayType(DoubleType,true),true),true),true),true),true),StructField(label,ArrayType(LongType,true),true),StructField(prediction,VectorUDT,true)))
```
Here we have a field called `predict` of type `VectorUDT`. The problem is that the prediction is multi-dimensional (an array of shape `(1, 4, 1000)`). When applying the produced data frame with `show()` or `count()` method, the following error will occur,
```python
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/intern/spark/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 377, in main
    process()
  File "/intern/spark/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 372, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/intern/spark/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/serializers.py", line 393, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/intern/spark/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/util.py", line 99, in wrapper
    return f(*args, **kwargs)
  File "/intern/spark/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/session.py", line 730, in prepare
  File "/intern/spark/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/types.py", line 1389, in verify
    verify_value(obj)
  File "/intern/spark/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/types.py", line 1370, in verify_struct
    verifier(v)
  File "/intern/spark/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/types.py", line 1389, in verify
    verify_value(obj)
  File "/intern/spark/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/types.py", line 1290, in verify_udf
    verifier(dataType.toInternal(obj))
  File "/intern/spark/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/types.py", line 685, in toInternal
    return self._cachedSqlType().toInternal(self.serialize(obj))
  File "/intern/spark/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/ml/linalg/__init__.py", line 164, in serialize
    values = [float(v) for v in obj]
  File "/intern/spark/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/ml/linalg/__init__.py", line 164, in <listcomp>
    values = [float(v) for v in obj]
TypeError: only size-1 arrays can be converted to Python scalars
```
For the code, please see the pull request #3602.

**Comment by GZHoffie** [comment]
Resolved by fixing the code of `zoo.orca.learn.utils.convert_predict_rdd_to_dataframe`. Only 1-D np.array can be fit in the `VectorUDT` struct type. For multi-dimensional array, it will not work.

To solve this problem, I converted `np.ndarray` to lists using `array.tolist()`, and fit the 3-D array into 
```python
ArrayType(ArrayType(ArrayType(FloatType())))
```
The produced DataFrame appeared to be functioning.
