### ISSUE TITLE
Different Number of Items in Batches when Calling `convert_predict_rdd_to_dataframe`

### ISSUE THREAD

**Issue by GZHoffie** [intel-analytics/analytics-zoo#3660]
I was trying to use `SparkEstimator.model.distributed_predict` to make predictions on a `SparkXShard`, which is originally a Spark DataFrame that looks like this
```python
sc = init_nncontext()
spark = SparkSession(sc)
rdd = sc.range(0, 4)
input_df = rdd.map(lambda x: (np.random.random([1, 4, 3, 224, 224]).tolist())).toDF(["feature"])
```
and I fit the dataframe to `dataframe_to_xshards` and `distributed_predict` to obtain a RDD containing the prediction. However, then the size of dataframe is larger than 4 (e.g. setting `rdd = sc.range(0, 10)`), the following error will occur:
```python
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/intern/spark/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 377, in main
    process()
  File "/intern/spark/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 372, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/intern/spark/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/serializers.py", line 393, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/intern/spark/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/rdd.py", line 1354, in takeUpToNumLeft
  File "/intern/spark/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/serializers.py", line 460, in _load_stream_without_unbatching
    " in batches: (%d, %d)" % (len(key_batch), len(val_batch)))
ValueError: Can not deserialize PairRDD with different number of items in batches: (5, 1)
```
For the code please check this PR #3602.

**Comment by GZHoffie** [comment]
This issue is temporarily resolved by setting the `numSlices` parameter to be equal or larger than the number of rows of the dataframe,
```python
rdd = sc.range(0, 10, numSlices=10)
```
After this setting the tests passed successfully.

**Comment by jason-dai** [comment]
@Le-Zheng please take a look

**Comment by GZHoffie** [comment]
The problem is now resolved by using 
```python
result_rdd.flatMap(lambda data: data)
```
before passing it to the function `convert_predict_rdd_to_dataframe`. This is not a problem with `distributed_predict`.
