### ISSUE TITLE
jenkins:  scala UT failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3765]
com.intel.analytics.zoo.serving.FrontendActorsSpec.actors sometimes fails, re-run success.

Regression
com.intel.analytics.zoo.serving.FrontendActorsSpec.actors should works well

Error Message
Futures timed out after [10 seconds]

Stacktrace
      java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
      at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
      at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
      at scala.concurrent.Await$.$anonfun$result$1(package.scala:220)
      at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
      at scala.concurrent.Await$.result(package.scala:146)
      at com.intel.analytics.zoo.serving.FrontendActorsSpec.$anonfun$new$15(FrontendActorsSpec.scala:122)
      at com.intel.analytics.zoo.serving.http.Supportive.timing(Supportive.scala:28)
      at com.intel.analytics.zoo.serving.http.Supportive.timing$(Supportive.scala:25)
      at com.intel.analytics.zoo.serving.FrontendActorsSpec.timing(FrontendActorsSpec.scala:35)
      at com.intel.analytics.zoo.serving.FrontendActorsSpec.$anonfun$new$12(FrontendActorsSpec.scala:123)
      at scala.collection.immutable.List.foreach(List.scala:392)

jenkins link:
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-3.0-SCALA/144/
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-2.4-SCALA/952/

**Comment by pinggao187** [comment]
should works well *** FAILED ***
  java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
  at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
  at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
  at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
  at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
  at scala.concurrent.Await$.result(package.scala:190)
  at com.intel.analytics.zoo.serving.FrontendActorsSpec$$anonfun$2$$anonfun$apply$mcV$sp$1$$anonfun$13.apply(FrontendActorsSpec.scala:122)
  at com.intel.analytics.zoo.serving.FrontendActorsSpec$$anonfun$2$$anonfun$apply$mcV$sp$1$$anonfun$13.apply(FrontendActorsSpec.scala:123)
  at com.intel.analytics.zoo.serving.http.Supportive$class.timing(Supportive.scala:28)
  at com.intel.analytics.zoo.serving.FrontendActorsSpec.timing(FrontendActorsSpec.scala:35)
  at com.intel.analytics.zoo.serving.FrontendActorsSpec$$anonfun$2$$anonfun$apply$mcV$sp$1.apply(FrontendActorsSpec.scala:121)

jenkins link:
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-2.4-SCALA-MAC/375/consoleFull

**Comment by helenlly** [comment]
@Litchilitchy pls have a look

**Comment by Litchilitchy** [comment]
@glorysdj Random fail? I found sometimes it raises `no operation 'xadd'`, is it mock redis problem?

**Comment by glorysdj** [comment]
https://github.com/intel-analytics/analytics-zoo/commit/c7b5788262179be656b8a4fb8e266c14719d4a62#diff-be32a8182e8ea8b310c1a8789df3aac0aaacc65846cefad5ac50180d91ca66a0R66
is this caused by
