### ISSUE TITLE
jenkins: python example tests timeout 11h

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3783]
#14 start example test for streaming Text Classification

Writing image to ./output/20210413-231821-2390022800234002300023400233002330022900
Writing image to ./output/20210413-231821-1620016000158001560015400152001490014800
Exception in thread "task-result-getter-0" java.lang.Error: java.lang.InterruptedException
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:206)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:222)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:220)
	at org.apache.spark.network.BlockTransferService.fetchBlockSync(BlockTransferService.scala:121)
	at org.apache.spark.storage.BlockManager.getRemoteBytes(BlockManager.scala:757)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3$$anonfun$run$1.apply$mcV$sp(TaskResultGetter.scala:82)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3$$anonfun$run$1.apply(TaskResultGetter.scala:63)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3$$anonfun$run$1.apply(TaskResultGetter.scala:63)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1945)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3.run(TaskResultGetter.scala:62)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	... 2 more

jenkins link:
http://10.239.47.210:18888/job/ZOO-NB-Python-ExampleTests-MAC/367/
http://10.239.47.210:18888/job/ZOO-NB-Python-ExampleTests-MAC/366/

**Comment by pinggao187** [comment]
update 
http://10.239.47.210:18888/job/ZOO-NB-Python-ExampleTests-MAC/369/console

**Comment by pinggao187** [comment]
#14 start example test for streaming Text Classification
analytics-zoo-data/data/streaming/text-model already exists
Picked up _JAVA_OPTIONS: -XX:MaxPermSize=3G -Xmx50G
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=3G; support was removed in 8.0
Picked up _JAVA_OPTIONS: -XX:MaxPermSize=3G -Xmx50G
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=3G; support was removed in 8.0
Traceback (most recent call last):
  File "/opt/work/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/daemon.py", line 170, in manager
  File "/opt/work/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/daemon.py", line 61, in worker
  File "/opt/work/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/serializers.py", line 678, in loads
    length = read_int(stream)
  File "/opt/work/spark-2.4.3-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/serializers.py", line 715, in read_int
    length = stream.read(4)
TimeoutError: [Errno 60] Operation timed out

http://10.239.47.210:18888/job/ZOO-NB-Python-ExampleTests-MAC/372/

**Comment by pinggao187** [comment]
pass
http://10.239.176.111:18888/job/ZOO-NB-Python-ExampleTests-MAC-py36/
