### ISSUE TITLE
jenkins: pip apptests failed on mac

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3825]
#20 start app test for zouwu-anomaly-detect

no. of n/a values:
cpu_usage    0
dtype: int64
Traceback (most recent call last):
  File "/var/jenkins_home/workspace/ZOO-NB-Pip-AppTests-MAC/dist/../pyzoo/zoo/zouwu/use-case/AIOps/AIOps_anomaly_detect.py", line 303, in <module>
    scaled_train = standard_scaler.fit_transform(train_df)
  File "/Users/arda/anaconda3/envs/py36pip/lib/python3.6/site-packages/sklearn/base.py", line 553, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/Users/arda/anaconda3/envs/py36pip/lib/python3.6/site-packages/sklearn/preprocessing/data.py", line 639, in fit
    return self.partial_fit(X, y)
  File "/Users/arda/anaconda3/envs/py36pip/lib/python3.6/site-packages/sklearn/preprocessing/data.py", line 663, in partial_fit
    force_all_finite='allow-nan')
  File "/Users/arda/anaconda3/envs/py36pip/lib/python3.6/site-packages/sklearn/utils/validation.py", line 550, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 2)) while a minimum of 1 is required by StandardScaler.

jenkins link:
http://10.239.47.210:18888/job/ZOO-NB-Pip-AppTests-MAC/349/console

**Comment by pinggao187** [comment]
upgrade scikit-learn-0.21.3 to scikit-learn-0.22.2. re-run

http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-Pip-AppTests-MAC/350/

**Comment by pinggao187** [comment]
The test still fails.
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-Pip-AppTests-MAC/352/

**Comment by yushan111** [comment]
That is because the data haven't finished written before being interrupted by a connection fail. http://10.239.47.210:18888/job/ZOO-NB-Pip-AppTests-MAC/343/console.

I replace the data with a complete data file and it works ok.

I open a PR which forces rewriting the data. And I will change back after MAC is stable.

**Comment by yushan111** [comment]
PR #3839 which forces rewriting the data has passed Jenkins and been merged.

We might test again on MAC.

It would be better if we could check the data integrity before skip downloading and run the test scripts.
