### ISSUE TITLE
jenkins: scala test failed on mac 

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3826]
Failed
com.intel.analytics.zoo.pipeline.api.keras.layers.Deconvolution2DSpec.Deconvolution2D without bias should be the same as Keras
Error Message
false was not true
Stacktrace
      org.scalatest.exceptions.TestFailedException: false was not true
      at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
      at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6723)
      at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6759)
      at com.intel.analytics.zoo.pipeline.api.keras.layers.KerasBaseSpec$$anonfun$checkOutputAndGrad$3.apply(KerasBaseSpec.scala:69)
      at com.intel.analytics.zoo.pipeline.api.keras.layers.KerasBaseSpec$$anonfun$checkOutputAndGrad$3.apply(KerasBaseSpec.scala:68)
      at scala.runtime.Tuple2Zipped$$anonfun$foreach$extension$1.apply(Tuple2Zipped.scala:108)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
      at scala.runtime.Tuple2Zipped$.foreach$extension(Tuple2Zipped.scala:106)
      at com.intel.analytics.zoo.pipeline.api.keras.layers.KerasBaseSpec.checkOutputAndGrad(KerasBaseSpec.scala:68)
      at com.intel.analytics.zoo.pipeline.api.keras.layers.Deconvolution2DSpec$$anonfun$2.apply$mcV$sp(Deconvolution2DSpec.scala:65)
      at com.intel.analytics.zoo.pipeline.api.keras.layers.Deconvolution2DSpec$$anonfun$2.apply(Deconvolution2DSpec.scala:51)
      at com.intel.analytics.zoo.pipeline.api.keras.layers.Deconvolution2DSpec$$anonfun$2.apply(Deconvolution2DSpec.scala:51)

jenkins link:
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-2.1-SCALA-MAC/326/

**Comment by hkvision** [comment]
Fixed by https://github.com/intel-analytics/analytics-zoo/pull/3831
Please have a check.

**Comment by pinggao187** [comment]
pass
http://10.239.47.210:18888/job/ZOO-NB-UnitTests-2.1-SCALA-MAC/329/
