### ISSUE TITLE
jenkins: pip exampletest failed on linux

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3827]
{'node_ip_address': '172.168.2.184', 'raylet_ip_address': '172.168.2.184', 'redis_address': '172.168.2.184:6379', 'object_store_address': '/tmp/ray/session_2021-04-20_13-22-43_875578_109173/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2021-04-20_13-22-43_875578_109173/sockets/raylet', 'webui_url': '172.168.2.184:8265', 'session_dir': '/tmp/ray/session_2021-04-20_13-22-43_875578_109173', 'metrics_export_port': 63939, 'node_id': 'c2100b0fc20da11ea8a63c6f972f41cd0b9d0a9c28c915391e7ef88a'}
Traceback (most recent call last):
  File "/opt/work/jenkins/workspace/ZOO-NB-Pip-ExampleTests-py37/pyzoo/zoo/examples/orca/automl/autoxgboost/AutoXGBoostClassifier.py", line 137, in <module>
    max_depth_range=max_depth_range,
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/zoo/zouwu/config/recipe.py", line 674, in __init__
    self.lr = tune.loguniform(lr[0], lr[1])
NameError: name 'tune' is not defined
Clearing up environment. Uninstalling analytics-zoo
Found existing installation: analytics-zoo 0.10.0.dev0
Uninstalling analytics-zoo-0.10.0.dev0:
  Successfully uninstalled analytics-zoo-0.10.0.dev0
Found existing installation: BigDL 0.12.1
Uninstalling BigDL-0.12.1:
  Successfully uninstalled BigDL-0.12.1
Found existing installation: pyspark 2.4.3
Uninstalling pyspark-2.4.3:
  Successfully uninstalled pyspark-2.4.3
auto-xgboost-classifier failed

jenkins link:
http://10.239.47.210:18888/job/ZOO-NB-Pip-ExampleTests-py37/332/console

**Comment by yushan111** [comment]
@PeterQiu0516 Would you mind fix that? It is related to PR #3726
