### ISSUE TITLE
ray.exceptions.RayActorError when run orca on k8s

### ISSUE THREAD

**Issue by Adria777** [intel-analytics/analytics-zoo#3851]
```
(pid=192, ip=172.30.83.4) Epoch 1/30
(pid=192, ip=172.30.83.4) WARNING:tensorflow:From /root/miniconda3/lib/python3.7/site-packages/tensorflow/python/data/ops/multi_device_iterator_ops.py:601: get_next_as_optional (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
(pid=192, ip=172.30.83.4) Instructions for updating:
(pid=192, ip=172.30.83.4) Use `tf.data.Iterator.get_next_as_optional()` instead.
(pid=192, ip=172.30.83.4) 2021-04-23 09:06:12.151584: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:172] Filling up shuffle buffer (this may take a while): 476 of 1000
(pid=192, ip=172.30.83.4) 2021-04-23 09:06:12.234362: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:221] Shuffle buffer filled.
2021-04-23 09:06:15,117 WARNING worker.py:1107 -- A worker died or was killed while executing task ffffffffffffffffa67dc375e60ddd1a23bd3bb901000000.
Traceback (most recent call last):
  File "train_az_3.py", line 330, in <module>
    callbacks=callbacks)
  File "/opt/analytics-zoo-0.10.0-SNAPSHOT/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-SNAPSHOT-python-api.zip/zoo/orca/learn/tf2/estimator.py", line 259, in fit
  File "/root/miniconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1458, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task. Check python-core-worker-*.log files for more information.
Stopping pgids: [8195]
Stopping by pgid 8195
Stopping orca context
```

How I init orca:

```

init_orca_context(cluster_mode="k8s", master="k8s://https://127.0.0.1:8443",
                  container_image="10.239.45.10/arda/hyper-zoo:e2c",
                  num_nodes=1, memory="10g", cores=8,
                  conf={"spark.driver.host": "172.16.0.200",
                      "spark.driver.port": "54321",
                      "spark.kubernetes.executor.volumes.persistentVolumeClaim.nfsvolumeclaim.options.claimName": "nfsvolumeclaim",
                      "spark.kubernetes.executor.volumes.persistentVolumeClaim.nfsvolumeclaim.mount.path": "/zoo"}, extra_python_lib="model.py")

```

The code I run:
```
# Callbacks
    callbacks = [
        LearningRateScheduler(lr_decay),
        EarlyStopping(monitor='loss',
                      patience=...,
                      verbose=...,
                      min_delta=...),
        ReduceLROnPlateau(monitor='loss',
                          factor=...,
                          patience=...,
                          verbose=...,
                          min_delta=...),
        ModelCheckpoint(filepath=chkpt_path,
                        monitor='loss',
                        mode='auto',
                        save_best_only=True,
                        save_weights_only=False),
        TensorBoard(log_dir='...'),
        CSVLogger('...'.format(..., ...))
    ]

```

**Comment by yangw1234** [comment]
what does this log say:

![image](https://user-images.githubusercontent.com/10561966/116022302-860bae00-a67c-11eb-9883-5d96d192eeb7.png)

**Comment by glorysdj** [comment]
since the logs are persisted in /tmp/ray/session_latest/logs, once the worker is failed, the k8s will delete the pod, we can not get the content of the worker log.
is there any conf to change the log dir to replace /tmp/ray/session_latest/logs?

**Comment by yangw1234** [comment]
can we mount that 

> since the logs are persisted in /tmp/ray/session_latest/logs, once the worker is failed, the k8s will delete the pod, we can not get the content of the worker log.
> is there any conf to change the log dir to replace /tmp/ray/session_latest/logs?

Maybe the following code would work.

```python
init_orca_context(..., extra_params = {"temp-dir": "/tmp/ray/"})
```

**Comment by glorysdj** [comment]
the log is like: 
```cat python-core-worker-03a5fba5b633bebb865ca97e8299da6c7b409816d9c8aea5542730ff_203.log
[2021-04-26 06:50:54,555 I 203 203] core_worker.cc:136: Constructing CoreWorkerProcess. pid: 203
[2021-04-26 06:50:54,558 I 203 203] grpc_server.cc:75: worker server started, listening on port 10004.
[2021-04-26 06:50:54,563 I 203 203] core_worker.cc:364: Initializing worker at address: 172.30.69.4:10004, worker ID 03a5fba5b633bebb865ca97e8299da6c7b409816d9c8aea5542730ff, raylet a84e0dec152c92144d4434f71ea80c97fc3c0dd12071bf9c540aed62
[2021-04-26 06:50:54,576 I 203 203] core_worker.cc:231: Worker 03a5fba5b633bebb865ca97e8299da6c7b409816d9c8aea5542730ff is created.
[2021-04-26 06:50:54,576 I 203 203] io_service_pool.cc:36: IOServicePool is running with 1 io_service.
[2021-04-26 06:50:54,577 I 203 276] service_based_accessor.cc:559: Received notification for node id = a84e0dec152c92144d4434f71ea80c97fc3c0dd12071bf9c540aed62, IsAlive = 1
[2021-04-26 06:50:54,577 I 203 276] service_based_accessor.cc:559: Received notification for node id = 9b72b7c3012b24db800aa6ffbb9686c95e41fa5a7f48f9938d05b9ac, IsAlive = 1
[2021-04-26 06:51:25,150 I 203 276] service_based_accessor.cc:559: Received notification for node id = 9b72b7c3012b24db800aa6ffbb9686c95e41fa5a7f48f9938d05b9ac, IsAlive = 0
[2021-04-26 06:51:25,150 I 203 276] core_worker.cc:658: Node failure 9b72b7c3012b24db800aa6ffbb9686c95e41fa5a7f48f9938d05b9ac```

**Comment by yangw1234** [comment]
still memory issue. Setting memory=100g can successfully run. The memory of the executor container is set to the summation of `memory` and `exra_executor_memory_for_ray`. I think you can set `init_orca_context(memory=10g, exra_executor_memory_for_ray=100g # or some other value)` 

I think you can run the application locally and see the memory usage and set that value to `exra_executor_memory_for_ray`.

**Comment by glorysdj** [comment]
thanks for the great help
