### ISSUE TITLE
When using TFDataset to predict ImageSet, it breaks NullPointerException

### ISSUE THREAD

**Issue by Cancerhzc** [intel-analytics/analytics-zoo#3859]
I'm new using Analytics-zoo.When I use my own Cifar-10 h5 model( also trained by Analytics-zoo ) and TFDataset to predict images in a file folder, it breaks **NullPointerException**. I don't know how to solve it.

Follows are my code
My python version is 3.6.12 and Analytics Zoo version is 0.10.0.dev0 nightly build.
`import os
import tensorflow as tf
from tensorflow.keras import layers, datasets, models
from zoo.tfpark import KerasModel, TFDataset,TFPredictor
from zoo import init_nncontext

from zoo.models.image.imageclassification import *
from zoo.feature.image.imagePreprocessing import *

class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck']
 

model = models.Sequential()
model.add(layers.Conv2D(64, (3, 3),padding='same', activation='relu', input_shape=(32, 32, 3)))
model.add(layers.Conv2D(64, (3, 3),padding='same', activation='relu'))
model.add(layers.MaxPooling2D((2, 2),strides=2,padding='same'))

model.add(layers.Conv2D(128, (3, 3),padding='same', activation='relu'))
model.add(layers.Conv2D(128, (3, 3),padding='same', activation='relu'))
model.add(layers.MaxPooling2D((2, 2),strides=2,padding='same'))

model.add(layers.Conv2D(256, (3, 3),padding='same', activation='relu'))
model.add(layers.Conv2D(256, (3, 3),padding='same', activation='relu'))
model.add(layers.MaxPooling2D((2, 2),strides=2,padding='same'))

model.add(layers.Conv2D(512, (3, 3),padding='same', activation='relu'))
model.add(layers.Conv2D(512, (3, 3),padding='same', activation='relu'))
model.add(layers.MaxPooling2D((2, 2),strides=2,padding='same'))

model.add(layers.Conv2D(512, (3, 3),padding='same', activation='relu'))
model.add(layers.Conv2D(512, (3, 3),padding='same', activation='relu'))
model.add(layers.MaxPooling2D((2, 2),strides=2,padding='same'))

model.add(layers.Flatten())
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(10,activation='softmax'))
 
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

sc = init_nncontext()
keras_model = KerasModel(model)

keras_model.load_weights("/xxxx/cifar10_model.h5")

local_image_set = ImageSet.read("/xxxx/pictest")
transformer = ImageResize(32, 32)
transformed = local_image_set.transform(transformer)

dataset=TFDataset.from_image_set(transformed, (tf.float32,[32,32,3]), (tf.int32, [1]), batch_size=-1, batch_per_thread=2, hard_code_batch_size=False, validation_image_set=None)
predictions = keras_model.predict(dataset,batch_per_thread=2, distributed=True)
print(predictions)
`

2021-04-25 23:14:55 WARN  TFNetForInference$:349 - Cannot find variable value for <total>, using default value zero
2021-04-25 23:14:55 WARN  TFNetForInference$:349 - Cannot find variable value for <count>, using default value zero
2021-04-25 23:14:56 ERROR ThreadPool$:136 - Error: java.lang.NullPointerException
        at com.intel.analytics.bigdl.dataset.SampleToMiniBatch$$anon$2.next(Transformer.scala:340)
        at com.intel.analytics.bigdl.dataset.SampleToMiniBatch$$anon$2.next(Transformer.scala:323)
        at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
        at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:798)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at com.intel.analytics.bigdl.optim.Predictor$.predictImageBatch(Predictor.scala:51)
        at com.intel.analytics.bigdl.optim.LocalPredictor$$anonfun$7$$anonfun$8$$anonfun$apply$5.apply(LocalPredictor.scala:178)
        at com.intel.analytics.bigdl.optim.LocalPredictor$$anonfun$7$$anonfun$8$$anonfun$apply$5.apply(LocalPredictor.scala:174)
        at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$invokeAndWait$1$$anonfun$apply$3.apply(ThreadPool.scala:133)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2021-04-25 23:14:56 ERROR ThreadPool$:136 - Error: java.lang.NullPointerException
        at com.intel.analytics.bigdl.dataset.SampleToMiniBatch$$anon$2.next(Transformer.scala:340)
        at com.intel.analytics.bigdl.dataset.SampleToMiniBatch$$anon$2.next(Transformer.scala:323)
        at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
        at scala.collection.Iterator$$anon$19.hasNext(Iterator.scala:798)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at com.intel.analytics.bigdl.optim.Predictor$.predictImageBatch(Predictor.scala:51)
        at com.intel.analytics.bigdl.optim.LocalPredictor$$anonfun$7$$anonfun$8$$anonfun$apply$5.apply(LocalPredictor.scala:178)
        at com.intel.analytics.bigdl.optim.LocalPredictor$$anonfun$7$$anonfun$8$$anonfun$apply$5.apply(LocalPredictor.scala:174)
        at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$invokeAndWait$1$$anonfun$apply$3.apply(ThreadPool.scala:133)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by Cancerhzc** [comment]
Do we have user groups in China? It's Google Group now, and it's not convenient to discuss by Google.

**Comment by yangw1234** [comment]
hi @Cancerhzc , I am afraid we need more information to diagnoise this problem. Would you mind replying the follwing questions? 
1. Do you run this application in spark local mode or yarn/spark-standalone mode? 
1. Is "/xxxx/pictest" a local data path or a hdfs data path? And what's data format inside "/xxxx/pictest".

**Comment by Cancerhzc** [comment]
hi @yangw1234 
1. I run this application in spark local mode
2. "/xxxx/pictest" is a local directory. In this diretory, there are some *.jpg and *.png images.

**Comment by yangw1234** [comment]
hi @Cancerhzc there are a few issues and you can take a look at the following code for reference.
1. you should pass the `sc` object to `ImageSet.read` to create a DistributedImageSet, otherwise `predict` will run locally.
2. if you pass the `sc`, we recommend you to prepend "file://" to your path to explictly state the path point to a directory in local file system
3. ImageSet.read will return a collection of `ImageFeature` object, and you can apply transformations on it like `ImageResize`. But to use it in TFPark, you should append two more transformations to transform namely `ImageMatToTensor(format="NHWC")` and `ImageSetToSample(input_keys=["imageTensor"])`
4. the `predictions` returned by `keras_model.predict` is lazy evaluted. You can call `predictions.get_predict()` to return a rdd of prediction tensors and call `collect()` on it to return the predictions.

I know it is a little complicated and we are currently working on improving the API and documentation.

```python
from zoo.feature.common import ChainedPreprocessing
local_image_set = ImageSet.read("file:///xxxx/pictest", sc)
transformer = ChainedPreprocessing([ImageResize(32, 32),
                                    ImageMatToTensor(format="NHWC"),
                                    ImageSetToSample(input_keys=["imageTensor"])])
transformed = local_image_set.transform(transformer)

dataset=TFDataset.from_image_set(transformed, (tf.float32,[32,32,3]), (tf.int32, [1]), batch_size=-1, batch_per_thread=1, hard_code_batch_size=False, validation_image_set=None)
predictions = keras_model.predict(dataset,batch_per_thread=1, distributed=True)
print(predictions.get_predict().collect())
```

**Comment by yangw1234** [comment]
Hi @Cancerhzc , would you mind sharing the full log?

**Comment by Cancerhzc** [comment]
Sorry, the previous message is wrong.

hi, @yangw1234
Thanks a lot for helping me and it can work properly now by your step.
But now I want to change the environment to yarn and pictures are on HDFS.
I change code from
`sc = init_nncontext()` to
`sc = init_spark_on_yarn(
        hadoop_conf="/home/xxx/hadoop-3.2.2/etc/hadoop",
        conda_name="zoo", # The name of the created conda-env
        num_executors=3,
        executor_cores=3,
        executor_memory="4g",
        driver_memory="2g",
        driver_cores=3
        )`

and

 `ImageSet.read("file:///xxxx/pictest", sc)` to 
`ImageSet.read("hdfs://slave0:9000/pictest",sc)`

I find the number of stage is only one. My HDFS cluster has 4 nodes, it contains 1 namenode and 3 datanodes.
Why can't they parallel process?

**Comment by yangw1234** [comment]
@Cancerhzc do you mean the stage in Spark? In Spark, one stage can contain many tasks and those tasks can run in parallel according to your cluster specificaiton (max num_executors*executor_cores tasks can run in parallel). Different stages runs serially in spark.

**Comment by Cancerhzc** [comment]
@yangw1234 Yes, the stage in Spark.
When I use bigDL to train a model,all nodes in the cluster work is under high CPU load.
But when I use bigDL to predict,only two nodes in the cluster is under high CPU load

**Comment by yangw1234** [comment]
> @yangw1234 Yes, the stage in Spark.
> When I use bigDL to train a model,all nodes in the cluster work is under high CPU load.
> But when I use bigDL to predict,only two nodes in the cluster is under high CPU load

hi @Cancerhzc , it is probably because the ImageSet has less partitions than your cpu cores. I think you can try setting "min_partitions" to a larger number, e.g. `ImageSet.read(path, sc, min_partitions=total_cpu_cores)` given that your total number images is larger than total cpu cores.

**Comment by Cancerhzc** [comment]
> > @yangw1234 Yes, the stage in Spark.
> > When I use bigDL to train a model,all nodes in the cluster work is under high CPU load.
> > But when I use bigDL to predict,only two nodes in the cluster is under high CPU load
> 
> hi @Cancerhzc , it is probably because the ImageSet has less partitions than your cpu cores. I think you can try setting "min_partitions" to a larger number, e.g. `ImageSet.read(path, sc, min_partitions=total_cpu_cores)` given that your total number images is larger than total cpu cores.

hi @yangw1234 , thank you for your help. But I found that only two nodes in the cluster are computing. My `min_partitions=9` and picture number in HDFS is 2 300.
Should I change some another places to solve this problem?

**Comment by yangw1234** [comment]
> > > @yangw1234 Yes, the stage in Spark.
> > > When I use bigDL to train a model,all nodes in the cluster work is under high CPU load.
> > > But when I use bigDL to predict,only two nodes in the cluster is under high CPU load
> > 
> > 
> > hi @Cancerhzc , it is probably because the ImageSet has less partitions than your cpu cores. I think you can try setting "min_partitions" to a larger number, e.g. `ImageSet.read(path, sc, min_partitions=total_cpu_cores)` given that your total number images is larger than total cpu cores.
> 
> hi @yangw1234 , thank you for your help. But I found that only two nodes in the cluster are computing. My `min_partitions=9` and picture number in HDFS is 2 300.
> Should I change some another places to solve this problem?

Would you mind sharing through what metrics do you conclude "only two nodes in the cluster are computing"?

**Comment by Cancerhzc** [comment]
> > > > @yangw1234 Yes, the stage in Spark.
> > > > When I use bigDL to train a model,all nodes in the cluster work is under high CPU load.
> > > > But when I use bigDL to predict,only two nodes in the cluster is under high CPU load
> > > 
> > > 
> > > hi @Cancerhzc , it is probably because the ImageSet has less partitions than your cpu cores. I think you can try setting "min_partitions" to a larger number, e.g. `ImageSet.read(path, sc, min_partitions=total_cpu_cores)` given that your total number images is larger than total cpu cores.
> > 
> > 
> > hi @yangw1234 , thank you for your help. But I found that only two nodes in the cluster are computing. My `min_partitions=9` and picture number in HDFS is 2 300.
> > Should I change some another places to solve this problem?
> 
> Would you mind sharing through what metrics you conclude "only two nodes in the cluster are computing"?

hi, @yangw1234. When I run this application, I use "top" command in another nodes in the cluster.My cluster has 1 master node and 3 slave nodes. But I found  CPU load of 2 slave nodes are very low, and CPU load of 1 slave node is 100% during running this application.

**Comment by Cancerhzc** [comment]
> > > > > > @yangw1234 Yes, the stage in Spark.
> > > > > > When I use bigDL to train a model,all nodes in the cluster work is under high CPU load.
> > > > > > But when I use bigDL to predict,only two nodes in the cluster is under high CPU load
> > > > > 
> > > > > 
> > > > > hi @Cancerhzc , it is probably because the ImageSet has less partitions than your cpu cores. I think you can try setting "min_partitions" to a larger number, e.g. `ImageSet.read(path, sc, min_partitions=total_cpu_cores)` given that your total number images is larger than total cpu cores.
> > > > 
> > > > 
> > > > hi @yangw1234 , thank you for your help. But I found that only two nodes in the cluster are computing. My `min_partitions=9` and picture number in HDFS is 2 300.
> > > > Should I change some another places to solve this problem?
> > > 
> > > 
> > > Would you mind sharing through what metrics you conclude "only two nodes in the cluster are computing"?
> > 
> > 
> > hi, @yangw1234. When I run this application, I use "top" command in another nodes in the cluster to observe the load. My cluster has 1 master node and 3 slave nodes. But I found CPU load of 2 slave nodes are very low, and CPU load of 1 slave node is 100% during running this application.
> 
> `min_partitions` may not work in spark versions below 2.4 due to https://issues.apache.org/jira/browse/SPARK-22357. If this is your case, could you try using spark 2.4 or above?

hi, @yangw1234 
I used  `pip install` to check the version of pyspark, it is 2.4.3. And I try to change my pyspark version to 2.4.7 but this problem still exists.

**Comment by yangw1234** [comment]
@Cancerhzc would you mind answer my pervious question?

**Comment by yangw1234** [comment]
> > @Cancerhzc would you mind answer my pervious question? That is: `Could you try predictions.get_predict().getNumPartitions() to checkout the number of partitions? Could you share your physical machine core number of your three slaves and your spark version?`
> 
> @yangw1234 I found this number is 1. But I have set the min_partitions
> 
> Core number of each physical machine is 4.
> I used `pip install analytics-zoo` and it automatically downloaded default version pyspark==2.4.3.
> 
> ============================================
> Follows are my code. Is there any error in it or needing to change some code in it?
> 
> `image_set = ImageSet.read("hdfs://master:9000/pictest",sc,min_partitions=9)
> 
> transformer = ChainedPreprocessing([ImageResize(32, 32),
> ImageMatToTensor(format="NHWC"),
> ImageSetToSample(input_keys=["imageTensor"])])
> transformed = image_set.transform(transformer)
> 
> dataset=TFDataset.from_image_set(transformed, (tf.float32,[32,32,3]), (tf.int32, [1]), batch_per_thread=2, hard_code_batch_size=False, validation_image_set=None)
> 
> predictions = keras_model.predict(dataset,batch_per_thread=2, distributed=True)
> predictions_list = predictions.get_predict().collect()
> print(predictions.get_predict().getNumPartitions())`

Hi @Cancerhzc , `min_partitions` is only a hint and the actuall number of partitions is computed by spark using a huristic using `min_partitions` and serveral other configurations. 

In your case, I think it is probably because your files too small to spread them to more partitions, and you can try with more data or decrease "spark.files.openCostInBytes" (default to 4MB) to increase parallelism. 

In the meantime, we will try to find ways to enable users have a better control over the number of partitions.

Here is the detailed explaination. `ImageSet.read` use `sc.binaryFiles` internally and the `min_partitions` is passed to `sc.binaryFiles`. `sc.binaryFiles` use a huristic to determine the max data size of a partition and thus determine the actual number of partitions. Here is code to caculate the max data size in each partition:

```scala
    val defaultMaxSplitBytes = sc.getConf.get(config.FILES_MAX_PARTITION_BYTES)
    val openCostInBytes = sc.getConf.get(config.FILES_OPEN_COST_IN_BYTES)
    val defaultParallelism = Math.max(sc.defaultParallelism, minPartitions)
    val files = listStatus(context).asScala
    val totalBytes = files.filterNot(_.isDirectory).map(_.getLen + openCostInBytes).sum
    val bytesPerCore = totalBytes / defaultParallelism
    val maxSplitSize = Math.min(defaultMaxSplitBytes, Math.max(openCostInBytes, bytesPerCore))
```
(see source here https://github.com/apache/spark/blob/v2.4.3/core/src/main/scala/org/apache/spark/input/PortableDataStream.scala#L47 )

**Comment by Cancerhzc** [comment]
Hi, @yangw1234 

It's exactly what you said. Each picture need to predict is around 30 KB and sum of the picture space is  around 60 MB. That is to say I need to change "spark.files.openCostInBytes" to around 30KB?
 
 Is right to change my `init_spark_on_yarn ` config if I need change "spark.files.openCostInBytes"  by using default spark in zoo?
How can I change this parameter? 

Is the following code right? Because I can't try this code right now until tomorrow. 

`
from pyspark import SparkConf
conf = SparkConf().set('spark.files.openCostInBytes', '30kb')
sc = init_spark_on_yarn(
    hadoop_conf="/home/hzc/hadoop-3.2.2/etc/hadoop",
    conda_name="zoo", # The name of the created conda-env
    num_executors=4,
    executor_cores=3,
    executor_memory="5g",
    driver_memory="2g",
    driver_cores=4,
    conf=conf)
 
`

**Comment by yangw1234** [comment]
> Hi, @yangw1234
> 
> It's exactly what you said. Each picture need to predict is around 30 KB and sum of the picture space is around 60 MB. That is to say I need to change "spark.files.openCostInBytes" to around 30KB?
> 
> Is right to change my `init_spark_on_yarn ` config if I need change "spark.files.openCostInBytes" by using default spark in zoo?
> How can I change this parameter?
> 
> Is the following code right? Because I can't try this code or trial right now until tomorrow.
> 
> ```
> from pyspark import SparkConf
> conf = SparkConf().set('spark.files.openCostInBytes', '30kb')
> sc = init_spark_on_yarn(
>     hadoop_conf="/home/hzc/hadoop-3.2.2/etc/hadoop",
>     conda_name="zoo", # The name of the created conda-env
>     num_executors=4,
>     executor_cores=3,
>     executor_memory="5g",
>     driver_memory="2g",
>     driver_cores=4,
>     conf=conf)
>  
> ```

There is a typo in the previous message, I think you should change `spark.files.maxPartitionBytes`.

**Comment by Cancerhzc** [comment]
> > Hi, @yangw1234
> > It's exactly what you said. Each picture need to predict is around 30 KB and sum of the picture space is around 60 MB. That is to say I need to change "spark.files.openCostInBytes" to around 30KB?
> > Is right to change my `init_spark_on_yarn ` config if I need change "spark.files.openCostInBytes" by using default spark in zoo?
> > How can I change this parameter?
> > Is the following code right? Because I can't try this code or trial right now until tomorrow.
> > ```
> > from pyspark import SparkConf
> > conf = SparkConf().set('spark.files.openCostInBytes', '30kb')
> > sc = init_spark_on_yarn(
> >     hadoop_conf="/home/hzc/hadoop-3.2.2/etc/hadoop",
> >     conda_name="zoo", # The name of the created conda-env
> >     num_executors=4,
> >     executor_cores=3,
> >     executor_memory="5g",
> >     driver_memory="2g",
> >     driver_cores=4,
> >     conf=conf)
> >  
> > ```
> 
> @Cancerhzc Not exactly.
> I think setting `conf = SparkConf().set('spark.files.openCostInBytes', '0')` can have relatively close number of partitions with "min_partitions", given that all your files have similar sizes.

@yangw1234 Hi, I ran this code and it breaks
File "testimg_yarn.py", line 59, in <module>
    conf=conf1
  File "/home/hzc/anaconda3/envs/zoo/lib/python3.6/site-packages/zoo/common/nncontext.py", line 125, in init_spark_on_yarn
    conf=conf)
  File "/home/hzc/anaconda3/envs/zoo/lib/python3.6/site-packages/zoo/util/spark.py", line 103, in init_spark_on_yarn
    extra_executor_memory_for_ray)
  File "/home/hzc/anaconda3/envs/zoo/lib/python3.6/site-packages/zoo/util/spark.py", line 295, in enrich_conf_for_spark
    conf.update({"spark.driver.cores": driver_cores,
AttributeError: 'SparkConf' object has no attribute 'update'

**Comment by yangw1234** [comment]
@Cancerhzc Sorry I forgot `conf` should be a simple dict, please try `conf = {'spark.files.openCostInBytes':'0'}`

**Comment by Cancerhzc** [comment]
> @Cancerhzc Sorry I forgot `conf` should be a simple dict, please try `conf = {'spark.files.openCostInBytes':'0'}`

hi, @yangw1234 
Thank you very much for your help. It's working now! Thanks again!
