### ISSUE TITLE
jenkins: app test failed on mac

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3896]
#23 start app test for zouwu-network-traffic-multivarite-multistep-tcnforecaster

Prepending /Users/arda/anaconda3/envs/py36pip/lib/python3.6/site-packages/bigdl/share/conf/spark-bigdl.conf to sys.path
Adding /Users/arda/anaconda3/envs/py36pip/lib/python3.6/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.12.2-spark_2.4.3-0.11.0-SNAPSHOT-jar-with-dependencies.jar to BIGDL_JARS
Prepending /Users/arda/anaconda3/envs/py36pip/lib/python3.6/site-packages/zoo/share/conf/spark-analytics-zoo.conf to sys.path
Traceback (most recent call last):
  File "/var/jenkins_home/workspace/ZOO-NB-Pip-AppTests-MAC-py36/dist/../pyzoo/zoo/zouwu/use-case/network_traffic/network_traffic_multivariate_multistep_tcnforecaster.py", line 308, in <module>
    forecaster.fit(x=x_train, y=y_train, epochs=2, batch_size=256, metric="mse")
  File "/Users/arda/anaconda3/envs/py36pip/lib/python3.6/site-packages/zoo/zouwu/model/forecast/tcn_forecaster.py", line 92, in fit
    **self.config)
  File "/Users/arda/anaconda3/envs/py36pip/lib/python3.6/site-packages/zoo/automl/model/base_pytorch_model.py", line 117, in fit_eval
    val_stats = self._validate(validation_data[0], validation_data[1], metric=metric)
  File "/Users/arda/anaconda3/envs/py36pip/lib/python3.6/site-packages/zoo/automl/model/base_pytorch_model.py", line 172, in _validate
    x = self._reshape_input(x)
  File "/Users/arda/anaconda3/envs/py36pip/lib/python3.6/site-packages/zoo/automl/model/base_pytorch_model.py", line 77, in _reshape_input
    if x.ndim == 1:
AttributeError: 'Tensor' object has no attribute 'ndim'

jenkins link:
http://10.239.47.210:18888/job/ZOO-NB-Pip-AppTests-MAC-py36/367/consoleFull

**Comment by helenlly** [comment]
@TheaperDeng  have a look?

**Comment by TheaperDeng** [comment]
it seems to be the same error as #3495
@helenlly

**Comment by TheaperDeng** [comment]
> @pinggao187 pls try the solution in #3495 (Update pytorch 1.1.0 to 1.7.1, re-run.)

If possible, 1.8.1 is the latest one. as illustrated in https://analytics-zoo.readthedocs.io/en/latest/doc/UserGuide/python.html >=1.5.0 will be fine

**Comment by pinggao187** [comment]
Update pytorch 1.1.0 to 1.7.1 
pass
http://10.239.47.210:18888/job/ZOO-NB-Pip-AppTests-MAC-py36/368/
