### ISSUE TITLE
jenkins: TypeError: 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3897]
#1 start app test for anomaly-detection-nyc-taxi
Traceback (most recent call last):
  File "/opt/work/jenkins/workspace/ZOO-NB-Python-AppTests-part1/dist/apps/anomaly-detection/tmp_test.py", line 24, in <module>
    sc = init_nncontext("Anomaly Detection Example")
  File "/opt/work/jenkins/workspace/ZOO-NB-Python-AppTests-part1/dist/lib/analytics-zoo-bigdl_0.12.2-spark_2.4.3-0.11.0-SNAPSHOT-python-api.zip/zoo/common/nncontext.py", line 389, in init_nncontext
  File "/opt/work/jenkins/workspace/ZOO-NB-Python-AppTests-part1/dist/lib/analytics-zoo-bigdl_0.12.2-spark_2.4.3-0.11.0-SNAPSHOT-python-api.zip/bigdl/util/common.py", line 449, in redire_spark_logs
  File "/opt/work/jenkins/workspace/ZOO-NB-Python-AppTests-part1/dist/lib/analytics-zoo-bigdl_0.12.2-spark_2.4.3-0.11.0-SNAPSHOT-python-api.zip/bigdl/util/common.py", line 592, in callBigDlFunc
  File "/opt/work/jenkins/workspace/ZOO-NB-Python-AppTests-part1/dist/lib/analytics-zoo-bigdl_0.12.2-spark_2.4.3-0.11.0-SNAPSHOT-python-api.zip/bigdl/util/common.py", line 56, in instance
  File "/opt/work/jenkins/workspace/ZOO-NB-Python-AppTests-part1/dist/lib/analytics-zoo-bigdl_0.12.2-spark_2.4.3-0.11.0-SNAPSHOT-python-api.zip/bigdl/util/common.py", line 96, in __init__
TypeError: 'JavaPackage' object is not callable

jenkins link:
http://10.239.47.210:18888/job/ZOO-NB-Python-AppTests-part1/887/console
http://10.239.47.210:18888/job/ZOO-NB-Python-ExampleTests-py36/429/console
http://10.239.47.210:18888/job/ZOO-NB-Python-AppTests-MAC-py36/327/console

**Comment by hkvision** [comment]
The build command changed from Spark_2.x to Spark_2.4+, rerunning: http://10.239.47.210:18888/job/ZOO-NB-Python-AppTests-part1/888/

**Comment by pinggao187** [comment]
pass 
http://10.239.47.210:18888/view/ZOO-NB/job/ZOO-NB-Python-AppTests-part1/888/
