### ISSUE TITLE
ValueError about “steps-per-epoch”

### ISSUE THREAD

**Issue by Adria777** [intel-analytics/analytics-zoo#3900]
We have 480 pictures and the batch-size is 80, so the default step-per-epoch is 6. Now num-nodes becomes 2, I tried to set step-per-epoch to be 3 and 6, but it didn't work

the error is
```
Traceback (most recent call last):
  File "train_az_3.py", line 339, in <module>
    callbacks=callbacks)
  File "/opt/analytics-zoo-0.10.0-SNAPSHOT/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-SNAPSHOT-python-api.zip/zoo/orca/learn/tf2/estimator.py", line 259, in fit
  File "/root/miniconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::TFRunner.step() (pid=142, ip=...)
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/opt/analytics-zoo-0.10.0-SNAPSHOT/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-SNAPSHOT-python-api.zip/zoo/orca/learn/tf2/tf_runner.py", line 369, in step
    validation_freq=validation_freq)
  File "/root/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 117, in _method_wrapper
    mode=dc.CoordinatorMode.INDEPENDENT_WORKER)
  File "/root/miniconda3/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_coordinator.py", line 860, in run_distribute_coordinator
    task_id, session_config, rpc_layer)
  File "/root/miniconda3/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_coordinator.py", line 360, in _run_single_worker
    return worker_fn(strategy)
  File "/root/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 115, in <lambda>
    lambda _: method(self, *args, **kwargs),
  File "/root/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1122, in fit
    steps_per_execution=self._steps_per_execution)
  File "/root/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1123, in __init__
    self._inferred_steps = self._infer_steps(steps_per_epoch, dataset)
  File "/root/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1253, in _infer_steps
    raise ValueError("When dataset is sharded across workers, please "
ValueError: When dataset is sharded across workers, please specify a reasonable `steps_per_epoch` such that all workers will train the same number of steps and each step can get data from dataset without EOF. This is required for allreduce to succeed. We will handle the last partial batch in the future. 
```

the  init_orca_context is
```

init_orca_context(cluster_mode="k8s", master="...",
                  container_image="...",
                  num_nodes=2, memory="50g", cores=8,
                  conf={"spark.driver.host": "...",
                      "spark.driver.port": "54321",
                      "spark.kubernetes.executor.volumes.persistentVolumeClaim.nfsvolumeclaim.options.claimName": "nfsvolumeclaim",
                      "spark.kubernetes.executor.volumes.persistentVolumeClaim.nfsvolumeclaim.mount.path": "/zoo",
                      }, extra_python_lib="model.py", extra_params = {"temp-dir": "/zoo"}

)

```  

this is where I set step-per-epoch:
```
 est = Estimator.from_keras(config=config, model_creator=model_creator)
    est.fit(train_data_creator,
            batch_size=cfg.batch_size,
            epochs=cfg.epochs,
            steps_per_epoch=3,
            validation_data=val_data_creator,
            callbacks=callbacks)

```
 
this is the config file
```

base_model_configs:
    base_model: 'mobilenet'
    base_application: 'MobileNet'
    decoder_filters: 200, 100, 64, 32, 16
    train_csv_path: '...'
    val_csv_path: '...'
    img_height:...
    img_width: ...
    batch_size: 80
    lr: ...
    lr_sched_drop: 0.5
    epochs: 2
    epochs_drop: 5
    optimizer: ...
    num_poplayers: 2
    gpu: '0'
    max_workers: 1
    multi_proc: 'True'
    multi_sample_dropout: 'False'
    aug_prob: ...

```

**Comment by glorysdj** [comment]
after set epoch, still get error:
···
WARNING:tensorflow:Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 6 batches). You may need to use the repeat() function when6/6 [==============================] - 492s 82s/step - loss: 0.2892 - accuracy: 0.7851 - iou_score: 0.5631 - val_loss: 0.3509 - val_accuracy: 0.4773 - val_iou_score: 0.4805
(pid=120, ip=172.16.103.135) WARNING:tensorflow:Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 6 batches). You may need to use the repeat() function when building your dataset.
(pid=120, ip=172.16.103.135) 2021-05-08 08:18:00.207181: E tensorflow/core/common_runtime/ring_alg.cc:274] Aborting RingReduce with Cancelled: RPC Request was cancelled
(pid=120, ip=172.16.103.135) 2021-05-08 08:18:00.207367: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at collective_ops.cc:257 : Cancelled: RPC Request was cancelled 
···

**Comment by jason-dai** [comment]
@Adria777 please update with the solution for this issue.
