### ISSUE TITLE
jenkins: colab pytorch test failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#3915]
#1 start example for pytorch_lenet_mnist_data_creator_func
Traceback (most recent call last):
  File "/opt/work/jenkins/workspace/ZOO-NB-Colab-Pytorch/docs/docs/colab-notebook/orca/quickstart/pytorch_lenet_mnist_data_creator_func.py", line 243, in <module>
    checkpoint_trigger=EveryEpoch())
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/zoo/orca/learn/pytorch/estimator.py", line 377, in fit
    train_fset, val_fset = self._handle_data_loader(data, validation_data)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/zoo/orca/learn/pytorch/estimator.py", line 314, in _handle_data_loader
    train_feature_set = FeatureSet.pytorch_dataloader(data, "", "")
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/zoo/feature/common.py", line 394, in pytorch_dataloader
    True, features, labels)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/zoo/common/utils.py", line 135, in callZooFunc
    raise e
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/zoo/common/utils.py", line 129, in callZooFunc
    java_result = api(*args)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o48.createFeatureSetFromPyTorch.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 1, localhost, executor driver): jep.JepException: jep.JepException: <class 'TypeError'>: train_loader_creator() missing 2 required positional arguments: 'config' and 'batch_size'

Jenkins link :
http://10.239.176.111:18888/view/ZOO-NB/job/ZOO-NB-Colab-Pytorch/101/console

**Comment by Le-Zheng** [comment]
In nightly-build test, we test with `pip install --pre analytics-zoo`. 
Need to release a new pre-release version. http://10.239.176.111:18888/view/ZOO-NB/job/ZOO-WEEKLY-Publish-PyPI/

**Comment by pinggao187** [comment]
pass
http://10.239.176.111:18888/view/ZOO-NB/job/ZOO-NB-Colab-Pytorch/104/
