### ISSUE TITLE
submit-examples-on-k8s: nnframes imageTransferLearning - Exception in thread "main" Caffe conversion error : Parsing caffe model error,only standard Caffe format is supported

### ISSUE THREAD

**Issue by zzti-bsj** [intel-analytics/analytics-zoo#3964]
## Exception in thread "main" Caffe conversion error : Parsing caffe model error,only standard Caffe format is supported
this is scala example link: [https://github.com/intel-analytics/analytics-zoo/blob/master/docker/hyperzoo/submit-examples-on-k8s.md](https://github.com/intel-analytics/analytics-zoo/blob/master/docker/hyperzoo/submit-examples-on-k8s.md)

### command
```java
/opt/spark/bin/spark-submit
   --master k8s://https://127.0.0.1:8443
   --deploy-mode cluster
   --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark
   --name analytics-zoo
   --conf spark.kubernetes.container.image=${RUNTIME_K8S_SPARK_IMAGE}
   --conf spark.executor.instances=1
   --conf spark.kubernetes.driver.volumes.persistentVolumeClaim.nfsvolumeclaim.options.claimName=nfsvolumeclaim
   --conf spark.kubernetes.driver.volumes.persistentVolumeClaim.nfsvolumeclaim.mount.path=/zoo
   --conf spark.kubernetes.executor.volumes.persistentVolumeClaim.nfsvolumeclaim.options.claimName=nfsvolumeclaim
   --conf spark.kubernetes.executor.volumes.persistentVolumeClaim.nfsvolumeclaim.mount.path=/zoo
   --conf spark.kubernetes.driver.label.az=true 
  --conf spark.kubernetes.executor.label.az=true
   --conf spark.kubernetes.node.selector.spark=true
   --executor-cores 16
   --executor-memory 10g
   --total-executor-cores 64
   --driver-cores 4
   --driver-memory 10g
   --properties-file /opt/analytics-zoo-0.11.0-SNAPSHOT/conf/spark-analytics-zoo.conf
   --py-files /opt/analytics-zoo-0.11.0-SNAPSHOT/lib/analytics-zoo-bigdl_0.12.2-spark_2.4.3-0.11.0-SNAPSHOT-python-api.zip   --conf spark.driver.extraJavaOptions=-Dderby.stream.error.file=/tmp
   --conf spark.sql.catalogImplementation='in-memory'
   --conf spark.driver.extraClassPath=/opt/analytics-zoo-0.11.0-SNAPSHOT/lib/analytics-zoo-bigdl_0.12.2-spark_2.4.3-0.11.0-SNAPSHOT-jar-with-dependencies.jar
   --conf spark.executor.extraClassPath=/opt/analytics-zoo-0.11.0-SNAPSHOT/lib/analytics-zoo-bigdl_0.12.2-spark_2.4.3-0.11.0-SNAPSHOT-jar-with-dependencies.jar
   --class com.intel.analytics.zoo.examples.nnframes.imageTransferLearning.ImageTransferLearning   /opt/analytics-zoo-0.11.0-SNAPSHOT/lib/analytics-zoo-bigdl_0.12.2-spark_2.4.3-0.11.0-SNAPSHOT-python-api.zip
   --caffeDefPath /zoo/data2/analytics-zoo-models/nnframes/deploy.prototxt
   --caffeWeightsPath /zoo/data2/analytics-zoo-models/nnframes/bvlc_googlenet.caffemodel
   --batchSize 64
   --imagePath /zoo/data2/nnframes/samples
   --nEpochs 2

```

### Exception info
```java
+ CMD=("$SPARK_HOME/bin/spark-submit" --conf "spark.driver.bindAddress=$SPARK_DRIVER_BIND_ADDRESS" --deploy-mode client "$@")
+ exec /sbin/tini -s -- /opt/spark/bin/spark-submit --conf spark.driver.bindAddress=172.30.14.4 --deploy-mode client --properties-file /opt/spark/conf/spark.properties --class com.intel.analytics.zoo.examples.nnframes.imageTransferLearning.ImageTransferLearning spark-internal --caffeDefPath /zoo/data2/analytics-zoo-models/nnframes/deploy.prototxt --caffeWeightsPath /zoo/data2/analytics-zoo-models/nnframes/bvlc_googlenet.caffemodel --batchSize 64 --imagePath /zoo/data2/nnframes/samples --nEpochs 2
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/analytics-zoo-0.11.0-SNAPSHOT/lib/analytics-zoo-bigdl_0.12.2-spark_2.4.3-0.11.0-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/spark/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2021-05-19 15:36:29 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2021-05-19 15:36:36 INFO  Engine$:121 - Auto detect executor number and executor cores number
2021-05-19 15:36:36 INFO  Engine$:123 - Executor number is 4 and executor cores number is 16
2021-05-19 15:36:37 INFO  ThreadPool$:95 - Set mkl threads to 1 on thread 1
2021-05-19 15:36:37 WARN  SparkContext:66 - Using an existing SparkContext; some configuration may not take effect.
2021-05-19 15:36:37 INFO  Engine$:446 - Find existing spark context. Checking the spark conf...
Exception in thread "main" Caffe conversion error : Parsing caffe model error,only standard Caffe format is supported
        at com.intel.analytics.bigdl.utils.caffe.CaffeLoader$.loadCaffe(CaffeLoader.scala:572)
        at com.intel.analytics.bigdl.nn.Module$.loadCaffeModel(Module.scala:82)
        at com.intel.analytics.zoo.examples.nnframes.imageTransferLearning.ImageTransferLearning$$anonfun$main$1.apply(ImageTransferLearning.scala:58)
        at com.intel.analytics.zoo.examples.nnframes.imageTransferLearning.ImageTransferLearning$$anonfun$main$1.apply(ImageTransferLearning.scala:44)
        at scala.Option.foreach(Option.scala:257)
        at com.intel.analytics.zoo.examples.nnframes.imageTransferLearning.ImageTransferLearning$.main(ImageTransferLearning.scala:44)
        at com.intel.analytics.zoo.examples.nnframes.imageTransferLearning.ImageTransferLearning.main(ImageTransferLearning.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by Le-Zheng** [comment]
Succeed when using correct "bvlc_googlenet.caffemodel". We may need to update the download link in [readme](https://github.com/intel-analytics/analytics-zoo/tree/master/zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/imageTransferLearning).
