### ISSUE TITLE
Prophet Pystan Model Compile Error on Mac

### ISSUE THREAD

**Issue by PeterQiu0516** [intel-analytics/analytics-zoo#3992]
Failed to build Prophet model on Mac, error message:
```bash
Building wheels for collected packages: prophet
  Building wheel for prophet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/arda/anaconda3/envs/py37/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/x4/yjpm4xlx7z53x_nxp13kwmlw0000gn/T/pip-install-wihyyzf_/prophet/setup.py'"'"'; __file__='"'"'/private/var/folders/x4/yjpm4xlx7z53x_nxp13kwmlw0000gn/T/pip-install-wihyyzf_/prophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/x4/yjpm4xlx7z53x_nxp13kwmlw0000gn/T/pip-wheel-1dtbz9b9
       cwd: /private/var/folders/x4/yjpm4xlx7z53x_nxp13kwmlw0000gn/T/pip-install-wihyyzf_/prophet/
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/prophet
  creating build/lib/prophet/stan_model
  INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec NOW.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for prophet
  Running setup.py clean for prophet
Failed to build prophet
Installing collected packages: prophet
    Running setup.py install for prophet ... -^[Oerror
    ERROR: Command errored out with exit status 1:
     command: /Users/arda/anaconda3/envs/py37/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/x4/yjpm4xlx7z53x_nxp13kwmlw0000gn/T/pip-install-wihyyzf_/prophet/setup.py'"'"'; __file__='"'"'/private/var/folders/x4/yjpm4xlx7z53x_nxp13kwmlw0000gn/T/pip-install-wihyyzf_/prophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/x4/yjpm4xlx7z53x_nxp13kwmlw0000gn/T/pip-record-d7nl0qp_/install-record.txt --single-version-externally-managed --compile --install-headers /Users/arda/anaconda3/envs/py37/include/python3.7m/prophet
         cwd: /private/var/folders/x4/yjpm4xlx7z53x_nxp13kwmlw0000gn/T/pip-install-wihyyzf_/prophet/
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/prophet
    creating build/lib/prophet/stan_model
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec NOW.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/arda/anaconda3/envs/py37/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/x4/yjpm4xlx7z53x_nxp13kwmlw0000gn/T/pip-install-wihyyzf_/prophet/setup.py'"'"'; __file__='"'"'/private/var/folders/x4/yjpm4xlx7z53x_nxp13kwmlw0000gn/T/pip-install-wihyyzf_/prophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/x4/yjpm4xlx7z53x_nxp13kwmlw0000gn/T/pip-record-d7nl0qp_/install-record.txt --single-version-externally-managed --compile --install-headers /Users/arda/anaconda3/envs/py37/include/python3.7m/prophet Check the logs for full command output.
```

After examination, we locate the error to be within `pystan` Model Compile Error.

Encountered Model Compile Error when executing the following code on a Mac server.
```python
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this line leads to error
```

Error Message:
```
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5944b02c79788fa0db5b3a93728ca2bf NOW.
Traceback (most recent call last):
  File "/Users/arda/anaconda3/envs/py37/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/Users/arda/anaconda3/envs/py37/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/Users/arda/anaconda3/envs/py37/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/Users/arda/anaconda3/envs/py37/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/arda/anaconda3/envs/py37/lib/python3.7/site-packages/pystan/model.py", line 378, in __init__
    build_extension.run()
  File "/Users/arda/anaconda3/envs/py37/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/Users/arda/anaconda3/envs/py37/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/Users/arda/anaconda3/envs/py37/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/Users/arda/anaconda3/envs/py37/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/Users/arda/anaconda3/envs/py37/lib/python3.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/Users/arda/anaconda3/envs/py37/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

```

Similar issue:
https://github.com/stan-dev/pystan2/issues/643
https://github.com/facebook/prophet/issues/930 
https://github.com/facebook/prophet/issues/326
https://github.com/facebook/prophet/issues/17 (1) downgrading pystan not working (2) reinstall XCode, will change dependency
https://github.com/stan-dev/pystan2/issues/622 (reinstall XCode, will change dependency)
https://github.com/stan-dev/pystan2/issues/734 (use `conda` to install `conda install clang_osx-64 clangxx_osx-64 -c anaconda`, will change dependency)
https://github.com/facebook/prophet/issues/1775 (solution here does not work)
https://github.com/facebook/prophet/issues/1807 (solution here does not work)

Prophet Installation Guide:
https://facebook.github.io/prophet/docs/installation.html#python (we follow the same steps on Mac here, and it works normally for Windows and Linux).
Pystan2 Installation Guide (we are checking this to try to solve the issue):
https://pystan2.readthedocs.io/en/latest/installation_beginner.html

**Comment by PeterQiu0516** [comment]
py36 env resolved.

**Comment by PeterQiu0516** [comment]
Jenkins passed: http://10.239.176.111:18888/job/ZOO-NB-UnitTests-2.4-PYTHON-MAC/361/console
