### ISSUE TITLE
jenkins: scala test failed on mac

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#4042]
All Failed Tests

com.intel.analytics.zoo.pipeline.api.keras.layers.BertSpec.Bert should be able to work | 0.42 sec | 1
-- | -- | --
com.intel.analytics.zoo.pipeline.api.keras.layers.BertSpec.Bert with output all blocks should be able to work | 5 ms | 1
com.intel.analytics.zoo.pipeline.api.keras.layers.BertSpec.Bert with configed embedding should be able to work | 4 ms | 1
com.intel.analytics.zoo.pipeline.api.keras.layers.BertSpec.BERT should be able to generate correct result | 4 ms | 1
com.intel.analytics.zoo.pipeline.api.keras.layers.BertSpec.Bert should save/load be able to work | 63 ms | 1
com.intel.analytics.zoo.pipeline.api.keras.layers.BertSpec.Bert gelu should be able to generate correct result

jenkins link:
http://10.239.176.111:18888/job/ZOO-NB-UnitTests-2.1-SCALA-MAC/368/

**Comment by helenlly** [comment]
@dding3  pls have a look

**Comment by dding3** [comment]
It's the same error as before. @glorysdj do we made any change of packing zoo jar recently?

**Comment by glorysdj** [comment]
the error is 
```
Layer info: InternalERF[866fc70a]
java.lang.Error: Can't extract dynamic lib file to /tmp dir.
java.lang.Error: Can't find dynamic lib file in jar, path = libzoojmkl.dylib
	at com.intel.analytics.zoo.mkl.MKL.extract(MKL.java:244)
	at com.intel.analytics.zoo.mkl.MKL.<clinit>(MKL.java:58)
	at com.intel.analytics.zoo.common.MKLBlas$.erf(MKLBlas.scala:36)
	at com.intel.analytics.zoo.pipeline.api.keras.layers.internal.InternalERF.updateOutput(InternalERF.scala:31)
	at com.intel.analytics.zoo.pipeline.api.keras.layers.internal.InternalERF.updateOutput(InternalERF.scala:26)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:282)
	at com.intel.analytics.zoo.pipeline.api.keras.layers.LayerWrapperByForward$.computeOutputShape(KerasLayerWrapper.scala:93)
	at com.intel.analytics.zoo.pipeline.api.keras.layers.LayerWrapperByForward.computeOutputShape(KerasLayerWrapper.scala:46)
	at com.intel.analytics.bigdl.nn.abstractnn.InferShape$class.build(InferShape.scala:71)
	at com.intel.analytics.bigdl.nn.keras.KerasLayer.build(KerasLayer.scala:314)
	at com.intel.analytics.bigdl.nn.keras.KerasLayer.inputs(KerasLayer.scala:331)
	at com.intel.analytics.zoo.pipeline.api.autograd.AutoGrad$.erf(math.scala:361)
	at com.intel.analytics.zoo.pipeline.api.keras.layers.BERT.gelu(BERT.scala:90)
```

**Comment by glorysdj** [comment]
changes are
```
Summary
Add DBscan anomaly detector (#4028) (commit: ae59a6c) (details)
Update pypi long description (#4031) (commit: f846a80) (details)
Update ContributeGuide.md (commit: f3d0e0b) (details)
Add Flink Sink with Xstream as outputQueue (#4013) (commit: 6ffd92b) (details)
[OpenVINO] Change predict output from JTensor to List<JTensor> (#4025) (commit: 5a8fe9b) (details)
Update pypi description (#4036) (commit: 2be6c53) (details)
Add current implemented TSDataset  deduplicate method to tsdataset api (commit: 753158b) (details)
Add scale/unscale method for TSDataset (#4034) (commit: f8f1343) (details)
```

**Comment by qiyuangong** [comment]
No. We didn't update MKL related files. In my latest built jar, this file exists in jar.

**Comment by qiyuangong** [comment]
After rebuilding zoo-core on mac by @Le-Zheng , `libzoojmkl.dylib` is correctly packaged into jar.

**Comment by pinggao187** [comment]
pass
http://10.239.176.111:18888/job/ZOO-NB-UnitTests-2.3-SCALA-MAC/363/
