### ISSUE TITLE
jenkins：running chronos tests failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#4170]
Running chronos tests

____________________________ TestAutoARIMA.test_fit ____________________________

self = <test.zoo.chronos.autots.model.test_auto_arima.TestAutoARIMA testMethod=test_fit>

    def test_fit(self):
        data, validation_data = get_data()
        auto_arima = AutoARIMA(metric="mse",
                               p=hp.randint(0, 4),
                               q=hp.randint(0, 4),
                               seasonality_mode=hp.choice([True, False]),
                               P=hp.randint(5, 12),
                               Q=hp.randint(5, 12),
                               m=hp.choice([4, 7])
                               )
        auto_arima.fit(data=data,
                       validation_data=validation_data,
                       epochs=1,
>                      n_sampling=1,
                       )

../test/zoo/chronos/autots/model/test_auto_arima.py:56: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../zoo/chronos/autots/model/auto_arima.py:135: in fit
    scheduler_params=scheduler_params
../zoo/orca/automl/auto_estimator.py:185: in fit
    self.searcher.run()
../zoo/automl/search/ray_tune_search_engine.py:170: in run
    reuse_actors=True

2021-06-28 18:53:12,641	ERROR trial_runner.py:616 -- Trial train_func_f6b93_00000: Error processing event.
Traceback (most recent call last):
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 586, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 609, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/ray/worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): [36mray::ImplicitFunc.train_buffered()[39m (pid=103412, ip=172.168.2.183)
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/ray/tune/trainable.py", line 167, in train_buffered
    result = self.train()
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/ray/tune/trainable.py", line 226, in train
    result = self.step()
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/ray/tune/function_runner.py", line 366, in step
    self._report_thread_runner_error(block=True)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/ray/tune/function_runner.py", line 513, in _report_thread_runner_error
    ("Trial raised an exception. Traceback:\n{}".format(err_tb_str)
ray.tune.error.TuneError: Trial raised an exception. Traceback:
[36mray::ImplicitFunc.train_buffered()[39m (pid=103412, ip=172.168.2.183)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/ray/tune/function_runner.py", line 316, in entrypoint
    self._status_reporter.get_checkpoint())
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/ray/tune/function_runner.py", line 576, in _trainable_func
    output = fn()
  File "/opt/work/jenkins/workspace/ZOO-NB-UnitTests-2.4-PYTHON/pyzoo/zoo/automl/search/ray_tune_search_engine.py", line 293, in train_func
    **config)
  File "/opt/work/jenkins/workspace/ZOO-NB-UnitTests-2.4-PYTHON/pyzoo/zoo/chronos/model/arima.py", line 81, in fit_eval
    self.model.fit(data)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/pmdarima/arima/arima.py", line 482, in fit
    self._fit(y, X, **fit_args)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/pmdarima/arima/arima.py", line 403, in _fit
    fit, self.arima_res_ = _fit_wrapper()
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/pmdarima/arima/arima.py", line 397, in _fit_wrapper
    **fit_args)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 659, in fit
    skip_hessian=True, **kwargs)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/statsmodels/base/model.py", line 526, in fit
    full_output=full_output)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/statsmodels/base/optimizer.py", line 218, in _fit
    hess=hessian)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/statsmodels/base/optimizer.py", line 440, in _fit_lbfgs
    **extra_kwargs)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py", line 198, in fmin_l_bfgs_b
    **opts)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py", line 360, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 260, in fun_and_grad
    self._update_fun()
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 226, in _update_fun
    self._update_fun_impl()
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 133, in update_fun
    self.f = fun_wrapped(self.x)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 130, in fun_wrapped
    return fun(x, *args)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/statsmodels/base/model.py", line 500, in f
    return -self.loglike(params, *args) / nobs
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 889, in loglike
    loglike = self.ssm.loglike(complex_step=complex_step, **kwargs)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/statsmodels/tsa/statespace/kalman_filter.py", line 977, in loglike
    kfilter = self._filter(**kwargs)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/statsmodels/tsa/statespace/kalman_filter.py", line 897, in _filter
    self._initialize_state(prefix=prefix, complex_step=complex_step)
  File "/opt/work/conda/envs/py37/lib/python3.7/site-packages/statsmodels/tsa/statespace/representation.py", line 950, in _initialize_state
    complex_step=complex_step)
  File "statsmodels/tsa/statespace/_representation.pyx", line 1334, in statsmodels.tsa.statespace._representation.dStatespace.initialize
  File "statsmodels/tsa/statespace/_initialization.pyx", line 288, in statsmodels.tsa.statespace._initialization.dInitialization.initialize
  File "statsmodels/tsa/statespace/_initialization.pyx", line 406, in statsmodels.tsa.statespace._initialization.dInitialization.initialize_stationary_stationary_cov
  File "statsmodels/tsa/statespace/_tools.pyx", line 1206, in statsmodels.tsa.statespace._tools._dsolve_discrete_lyapunov
numpy.linalg.LinAlgError: LU decomposition error.

jenkins link:
http://10.239.176.111:18888/job/ZOO-NB-UnitTests-2.4-PYTHON/1055/console

**Comment by pinggao187** [comment]
@PeterQiu0516 pls have a look.

**Comment by PeterQiu0516** [comment]
From the error message this looks like a random issue as `numpy.linalg.LinAlgError: LU decomposition error.` may arise from irregular matrix values that lead to LU Decomposition Error.

**Comment by pinggao187** [comment]
rerun success
http://10.239.176.111:18888/job/ZOO-NB-UnitTests-2.4-PYTHON/1056/

**Comment by PeterQiu0516** [comment]
As shown above, after further testing we confirmed that this was indeeded a random error, and for now we will use a fixed random seed for generating testing data to deal with it.
