### ISSUE TITLE
kss cluster mode: could not initialized spark storageutil class 

### ISSUE THREAD

**Issue by JavadHosseini** [intel-analytics/analytics-zoo#4241]
I initialized orca context  like this:

`from zoo.orca import init_orca_context`

`sc = init_orca_context(cluster_mode="k8s", cores=4, memory="4g", num_nodes=2, master="k8s://192.168.1.30:6443", container_image ="intelanalytics/hyper-zoo:latest", conf={"spark.driver.host": "10.0.29.243","spark.driver.port": "29413"}) 
`
but i get this error:
`Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.storage.StorageUtils$
	at org.apache.spark.storage.BlockManagerMasterEndpoint.<init>(BlockManagerMasterEndpoint.scala:109)
	at org.apache.spark.SparkEnv$.$anonfun$create$9(SparkEnv.scala:371)
	at org.apache.spark.SparkEnv$.registerOrLookupEndpoint$1(SparkEnv.scala:311)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:359)
	at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:189)
	at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:277)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:458)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:829)`

my spark driver working OK, I can initialize spark context normally.

**Comment by yushan111** [comment]
@glorysdj Would you help take a look at this?

**Comment by glorysdj** [comment]
We will try to reproduce it.

**Comment by glorysdj** [comment]
We didn't get this error when try to reproduce  it.
Please check your env of the driver, especially the spark version. FYI, intelanalytics/hyper-zoo:latest is based on spark 2.4.3. We should add this info in the tag, and we will update the release job for this.
BTW, you can start a docker container with the intelanalytics/hyper-zoo:latest image, and run the code in the container to keep the env same with spark driver and executor.

**Comment by JavadHosseini** [comment]
@glorysdj thank you for your help, unfortunately my spark version is 3.1.1 and I didn't pay attention to this. sorry for that. Is there any chance to run analytics zoo on spark 3+?

**Comment by glorysdj** [comment]
hi @JavadHosseini, sure, we will release a image for spark 3+.

**Comment by glorysdj** [comment]
> hi @JavadHosseini, sure, we will release a image for spark 3+. once it's ready, I will notify you here.

intelanalytics/hyper-zoo-spark-3.0.0:0.11.0-RC1 is now published, please have a try.

**Comment by JavadHosseini** [comment]
@glorysdj hi, one more question,
will there be a spark 3.1.1 publish?

**Comment by glorysdj** [comment]
For now, analytics zoo mainly supports spark 3.0.0. We will evaluate version 3.1.1.

**Comment by glorysdj** [comment]
Hi @JavadHosseini Analytics Zoo is now supporting spark 3.1.2, and a hyperzoo image is also released for spark 3.1.2
please try intelanalytics/hyper-zoo-spark-3.1.2:0.12.0-SNAPSHOT
