### ISSUE TITLE
Colab Example "ncf_dataframe" Not pass

### ISSUE THREAD

**Issue by Elena-Qiu** [intel-analytics/analytics-zoo#4264]
For the colab notebook example `analytics-zoo/docs/docs/colab-notebook/orca/quickstart/ncf_dataframe.ipynb`, it gets error at 
```
est = Estimator.from_keras(model_creator=model_creator, workers_per_node=1)
```
The error information is as follows:
```
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-11-116acc147717> in <module>()
      4 
      5 # create an Estimator
----> 6 est = Estimator.from_keras(model_creator=model_creator, workers_per_node=1)
      7 
      8 stats = est.fit(train_data,

/usr/local/lib/python3.7/dist-packages/zoo/orca/learn/tf2/estimator.py in from_keras(model_creator, config, verbose, workers_per_node, compile_args_creator, backend, cpu_binding)
     66                                     verbose=verbose, workers_per_node=workers_per_node,
     67                                     backend=backend, compile_args_creator=compile_args_creator,
---> 68                                     cpu_binding=cpu_binding)
     69 
     70 

/usr/local/lib/python3.7/dist-packages/zoo/orca/learn/tf2/estimator.py in __init__(self, model_creator, compile_args_creator, config, verbose, backend, workers_per_node, cpu_binding)
     98         self.verbose = verbose
     99 
--> 100         ray_ctx = RayContext.get()
    101         if "batch_size" in self.config:
    102             raise Exception("Please do not specify batch_size in config. Input batch_size in the"

/usr/local/lib/python3.7/dist-packages/zoo/ray/raycontext.py in get(cls, initialize)
    450             ray_ctx = RayContext._active_ray_context
    451             if initialize and not ray_ctx.initialized:
--> 452                 ray_ctx.init()
    453             return ray_ctx
    454         else:

/usr/local/lib/python3.7/dist-packages/zoo/ray/raycontext.py in init(self, driver_cores)
    533                                               include_dashboard=self.include_webui,
    534                                               dashboard_host="0.0.0.0",
--> 535                                               *kwargs)
    536             else:
    537                 self.cluster_ips = self._gather_cluster_ips()

/usr/local/lib/python3.7/dist-packages/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
     45         if client_mode_enabled and _client_hook_enabled:
     46             return getattr(ray, func.__name__)(*args, **kwargs)
---> 47         return func(*args, **kwargs)
     48 
     49     return wrapper

/usr/local/lib/python3.7/dist-packages/ray/worker.py in init(address, num_cpus, num_gpus, resources, object_store_memory, local_mode, ignore_reinit_error, include_dashboard, dashboard_host, dashboard_port, job_config, configure_logging, logging_level, logging_format, log_to_driver, _enable_object_reconstruction, _redis_max_memory, _plasma_directory, _node_ip_address, _driver_object_store_memory, _memory, _redis_password, _java_worker_options, _temp_dir, _lru_evict, _metrics_export_port, _system_config)
    716             shutdown_at_exit=False,
    717             spawn_reaper=True,
--> 718             ray_params=ray_params)
    719     else:
    720         # In this case, we are connecting to an existing cluster.

/usr/local/lib/python3.7/dist-packages/ray/node.py in __init__(self, ray_params, head, shutdown_at_exit, spawn_reaper, connect_only)
    218         # Start processes.
    219         if head:
--> 220             self.start_head_processes()
    221             redis_client = self.create_redis_client()
    222             redis_client.set("session_name", self.session_name)

/usr/local/lib/python3.7/dist-packages/ray/node.py in start_head_processes(self)
    836 
    837         if self._ray_params.include_dashboard:
--> 838             self.start_dashboard(require_dashboard=True)
    839         elif self._ray_params.include_dashboard is None:
    840             self.start_dashboard(require_dashboard=False)

/usr/local/lib/python3.7/dist-packages/ray/node.py in start_dashboard(self, require_dashboard)
    678             redis_password=self._ray_params.redis_password,
    679             fate_share=self.kernel_fate_share,
--> 680             port=self._ray_params.dashboard_port)
    681         assert ray_constants.PROCESS_TYPE_DASHBOARD not in self.all_processes
    682         if process_info is not None:

/usr/local/lib/python3.7/dist-packages/ray/_private/services.py in start_dashboard(require_dashboard, host, redis_address, temp_dir, logdir, port, stdout_file, stderr_file, redis_password, fate_share)
   1148     dashboard_dependencies_present = True
   1149     try:
-> 1150         import aiohttp  # noqa: F401
   1151         import grpc  # noqa: F401
   1152     except ImportError:

/usr/local/lib/python3.7/dist-packages/aiohttp/__init__.py in <module>()
      4 
      5 from . import hdrs as hdrs
----> 6 from .client import BaseConnector as BaseConnector
      7 from .client import ClientConnectionError as ClientConnectionError
      8 from .client import (

/usr/local/lib/python3.7/dist-packages/aiohttp/client.py in <module>()
     33 from yarl import URL
     34 
---> 35 from . import hdrs, http, payload
     36 from .abc import AbstractCookieJar
     37 from .client_exceptions import ClientConnectionError as ClientConnectionError

/usr/local/lib/python3.7/dist-packages/aiohttp/http.py in <module>()
      5 from . import __version__
      6 from .http_exceptions import HttpProcessingError as HttpProcessingError
----> 7 from .http_parser import HeadersParser as HeadersParser
      8 from .http_parser import HttpParser as HttpParser
      9 from .http_parser import HttpRequestParser as HttpRequestParser

/usr/local/lib/python3.7/dist-packages/aiohttp/http_parser.py in <module>()
     13 from . import hdrs
     14 from .base_protocol import BaseProtocol
---> 15 from .helpers import NO_EXTENSIONS, BaseTimerContext
     16 from .http_exceptions import (
     17     BadStatusLine,

/usr/local/lib/python3.7/dist-packages/aiohttp/helpers.py in <module>()
    610 
    611 
--> 612 class CeilTimeout(async_timeout.timeout):
    613 
    614     def __enter__(self) -> async_timeout.timeout:

TypeError: function() argument 1 must be code, not str

```

**Comment by Le-Zheng** [comment]
New error occurs on colab @yangw1234 :

```
RayTaskError(AssertionError)              Traceback (most recent call last)
<ipython-input-9-58c58ff5afa2> in <module>()
      2 
      3 batch_size = 320
----> 4 est = Estimator.from_keras(model_creator=model_creator, workers_per_node=1)

4 frames
/usr/local/lib/python3.7/dist-packages/zoo/orca/learn/tf2/estimator.py in from_keras(model_creator, config, verbose, workers_per_node, compile_args_creator, backend, cpu_binding)
     66                                     verbose=verbose, workers_per_node=workers_per_node,
     67                                     backend=backend, compile_args_creator=compile_args_creator,
---> 68                                     cpu_binding=cpu_binding)
     69 
     70 

/usr/local/lib/python3.7/dist-packages/zoo/orca/learn/tf2/estimator.py in __init__(self, model_creator, compile_args_creator, config, verbose, backend, workers_per_node, cpu_binding)
    129                 worker_cls=TFRunner,
    130                 worker_param=params,
--> 131                 cpu_binding=cpu_binding
    132             )
    133             self.remote_workers = self.cluster.get_workers()

/usr/local/lib/python3.7/dist-packages/zoo/orca/learn/dl_cluster.py in __init__(self, num_workers, worker_cores, worker_cls, worker_param, cpu_binding)
     90                                                    self.worker_cores)
     91                 cpu_binding_refs.append(ref)
---> 92             cpu_bindings = ray.get(cpu_binding_refs)
     93 
     94             result = []

/usr/local/lib/python3.7/dist-packages/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
     45         if client_mode_enabled and _client_hook_enabled:
     46             return getattr(ray, func.__name__)(*args, **kwargs)
---> 47         return func(*args, **kwargs)
     48 
     49     return wrapper

/usr/local/lib/python3.7/dist-packages/ray/worker.py in get(object_refs, timeout)
   1454                     worker.core_worker.dump_object_store_memory_usage()
   1455                 if isinstance(value, RayTaskError):
-> 1456                     raise value.as_instanceof_cause()
   1457                 else:
   1458                     raise value

RayTaskError(AssertionError): ray::Worker.run() (pid=1422, ip=172.28.0.2)
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/usr/local/lib/python3.7/dist-packages/zoo/orca/learn/dl_cluster.py", line 46, in run
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/zoo/orca/cpu_info.py", line 84, in schedule_workers
    assert cores_per_worker * num_workers <= len(p_cores), msg
AssertionError: total number of cores requested must be smaller or equal than the physical cores available
```
