### ISSUE TITLE
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.

### ISSUE THREAD

**Issue by GitEasonXu** [intel-analytics/analytics-zoo#4286]
I get Runtime Error, When running test. I've set `LC_ALL` up, but still can't solve the problem.

```python
Initializing orca context
Current pyspark location is : /root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/pyspark/__init__.py
Initializing SparkContext for yarn-client mode
Start to pack current python env
Packing has been completed: /tmp/tmpb1xj39bt/python_env.tar.gz
pyspark_submit_args is: --master yarn --deploy-mode client --archives /tmp/tmpb1xj39bt/python_env.tar.gz#python_env --driver-cores 4 --driver-memory 8g --num-executors 3 --executor-cores 2 --executor-memory 16g --driver-class-path /root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.12.1-spark_2.4.3-0.10.0-SNAPSHOT-jar-with-dependencies.jar:/root/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/bigdl/share/lib/bigdl-0.12.1-jar-with-dependencies.jar pyspark-shell
master : yarn
cluster_ips---------------------: ['10.180.210.67', '10.180.210.7', '10.180.210.122']
JavaGatewayServer has been successfully launched on executors
Start to launch ray on cluster
num ray nodes:3  numSlices: 3
process info: [<zoo.ray.process.ProcessInfo object at 0x7fe78fe0f828>, <zoo.ray.process.ProcessInfo object at 0x7fe78fe0fac8>, <zoo.ray.process.ProcessInfo object at 0x7fe78fe0f860>]
master pids num: 1
slave pids num: 2
master info:  node_ip: 10.180.210.67 tag: ray-master, pgid: 3206, pids: [], returncode: 1,                 master_addr: 10.180.210.67:47152,  
  Traceback (most recent call last):
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626167962011_0008/container_e03_1626167962011_0008_01_000002/python_env/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626167962011_0008/container_e03_1626167962011_0008_01_000002/python_env/lib/python3.6/site-packages/ray/scripts/scripts.py", line 1014, in main
    return cli()
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626167962011_0008/container_e03_1626167962011_0008_01_000002/python_env/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626167962011_0008/container_e03_1626167962011_0008_01_000002/python_env/lib/python3.6/site-packages/click/core.py", line 760, in main
    _verify_python3_env()
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626167962011_0008/container_e03_1626167962011_0008_01_000002/python_env/lib/python3.6/site-packages/click/_unicodefun.py", line 130, in _verify_python3_env
    " mitigation steps.{}".format(extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps.

This system lists a couple of UTF-8 supporting locales that you can pick from. The following suitable locales were discovered: en_US.utf8
master : yarn
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<timed exec> in <module>

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/zoo/orca/common.py in init_orca_context(cluster_mode, cores, memory, num_nodes, init_ray_on_spark, **kwargs)
    204         if "driver_cores" in kwargs:
    205             driver_cores = kwargs["driver_cores"]
--> 206         ray_ctx.init(driver_cores=driver_cores)
    207     return sc
    208 

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/zoo/ray/raycontext.py in init(self, driver_cores)
    472                 init_executor_gateway(self.sc)
    473                 print("JavaGatewayServer has been successfully launched on executors")
--> 474                 redis_address = self._start_cluster()
    475                 self._address_info = self._start_driver(num_cores=driver_cores,
    476                                                         redis_address=redis_address)

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/zoo/ray/raycontext.py in _start_cluster(self)
    502         print("process info:",process_infos)
    503         self.ray_processesMonitor = ProcessMonitor(process_infos, self.sc, ray_rdd, self,
--> 504                                                    verbose=self.verbose)
    505         return self.ray_processesMonitor.master.master_addr
    506 

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/zoo/ray/process.py in __init__(self, process_infos, sc, ray_rdd, raycontext, verbose)
    114         print("master info: ", self.master)
    115         if not is_local(self.sc):
--> 116             self.print_ray_remote_err_out()
    117 
    118     def print_ray_remote_err_out(self):

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/zoo/ray/process.py in print_ray_remote_err_out(self)
    118     def print_ray_remote_err_out(self):
    119         if self.master.errorcode != 0:
--> 120             raise Exception(str(self.master))
    121         for slave in self.slaves:
    122             if slave.errorcode != 0:

Exception: node_ip: 10.180.210.67 tag: ray-master, pgid: 3206, pids: [], returncode: 1,                 master_addr: 10.180.210.67:47152,  
  Traceback (most recent call last):
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626167962011_0008/container_e03_1626167962011_0008_01_000002/python_env/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626167962011_0008/container_e03_1626167962011_0008_01_000002/python_env/lib/python3.6/site-packages/ray/scripts/scripts.py", line 1014, in main
    return cli()
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626167962011_0008/container_e03_1626167962011_0008_01_000002/python_env/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626167962011_0008/container_e03_1626167962011_0008_01_000002/python_env/lib/python3.6/site-packages/click/core.py", line 760, in main
    _verify_python3_env()
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626167962011_0008/container_e03_1626167962011_0008_01_000002/python_env/lib/python3.6/site-packages/click/_unicodefun.py", line 130, in _verify_python3_env
    " mitigation steps.{}".format(extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps.

This system lists a couple of UTF-8 supporting locales that you can pick from. The following suitable locales were discovered: en_US.utf8
```

```
(zoo-tf2.3) [root@manager workspace]# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by yangw1234** [comment]
Hi @hkvision , would you kindly take a look at this issue?

**Comment by hkvision** [comment]
May be similar to the issue here due to the system environment: https://analytics-zoo.readthedocs.io/en/latest/doc/Ray/Overview/ray.html#known-issue?

Can you add the `env` when init_orca_context?
```
env={"LANG": "en_US.utf-8", "LC_ALL": "en_US.utf-8"})
```

**Comment by GitEasonXu** [comment]
Add `env` to solve the problem. Thank you for your advice.

Is there any reference on the ray env config?

**Comment by hkvision** [comment]
Actually I'm not sure why this happens, probably due to system settings. Normally you don't need to set the env...
I will add your error to known issues to help other users :) Thanks so much!

**Comment by GitEasonXu** [comment]
I encountered a problem that `libhdfs.so` could not be loaded, even though I have configured correct `env`.
```
env={"LD_LIBRARY_PATH": os.environ["LD_LIBRARY_PATH"],
     "HADOOP_HDFS_HOME":"/usr/hdp/3.0.1.0-187/usr/lib",
     "CLASSPATH":os.environ["CLASSPATH"],
     "LANG": "en_US.utf-8",
     "LC_ALL": "en_US.utf-8"}
```

Error log:
```
pid=47003, ip=10.180.210.67) 2021-07-20 23:28:57.464396: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:115] HadoopFileSystem load error: /usr/jdk64/java/jre/lib/amd64/server:/usr/hdp/3.0.1.0-187/usr/lib/lib/native/libhdfs.so: cannot open shared object file: No such file or directory
(pid=47047, ip=10.180.210.67) 2021-07-20 23:28:57.470413: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:115] HadoopFileSystem load error: /usr/jdk64/java/jre/lib/amd64/server:/usr/hdp/3.0.1.0-187/usr/lib/lib/native/libhdfs.so: cannot open shared object file: No such file or directory
(pid=47048, ip=10.180.210.67) 2021-07-20 23:28:57.463456: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:115] HadoopFileSystem load error: /usr/jdk64/java/jre/lib/amd64/server:/usr/hdp/3.0.1.0-187/usr/lib/lib/native/libhdfs.so: cannot open shared object file: No such file or directory
---------------------------------------------------------------------------
RayTaskError(NotFoundError)               Traceback (most recent call last)
<timed exec> in <module>

<ipython-input-12-f49272480269> in main(max_epoch)
     11                     steps_per_epoch=50000 // batch_size,
     12                     validation_data_creator=val_data_creator,
---> 13                     validation_steps=10000 // batch_size
     14                      )
     15     print(history)

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/zoo/orca/learn/tf2/tf_ray_estimator.py in fit(self, data_creator, epochs, verbose, callbacks, validation_data_creator, class_weight, steps_per_epoch, validation_steps, validation_freq, data_config, feature_cols, label_cols)
    257 
    258             worker_stats = ray.get([self.remote_workers[i].step.remote(**params_list[i])
--> 259                                     for i in range(self.num_workers)])
    260             worker_stats = list(itertools.chain.from_iterable(worker_stats))
    261         stats = worker_stats[0].copy()

~/anaconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/ray/worker.py in get(object_ids, timeout)
   1511                     worker.core_worker.dump_object_store_memory_usage()
   1512                 if isinstance(value, RayTaskError):
-> 1513                     raise value.as_instanceof_cause()
   1514                 else:
   1515                     raise value

RayTaskError(NotFoundError): ray::TFRunner.step() (pid=47075, ip=10.180.210.122)
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task.function_executor
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626685606657_0074/container_e06_1626685606657_0074_01_000003/python_env/lib/python3.6/site-packages/zoo/orca/learn/tf2/tf_runner.py", line 365, in step
    validation_freq=validation_freq)
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626685606657_0074/container_e06_1626685606657_0074_01_000003/python_env/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 117, in _method_wrapper
    mode=dc.CoordinatorMode.INDEPENDENT_WORKER)
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626685606657_0074/container_e06_1626685606657_0074_01_000003/python_env/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_coordinator.py", line 860, in run_distribute_coordinator
    task_id, session_config, rpc_layer)
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626685606657_0074/container_e06_1626685606657_0074_01_000003/python_env/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_coordinator.py", line 360, in _run_single_worker
    return worker_fn(strategy)
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626685606657_0074/container_e06_1626685606657_0074_01_000003/python_env/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 115, in <lambda>
    lambda _: method(self, *args, **kwargs),
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626685606657_0074/container_e06_1626685606657_0074_01_000003/python_env/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626685606657_0074/container_e06_1626685606657_0074_01_000003/python_env/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626685606657_0074/container_e06_1626685606657_0074_01_000003/python_env/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626685606657_0074/container_e06_1626685606657_0074_01_000003/python_env/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626685606657_0074/container_e06_1626685606657_0074_01_000003/python_env/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626685606657_0074/container_e06_1626685606657_0074_01_000003/python_env/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626685606657_0074/container_e06_1626685606657_0074_01_000003/python_env/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/hadoop/yarn/local/usercache/hdfs/appcache/application_1626685606657_0074/container_e06_1626685606657_0074_01_000003/python_env/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.NotFoundError:  libhdfs.so: cannot open shared object file: No such file or directory
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional]] [Op:__inference_train_function_1518]

Function call stack:
train_function
```

**Comment by GitEasonXu** [comment]
I found the problem because Yarn Node Manager did not contain `libhdfs.so`.
