### ISSUE TITLE
jenkins: apptest failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#4352]
#23 start app test for chronos-network-traffic-multivarite-multistep-tcnforecaster
~~~
[NbConvertApp] Converting notebook /opt/work/jenkins/workspace/ZOO-NB-Pip-AppTests-part4/dist/../pyzoo/zoo/chronos/use-case/network_traffic/network_traffic_multivariate_multistep_tcnforecaster.tmp.ipynb to python
[NbConvertApp] Writing 8190 bytes to /opt/work/jenkins/workspace/ZOO-NB-Pip-AppTests-part4/dist/../pyzoo/zoo/chronos/use-case/network_traffic/network_traffic_multivariate_multistep_tcnforecaster.tmp.py
/opt/work/jenkins/workspace/ZOO-NB-Pip-AppTests-part4/dist/../pyzoo/zoo/chronos/use-case/network_traffic/data/data.csv already exists.
Traceback (most recent call last):
  File "/opt/work/jenkins/workspace/ZOO-NB-Pip-AppTests-part4/dist/../pyzoo/zoo/chronos/use-case/network_traffic/network_traffic_multivariate_multistep_tcnforecaster.py", line 50, in <module>
    raw_df = pd.read_csv("/home/junweid/intel_PR4/analytics-zoo/pyzoo/zoo/chronos/use-case/network_traffic/data/data.csv")
  File "/opt/work/conda/envs/py36/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/work/conda/envs/py36/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/opt/work/conda/envs/py36/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/opt/work/conda/envs/py36/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/opt/work/conda/envs/py36/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '/home/junweid/intel_PR4/analytics-zoo/pyzoo/zoo/chronos/use-case/network_traffic/data/data.csv'
~~~

Jenkins link:
http://10.239.176.111:18888/job/ZOO-NB-Pip-AppTests-part4/497/

**Comment by pinggao187** [comment]
@TheaperDeng

**Comment by TheaperDeng** [comment]
I mistakenly cp my prefix here. I will fix it soon.

**Comment by TheaperDeng** [comment]
fixed and merged, app test pass, pls rerun

**Comment by pinggao187** [comment]
pass
http://10.239.176.111:18888/view/ZOO-NB/job/ZOO-NB-Pip-AppTests-part4/498/
