### ISSUE TITLE
How can I use write_parquet to save data to HDFS?

### ISSUE THREAD

**Issue by GitEasonXu** [intel-analytics/analytics-zoo#4458]
```python
def write_cifar10(images, labels, output_path, **kwargs):
    images_shape = [int(x) for x in images.shape[1:]]
    labels_shape = [int(x) for x in labels.shape[1:]]
    def make_generator():
        for image, label in zip(images, labels):
            yield {"image": image, "label": label}
    
    schema = {
        "image": SchemaField(feature_type=FeatureType.NDARRAY,
                             dtype=ndarray_dtype_to_dtype(images.dtype),
                             shape=images_shape),
        "label": SchemaField(feature_type=FeatureType.NDARRAY,
                             dtype=ndarray_dtype_to_dtype(labels.dtype),
                             shape=labels_shape)
    }
    ParquetDataset.write(output_path, make_generator(), schema, **kwargs)

hostname = socket.gethostname()
output_path = "hdfs://{}:8020/zoo/dataset/cifar10".format(hostname)

sc = init_orca_context(cores=4, spark_log_level="INFO", object_store_memory="1g", init_ray_on_spark=True)
write_cifar10(train_images, train_labels, output_path)
```
Error logs：
```
Traceback (most recent call last):                                              
  File "/opt/workspace/write_parquet.py", line 39, in <module>
    write_cifar10(train_images, train_labels, output_path)
  File "/opt/workspace/write_parquet.py", line 33, in write_cifar10
    ParquetDataset.write(output_path, make_generator(), schema, **kwargs)
  File "/root/miniconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/zoo/orca/data/image/parquet_dataset.py", line 76, in write
    write_mode).parquet(chunk_path)
  File "/root/miniconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/pyspark/sql/readwriter.py", line 844, in parquet
    self._jwrite.parquet(path)
  File "/root/miniconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/root/miniconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/root/miniconda3/envs/zoo-tf2.3/lib/python3.6/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o133.parquet.
: org.apache.hadoop.security.AccessControlException: Permission denied: user=root, access=WRITE, inode="/zoo/dataset/cifar10":hdfs:hdfs:drwxr-xr-x
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:399)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:255)
        at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:193)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1850)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1834)
        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkAncestorAccess(FSDirectory.java:1793)
        at org.apache.hadoop.hdfs.server.namenode.FSDirMkdirOp.mkdirs(FSDirMkdirOp.java:59)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.mkdirs(FSNamesystem.java:3150)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.mkdirs(NameNodeRpcServer.java:1126)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.mkdirs(ClientNamenodeProtocolServerSideTranslatorPB.java:707)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:524)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1025)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:876)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:822)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2682)
```
It's due to `root user Permission`. What should I do to fix this problem?

**Comment by qiyuangong** [comment]
Hi @GitEasonXu . 

Yes. This error is caused by HDFS permission.  According to your error log, root doesn't have write permission in `/zoo/dataset/cifar10`.

To fix this issue, you can change username by adding this env

```
export HADOOP_USER_NAME=hdfs
```

**Comment by qiyuangong** [comment]
> No such file or directory when trying to connect to '/var/lib/hadoop-hdfs/dn_socket'

Hi @GitEasonXu 
Seems you are using hdfs short-circuit read feature(quite similar to this [link](https://stackoverflow.com/questions/43142592/connectexception-connect-error-no-such-file-or-directory-when-trying-to-connec)). 

Pls check if `/var/lib/hadoop-hdfs/dn_socket` exist in your local env, and if `HADOOP_CONF_DIR` and `HADOOP_HOME` are correctly set.

**Comment by GitEasonXu** [comment]
Thanks so much, I try to fix this problem according to this method.
