### ISSUE TITLE
jenkins: stock_prediction_prophet test failed

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#4598]
~~~
Traceback (most recent call last):
  File "/var/jenkins_home/workspace/ZOO-NB-Pip-AppTests-MAC-py37/dist/../pyzoo/zoo/chronos/use-case/fsi/stock_prediction_prophet.py", line 132, in <module>
    freq="1D")
  File "/Users/arda/anaconda3/envs/py37pip/lib/python3.7/site-packages/zoo/chronos/autots/model/auto_prophet.py", line 152, in fit
    scheduler_params=scheduler_params
  File "/Users/arda/anaconda3/envs/py37pip/lib/python3.7/site-packages/zoo/orca/automl/auto_estimator.py", line 185, in fit
    self.searcher.run()
  File "/Users/arda/anaconda3/envs/py37pip/lib/python3.7/site-packages/zoo/automl/search/ray_tune_search_engine.py", line 171, in run
    reuse_actors=True
  File "/Users/arda/anaconda3/envs/py37pip/lib/python3.7/site-packages/ray/tune/tune.py", line 444, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [train_func_c1d65_00023, train_func_c1d65_00027, train_func_c1d65_00030, train_func_c1d65_00032, train_func_c1d65_00033, train_func_c1d65_00040])
Stopping orca context
~~~
jenkins link:
http://10.112.231.51:18888/job/ZOO-NB-Pip-AppTests-MAC-py37/127/console
@TheaperDeng pls have a look.

**Comment by TheaperDeng** [comment]
Working on it. Since it is a MAC-ONLY problem, I will try to replay the error and error log on our MAC server.

**Comment by TheaperDeng** [comment]
to workaround in the notebook since mac support is not our high priority. @liangs6212 will handle the issue

**Comment by pinggao187** [comment]
pass
http://10.112.231.51:18888/job/ZOO-NB-Pip-AppTests-MAC-py37/130/
