### ISSUE TITLE
jenkins: java.lang.NoClassDefFoundError: com/intel/analytics/bigdl/python/api/PythonBigDLKeras

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#4939]
#10 start app test for using_variational_autoencoder_and_deep_feature_loss_to_generate_faces
~~~
2021-10-13 01:37:00 WARN  Utils:66 - Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: com/intel/analytics/bigdl/python/api/PythonBigDLKeras
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at py4j.reflection.CurrentThreadClassLoadingStrategy.classForName(CurrentThreadClassLoadingStrategy.java:40)
	at py4j.reflection.ReflectionUtil.classForName(ReflectionUtil.java:51)
	at py4j.reflection.TypeUtil.forName(TypeUtil.java:243)
	at py4j.commands.ReflectionCommand.getUnknownMember(ReflectionCommand.java:175)
	at py4j.commands.ReflectionCommand.execute(ReflectionCommand.java:87)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.intel.analytics.bigdl.python.api.PythonBigDLKeras
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 34 more
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/opt/work/conda/envs/py36/lib/python3.6/site-packages/py4j/java_gateway.py", line 1159, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/work/conda/envs/py36/lib/python3.6/site-packages/py4j/java_gateway.py", line 985, in send_command
    response = connection.send_command(command)
  File "/opt/work/conda/envs/py36/lib/python3.6/site-packages/py4j/java_gateway.py", line 1164, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
pyspark_submit_args is:  --driver-class-path /opt/work/conda/envs/py36/lib/python3.6/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.13.0-spark_2.4.6-0.12.0-SNAPSHOT-jar-with-dependencies.jar pyspark-shell 
Traceback (most recent call last):
  File "/opt/work/jenkins/workspace/ZOO-NB-Pip-AppTests-part3/dist/apps/variational-autoencoder/using_variational_autoencoder_and_deep_feature_loss_to_generate_faces.py", line 34, in <module>
    sc = init_nncontext("Variational Autoencoder Example")
  File "/opt/work/conda/envs/py36/lib/python3.6/site-packages/zoo/common/nncontext.py", line 404, in init_nncontext
    redire_spark_logs()
  File "/opt/work/conda/envs/py36/lib/python3.6/site-packages/bigdl/util/common.py", line 449, in redire_spark_logs
    callBigDlFunc(bigdl_type, "redirectSparkLogs", log_path)
  File "/opt/work/conda/envs/py36/lib/python3.6/site-packages/bigdl/util/common.py", line 592, in callBigDlFunc
    for jinvoker in JavaCreator.instance(bigdl_type, gateway).value:
  File "/opt/work/conda/envs/py36/lib/python3.6/site-packages/bigdl/util/common.py", line 56, in instance
    cls._instance = cls(bigdl_type, *args)
  File "/opt/work/conda/envs/py36/lib/python3.6/site-packages/bigdl/util/common.py", line 94, in __init__
    jclass = getattr(gateway.jvm, creator_class)
  File "/opt/work/conda/envs/py36/lib/python3.6/site-packages/py4j/java_gateway.py", line 1659, in __getattr__
    raise Py4JError(message)
py4j.protocol.Py4JError: com.intel.analytics.zoo.tfpark.python.PythonTFPark does not exist in the JVM
~~~
jenkins link:
http://10.112.231.51:18888/job/ZOO-NB-Pip-AppTests-part3/602/

**Comment by qiuxin2012** [comment]
`pyspark_submit_args is:  --driver-class-path /opt/work/conda/envs/py36/lib/python3.6/site-packages/zoo/share/lib/analytics-zoo-bigdl_0.13.0-spark_2.4.6-0.12.0-SNAPSHOT-jar-with-dependencies.jar` the driver-class-path is incorrect, please change to orca's jar
