### ISSUE TITLE
(raylet) socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by xunaichao** [intel-analytics/analytics-zoo#5118]
When I run https://analytics-zoo.readthedocs.io/en/latest/doc/Orca/QuickStart/orca-tf2keras-quickstart.html tensorFlow 2 For example.
############
Error：
(raylet) Traceback (most recent call last):
(raylet)   File "/usr/local/miniconda3/envs/zoo/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 334, in <module>
(raylet)     raise e
(raylet)   File "/usr/local/miniconda3/envs/zoo/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 323, in <module>
(raylet)     loop.run_until_complete(agent.run())
(raylet)   File "/usr/local/miniconda3/envs/zoo/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
(raylet)     return future.result()
(raylet)   File "/usr/local/miniconda3/envs/zoo/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 138, in run
(raylet)     modules = self._load_modules()
(raylet)   File "/usr/local/miniconda3/envs/zoo/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 92, in _load_modules
(raylet)     c = cls(self)
(raylet)   File "/usr/local/miniconda3/envs/zoo/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py", line 72, in __init__
(raylet)     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)
(raylet)   File "/usr/local/miniconda3/envs/zoo/lib/python3.7/site-packages/ray/metrics_agent.py", line 76, in __init__
(raylet)     namespace="ray", port=metrics_export_port)))
(raylet)   File "/usr/local/miniconda3/envs/zoo/lib/python3.7/site-packages/ray/prometheus_exporter.py", line 334, in new_stats_exporter
(raylet)     options=option, gatherer=option.registry, collector=collector)
(raylet)   File "/usr/local/miniconda3/envs/zoo/lib/python3.7/site-packages/ray/prometheus_exporter.py", line 266, in __init__
(raylet)     self.serve_http()
(raylet)   File "/usr/local/miniconda3/envs/zoo/lib/python3.7/site-packages/ray/prometheus_exporter.py", line 321, in serve_http
(raylet)     port=self.options.port, addr=str(self.options.address))
(raylet)   File "/usr/local/miniconda3/envs/zoo/lib/python3.7/site-packages/prometheus_client/exposition.py", line 168, in start_wsgi_server
(raylet)     TmpServer.address_family, addr = _get_best_family(addr, port)
(raylet)   File "/usr/local/miniconda3/envs/zoo/lib/python3.7/site-packages/prometheus_client/exposition.py", line 157, in _get_best_family
(raylet)     infos = socket.getaddrinfo(address, port)
(raylet)   File "/usr/local/miniconda3/envs/zoo/lib/python3.7/socket.py", line 753, in getaddrinfo
(raylet)     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
(raylet) socket.gaierror: [Errno -2] Name or service not known
##############

Hosts file
![image](https://user-images.githubusercontent.com/92299719/171099953-e57bb280-c746-4bb0-8ea2-c205a16c3ac2.png)

After running the example, session files are generated in /tmp/ray/ of the system
![image](https://user-images.githubusercontent.com/92299719/171099997-12c2c495-126a-4e39-a343-7f3e33fc6cb9.png)

Runtime environment: Docker deployment uses Miniconda to install AZ and Ray

Conda create -n zoo python=3.7
conda activate zoo
pip install --pre --upgrade analytics-zoo
pip install analytics-zoo[ray]
PIP install tensorflow = = 2.3.0

conda list

 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   1.0.0                    pypi_0    pypi
aiohttp                   3.7.0                    pypi_0    pypi
aiohttp-cors              0.7.0                    pypi_0    pypi
aioredis                  1.1.0                    pypi_0    pypi
analytics-zoo             0.12.0b2022052501          pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
async-timeout             3.0.1                    pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
bigdl                     0.13.1.dev1              pypi_0    pypi
blessings                 1.7                      pypi_0    pypi
ca-certificates           2022.4.26            h06a4308_0  
cachetools                5.1.0                    pypi_0    pypi
certifi                   2022.5.18.1      py37h06a4308_0  
chardet                   3.0.4                    pypi_0    pypi
charset-normalizer        2.0.12                   pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
colorful                  0.5.4                    pypi_0    pypi
conda-pack                0.3.1                    pypi_0    pypi
deprecated                1.2.13                   pypi_0    pypi
filelock                  3.7.0                    pypi_0    pypi
gast                      0.3.3                    pypi_0    pypi
google-api-core           2.8.0                    pypi_0    pypi
google-auth               2.6.6                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
googleapis-common-protos  1.56.1                   pypi_0    pypi
gpustat                   0.6.0                    pypi_0    pypi
grpcio                    1.46.3                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
hiredis                   1.1.0                    pypi_0    pypi
idna                      3.3                      pypi_0    pypi
importlib-metadata        4.11.4                   pypi_0    pypi
importlib-resources       5.7.1                    pypi_0    pypi
jsonschema                4.5.1                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
libedit                   3.1.20210910         h7f8727e_0  
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 11.2.0               h1234567_0  
libgomp                   11.2.0               h1234567_0  
libstdcxx-ng              11.2.0               h1234567_0  
markdown                  3.3.7                    pypi_0    pypi
msgpack                   1.0.3                    pypi_0    pypi
multidict                 6.0.2                    pypi_0    pypi
ncurses                   6.3                  h7f8727e_2  
numpy                     1.18.5                   pypi_0    pypi
nvidia-ml-py3             7.352.0                  pypi_0    pypi
oauthlib                  3.2.0                    pypi_0    pypi
opencensus                0.9.0                    pypi_0    pypi
opencensus-context        0.1.2                    pypi_0    pypi
opencv-python             4.5.5.64                 pypi_0    pypi
openssl                   1.0.2u               h7b6447c_0  
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pip                       21.2.2           py37h06a4308_0  
prometheus-client         0.14.1                   pypi_0    pypi
protobuf                  3.20.1                   pypi_0    pypi
psutil                    5.9.1                    pypi_0    pypi
py-spy                    0.3.12                   pypi_0    pypi
py4j                      0.10.7                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
pyspark                   2.4.6                    pypi_0    pypi
python                    3.7.0                h6e4f718_3  
pyyaml                    6.0                      pypi_0    pypi
ray                       1.2.0                    pypi_0    pypi
readline                  7.0                  h7b6447c_5  
redis                     4.1.4                    pypi_0    pypi
requests                  2.27.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
setproctitle              1.2.3                    pypi_0    pypi
setuptools                61.2.0           py37h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.33.0               h62c20be_0  
tensorboard               2.9.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.3.0                    pypi_0    pypi
tensorflow-estimator      2.3.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.11               h1ccaba5_1  
typing-extensions         4.2.0                    pypi_0    pypi
urllib3                   1.26.9                   pypi_0    pypi
werkzeug                  2.1.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
wrapt                     1.14.1                   pypi_0    pypi
xz                        5.2.5                h7f8727e_1  
yarl                      1.7.2                    pypi_0    pypi
zipp                      3.8.0                    pypi_0    pypi
zlib                      1.2.12               h7f8727e_2  

————————————————————
1、Check python:
from zoo.util.utils import detect_python_location
detect_python_location()
![image](https://user-images.githubusercontent.com/92299719/171100036-4b95d853-56a8-4759-9624-101cca58518f.png)

2、Check ray installation
/usr/local/miniconda3/envs/zoo/bin/python /usr/local/miniconda3/envs/zoo/bin/ray start --head --include-dashboard ture --dashboard-host 172.27.0.2 --port 35413 --redis-password 123456 --num-cpus 1
![image](https://user-images.githubusercontent.com/92299719/171100072-65b6a9ed-6144-453c-a6d3-b46809012b96.png)

/usr/local/miniconda3/envs/zoo/bin/python /usr/local/miniconda3/envs/zoo/bin/ray start --address 172.27.0.2:35413 --redis-password 123456 --num-cpus 1
![image](https://user-images.githubusercontent.com/92299719/171100093-91bc8c3f-33de-460b-b697-8bb65af7b69f.png)

ray start --address=‘172.27.0.2:35413' --redis-password='0'

![image](https://user-images.githubusercontent.com/92299719/171100119-f8c468cb-904f-4d33-903e-b6fc241ea8c4.png)

[Related documents.zip](https://github.com/intel-analytics/analytics-zoo/files/8802233/Related.documents.zip)

**Comment by xunaichao** [comment]
Please help solve it. Thank you

I'm going crazy

**Comment by jason-dai** [comment]
@xunaichao As mentioned in https://github.com/intel-analytics/analytics-zoo/blob/master/README.md, we have migrated to project to https://github.com/intel-analytics/bigdl; please try https://bigdl.readthedocs.io/en/latest/doc/Orca/QuickStart/orca-tf2keras-quickstart.html instead

**Comment by hkvision** [comment]
Hi @xunaichao 

I checked the code and run it on Google Colab, I can get this error as well. But seems this error doesn't impact or interrupt the running, you can find the train and evaluate results in your log. Seems the error comes from ray dashboard, not sure whether this is caused by the out-of-date ray version.

As mentioned above, you are highly recommended to switch to the latest version of BigDL, I run the same BigDL example in Google Colab and there's no such error: https://bigdl.readthedocs.io/en/latest/doc/Orca/QuickStart/orca-tf2keras-quickstart.html

**Comment by yushan111** [comment]
It seems you may try to load the wrong weights: 
```
./yolov3/yolov3.weights: DATA_LOSS: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
```
You may need to convert the pre-trained darknet weights first, as does in [yolo v3 example](https://github.com/intel-analytics/BigDL/blob/main/python/orca/example/learn/tf2/yolov3/yoloV3.py#L606-L608).

And you could always refer to our [Yolov3 example in BigDL](https://github.com/intel-analytics/BigDL/tree/main/python/orca/example/learn/tf2/yolov3). Hope that helps.

**Comment by yushan111** [comment]
May I ask whether you met the same error with your TensorFlow code (without using `bigdl`), i.e with your `tflocal` mode?

**Comment by xunaichao** [comment]
we use, https://bigdl.readthedocs.io/en/latest/doc/Orca/QuickStart/orca-tf2keras-quickstart.html, this example to save the model. and change the save module to :
![4061654161657_ pic](https://user-images.githubusercontent.com/92299719/171599123-8ee3991e-4001-4eba-9889-2703fdd10e20.jpg)
we now get the .pb file sucessfully, but have an exception when i use model optimizer of openvino to convert the model format to IR. the error is like this:
 
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      /az/test1/saved_model.pb
        - Path for generated IR:        /opt/intel/openvino_2021.4.752/deployment_tools/model_optimizer/.
        - IR output name:       saved_model
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         Not specified, inherited from the model
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         [1,120,120,3]
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       None
        - Reverse input channels:       False
TensorFlow specific parameters:
        - Input model in text protobuf format:  False
        - Path to model dump for TensorBoard:   None
        - List of shared libraries with TensorFlow custom layers implementation:        None
        - Update the configuration file with input/output node names:   None
        - Use configuration file used to generate the model with Object Detection API:  None
        - Use the config file:  None
        - Inference Engine found in:    /opt/intel/openvino_2021.4.752/python/python3.6/openvino
Inference Engine version:       2021.4.2-3974-e2a469a3450-releases/2021/4
Model Optimizer version:        2021.4.2-3974-e2a469a3450-releases/2021/4
2022-06-02 09:03:05.880400: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/opt/intel/openvino_2021.4.752/deployment_tools/model_optimizer/mo/utils/../../../inference_engine/lib/intel64:/opt/intel/openvino_2021.4.752/deployment_tools/model_optimizer/mo/utils/../../../inference_engine/external/tbb/lib:/opt/intel/openvino_2021.4.752/deployment_tools/model_optimizer/mo/utils/../../../ngraph/lib
2022-06-02 09:03:05.880451: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py:22: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[ FRAMEWORK ERROR ]  Cannot load input model: TensorFlow cannot read the model file: "/az/test1/saved_model.pb" is incorrect TensorFlow model file. 
The file should contain one of the following TensorFlow graphs:
1. frozen graph in text or binary format
2. inference graph for freezing with checkpoint (--input_checkpoint) in text or binary format
3. meta graph

Make sure that --input_model_is_text is provided for a model in text format. By default, a model is interpreted in binary format. Framework error details: Error parsing message. 
 For more information please refer to Model Optimizer FAQ, question #43. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=43#question-43)
can you help us, thank you very much!
@yushan111 thank you for the example, it helps a lot!

**Comment by yushan111** [comment]
You will get a `tf.keras` model with `est.get_model()`,  and you could successfully save the model with `tf.saved_model` API. 

After that, it depends on you how you would like to use your tensorflow model.

About using Openvino to convert your tensorflow model, maybe you could open an issue in the Openvino project.

**Comment by xunaichao** [comment]
@yushan111  thanks for your help
