### ISSUE TITLE
nnframes.imageInference.ImageInferenceExample failed to parse bvlc_googlenet.caffemodel

### ISSUE THREAD

**Issue by ZeweiChen11** [intel-analytics/analytics-zoo#808]
Analytics-zoo v0.2.0 nnframes.imageInference.ImageInferenceExample

Caffe model is downloaded from http://dl.caffe.berkeleyvision.org/bvlc_googlenet.caffemodel

Building command line:
`bash make-dist.sh -Dspark.version=2.3.1 -Dbigdl.artifactId=bigdl-SPARK_2.3`

Running command line:
```
ANALYTICS_ZOO_HOME=/root/analytics-zoo/dist
ANALYTICS_ZOO_JAR=${ANALYTICS_ZOO_HOME}/lib/analytics-zoo-*-jar-with-dependencies.jar
master=yarn

modelPath=/root/caffe_inceptionv1/bvlc_googlenet.caffemodel
caffedefPath=/root/caffe_inceptionv1/
imagePath=hdfs:///user/root/imagenet

spark-submit \
    --verbose \
    --master $master \
    --deploy-mode client \
    --executor-cores 8 \
    --num-executors 5 \
    --driver-memory 10g \
    --executor-memory 100g \
    --class com.intel.analytics.zoo.examples.nnframes.imageInference.ImageInferenceExample \
    ${ANALYTICS_ZOO_JAR}  \
    --modelPath /root/caffe_inceptionv1/bvlc_googlenet.caffemodel \
    --caffeDefPath /root/caffe_inceptionv1/deploy.prototxt \
    --batchSize 160 \
    --folder $imagePath
```

Error messages:
```
18/10/18 09:34:28 INFO utils.ThreadPool$: Set mkl threads to 1 on thread 1
18/10/18 09:34:44 INFO utils.Engine$: Auto detect executor number and executor cores number
18/10/18 09:34:44 INFO utils.Engine$: Executor number is 5 and executor cores number is 8
18/10/18 09:34:44 INFO utils.Engine$: Find existing spark context. Checking the spark conf...
Exception in thread "main" Caffe conversion error : Parsing caffe model error,only standard Caffe format is supported
        at com.intel.analytics.bigdl.utils.caffe.CaffeLoader$.loadCaffe(CaffeLoader.scala:570)
        at com.intel.analytics.bigdl.nn.Module$.loadCaffeModel(Module.scala:82)
        at com.intel.analytics.zoo.examples.nnframes.imageInference.ImageInferenceExample$$anonfun$main$1.apply(ImageInferenceExample.scala:44)
        at com.intel.analytics.zoo.examples.nnframes.imageInference.ImageInferenceExample$$anonfun$main$1.apply(ImageInferenceExample.scala:34)
        at scala.Option.foreach(Option.scala:257)
        at com.intel.analytics.zoo.examples.nnframes.imageInference.ImageInferenceExample$.main(ImageInferenceExample.scala:34)
        at com.intel.analytics.zoo.examples.nnframes.imageInference.ImageInferenceExample.main(ImageInferenceExample.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:896)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by hhbyyh** [comment]
Hi @ZeweiChen11 I tried it and cannot repro the issue. 

Can I know which prototxt did you use?

**Comment by ZeweiChen11** [comment]
Hi @hhbyyh , I download from https://github.com/BVLC/caffe/blob/master/models/bvlc_googlenet/deploy.prototxt .

**Comment by ZeweiChen11** [comment]
Fixed by re-downloading deploy.prototxt, thanks yuhao!
