### ISSUE TITLE
AUC issues

### ISSUE THREAD

**Issue by hhbyyh** [intel-analytics/analytics-zoo#811]
1. AUC does not print score for each of the class during validation.
    master local[1] will print, but local[4] and local[*] (8 cores in total) do not print.

2. AUC reports tensorsize mismatch exception when using master local[2]
    ```
java.lang.IllegalArgumentException: requirement failed: tensor size not match 200x15 200
	at scala.Predef$.require(Predef.scala:224)
	at com.intel.analytics.bigdl.tensor.DenseTensor$.expandSize(DenseTensor.scala:2716)
	at com.intel.analytics.bigdl.tensor.DenseTensor.expandTensor(DenseTensor.scala:976)
	at com.intel.analytics.bigdl.tensor.DenseTensor.add(DenseTensor.scala:970)
	at com.intel.analytics.zoo.pipeline.api.keras.metrics.AucScore.$plus(AUC.scala:50)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$16$$anonfun$apply$29$$anonfun$apply$32$$anonfun$apply$33.apply(DistriOptimizer.scala:749)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$16$$anonfun$apply$29$$anonfun$apply$32$$anonfun$apply$33.apply(DistriOptimizer.scala:748)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$16$$anonfun$apply$29$$anonfun$apply$32.apply(DistriOptimizer.scala:748)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$16$$anonfun$apply$29$$anonfun$apply$32.apply(DistriOptimizer.scala:747)
	at scala.collection.TraversableOnce$$anonfun$reduceLeft$1.apply(TraversableOnce.scala:190)
	at scala.collection.TraversableOnce$$anonfun$reduceLeft$1.apply(TraversableOnce.scala:185)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:185)
	at scala.collection.AbstractTraversable.reduceLeft(Traversable.scala:104)
	at scala.collection.TraversableOnce$class.reduce(TraversableOnce.scala:208)
	at scala.collection.AbstractTraversable.reduce(Traversable.scala:104)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$16$$anonfun$apply$29.apply(DistriOptimizer.scala:747)
	at com.intel.analytics.bigdl.optim.DistriOptimizer$$anonfun$16$$anonfun$apply$29.apply(DistriOptimizer.scala:728)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:185)
	at scala.collection.AbstractIterator.reduceLeft(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$15.apply(RDD.scala:1012)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$15.apply(RDD.scala:1010)
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:2118)
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:2118)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
     ```

code to repro
```
from bigdl.nn.criterion import *
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, udf
from pyspark.sql.types import DoubleType, StringType, ArrayType
from zoo.common.nncontext import *
from zoo.feature.image import *
from zoo.pipeline.api.keras.layers import Input, Flatten, Dense
from zoo.pipeline.api.keras.models import *
from zoo.pipeline.api.net import *
from zoo.pipeline.nnframes import *
from zoo.feature.image.imagePreprocessing import *
import random
from pyspark.ml.evaluation import MulticlassClassificationEvaluator
from bigdl.transform.vision.image import RandomTransformer, HFlip
from pyspark.sql.types import *
import numpy as np
from sklearn.metrics import roc_auc_score
from pyspark.ml import Pipeline
from bigdl.optim.optimizer import *
from zoo.pipeline.api.keras.metrics import AUC
random.seed(1234)

def Read_Pathes():
    model_path ="/home/yuhao/workspace/model/bigdl_inception-v1_imagenet_0.4.0.model"
    image_test_path ="/home/yuhao/workspace/data/xray/middle_images"
    image_path ="/home/yuhao/workspace/data/xray/middle_images"
    label_path = "/home/yuhao/workspace/data/xray/Data_Entry_2017.csv"
    return model_path,image_test_path,image_path,label_path

model_path,image_test_path,image_path,label_path=Read_Pathes()
sparkConf = create_spark_conf().setAppName("testNNClassifer")
sc = init_nncontext(sparkConf)
spark = SparkSession.builder.config(conf=sparkConf).getOrCreate()
print(sc.master)

label_texts = list("""Atelectasis, Consolidation, Infiltration, Pneumothorax, Edema, Emphysema, Fibrosis, Effusion, Pneumonia, Pleural_Thickening, Cardiomegaly, Nodule, Mass, Hernia, No Finding""".replace("\n", "").split(", "))
label_map = {k: v for v, k in enumerate(label_texts)}


def text_to_label(text):
    arr = [0.0] * len(label_texts)
    for l in text.split("|"):
        arr[label_map[l]] = 1.0

    return arr

getLabel = udf(lambda x: text_to_label(x), ArrayType(DoubleType()))
getName = udf(lambda row: os.path.basename(row[0]), StringType())
imageDF = NNImageReader.readImages(image_path, sc, resizeH=256, resizeW=256, image_codec=1) \
    .withColumn("Image Index", getName(col('image')))
imageDF=imageDF.withColumnRenamed('Image Index', 'Image_Index')
labelDF = spark.read.load(label_path, format="csv", sep=",", inferSchema="true", header="true") \
   .select("Image Index", "Finding Labels") \
   .withColumn("label", getLabel(col('Finding Labels')))

labelDF = labelDF.withColumnRenamed('Image Index', 'Image_Index')\
    .withColumnRenamed('Finding Labels', 'Finding_Labels')
labelDF.printSchema()

train_df = imageDF.join(labelDF, on="Image_Index", how="inner")
(trainingDF, validationDF) = train_df.randomSplit([0.7, 0.3])

full_model = Net.load_bigdl(model_path)

model = full_model.new_graph(["pool5/drop_7x7_s1"])  # this inception
inputNode = Input(name="input", shape=(3, 224, 224))
inception = model.to_keras()(inputNode)
flatten = Flatten()(inception)
logits = Dense(15, activation="sigmoid")(flatten)
lrModel = Model(inputNode, logits)

#logdir ='/logDirectory'
train_summary = TrainSummary(log_dir="./logs", app_name="testNNClassifer")
val_summary = ValidationSummary(log_dir="./logs", app_name="testNNClassifer")

train_summary.set_summary_trigger("Parameters", SeveralIteration(1))
train_summary.set_summary_trigger("LearningRate", SeveralIteration(1))

transformer = ChainedPreprocessing(
    [RowToImageFeature(), ImageCenterCrop(224, 224), BigDLAdapter(RandomTransformer(HFlip(), 0.5)),
     ImageChannelNormalize(123.68, 116.779, 103.939), ImageMatToTensor(), ImageFeatureToTensor()])


classifier = NNEstimator(lrModel, MultiLabelSoftMarginCriterion(), transformer, SeqToTensor([15])) \
     .setLearningRate(0.005).setBatchSize(4).setMaxEpoch(8).setFeaturesCol("image")\
     .setCachingSample(False)\
     .setValidation(EveryEpoch(), validationDF, [AUC()], 4)\
     .setTrainSummary(train_summary) \
     .setValidationSummary(val_summary) \
     .setCheckpoint("./checkpoints", EveryEpoch(), False)

nnModel = classifier.fit(trainingDF)
print("Finished training")
```

data available from https://www.kaggle.com/nih-chest-xrays/data 
I also put a part of the data in https://drive.google.com/open?id=17spunvyAdejvjB5qzsh9u6PkTI-hMKT2 for your convenience.

**Comment by hhbyyh** [comment]
cc @dding3 Can you please help take a look? Thanks

**Comment by hhbyyh** [comment]
issue fixed.
