### ISSUE TITLE
java.lang.UnsatisfiedLinkError in examples/nnframes/finetune

### ISSUE THREAD

**Issue by insularZJ** [intel-analytics/analytics-zoo#881]
We met an error when testing examples/nnframes/finetune.

Execution script:
`
${ANALYTICS_ZOO_HOME}/bin/spark-shell-with-zoo.sh --master spark://Gondolin-Node-050:7077 --driver-memory 5g --executor-memory 10g --total-executor-cores 32 --executor-cores 8 --class com.intel.analytics.zoo.examples.nnframes.finetune.ImageFinetune --modelPath /opt/work/analytics-zoo_inception-v1_imagenet_0.1.0.model --batchSize 32 --imagePath hdfs://172.168.2.181:9000/dogs_cats/samples --nEpochs 2`

Error:
```
2018-10-25 14:46:40 INFO  DistriOptimizer$:672 - Cache thread models...
2018-10-25 14:46:43 INFO  DistriOptimizer$:674 - Cache thread models... done
2018-10-25 14:46:43 INFO  DistriOptimizer$:144 - Count dataset
2018-10-25 14:46:43 ERROR TaskSetManager:70 - Task 1 in stage 5.0 failed 4 times; aborting job
2018-10-25 14:46:43 ERROR DistriOptimizer$:993 - Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 5.0 failed 4 times, most recent failure: Lost task 1.3 in stage 5.0 (TID 18, 172.168.2.151, executor 1): java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_Mat(III)J
        at org.opencv.core.Mat.n_Mat(Native Method)
        at org.opencv.core.Mat.<init>(Mat.java:37)
        at com.intel.analytics.zoo.pipeline.nnframes.NNImageSchema$.row2IMF(NNImageReader.scala:103)
        at com.intel.analytics.zoo.feature.image.RowToImageFeature$$anonfun$apply$1.apply(RowToImageFeature.scala:34)
        at com.intel.analytics.zoo.feature.image.RowToImageFeature$$anonfun$apply$1.apply(RowToImageFeature.scala:33)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at com.intel.analytics.zoo.feature.common.FeatureLabelPreprocessing$$anonfun$apply$1.apply(FeatureLabelPreprocessing.scala:40)
        at com.intel.analytics.zoo.feature.common.FeatureLabelPreprocessing$$anonfun$apply$1.apply(FeatureLabelPreprocessing.scala:39)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at com.intel.analytics.bigdl.dataset.SampleToMiniBatch$$anon$2.next(Transformer.scala:331)
        at com.intel.analytics.bigdl.dataset.SampleToMiniBatch$$anon$2.next(Transformer.scala:323)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:185)
        at scala.collection.AbstractIterator.reduceLeft(Iterator.scala:1336)
        at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$15.apply(RDD.scala:1011)
        at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$15.apply(RDD.scala:1009)
        at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:1980)
        at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:1980)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by hhbyyh** [comment]
Should be fixed by the PR.
